// Desayunos — parte 2. Panes con relleno, la base del desayuno peruano.

export const parte = [
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con pollo',
    descripcion: 'Pan francés relleno de pollo deshilachado con mayonesa y lechuga.',
    ingredientes: [
      '4 panes franceses',
      '400 g de pechuga de pollo cocida',
      '1/2 taza de mayonesa',
      '4 hojas de lechuga',
      '1 limón',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Cocinar la pechuga en agua con sal, ajo y laurel hasta que esté tierna',
      'Dejarla enfriar dentro de su caldo para que no se seque',
      'Deshilachar el pollo con las manos siguiendo la fibra de la carne',
      'Mezclarlo con mayonesa, sal, pimienta y unas gotas de limón',
      'Abrir el pan francés por la mitad sin separarlo del todo',
      'Colocar una hoja de lechuga y encima una porción generosa del pollo',
      'Servir de inmediato con ají al gusto',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_pollo.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Butifarra',
    descripcion: 'Pan francés con jamón del país, salsa criolla y lechuga.',
    ingredientes: [
      '4 panes franceses',
      '300 g de jamón del país en lonjas',
      '1 cebolla roja en pluma',
      '1 ají limo picado',
      '2 limones',
      '4 hojas de lechuga',
    ],
    preparacion: [
      'Cortar el jamón del país en lonjas delgadas',
      'Preparar la salsa criolla con cebolla en pluma fina',
      'Enjuagar la cebolla en agua fría para quitarle el picor fuerte',
      'Aliñarla con limón, sal, pimienta, ají limo y un chorrito de aceite',
      'Abrir el pan y colocar una hoja de lechuga en la base',
      'Acomodar las lonjas de jamón del país encima',
      'Coronar con abundante salsa criolla y cerrar el pan',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/butifarra.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con lechón',
    descripcion: 'Pan relleno de lechón horneado con camote frito y salsa criolla.',
    ingredientes: [
      '4 panes francés',
      '400 g de lechón horneado',
      '2 camotes en rodajas fritas',
      '1 cebolla roja en pluma',
      '2 limones',
      '1 ají limo picado',
    ],
    preparacion: [
      'Cortar el lechón horneado en tajadas delgadas aprovechando la parte crocante',
      'Calentarlo brevemente en sartén para que recupere su textura',
      'Freír las rodajas de camote hasta que estén doradas y dulces',
      'Preparar la salsa criolla con cebolla en pluma, limón, ají limo y sal',
      'Abrir el pan y colocar las rodajas de camote frito en la base',
      'Acomodar encima las tajadas de lechón',
      'Terminar con salsa criolla y cerrar el pan',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_lechon.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con pavo',
    descripcion: 'Pan relleno de pavo horneado con salsa criolla, clásico de fiestas.',
    ingredientes: [
      '4 panes franceses',
      '400 g de pavo horneado en tajadas',
      '1 cebolla roja en pluma',
      '2 limones',
      '4 hojas de lechuga',
      '1 ají limo picado',
    ],
    preparacion: [
      'Cortar el pavo horneado en tajadas delgadas contra la fibra',
      'Calentarlo apenas para que no pierda jugosidad',
      'Preparar la salsa criolla cortando la cebolla en pluma muy fina',
      'Aliñar la cebolla con limón, sal, pimienta y ají limo picado',
      'Abrir el pan y colocar una hoja de lechuga',
      'Acomodar las tajadas de pavo encima',
      'Coronar con salsa criolla bien escurrida y servir',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_pavo.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con asado',
    descripcion: 'Pan relleno de asado de res en su jugo con cebolla encurtida.',
    ingredientes: [
      '4 panes franceses',
      '400 g de asado de res en tajadas',
      '1 taza del jugo del asado',
      '1 cebolla roja en pluma',
      '2 limones',
      'Perejil picado',
    ],
    preparacion: [
      'Cortar el asado ya cocido en tajadas delgadas y parejas',
      'Calentar las tajadas dentro de su propio jugo para que queden jugosas',
      'Cortar la cebolla en pluma y encurtirla con limón, sal y perejil',
      'Abrir el pan francés por la mitad',
      'Mojar ligeramente la miga con el jugo del asado',
      'Colocar las tajadas de carne generosamente',
      'Terminar con la cebolla encurtida y cerrar el pan',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_asado.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con camote frito',
    descripcion: 'Pan con rodajas de camote frito caramelizado y un toque de sal.',
    ingredientes: [
      '4 panes franceses',
      '3 camotes medianos',
      'Aceite para freír',
      'Sal al gusto',
      '1 cucharada de azúcar',
      '1 cebolla roja en pluma',
    ],
    preparacion: [
      'Pelar los camotes y cortarlos en rodajas de medio centímetro',
      'Sancocharlos brevemente para que queden tiernos por dentro',
      'Escurrirlos bien y dejarlos secar unos minutos',
      'Freírlos en aceite caliente hasta que caramelicen por fuera',
      'Escurrir sobre papel absorbente y salar ligeramente',
      'Abrir el pan y acomodar las rodajas de camote',
      'Agregar salsa criolla si se desea y servir caliente',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_camote_frito.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con relleno',
    descripcion: 'Pan norteño con relleno de sangre de cerdo especiado.',
    ingredientes: [
      '4 panes franceses',
      '300 g de relleno de cerdo',
      '1 cebolla roja en pluma',
      '2 limones',
      '1 ají limo picado',
      'Culantro picado',
    ],
    preparacion: [
      'Cortar el relleno en rodajas de un centímetro de grosor',
      'Calentarlo en una sartén con poco aceite hasta que dore por ambos lados',
      'Cuidar que no se reseque, debe quedar crocante por fuera y suave por dentro',
      'Preparar una salsa criolla con cebolla en pluma, limón, ají limo y culantro',
      'Abrir el pan francés por la mitad',
      'Colocar las rodajas de relleno caliente',
      'Coronar con la salsa criolla y servir de inmediato',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_relleno.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con salchicha huachana',
    descripcion: 'Pan con salchicha huachana desmenuzada y frita con huevo.',
    ingredientes: [
      '4 panes franceses',
      '300 g de salchicha huachana',
      '3 huevos',
      '1 cebolla picada',
      'Culantro picado',
      'Sal al gusto',
    ],
    preparacion: [
      'Retirar la tripa de la salchicha huachana y desmenuzarla con las manos',
      'Colocarla en una sartén fría y llevarla a fuego medio',
      'Dejar que suelte su propia grasa anaranjada mientras se cocina',
      'Remover hasta que quede suelta y ligeramente dorada',
      'Batir los huevos y verterlos sobre la salchicha, revolviendo hasta cuajar',
      'Rectificar la sal y agregar culantro picado',
      'Rellenar el pan francés con la mezcla caliente y servir',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_salchicha_huachana.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con huevo frito',
    descripcion: 'Pan francés con huevo frito de yema líquida y un toque de sal.',
    ingredientes: [
      '4 panes franceses',
      '4 huevos',
      '2 cucharadas de aceite',
      'Sal al gusto',
      'Pimienta al gusto',
      '1 cucharada de mantequilla',
    ],
    preparacion: [
      'Calentar una sartén con aceite a fuego medio',
      'Romper el huevo en un bowl pequeño antes de verterlo para no romper la yema',
      'Verter el huevo en la sartén y bajar el fuego',
      'Bañar la clara con el aceite caliente usando una cuchara para que cuaje pareja',
      'Retirar cuando la clara esté firme y la yema siga líquida',
      'Abrir el pan francés, untarlo con mantequilla y tostarlo ligeramente',
      'Colocar el huevo dentro, salpimentar y servir de inmediato',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_huevo_frito.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con huevo revuelto',
    descripcion: 'Pan relleno de huevos revueltos cremosos con cebolla china.',
    ingredientes: [
      '4 panes franceses',
      '6 huevos',
      '2 tallos de cebolla china',
      '2 cucharadas de mantequilla',
      '2 cucharadas de leche',
      'Sal al gusto',
    ],
    preparacion: [
      'Batir los huevos con la leche, sal y pimienta hasta integrar bien',
      'Calentar la mantequilla en una sartén a fuego bajo',
      'Verter los huevos y esperar unos segundos sin remover',
      'Remover suavemente con espátula formando pliegues grandes',
      'Retirar del fuego cuando todavía se vean ligeramente húmedos, porque siguen cocinándose',
      'Agregar la cebolla china picada y mezclar',
      'Rellenar el pan y servir de inmediato',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_huevo_revuelto.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con palta y huevo',
    descripcion: 'Pan tostado con palta aplastada y huevo frito encima.',
    ingredientes: [
      '4 panes franceses',
      '2 paltas maduras',
      '4 huevos',
      '1 limón',
      'Sal al gusto',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Tostar el pan francés abierto hasta que la corteza quede crocante',
      'Aplastar la palta con tenedor dejando algunos trozos para dar textura',
      'Sazonarla con sal, pimienta y unas gotas de limón',
      'Freír los huevos dejando la yema líquida',
      'Untar la palta generosamente sobre el pan tostado',
      'Colocar el huevo frito encima de la palta',
      'Terminar con pimienta molida y servir de inmediato',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_palta_y_huevo.jpg',
    bebida: 'Jugo de naranja',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con atún',
    descripcion: 'Pan relleno de atún con mayonesa, cebolla y limón.',
    ingredientes: [
      '4 panes franceses',
      '2 latas de atún',
      '1/2 taza de mayonesa',
      '1/2 cebolla picada fina',
      '1 limón',
      '4 hojas de lechuga',
    ],
    preparacion: [
      'Escurrir muy bien el atún para que el relleno no quede aguado',
      'Picar la cebolla finamente y enjuagarla en agua fría',
      'Mezclar el atún con la mayonesa, la cebolla, sal y pimienta',
      'Agregar unas gotas de limón para realzar el sabor',
      'Abrir el pan francés y colocar una hoja de lechuga',
      'Rellenar con la mezcla de atún',
      'Servir de inmediato para que el pan no se humedezca',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_atun.jpg',
    bebida: 'Jugo de naranja',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con mantequilla',
    descripcion: 'El desayuno más simple: pan francés caliente con mantequilla.',
    ingredientes: [
      '4 panes franceses',
      '80 g de mantequilla',
      'Sal al gusto',
      '1 cucharadita de azúcar',
      'Café para acompañar',
      'Leche al gusto',
    ],
    preparacion: [
      'Calentar el pan francés en el horno o tostadora unos minutos',
      'Buscar que la corteza quede crocante y la miga tibia',
      'Abrirlo por la mitad mientras aún está caliente',
      'Untar la mantequilla de inmediato para que se derrita sobre la miga',
      'Espolvorear una pizca de sal si se prefiere salado',
      'O espolvorear azúcar si se prefiere dulce',
      'Servir acompañado de café pasado o leche caliente',
    ],
    tiempo_minutos: 8,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_mantequilla.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con manjar blanco',
    descripcion: 'Pan francés untado con manjar blanco casero espeso.',
    ingredientes: [
      '4 panes franceses',
      '1 taza de manjar blanco',
      '1 litro de leche fresca',
      '300 g de azúcar',
      '1 palito de canela',
      '1 cucharadita de bicarbonato',
    ],
    preparacion: [
      'Hervir la leche con el azúcar, la canela y una pizca de bicarbonato',
      'Cocinar a fuego bajo removiendo constantemente con cuchara de madera',
      'Mantener el movimiento para que no se pegue al fondo de la olla',
      'Cocinar entre 40 minutos y una hora hasta que espese y tome color caramelo',
      'Comprobar el punto pasando la cuchara por el fondo: debe dejar un surco visible',
      'Dejar enfriar completamente, porque espesa aún más al enfriar',
      'Untar generosamente sobre el pan francés recién tostado',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pan_con_manjar_blanco.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con mermelada',
    descripcion: 'Pan tostado con mermelada casera de fresa.',
    ingredientes: [
      '4 panes franceses',
      '500 g de fresas',
      '250 g de azúcar',
      '1 limón',
      '40 g de mantequilla',
      '1 palito de canela',
    ],
    preparacion: [
      'Lavar y cortar las fresas en cuartos retirando las hojas',
      'Colocarlas en una olla con el azúcar y dejarlas macerar 30 minutos',
      'Llevar a fuego medio y agregar el jugo de limón, que ayuda a que cuaje',
      'Cocinar removiendo y retirando la espuma que se forma en la superficie',
      'Cuando la mezcla espese y una gota cuaje en un plato frío, está lista',
      'Dejar enfriar y guardar en frasco limpio',
      'Tostar el pan, untar mantequilla y encima la mermelada',
    ],
    tiempo_minutos: 50,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_mermelada.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con queso mantecoso',
    descripcion: 'Pan con queso mantecoso cajamarquino derretido.',
    ingredientes: [
      '4 panes franceses',
      '250 g de queso mantecoso',
      '2 cucharadas de mantequilla',
      'Sal al gusto',
      '1 tomate en rodajas',
      'Orégano al gusto',
    ],
    preparacion: [
      'Cortar el queso mantecoso en láminas gruesas',
      'Abrir el pan francés por la mitad',
      'Untar una capa fina de mantequilla en la miga',
      'Colocar las láminas de queso dentro del pan',
      'Llevar al horno o sartén tapada unos minutos para que el queso se derrita',
      'Agregar rodajas de tomate y un poco de orégano si se desea',
      'Servir caliente mientras el queso sigue cremoso',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_queso_mantecoso.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con chicharrón de pescado',
    descripcion: 'Pan relleno de chicharrón de pescado crocante con salsa criolla.',
    ingredientes: [
      '4 panes franceses',
      '400 g de filete de pescado en trozos',
      '1 taza de chuño',
      '1 cebolla roja en pluma',
      '2 limones',
      'Aceite para freír',
    ],
    preparacion: [
      'Cortar el pescado en trozos del tamaño del pan',
      'Sazonarlos con sal, pimienta, ajo y unas gotas de limón',
      'Pasarlos por chuño hasta cubrirlos de manera pareja',
      'Freírlos en abundante aceite caliente hasta que queden dorados',
      'Escurrirlos sobre papel absorbente',
      'Preparar salsa criolla con cebolla en pluma, limón, ají limo y sal',
      'Rellenar el pan con el chicharrón y coronar con la salsa criolla',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_chicharron_de_pescado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con escabeche',
    descripcion: 'Pan relleno de cebolla encurtida con ají amarillo y pollo.',
    ingredientes: [
      '4 panes franceses',
      '300 g de pollo cocido en tiras',
      '2 cebollas en pluma gruesa',
      '2 ajíes amarillos en tiras',
      '1/4 taza de vinagre tinto',
      '1 cucharadita de orégano',
    ],
    preparacion: [
      'Saltear la cebolla en pluma gruesa con ají amarillo a fuego alto',
      'Agregar orégano, comino, sal y pimienta',
      'Verter el vinagre y dejar hervir un minuto para suavizar su acidez',
      'Incorporar el pollo cocido en tiras y mezclar',
      'Dejar enfriar un poco para que los sabores se integren',
      'Abrir el pan francés por la mitad',
      'Rellenar con el escabeche bien escurrido y servir',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_escabeche.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con hot dog',
    descripcion: 'Pan con salchicha, papas al hilo y cremas, clásico de carretilla.',
    ingredientes: [
      '4 panes franceses',
      '4 salchichas',
      '1 taza de papas al hilo',
      '1/2 taza de mayonesa',
      '1/4 taza de kétchup',
      '1/4 taza de mostaza',
    ],
    preparacion: [
      'Hervir las salchichas en agua caliente sin dejar que se revienten',
      'Hacerles cortes diagonales superficiales para que se doren mejor',
      'Dorarlas brevemente en una sartén o plancha',
      'Abrir el pan francés por la mitad',
      'Untar mayonesa en la base del pan',
      'Colocar la salchicha y coronar con kétchup y mostaza',
      'Terminar con abundantes papas al hilo y servir de inmediato',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_hot_dog.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con tocino y huevo',
    descripcion: 'Pan con tocino crocante y huevo frito en su grasa.',
    ingredientes: [
      '4 panes franceses',
      '8 lonjas de tocino',
      '4 huevos',
      'Pimienta al gusto',
      '4 hojas de lechuga',
      '1 tomate en rodajas',
    ],
    preparacion: [
      'Colocar las lonjas de tocino en una sartén fría y llevarla a fuego medio',
      'Dejar que la grasa se derrita lentamente para que el tocino quede crocante',
      'Retirar el tocino y escurrirlo sobre papel absorbente',
      'Freír los huevos en la misma grasa del tocino',
      'Tostar el pan abierto en esa sartén para que absorba el sabor',
      'Armar el pan con lechuga, tomate, tocino y huevo',
      'Salpimentar y servir de inmediato',
    ],
    tiempo_minutos: 18,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_tocino_y_huevo.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sándwich triple',
    descripcion: 'Sándwich de pan de molde con palta, huevo y tomate en capas.',
    ingredientes: [
      '12 rebanadas de pan de molde',
      '2 paltas maduras',
      '4 huevos duros',
      '2 tomates en rodajas',
      '1/2 taza de mayonesa',
      '1 limón',
    ],
    preparacion: [
      'Retirar las cortezas del pan de molde para que el triple quede parejo',
      'Aplastar la palta con sal, pimienta y unas gotas de limón',
      'Picar los huevos duros y mezclarlos con mayonesa',
      'Cortar el tomate en rodajas delgadas y escurrirlas sobre papel',
      'Armar la primera capa con palta, cubrir con otra rebanada de pan',
      'Poner la capa de huevo con mayonesa y otra de tomate',
      'Cerrar, presionar ligeramente y cortar en triángulos',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sandwich_triple.jpg',
    bebida: 'Jugo surtido',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sándwich de pavo',
    descripcion: 'Sándwich de pan de molde con pavo, queso y lechuga.',
    ingredientes: [
      '8 rebanadas de pan de molde',
      '300 g de pavo en lonjas',
      '4 lonjas de queso',
      '4 hojas de lechuga',
      '1 tomate en rodajas',
      '1/4 taza de mayonesa',
    ],
    preparacion: [
      'Tostar ligeramente las rebanadas de pan de molde',
      'Untar mayonesa en una de las caras de cada rebanada',
      'Colocar una hoja de lechuga bien seca sobre la base',
      'Acomodar las lonjas de pavo dobladas para dar volumen',
      'Agregar el queso y las rodajas de tomate',
      'Salpimentar y cerrar el sándwich',
      'Cortar en diagonal y servir',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sandwich_de_pavo.jpg',
    bebida: 'Jugo de naranja',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sándwich de huevo con palta',
    descripcion: 'Pan de molde con huevo duro picado, palta y mayonesa.',
    ingredientes: [
      '8 rebanadas de pan de molde',
      '4 huevos duros',
      '2 paltas maduras',
      '1/3 taza de mayonesa',
      '1 limón',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Cocinar los huevos en agua hirviendo por 10 minutos y enfriarlos en agua fría',
      'Pelarlos y picarlos en trozos pequeños',
      'Mezclarlos con mayonesa, sal y pimienta',
      'Aplastar la palta con limón y sal por separado',
      'Tostar el pan de molde ligeramente',
      'Untar la palta en una rebanada y el huevo con mayonesa en la otra',
      'Cerrar el sándwich, cortar en diagonal y servir',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sandwich_de_huevo_con_palta.jpg',
    bebida: 'Jugo de papaya',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sándwich mixto caliente',
    descripcion: 'Pan de molde con jamón y queso prensado y dorado en sartén.',
    ingredientes: [
      '8 rebanadas de pan de molde',
      '8 lonjas de jamón',
      '8 lonjas de queso',
      '40 g de mantequilla',
      'Orégano al gusto',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Untar mantequilla en la cara exterior de cada rebanada de pan',
      'Armar el sándwich con jamón y queso alternados en el interior',
      'Agregar un poco de orégano y pimienta entre las capas',
      'Calentar una sartén a fuego medio bajo',
      'Colocar el sándwich y presionarlo con una espátula o plancha',
      'Dorar 3 minutos por lado hasta que el queso se derrita por completo',
      'Cortar en diagonal y servir caliente',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sandwich_mixto_caliente.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con aceituna y queso',
    descripcion: 'Pan francés con crema de aceituna botija y queso fresco.',
    ingredientes: [
      '4 panes franceses',
      '150 g de aceitunas botija',
      '200 g de queso fresco',
      '2 cucharadas de aceite de oliva',
      '1 limón',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Deshuesar las aceitunas botija con cuidado',
      'Licuarlas con un poco de aceite de oliva hasta formar una pasta',
      'Ajustar con unas gotas de limón y pimienta, sin agregar sal',
      'Cortar el queso fresco en láminas gruesas',
      'Abrir el pan francés y tostarlo ligeramente',
      'Untar la crema de aceituna en una cara del pan',
      'Colocar las láminas de queso fresco y cerrar el pan',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_aceituna_y_queso.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con jamonada',
    descripcion: 'Pan francés con jamonada, mayonesa y lechuga.',
    ingredientes: [
      '4 panes franceses',
      '300 g de jamonada en lonjas',
      '1/3 taza de mayonesa',
      '4 hojas de lechuga',
      '1 tomate en rodajas',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Cortar la jamonada en lonjas delgadas',
      'Dorarlas brevemente en sartén si se prefiere caliente',
      'Abrir el pan francés por la mitad',
      'Untar mayonesa en la miga del pan',
      'Colocar una hoja de lechuga bien seca',
      'Acomodar las lonjas de jamonada y las rodajas de tomate',
      'Salpimentar, cerrar el pan y servir',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_jamonada.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con chorizo',
    descripcion: 'Pan francés con chorizo frito y cebolla encurtida.',
    ingredientes: [
      '4 panes franceses',
      '4 chorizos',
      '1 cebolla roja en pluma',
      '2 limones',
      '1 ají limo picado',
      'Culantro picado',
    ],
    preparacion: [
      'Cortar los chorizos por la mitad a lo largo para que se cocinen parejos',
      'Colocarlos en una sartén a fuego medio sin aceite adicional',
      'Dejar que suelten su propia grasa y se doren por ambos lados',
      'Tostar el pan abierto en esa misma grasa',
      'Preparar salsa criolla con cebolla en pluma, limón, ají limo y culantro',
      'Colocar el chorizo dentro del pan',
      'Coronar con la salsa criolla escurrida y servir caliente',
    ],
    tiempo_minutos: 18,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_chorizo.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con tortilla de verduras',
    descripcion: 'Pan relleno de tortilla de huevo con verduras picadas.',
    ingredientes: [
      '4 panes franceses',
      '5 huevos',
      '1 zanahoria rallada',
      '1 taza de espinaca picada',
      '1/2 cebolla picada',
      '2 cucharadas de aceite',
    ],
    preparacion: [
      'Saltear la cebolla, la zanahoria rallada y la espinaca hasta que pierdan agua',
      'Dejar enfriar un poco las verduras para que no cuajen el huevo antes de tiempo',
      'Batir los huevos con sal y pimienta',
      'Mezclar las verduras con el huevo batido',
      'Verter en una sartén caliente con poco aceite y cocinar a fuego bajo',
      'Voltear con ayuda de un plato y dorar del otro lado',
      'Cortar porciones del tamaño del pan y rellenar',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_tortilla_de_verduras.jpg',
    bebida: 'Jugo surtido',
    acompanamiento: null,
    video_url: null,
  },
];
