// Recetas de la categoría "desayunos". Fuente canónica del seed.
// Los generadores de database/*.mjs leen de aquí vía recetasSeedData.js.

export const parte = [
  {
    categoria_slug: 'desayunos',
    nombre: "Pan con palta",
    descripcion: "Pan francés crocante con palta fresca aplastada y un toque de sal.",
    ingredientes: [
      "4 panes franceses",
      "2 paltas maduras grandes",
      "Sal al gusto",
      "1 limón",
    ],
    preparacion: [
      "Cortar el pan francés por la mitad sin llegar a separarlo del todo y tostarlo unos minutos hasta que la corteza quede crocante",
      "Pelar la palta madura y retirar la pepa, colocando la pulpa en un bowl",
      "Aplastar la palta con un tenedor hasta lograr una pasta suave con algunos trozos",
      "Sazonar con sal al gusto y unas gotas de limón, mezclando bien para evitar que se oxide",
      "Untar generosamente la palta sazonada sobre el pan tostado",
      "Servir de inmediato para disfrutar el pan crocante con la palta fresca",
    ],
    tiempo_minutos: 10,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/pan_con_palta.jpg",
    bebida: "Café pasado",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Pan con chicharrón",
    descripcion: "Chicharrón de cerdo crocante servido en pan francés con salsa criolla y camote.",
    ingredientes: [
      "4 panes franceses",
      "500 g de panceta o pierna de cerdo",
      "2 camotes medianos, en rodajas",
      "1 cebolla roja mediana",
      "2 limones",
      "1 ají amarillo, en tiras",
    ],
    preparacion: [
      "Cortar la carne de cerdo en trozos medianos y sazonar con sal, comino y ajo molido",
      "Freír el cerdo en su propia grasa a fuego medio hasta que quede dorado y crocante por fuera y jugoso por dentro",
      "Pelar y cortar el camote en rodajas gruesas y freírlo aparte hasta que dore",
      "Cortar la cebolla en pluma fina y lavarla con agua fría para suavizar su sabor",
      "Preparar la salsa criolla mezclando la cebolla con limón, sal, ají amarillo en tiras finas y un poco de culantro picado",
      "Abrir el pan francés y colocar dentro el chicharrón caliente junto con las rodajas de camote frito",
      "Coronar con abundante salsa criolla y servir de inmediato",
    ],
    tiempo_minutos: 35,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/pan_con_chicharron.jpg",
    bebida: "Café pasado",
    acompanamiento: "Camote frito",
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Pan con tamal",
    descripcion: "Tamal de maíz relleno de pollo envuelto en pan, clásico desayuno limeño.",
    ingredientes: [
      "4 tamales de maíz con pollo",
      "150 g de pollo deshilachado adicional",
      "4 panes franceses",
      "1 taza de salsa criolla",
    ],
    preparacion: [
      "Colocar el tamal envuelto en su panca sobre una vaporera y calentar por 10 minutos hasta que esté bien caliente",
      "Retirar con cuidado la panca de choclo o plátano que envuelve el tamal",
      "Cortar el tamal en rodajas gruesas, procurando que conserve el relleno de pollo en cada trozo",
      "Preparar una salsa criolla fresca con cebolla en pluma, limón, sal y un toque de ají amarillo",
      "Abrir el pan francés por la mitad y colocar las rodajas de tamal dentro",
      "Añadir la salsa criolla por encima y cerrar el pan",
      "Servir tibio acompañado de una taza de café pasado",
    ],
    tiempo_minutos: 15,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/pan_con_tamal.jpg",
    bebida: "Café pasado",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Pan con tortilla",
    descripcion: "Tortilla de verduras esponjosa servida caliente en pan francés.",
    ingredientes: [
      "4 huevos",
      "1 taza de verduras picadas (cebolla, tomate y pimiento)",
      "4 panes franceses",
      "1/2 cucharadita de sal",
      "1/4 cucharadita de pimienta",
    ],
    preparacion: [
      "Picar finamente las verduras (cebolla, tomate, pimiento) en cubos pequeños",
      "Batir los huevos enérgicamente en un bowl junto con sal y pimienta al gusto",
      "Incorporar las verduras picadas a los huevos batidos y mezclar bien",
      "Calentar una sartén con un poco de aceite a fuego medio",
      "Verter la mezcla y cocinar tapado unos 3 minutos hasta que cuaje por debajo",
      "Voltear la tortilla con ayuda de un plato y cocinar el otro lado hasta dorar ligeramente",
      "Colocar la tortilla caliente dentro del pan francés recién partido y servir",
    ],
    tiempo_minutos: 15,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/pan_con_tortilla.jpg",
    bebida: "Emoliente",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Pan con huevo",
    descripcion: "Huevo frito o revuelto servido en pan francés recién horneado.",
    ingredientes: [
      "4 huevos",
      "4 panes franceses",
      "Sal al gusto",
      "2 cucharadas de aceite",
    ],
    preparacion: [
      "Calentar un chorrito de aceite en una sartén pequeña a fuego medio",
      "Romper el huevo directamente sobre la sartén caliente, cuidando que la yema no se rompa si se desea frito",
      "Sazonar con sal apenas se vierte el huevo",
      "Cocinar hasta que la clara esté firme y la yema al punto deseado, o revolver constantemente si se prefiere revuelto",
      "Retirar el huevo con una espátula procurando mantener su forma",
      "Colocar el huevo caliente dentro del pan francés recién abierto y servir de inmediato",
    ],
    tiempo_minutos: 8,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/pan_con_huevo.jpg",
    bebida: "Leche con café",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Humitas",
    descripcion: "Masa de choclo tierno al vapor envuelta en su propia panca, dulce o salada.",
    ingredientes: [
      "8 choclos tiernos con panca",
      "4 cucharadas de manteca",
      "1 cucharadita de anís",
      "Sal o azúcar al gusto",
      "16 pancas de choclo para envolver",
    ],
    preparacion: [
      "Desgranar los choclos tiernos y reservar las pancas más grandes y en buen estado para envolver",
      "Moler los granos de choclo en una licuadora o batán junto con el anís hasta obtener una masa espesa",
      "Calentar la manteca en una sartén y mezclarla con la masa de choclo, sazonando con sal o azúcar según se prefiera dulce o salada",
      "Cocinar la masa a fuego suave por 5 minutos, revolviendo constantemente hasta que espese un poco más",
      "Colocar dos cucharadas de masa en el centro de cada panca y doblar los extremos formando un paquete",
      "Amarrar cada humita con tiras de la misma panca o pabilo",
      "Colocar las humitas en una olla con agua hirviendo, apoyadas sobre más pancas en el fondo, y cocer al vapor durante 40 minutos",
      "Retirar, dejar reposar unos minutos y servir calientes",
    ],
    tiempo_minutos: 60,
    dificultad: "dificil",
    imagen_asset: "/assets/images/recetas/humitas.jpg",
    bebida: "Café pasado",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Tamales",
    descripcion: "Masa de maíz rellena de pollo o cerdo, envuelta en hoja de plátano y cocida al vapor.",
    ingredientes: [
      "1 kg de maíz pelado",
      "500 g de pollo o cerdo, en trozos",
      "4 cucharadas de ají panca licuado",
      "8 hojas de plátano",
      "8 aceitunas de botija",
    ],
    preparacion: [
      "Remojar el maíz pelado la noche anterior y luego molerlo hasta obtener una masa fina",
      "Sofreír ají panca licuado con ajo y cebolla, e incorporarlo a la masa de maíz junto con manteca y sal, cocinando a fuego lento hasta espesar",
      "Sazonar y cocer el pollo o cerdo en trozos con sal, comino y un poco del mismo aderezo de ají panca",
      "Pasar las hojas de plátano por fuego directo unos segundos para flexibilizarlas y lavarlas bien",
      "Colocar una porción de masa sobre la hoja, añadir un trozo de carne y una aceituna en el centro",
      "Envolver la hoja formando un paquete rectangular y amarrar firmemente con pabilo o tiras de la misma hoja",
      "Acomodar los tamales en una olla grande sobre una base de hojas y cocer al vapor durante 90 minutos",
      "Verificar el punto de cocción, dejar reposar 10 minutos y servir calientes con salsa criolla",
    ],
    tiempo_minutos: 90,
    dificultad: "dificil",
    imagen_asset: "/assets/images/recetas/tamales.jpg",
    bebida: "Café pasado",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Pan con queso fresco",
    descripcion: "Pan francés con láminas de queso fresco andino.",
    ingredientes: [
      "4 panes franceses",
      "200 g de queso fresco",
      "2 cucharadas de mantequilla",
    ],
    preparacion: [
      "Cortar el pan francés por la mitad sin separarlo completamente",
      "Untar una capa fina de mantequilla en ambos lados del pan",
      "Cortar el queso fresco en láminas de aproximadamente medio centímetro de grosor",
      "Rellenar el pan con dos o tres láminas de queso fresco",
      "Presionar ligeramente para que el queso se adhiera bien y servir de inmediato",
    ],
    tiempo_minutos: 5,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/pan_con_queso_fresco.jpg",
    bebida: "Emoliente",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Pan con aceitunas",
    descripcion: "Pan francés con aceitunas de botija molidas al estilo criollo.",
    ingredientes: [
      "4 panes franceses",
      "150 g de aceitunas de botija",
      "1/2 ají amarillo, picado",
      "100 g de queso fresco (opcional)",
    ],
    preparacion: [
      "Deshuesar las aceitunas de botija con cuidado, retirando toda la pepa",
      "Triturar las aceitunas en un mortero o procesadora hasta formar una pasta gruesa",
      "Mezclar la pasta con un toque de ají amarillo picado y, si se desea, unos trozos pequeños de queso fresco",
      "Probar y ajustar el sabor, ya que la aceituna aporta bastante sal por sí sola",
      "Abrir el pan francés y untar generosamente la pasta de aceitunas",
      "Servir de inmediato acompañado de café pasado",
    ],
    tiempo_minutos: 10,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/pan_con_aceitunas.jpg",
    bebida: "Café pasado",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Sándwich de pollo",
    descripcion: "Pollo deshilachado con mayonesa y apio, un clásico de panadería peruana.",
    ingredientes: [
      "2 pechugas de pollo (400 g)",
      "4 cucharadas de mayonesa",
      "1 tallo de apio, picado",
      "4 panes franceses",
    ],
    preparacion: [
      "Cocer la pechuga de pollo en agua con sal durante 20 minutos hasta que esté bien cocida",
      "Dejar enfriar y deshilachar la pechuga con las manos o dos tenedores en tiras finas",
      "Picar el apio en cubos muy pequeños",
      "Mezclar el pollo deshilachado con la mayonesa y el apio picado hasta integrar bien",
      "Sazonar con sal y pimienta al gusto",
      "Rellenar el pan francés con la mezcla y servir frío o a temperatura ambiente",
    ],
    tiempo_minutos: 25,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/sandwich_de_pollo.jpg",
    bebida: "Chicha morada",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: "Sándwich de jamón",
    descripcion: "Pan francés con jamón y queso, simple y rápido.",
    ingredientes: [
      "4 panes franceses",
      "8 láminas de jamón",
      "8 láminas de queso",
      "2 cucharadas de mantequilla",
    ],
    preparacion: [
      "Cortar el pan francés por la mitad sin separarlo del todo",
      "Untar una capa fina de mantequilla en ambos lados",
      "Colocar una o dos láminas de jamón sobre el pan",
      "Añadir una lámina de queso encima del jamón",
      "Cerrar el pan y, si se desea, tostarlo ligeramente en sartén o plancha para que el queso se derrita un poco",
      "Servir de inmediato",
    ],
    tiempo_minutos: 5,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/sandwich_de_jamon.jpg",
    bebida: "Jugo de papaya",
    acompanamiento: null,
    video_url: null,
  },
];
