// Desayunos — parte 3. Tamales, humitas, huevos y frituras de mañana.

export const parte = [
  {
    categoria_slug: 'desayunos',
    nombre: 'Tamal verde',
    descripcion: 'Tamal norteño de masa de maíz teñida con culantro y relleno de cerdo.',
    ingredientes: [
      '1 kg de maíz blanco molido',
      '1 atado grande de culantro licuado',
      '500 g de carne de cerdo en trozos',
      '1 taza de manteca de cerdo',
      'Hojas de plátano',
      '1 taza de arvejas',
    ],
    preparacion: [
      'Remojar el maíz desde la noche anterior y molerlo hasta obtener una masa fina',
      'Licuar el culantro con un poco de agua y colarlo',
      'Derretir la manteca y freír ajo, luego incorporar la masa removiendo constantemente',
      'Agregar el culantro licuado y cocinar hasta que la masa espese y tome color verde',
      'Pasar las hojas de plátano por calor para que se ablanden y no se rompan',
      'Colocar masa sobre la hoja, poner un trozo de cerdo y arvejas al centro, y envolver',
      'Amarrar los tamales y cocinarlos al vapor durante una hora y media',
    ],
    tiempo_minutos: 180,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/tamal_verde.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tamal criollo',
    descripcion: 'Tamal limeño de masa de maíz amarillo con cerdo, huevo y aceituna.',
    ingredientes: [
      '1 kg de maíz amarillo molido',
      '500 g de carne de cerdo',
      '4 huevos duros',
      '100 g de aceitunas negras',
      '1 taza de manteca de cerdo',
      'Hojas de plátano',
    ],
    preparacion: [
      'Remojar el maíz amarillo toda la noche y molerlo hasta obtener masa',
      'Cocinar el cerdo en agua con sal y ajo, reservando el caldo',
      'Freír ajo y ají panca en manteca, luego incorporar la masa con el caldo',
      'Cocinar removiendo sin parar hasta que la masa espese y se despegue de la olla',
      'Ablandar las hojas de plátano pasándolas por calor',
      'Colocar masa, un trozo de cerdo, medio huevo duro, aceituna y maní al centro',
      'Envolver, amarrar y cocinar al vapor una hora y media',
    ],
    tiempo_minutos: 180,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/tamal_criollo.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tamalito verde piurano',
    descripcion: 'Tamal pequeño de choclo con culantro, sin relleno, muy suave.',
    ingredientes: [
      '8 choclos tiernos molidos',
      '1 atado de culantro licuado',
      '1/2 taza de manteca',
      'Pancas de choclo',
      '2 cucharaditas de sal',
      '4 dientes de ajo molidos',
    ],
    preparacion: [
      'Moler los choclos tiernos hasta obtener una pasta espesa',
      'Licuar el culantro con poca agua y colarlo para obtener un extracto concentrado',
      'Derretir la manteca y freír el ajo molido',
      'Incorporar la masa de choclo y el culantro, removiendo a fuego bajo',
      'Cocinar hasta que la masa espese y tome un color verde parejo',
      'Colocar porciones sobre las pancas de choclo y envolver como paquetitos',
      'Cocinar al vapor durante 45 minutos y servir tibios',
    ],
    tiempo_minutos: 90,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tamalito_verde_piurano.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Humita dulce',
    descripcion: 'Humita de choclo tierno con pasas y canela, envuelta en panca.',
    ingredientes: [
      '8 choclos tiernos',
      '1/2 taza de azúcar',
      '1/2 taza de pasas',
      '1 cucharadita de canela',
      '100 g de mantequilla',
      'Pancas de choclo',
    ],
    preparacion: [
      'Desgranar los choclos tiernos reservando las pancas más anchas',
      'Moler los granos hasta obtener una pasta con algo de textura',
      'Derretir la mantequilla y mezclarla con la masa de choclo',
      'Agregar el azúcar, la canela molida y las pasas',
      'Colocar una porción de masa sobre dos pancas superpuestas',
      'Doblar los extremos formando un paquete y amarrarlo con tiras de panca',
      'Cocinar al vapor durante 45 minutos y dejar reposar antes de abrir',
    ],
    tiempo_minutos: 75,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/humita_dulce.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Humita salada',
    descripcion: 'Humita de choclo con queso fresco y ají amarillo.',
    ingredientes: [
      '8 choclos tiernos',
      '200 g de queso fresco',
      '3 cucharadas de ají amarillo molido',
      '100 g de manteca',
      'Pancas de choclo',
      'Sal al gusto',
    ],
    preparacion: [
      'Desgranar los choclos y molerlos hasta obtener una pasta espesa',
      'Preparar un aderezo friendo cebolla, ajo y ají amarillo en manteca',
      'Mezclar el aderezo con la masa de choclo y sazonar con sal',
      'Cortar el queso fresco en bastones',
      'Colocar masa sobre dos pancas superpuestas y poner un bastón de queso al centro',
      'Cubrir con más masa y cerrar el paquete amarrándolo con tiras de panca',
      'Cocinar al vapor 45 minutos y servir tibio con salsa criolla',
    ],
    tiempo_minutos: 75,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/humita_salada.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tamal dulce',
    descripcion: 'Tamal de maíz endulzado con pasas y canela, sin relleno de carne.',
    ingredientes: [
      '1 kg de maíz blanco molido',
      '1 taza de azúcar',
      '1/2 taza de pasas',
      '1 cucharadita de canela',
      '1 taza de manteca',
      'Hojas de plátano',
    ],
    preparacion: [
      'Remojar el maíz desde la noche anterior y molerlo hasta obtener masa fina',
      'Derretir la manteca en una olla amplia',
      'Incorporar la masa removiendo constantemente para que no se formen grumos',
      'Agregar el azúcar, la canela y un poco de agua tibia',
      'Cocinar hasta que la masa espese y se desprenda del fondo',
      'Colocar porciones sobre hojas de plátano con pasas al centro y envolver',
      'Amarrar y cocinar al vapor durante una hora y media',
    ],
    tiempo_minutos: 160,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/tamal_dulce.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Huevos revueltos con salchicha',
    descripcion: 'Huevos revueltos con salchicha picada y cebolla china.',
    ingredientes: [
      '6 huevos',
      '3 salchichas en rodajas',
      '2 tallos de cebolla china',
      '2 cucharadas de mantequilla',
      'Sal al gusto',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Cortar las salchichas en rodajas delgadas',
      'Dorarlas en una sartén con un poco de mantequilla',
      'Batir los huevos con sal y pimienta hasta integrar la yema y la clara',
      'Bajar el fuego y verter los huevos sobre las salchichas',
      'Remover suavemente formando pliegues grandes',
      'Retirar cuando aún se vean ligeramente húmedos',
      'Agregar cebolla china picada y servir con pan francés',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/huevos_revueltos_con_salchicha.jpg',
    bebida: 'Café con leche',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Huevo a la copa',
    descripcion: 'Huevos pasados por agua servidos en copa con sal y pan.',
    ingredientes: [
      '4 huevos frescos',
      'Sal al gusto',
      'Pimienta al gusto',
      '4 panes franceses',
      '20 g de mantequilla',
      'Agua para hervir',
    ],
    preparacion: [
      'Sacar los huevos del refrigerador 15 minutos antes para que no se rajen',
      'Hervir agua en una olla pequeña',
      'Introducir los huevos con cuidado usando una cuchara',
      'Cocinar exactamente 4 minutos para que la clara cuaje y la yema quede líquida',
      'Retirar y pasarlos brevemente por agua fría para poder manipularlos',
      'Romper la parte superior del huevo y vaciarlo en una copa',
      'Salpimentar y servir con pan francés con mantequilla para mojar',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/huevo_a_la_copa.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Huevos fritos con arroz',
    descripcion: 'Arroz blanco con dos huevos fritos encima y plátano frito.',
    ingredientes: [
      '3 tazas de arroz cocido',
      '4 huevos',
      '2 plátanos maduros',
      '3 cucharadas de aceite',
      'Sal al gusto',
      'Ají al gusto',
    ],
    preparacion: [
      'Calentar el arroz cocido en una sartén con unas gotas de aceite',
      'Cortar los plátanos maduros en tiras diagonales',
      'Freírlos hasta que caramelicen por fuera y queden suaves por dentro',
      'En la misma sartén freír los huevos con abundante aceite caliente',
      'Bañar la clara con el aceite para que cuaje sin quemarse',
      'Retirar cuando la yema siga líquida',
      'Servir el arroz con los huevos encima y el plátano frito al costado',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/huevos_fritos_con_arroz.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Plátano frito',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tortilla de papa',
    descripcion: 'Tortilla gruesa de papa en rodajas con huevo y cebolla.',
    ingredientes: [
      '4 papas medianas',
      '6 huevos',
      '1 cebolla en pluma',
      '1/2 taza de aceite',
      'Sal al gusto',
      'Perejil picado',
    ],
    preparacion: [
      'Pelar las papas y cortarlas en rodajas delgadas',
      'Freírlas a fuego bajo en aceite hasta que estén tiernas sin dorarse demasiado',
      'Agregar la cebolla en pluma y cocinar hasta que transparente',
      'Escurrir el exceso de aceite',
      'Batir los huevos con sal y mezclarlos con la papa y la cebolla',
      'Verter en una sartén caliente y cocinar a fuego bajo hasta que cuaje la base',
      'Voltear con ayuda de un plato y cocinar 4 minutos más del otro lado',
    ],
    tiempo_minutos: 35,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tortilla_de_papa.jpg',
    bebida: 'Jugo de naranja',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Torreja de choclo',
    descripcion: 'Tortitas fritas de choclo molido con queso y hierbas.',
    ingredientes: [
      '6 choclos tiernos',
      '200 g de queso fresco',
      '2 huevos',
      '1/2 taza de harina',
      'Huacatay al gusto',
      'Aceite para freír',
    ],
    preparacion: [
      'Desgranar los choclos y molerlos dejando algo de textura',
      'Mezclar la masa con los huevos batidos y la harina',
      'Agregar el queso fresco desmenuzado y el huacatay picado',
      'Sazonar con sal y pimienta hasta obtener una mezcla espesa',
      'Calentar aceite en una sartén a fuego medio',
      'Verter cucharadas de la mezcla formando tortitas',
      'Freír 3 minutos por lado hasta dorar y escurrir sobre papel',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/torreja_de_choclo.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Yuca frita con queso',
    descripcion: 'Bastones de yuca sancochada y frita servidos con queso fresco.',
    ingredientes: [
      '1 kg de yuca',
      '250 g de queso fresco',
      'Aceite para freír',
      'Sal al gusto',
      '1 limón',
      'Salsa de ají al gusto',
    ],
    preparacion: [
      'Pelar la yuca y cortarla en trozos gruesos',
      'Sancocharla en agua con sal hasta que esté tierna pero no deshecha',
      'Escurrirla y retirar la fibra central de cada trozo',
      'Dejarla secar unos minutos para que no salte el aceite',
      'Cortarla en bastones y freírla en aceite caliente hasta dorar',
      'Escurrir sobre papel absorbente y salar',
      'Servir con queso fresco en cubos y salsa de ají',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/yuca_frita_con_queso.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Salsa de ají',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Camote frito con miel',
    descripcion: 'Rodajas de camote fritas bañadas en miel de chancaca.',
    ingredientes: [
      '4 camotes medianos',
      '200 g de chancaca',
      '1 palito de canela',
      '2 clavos de olor',
      'Aceite para freír',
      '1 naranja',
    ],
    preparacion: [
      'Pelar los camotes y cortarlos en rodajas gruesas',
      'Sancocharlas brevemente para que queden tiernas por dentro',
      'Escurrir y secar bien las rodajas',
      'Freírlas en aceite caliente hasta que caramelicen por fuera',
      'Derretir la chancaca con agua, canela, clavo y cáscara de naranja',
      'Cocinar la miel a fuego bajo hasta que espese ligeramente',
      'Bañar el camote frito con la miel y servir tibio',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/camote_frito_con_miel.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Empanada de carne',
    descripcion: 'Empanada horneada rellena de carne guisada con huevo y aceituna.',
    ingredientes: [
      '500 g de harina',
      '200 g de manteca',
      '400 g de carne molida',
      '2 huevos duros picados',
      '50 g de aceitunas picadas',
      '1 cebolla picada fina',
    ],
    preparacion: [
      'Formar la masa mezclando harina, manteca, sal y agua fría hasta que quede lisa',
      'Dejarla reposar en frío por 30 minutos envuelta en film',
      'Preparar el relleno con aderezo de cebolla, ajo y ají panca, y dorar la carne',
      'Agregar huevo duro, aceitunas y pasas, y dejar enfriar por completo',
      'Estirar la masa y cortar discos de unos 12 centímetros',
      'Colocar relleno al centro, cerrar y repulgar los bordes con los dedos',
      'Pincelar con huevo batido y hornear a 200 grados por 20 minutos',
    ],
    tiempo_minutos: 80,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/empanada_de_carne.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Empanada de pollo',
    descripcion: 'Empanada horneada rellena de pollo deshilachado con ají amarillo.',
    ingredientes: [
      '500 g de harina',
      '200 g de manteca',
      '400 g de pollo cocido deshilachado',
      '3 cucharadas de ají amarillo molido',
      '1 cebolla picada',
      '1 huevo para pincelar',
    ],
    preparacion: [
      'Preparar la masa con harina, manteca, sal y agua fría, y dejarla reposar en frío',
      'Cocinar la pechuga de pollo y deshilacharla finamente',
      'Hacer un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Incorporar el pollo deshilachado y cocinar unos minutos, luego enfriar',
      'Estirar la masa y cortar discos',
      'Rellenar, cerrar y repulgar los bordes presionando bien para que no se abran',
      'Pincelar con huevo y hornear a 200 grados por 20 minutos hasta dorar',
    ],
    tiempo_minutos: 80,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/empanada_de_pollo.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Empanada de queso',
    descripcion: 'Empanada rellena de queso fresco derretido con un toque de orégano.',
    ingredientes: [
      '500 g de harina',
      '200 g de mantequilla',
      '400 g de queso fresco',
      '1 cucharadita de orégano',
      '1 huevo para pincelar',
      'Sal al gusto',
    ],
    preparacion: [
      'Formar la masa con harina, mantequilla fría en cubos, sal y agua helada',
      'Trabajarla lo mínimo necesario y dejarla reposar en frío 30 minutos',
      'Cortar el queso fresco en cubos pequeños',
      'Mezclarlo con orégano y una pizca de pimienta',
      'Estirar la masa y cortar discos de 12 centímetros',
      'Poner el queso al centro, cerrar y sellar bien los bordes',
      'Pincelar con huevo y hornear a 200 grados 18 minutos hasta dorar',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/empanada_de_queso.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Cachanga',
    descripcion: 'Masa frita crocante y esponjosa, típica del desayuno serrano.',
    ingredientes: [
      '500 g de harina',
      '1 cucharadita de levadura',
      '2 cucharadas de azúcar',
      '1 cucharadita de sal',
      '1 taza de agua tibia',
      'Aceite para freír',
    ],
    preparacion: [
      'Mezclar la harina con la levadura, el azúcar y la sal',
      'Agregar el agua tibia poco a poco hasta formar una masa suave',
      'Amasar unos minutos hasta que quede lisa y elástica',
      'Dejar reposar tapada durante una hora hasta que doble su volumen',
      'Tomar porciones y estirarlas con las manos hasta dejarlas delgadas',
      'Freír en abundante aceite caliente hasta que inflen y doren',
      'Escurrir sobre papel y servir con miel, mermelada o queso',
    ],
    tiempo_minutos: 90,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cachanga.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Miel de chancaca',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Chapana',
    descripcion: 'Dulce de yuca rallada con chancaca envuelto en hoja de plátano.',
    ingredientes: [
      '1 kg de yuca rallada',
      '300 g de chancaca',
      '1 cucharadita de anís',
      '1 palito de canela',
      'Hojas de plátano',
      '4 clavos de olor',
    ],
    preparacion: [
      'Rallar la yuca cruda finamente y exprimirla ligeramente',
      'Derretir la chancaca en agua con canela, clavo y anís hasta formar una miel',
      'Colar la miel y mezclarla con la yuca rallada',
      'Trabajar la mezcla hasta que quede homogénea y manejable',
      'Cortar las hojas de plátano en rectángulos y pasarlas por calor',
      'Colocar una porción de la mezcla y envolver formando paquetitos',
      'Cocinar al vapor durante 40 minutos y servir tibias',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chapana.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan chuta',
    descripcion: 'Pan grande y dulce de Oropesa, con anís y manteca.',
    ingredientes: [
      '1 kg de harina',
      '200 g de azúcar',
      '200 g de manteca',
      '2 cucharadas de anís',
      '25 g de levadura',
      '2 tazas de agua tibia',
    ],
    preparacion: [
      'Disolver la levadura en agua tibia con una cucharada de azúcar y dejar espumar',
      'Hervir el anís en agua y colar esa infusión para aromatizar la masa',
      'Mezclar la harina con el azúcar, la manteca y la infusión de anís',
      'Agregar la levadura activada y amasar largo rato hasta que la masa quede elástica',
      'Dejar leudar tapada hasta que doble su volumen, alrededor de dos horas',
      'Formar discos grandes y planos, y dejarlos reposar 30 minutos más',
      'Hornear a 200 grados por 25 minutos hasta que doren',
    ],
    tiempo_minutos: 210,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/pan_chuta.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Chancay',
    descripcion: 'Pan dulce suave y esponjoso, clásico de la lonchera peruana.',
    ingredientes: [
      '1 kg de harina',
      '250 g de azúcar',
      '150 g de mantequilla',
      '4 huevos',
      '25 g de levadura',
      '1 taza de leche tibia',
    ],
    preparacion: [
      'Activar la levadura en leche tibia con una cucharada de azúcar',
      'Mezclar la harina con el azúcar y hacer un volcán en el centro',
      'Agregar los huevos, la mantequilla blanda y la levadura activada',
      'Amasar durante 15 minutos hasta obtener una masa lisa y elástica',
      'Dejar leudar tapada hasta que doble su volumen',
      'Formar bollos, colocarlos en bandeja y dejar leudar otra media hora',
      'Pincelar con huevo y hornear a 180 grados por 18 minutos',
    ],
    tiempo_minutos: 150,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chancay.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan de anís',
    descripcion: 'Pan casero aromatizado con anís, suave y ligeramente dulce.',
    ingredientes: [
      '1 kg de harina',
      '200 g de azúcar',
      '2 cucharadas de anís en grano',
      '150 g de manteca',
      '25 g de levadura',
      '2 tazas de agua tibia',
    ],
    preparacion: [
      'Hervir el anís en una taza de agua y dejar infusionar 10 minutos, luego colar',
      'Activar la levadura en agua tibia con azúcar hasta que espume',
      'Mezclar la harina con el azúcar, la manteca y la infusión de anís tibia',
      'Incorporar la levadura y amasar hasta obtener una masa suave',
      'Dejar leudar tapada hasta que doble su volumen',
      'Formar los panes y dejarlos reposar 30 minutos en la bandeja',
      'Hornear a 190 grados por 20 minutos hasta que doren',
    ],
    tiempo_minutos: 150,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pan_de_anis.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan de yema',
    descripcion: 'Pan dorado y esponjoso elaborado con abundantes yemas de huevo.',
    ingredientes: [
      '1 kg de harina',
      '10 yemas de huevo',
      '200 g de mantequilla',
      '180 g de azúcar',
      '25 g de levadura',
      '1 taza de leche tibia',
    ],
    preparacion: [
      'Activar la levadura en leche tibia con una cucharada de azúcar',
      'Batir las yemas con el azúcar hasta que blanqueen',
      'Mezclar la harina con las yemas batidas y la levadura activada',
      'Incorporar la mantequilla blanda poco a poco mientras se amasa',
      'Amasar hasta que la masa se despegue de las manos y quede elástica',
      'Dejar leudar hasta doblar el volumen, formar los panes y leudar otra vez',
      'Pincelar con yema y hornear a 180 grados por 20 minutos',
    ],
    tiempo_minutos: 160,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/pan_de_yema.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Panqueques con miel',
    descripcion: 'Panqueques esponjosos servidos con miel de abeja y mantequilla.',
    ingredientes: [
      '2 tazas de harina',
      '2 huevos',
      '2 tazas de leche',
      '2 cucharadas de azúcar',
      '1 cucharada de polvo de hornear',
      '40 g de mantequilla',
    ],
    preparacion: [
      'Mezclar los ingredientes secos: harina, azúcar, polvo de hornear y una pizca de sal',
      'Batir aparte los huevos con la leche y la mantequilla derretida',
      'Verter los líquidos sobre los secos y mezclar sin batir en exceso',
      'Dejar reposar la mezcla 10 minutos para que la harina se hidrate',
      'Calentar una sartén antiadherente a fuego medio y engrasarla ligeramente',
      'Verter un cucharón de mezcla y cocinar hasta que aparezcan burbujas en la superficie',
      'Voltear y cocinar un minuto más, servir apilados con miel y mantequilla',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/panqueques_con_miel.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tostadas francesas',
    descripcion: 'Rebanadas de pan remojadas en huevo con leche y doradas en mantequilla.',
    ingredientes: [
      '8 rebanadas de pan de molde',
      '3 huevos',
      '1 taza de leche',
      '2 cucharadas de azúcar',
      '1 cucharadita de canela',
      '40 g de mantequilla',
    ],
    preparacion: [
      'Batir los huevos con la leche, el azúcar, la canela y una pizca de sal',
      'Usar pan del día anterior, que absorbe mejor sin deshacerse',
      'Remojar cada rebanada en la mezcla por ambos lados sin dejarla demasiado tiempo',
      'Calentar mantequilla en una sartén a fuego medio',
      'Dorar las rebanadas 2 minutos por lado hasta que queden doradas',
      'Escurrir el exceso de mantequilla sobre papel',
      'Servir espolvoreadas con azúcar y canela o con miel',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tostadas_francesas.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Queque de plátano',
    descripcion: 'Bizcocho húmedo de plátano maduro con nueces.',
    ingredientes: [
      '3 plátanos maduros',
      '2 tazas de harina',
      '1 taza de azúcar',
      '2 huevos',
      '120 g de mantequilla',
      '1 cucharadita de polvo de hornear',
    ],
    preparacion: [
      'Aplastar los plátanos bien maduros con un tenedor hasta hacerlos puré',
      'Batir la mantequilla con el azúcar hasta que quede cremosa',
      'Agregar los huevos uno a uno batiendo entre cada adición',
      'Incorporar el puré de plátano y mezclar',
      'Añadir la harina cernida con el polvo de hornear en movimientos envolventes',
      'Verter en un molde engrasado y enharinado',
      'Hornear a 180 grados por 45 minutos hasta que el palillo salga limpio',
    ],
    tiempo_minutos: 65,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/queque_de_platano.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Bizcocho de naranja',
    descripcion: 'Queque esponjoso aromatizado con ralladura y jugo de naranja.',
    ingredientes: [
      '2 tazas de harina',
      '1 taza de azúcar',
      '3 huevos',
      '1/2 taza de jugo de naranja',
      'Ralladura de 2 naranjas',
      '150 g de mantequilla',
    ],
    preparacion: [
      'Batir la mantequilla con el azúcar hasta obtener una crema pálida',
      'Agregar los huevos uno a uno sin dejar de batir',
      'Incorporar la ralladura de naranja para aromatizar la masa',
      'Alternar la harina cernida con polvo de hornear y el jugo de naranja',
      'Mezclar con movimientos envolventes para no perder aire',
      'Verter en un molde engrasado y enharinado',
      'Hornear a 180 grados por 40 minutos y dejar enfriar antes de desmoldar',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/bizcocho_de_naranja.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Mote con queso',
    descripcion: 'Mote sancochado servido caliente con queso fresco, desayuno serrano.',
    ingredientes: [
      '2 tazas de mote pelado',
      '250 g de queso fresco',
      'Sal al gusto',
      '1 cucharada de manteca',
      'Salsa de ají al gusto',
      'Agua para cocinar',
    ],
    preparacion: [
      'Remojar el mote desde la noche anterior en abundante agua',
      'Escurrirlo y cocinarlo en agua nueva con sal',
      'Hervir a fuego medio entre una y dos horas hasta que los granos revienten',
      'Comprobar que el mote esté suave por dentro y no quede duro al centro',
      'Escurrirlo y agregarle una cucharada de manteca para darle brillo',
      'Cortar el queso fresco en cubos generosos',
      'Servir el mote caliente con el queso encima y salsa de ají al costado',
    ],
    tiempo_minutos: 120,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/mote_con_queso.jpg',
    bebida: 'Mate de coca',
    acompanamiento: 'Salsa de ají',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Choclo con queso',
    descripcion: 'Choclo serrano sancochado servido con queso fresco y anís.',
    ingredientes: [
      '4 choclos serranos',
      '300 g de queso fresco',
      '1 cucharada de anís',
      '1 cucharada de azúcar',
      'Sal al gusto',
      'Agua para cocinar',
    ],
    preparacion: [
      'Retirar las pancas del choclo reservando algunas para la cocción',
      'Colocar el agua a hervir con las pancas reservadas, anís, azúcar y sal',
      'Las pancas en el agua ayudan a que el choclo conserve su sabor dulce',
      'Agregar los choclos y cocinar entre 20 y 30 minutos según su tamaño',
      'Comprobar el punto pinchando un grano: debe estar tierno pero firme',
      'Escurrir los choclos y dejarlos entibiar un momento',
      'Servir con una tajada gruesa de queso fresco al costado',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/choclo_con_queso.jpg',
    bebida: 'Mate de muña',
    acompanamiento: null,
    video_url: null,
  },
];
