// Desayunos — parte 4. Sierra, selva y caldos de mañana.

export const parte = [
  {
    categoria_slug: 'desayunos',
    nombre: 'Mote con chicharrón',
    descripcion: 'Desayuno cusqueño de mote reventado con chicharrón de cerdo crocante.',
    ingredientes: [
      '2 tazas de mote pelado',
      '500 g de panceta de cerdo',
      '1 cebolla roja en pluma',
      '4 dientes de ajo molidos',
      '1 cucharadita de comino',
      'Rocoto picado al gusto',
    ],
    preparacion: [
      'Remojar el mote desde la noche anterior y cocinarlo hasta que reviente',
      'Cortar la panceta en trozos y sazonarla con ajo, comino, sal y pimienta',
      'Colocarla en una olla con poca agua y cocinar tapada hasta que el agua se evapore',
      'Dejar que la carne se fría en su propia grasa hasta quedar crocante',
      'Preparar una ensalada de cebolla en pluma con limón, sal y rocoto picado',
      'Escurrir el mote y servirlo caliente en el plato',
      'Colocar el chicharrón encima y la ensalada al costado',
    ],
    tiempo_minutos: 140,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/mote_con_chicharron.jpg',
    bebida: 'Mate de coca',
    acompanamiento: 'Ensalada de cebolla',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Habas con queso',
    descripcion: 'Habas frescas sancochadas servidas con queso fresco serrano.',
    ingredientes: [
      '1 kg de habas frescas en vaina',
      '250 g de queso fresco',
      'Sal al gusto',
      '1 ramita de hierbabuena',
      'Salsa de ají al gusto',
      'Agua para cocinar',
    ],
    preparacion: [
      'Desvainar las habas frescas descartando las que estén muy duras',
      'Hervir agua con sal y una ramita de hierbabuena',
      'Cocinar las habas entre 15 y 20 minutos hasta que estén tiernas',
      'Comprobar el punto aplastando una haba entre los dedos',
      'Escurrirlas y dejar que pierdan el exceso de vapor',
      'Cortar el queso fresco en cubos',
      'Servir las habas tibias con el queso y salsa de ají al costado',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/habas_con_queso.jpg',
    bebida: 'Mate de muña',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Papa sancochada con queso',
    descripcion: 'Papas andinas sancochadas con queso fresco y salsa de huacatay.',
    ingredientes: [
      '8 papas andinas',
      '250 g de queso fresco',
      '1 atado de huacatay',
      '2 ajíes amarillos',
      '1/4 taza de aceite',
      'Sal al gusto',
    ],
    preparacion: [
      'Lavar bien las papas y cocinarlas con cáscara en agua con sal',
      'Hervir entre 20 y 25 minutos hasta que se pinchen con facilidad',
      'Escurrirlas y dejarlas destapadas un momento para que sequen',
      'Licuar el huacatay con el ají amarillo, aceite y sal para hacer la salsa',
      'Cortar el queso fresco en cubos generosos',
      'Servir las papas calientes partidas por la mitad',
      'Acompañar con el queso y la salsa de huacatay',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/papa_sancochada_con_queso.jpg',
    bebida: 'Mate de muña',
    acompanamiento: 'Salsa de huacatay',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Cancha con queso',
    descripcion: 'Maíz chulpe tostado en sartén servido con queso fresco.',
    ingredientes: [
      '2 tazas de maíz chulpe',
      '250 g de queso fresco',
      '3 cucharadas de aceite',
      'Sal al gusto',
      'Ají en polvo al gusto',
      'Agua para remojar',
    ],
    preparacion: [
      'Calentar una sartén de fondo grueso con un poco de aceite',
      'Agregar el maíz chulpe en una sola capa, sin amontonarlo',
      'Tapar la sartén y mover constantemente para que no se queme',
      'Escuchar cómo revientan los granos y seguir moviendo hasta que doren',
      'Retirar cuando la mayoría esté dorada y crocante',
      'Salar de inmediato mientras siguen calientes',
      'Servir con cubos de queso fresco al costado',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cancha_con_queso.jpg',
    bebida: 'Mate de coca',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Chapla con queso',
    descripcion: 'Pan plano cusqueño de harina integral servido con queso y mate.',
    ingredientes: [
      '500 g de harina integral',
      '250 g de queso fresco',
      '15 g de levadura',
      '1 cucharadita de sal',
      '1 taza de agua tibia',
      '2 cucharadas de manteca',
    ],
    preparacion: [
      'Activar la levadura en agua tibia con una pizca de azúcar',
      'Mezclar la harina integral con la sal y la manteca',
      'Agregar la levadura activada y amasar hasta obtener una masa suave',
      'Dejar leudar tapada durante una hora',
      'Formar bolas y aplanarlas con la mano hasta dejarlas delgadas',
      'Hornear a 220 grados por 12 minutos hasta que se inflen y doren',
      'Servir tibias, abiertas por la mitad, con queso fresco dentro',
    ],
    tiempo_minutos: 100,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chapla_con_queso.jpg',
    bebida: 'Mate de coca',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tacacho de desayuno',
    descripcion: 'Bola de plátano verde majado con manteca y chicharrón, versión de mañana.',
    ingredientes: [
      '4 plátanos verdes',
      '150 g de chicharrón de cerdo',
      '3 cucharadas de manteca',
      'Sal al gusto',
      '1 cebolla en pluma',
      'Ají charapita al gusto',
    ],
    preparacion: [
      'Asar los plátanos verdes con cáscara sobre la brasa o parrilla',
      'Pelarlos mientras siguen calientes, que es cuando se majan mejor',
      'Machacarlos en un batán o mortero hasta obtener una masa gruesa',
      'Agregar la manteca de cerdo y el chicharrón picado',
      'Mezclar hasta que la masa quede homogénea y sazonar con sal',
      'Formar bolas compactas del tamaño de un puño',
      'Servir con una ensalada de cebolla con ají charapita',
    ],
    tiempo_minutos: 40,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tacacho_de_desayuno.jpg',
    bebida: 'Chapo',
    acompanamiento: 'Ensalada de cebolla',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Juane pequeño de desayuno',
    descripcion: 'Versión reducida del juane amazónico, ideal para la mañana.',
    ingredientes: [
      '2 tazas de arroz cocido',
      '300 g de pollo deshilachado',
      '4 huevos',
      'Hojas de bijao',
      '1 cucharadita de palillo',
      'Aceitunas al gusto',
    ],
    preparacion: [
      'Cocinar el pollo con ajo, sal y palillo hasta que esté suave y deshilacharlo',
      'Cocinar el arroz en el caldo del pollo para que tome color y sabor',
      'Batir los huevos y mezclarlos con el arroz caliente',
      'Ablandar las hojas de bijao pasándolas por calor',
      'Colocar una porción pequeña de arroz sobre la hoja',
      'Poner pollo, medio huevo duro y una aceituna al centro, y envolver',
      'Amarrar y hervir 30 minutos, servir caliente en su hoja',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/juane_pequeno_de_desayuno.jpg',
    bebida: 'Chapo',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Plátano asado con queso',
    descripcion: 'Plátano maduro asado abierto y relleno de queso derretido.',
    ingredientes: [
      '4 plátanos maduros',
      '200 g de queso fresco',
      '2 cucharadas de mantequilla',
      '1 cucharadita de canela',
      '2 cucharadas de azúcar',
      'Sal al gusto',
    ],
    preparacion: [
      'Elegir plátanos bien maduros, con la cáscara oscura',
      'Hacer un corte a lo largo sin llegar a separar las mitades',
      'Colocarlos en una fuente con la cáscara hacia abajo',
      'Rellenar la abertura con queso fresco en bastones y un poco de mantequilla',
      'Espolvorear azúcar y canela por encima',
      'Hornear a 200 grados por 20 minutos hasta que el queso se derrita',
      'Servir caliente dentro de la propia cáscara',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/platano_asado_con_queso.jpg',
    bebida: 'Chapo',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Caldo blanco',
    descripcion: 'Caldo ligero y claro de res con papa y huevo, típico desayuno andino.',
    ingredientes: [
      '600 g de carne de res con hueso',
      '4 papas enteras',
      '4 huevos',
      '1 cebolla en cuartos',
      'Hierbabuena al gusto',
      'Sal al gusto',
    ],
    preparacion: [
      'Colocar la carne con hueso en una olla con agua fría y sal',
      'Llevar a hervor lento retirando la espuma para que el caldo quede claro',
      'Agregar la cebolla en cuartos y cocinar a fuego bajo una hora y media',
      'Incorporar las papas enteras y cocinar hasta que estén tiernas',
      'Escalfar los huevos directamente en el caldo caliente',
      'Rectificar la sal sin sobrecargar, el caldo debe quedar suave',
      'Servir con hierbabuena picada y ají al gusto',
    ],
    tiempo_minutos: 120,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/caldo_blanco.jpg',
    bebida: 'Mate de coca',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Caldo de cabeza',
    descripcion: 'Caldo sustancioso de cabeza de cordero con mote y hierbabuena.',
    ingredientes: [
      '1 cabeza de cordero en trozos',
      '1 taza de mote cocido',
      '3 papas en trozos',
      '1 cebolla picada',
      'Hierbabuena al gusto',
      '1 trozo de kion',
    ],
    preparacion: [
      'Limpiar muy bien la cabeza de cordero y partirla en trozos manejables',
      'Hervirla brevemente y desechar esa primera agua para limpiar el caldo',
      'Colocar en agua nueva con kion, cebolla y sal',
      'Cocinar a fuego bajo durante dos horas retirando la espuma',
      'Agregar el mote ya cocido y las papas en trozos',
      'Continuar la cocción hasta que la papa esté tierna',
      'Servir bien caliente con hierbabuena picada y limón al gusto',
    ],
    tiempo_minutos: 170,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/caldo_de_cabeza.jpg',
    bebida: 'Mate de coca',
    acompanamiento: 'Cancha tostada',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sopa de sémola',
    descripcion: 'Sopa suave de sémola con leche y huevo, ideal para niños.',
    ingredientes: [
      '1/2 taza de sémola',
      '1 litro de leche',
      '2 huevos',
      '2 cucharadas de mantequilla',
      '2 cucharadas de azúcar',
      'Canela al gusto',
    ],
    preparacion: [
      'Calentar la leche con la canela a fuego medio sin dejar que hierva fuerte',
      'Tostar ligeramente la sémola en una sartén con mantequilla',
      'Verter la sémola en la leche caliente en forma de lluvia mientras se remueve',
      'Remover constantemente para evitar que se formen grumos',
      'Cocinar 8 minutos hasta que espese ligeramente',
      'Batir los huevos y verterlos en hilo removiendo con energía',
      'Endulzar al gusto y servir caliente',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sopa_de_semola.jpg',
    bebida: 'Café con leche',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Arroz con leche',
    descripcion: 'Arroz cocido en leche con canela, clavo y pasas.',
    ingredientes: [
      '1 taza de arroz',
      '1 litro de leche',
      '1 taza de azúcar',
      '1 palito de canela',
      '4 clavos de olor',
      '1/2 taza de pasas',
    ],
    preparacion: [
      'Hervir el arroz en agua con canela y clavo hasta que esté medio cocido',
      'Escurrir el exceso de agua dejando el arroz húmedo',
      'Agregar la leche y cocinar a fuego bajo removiendo con frecuencia',
      'Mantener el fuego bajo para que la leche no se corte ni se pegue',
      'Cuando el arroz esté suave, incorporar el azúcar y las pasas',
      'Cocinar 10 minutos más hasta que espese, recordando que espesa al enfriar',
      'Servir tibio o frío espolvoreado con canela molida',
    ],
    tiempo_minutos: 50,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/arroz_con_leche.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Mazamorra de calabaza',
    descripcion: 'Postre-desayuno cremoso de zapallo con leche, canela y azúcar.',
    ingredientes: [
      '1 kg de zapallo macre',
      '1 litro de leche',
      '1 taza de azúcar',
      '1 palito de canela',
      '4 clavos de olor',
      '3 cucharadas de chuño',
    ],
    preparacion: [
      'Pelar el zapallo y cortarlo en cubos grandes',
      'Cocinarlo en poca agua con canela y clavo hasta que se deshaga',
      'Aplastar el zapallo hasta obtener un puré sin grumos',
      'Agregar la leche y el azúcar, y cocinar removiendo a fuego bajo',
      'Disolver el chuño en un poco de leche fría',
      'Verterlo en hilo sobre la mazamorra removiendo sin parar hasta que espese',
      'Servir tibia espolvoreada con canela molida',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/mazamorra_de_calabaza.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Champús',
    descripcion: 'Bebida-postre espesa de mote, membrillo y piña con chancaca.',
    ingredientes: [
      '1 taza de mote cocido',
      '2 membrillos',
      '1 piña',
      '200 g de chancaca',
      '1 palito de canela',
      '3 cucharadas de harina de maíz',
    ],
    preparacion: [
      'Cocinar el membrillo y la cáscara de piña en agua con canela y clavo',
      'Colar esa infusión aromática y reservarla',
      'Disolver la harina de maíz en agua fría para que no forme grumos',
      'Verterla en la infusión caliente removiendo constantemente hasta espesar',
      'Agregar la chancaca derretida y colada',
      'Incorporar el mote cocido y la fruta picada en cubos',
      'Cocinar 10 minutos más y servir caliente en taza',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/champus.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con salchicha de Huacho y papa',
    descripcion: 'Plato de salchicha huachana con papa dorada y huevo.',
    ingredientes: [
      '400 g de salchicha huachana',
      '4 papas en cubos',
      '4 huevos',
      '4 panes franceses',
      '1 cebolla picada',
      'Culantro picado',
    ],
    preparacion: [
      'Sancochar las papas en cubos hasta que estén tiernas y escurrirlas',
      'Retirar la tripa de la salchicha y desmenuzarla',
      'Cocinarla en sartén a fuego medio hasta que suelte su grasa anaranjada',
      'Agregar las papas en cubos y dorarlas en esa grasa',
      'Batir los huevos y verterlos sobre la mezcla, revolviendo hasta cuajar',
      'Rectificar la sal y añadir culantro picado',
      'Servir caliente con pan francés al costado',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_salchicha_de_huacho_y_papa.jpg',
    bebida: 'Café con leche',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tortilla de espinaca',
    descripcion: 'Tortilla de huevo con espinaca salteada y queso.',
    ingredientes: [
      '6 huevos',
      '2 tazas de espinaca',
      '150 g de queso fresco',
      '1/2 cebolla picada',
      '2 cucharadas de aceite',
      'Sal al gusto',
    ],
    preparacion: [
      'Lavar bien la espinaca y blanquearla 1 minuto en agua hirviendo',
      'Escurrirla y exprimirla con las manos para quitar toda el agua',
      'Picarla y saltearla con cebolla y ajo hasta que pierda humedad',
      'Batir los huevos con sal, pimienta y una pizca de nuez moscada',
      'Mezclar la espinaca y el queso desmenuzado con el huevo batido',
      'Verter en sartén caliente y cocinar a fuego bajo hasta que cuaje la base',
      'Voltear con ayuda de un plato y dorar del otro lado',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tortilla_de_espinaca.jpg',
    bebida: 'Jugo de naranja',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Revuelto de champiñones',
    descripcion: 'Huevos revueltos con champiñones salteados y perejil.',
    ingredientes: [
      '6 huevos',
      '250 g de champiñones en láminas',
      '2 cucharadas de mantequilla',
      '2 dientes de ajo picados',
      'Perejil picado',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Limpiar los champiñones con un paño húmedo, sin lavarlos bajo el chorro',
      'Cortarlos en láminas y saltearlos en sartén muy caliente sin sal',
      'Esperar a que suelten el agua y se evapore antes de agregar sal',
      'Agregar el ajo picado y cocinar un minuto más',
      'Batir los huevos con sal y pimienta',
      'Bajar el fuego, verter los huevos y remover suavemente hasta cuajar',
      'Terminar con perejil picado y servir con pan tostado',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/revuelto_de_champinones.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Pan tostado',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con chicharrón de prensa',
    descripcion: 'Pan francés con chicharrón de prensa y salsa criolla.',
    ingredientes: [
      '4 panes franceses',
      '300 g de chicharrón de prensa',
      '1 cebolla roja en pluma',
      '2 limones',
      '1 ají limo picado',
      'Culantro picado',
    ],
    preparacion: [
      'Cortar el chicharrón de prensa en rodajas delgadas',
      'Dorarlas en una sartén caliente sin agregar aceite',
      'Dejar que suelten su propia grasa y queden crocantes en los bordes',
      'Tostar el pan abierto en esa misma sartén',
      'Preparar salsa criolla con cebolla en pluma, limón, ají limo y culantro',
      'Colocar las rodajas de chicharrón dentro del pan',
      'Coronar con la salsa criolla escurrida y servir',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_chicharron_de_prensa.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con queso y tomate',
    descripcion: 'Pan tostado con queso fresco, tomate en rodajas y orégano.',
    ingredientes: [
      '4 panes franceses',
      '250 g de queso fresco',
      '2 tomates en rodajas',
      '2 cucharadas de aceite de oliva',
      'Orégano al gusto',
      'Sal al gusto',
    ],
    preparacion: [
      'Cortar el tomate en rodajas y escurrirlas un momento sobre papel',
      'Cortar el queso fresco en láminas del mismo grosor',
      'Abrir el pan francés y tostarlo hasta que la corteza quede crocante',
      'Rociar la miga con un poco de aceite de oliva',
      'Acomodar las láminas de queso sobre el pan',
      'Colocar las rodajas de tomate encima',
      'Salar, espolvorear orégano y servir',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_queso_y_tomate.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con huevo y queso',
    descripcion: 'Pan relleno de huevo frito con queso derretido encima.',
    ingredientes: [
      '4 panes franceses',
      '4 huevos',
      '200 g de queso edam',
      '2 cucharadas de mantequilla',
      'Sal al gusto',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Freír los huevos en mantequilla dejando la yema líquida',
      'Colocar una lonja de queso sobre el huevo aún en la sartén',
      'Tapar la sartén un minuto para que el queso se derrita con el vapor',
      'Abrir el pan francés y tostarlo ligeramente',
      'Trasladar con cuidado el huevo con queso al pan',
      'Salpimentar al gusto',
      'Cerrar el pan y servir de inmediato',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_huevo_y_queso.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Croissant con jamón y queso',
    descripcion: 'Croissant caliente relleno de jamón y queso derretido.',
    ingredientes: [
      '4 croissants',
      '8 lonjas de jamón',
      '8 lonjas de queso',
      '2 cucharadas de mantequilla',
      'Orégano al gusto',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Abrir los croissants por la mitad sin separarlos del todo',
      'Untar una capa muy fina de mantequilla en el interior',
      'Colocar las lonjas de jamón dobladas para dar volumen',
      'Agregar el queso encima del jamón',
      'Espolvorear un poco de orégano y pimienta',
      'Hornear a 180 grados por 8 minutos hasta que el queso se derrita',
      'Servir caliente mientras el croissant sigue crocante',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/croissant_con_jamon_y_queso.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Yogurt con granola y fruta',
    descripcion: 'Bowl de yogurt natural con granola casera y fruta fresca.',
    ingredientes: [
      '2 tazas de yogurt natural',
      '1 taza de granola',
      '1 plátano en rodajas',
      '1 taza de fresas',
      '2 cucharadas de miel',
      '1 cucharada de semillas de chía',
    ],
    preparacion: [
      'Lavar y cortar las fresas en cuartos y el plátano en rodajas',
      'Colocar el yogurt natural en el fondo del bowl',
      'Agregar una capa de granola sin mezclarla, para que se mantenga crocante',
      'Acomodar la fruta fresca encima ordenada por tipo',
      'Espolvorear las semillas de chía',
      'Rociar con miel al gusto',
      'Servir de inmediato para que la granola no se ablande',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/yogurt_con_granola_y_fruta.jpg',
    bebida: 'Jugo de naranja',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Ensalada de frutas',
    descripcion: 'Mezcla de frutas frescas de estación con miel y yogurt.',
    ingredientes: [
      '1 papaya pequeña',
      '2 plátanos',
      '1 taza de piña en cubos',
      '1 manzana',
      '2 cucharadas de miel',
      '1 taza de yogurt',
    ],
    preparacion: [
      'Lavar y pelar todas las frutas antes de empezar a cortarlas',
      'Cortar la papaya y la piña en cubos del mismo tamaño',
      'Cortar la manzana con cáscara y rociarla con limón para que no se oxide',
      'Cortar el plátano al final para que no se ponga oscuro',
      'Mezclar todas las frutas en un bowl con movimientos suaves',
      'Agregar la miel y mezclar con cuidado',
      'Servir con yogurt encima y granola si se desea',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/ensalada_de_frutas.jpg',
    bebida: 'Jugo surtido',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Avena con manzana',
    descripcion: 'Bowl de avena cocida con manzana rallada y canela.',
    ingredientes: [
      '1 taza de avena en hojuelas',
      '2 tazas de leche',
      '2 manzanas ralladas',
      '1 cucharadita de canela',
      '2 cucharadas de miel',
      '1/4 taza de pasas',
    ],
    preparacion: [
      'Calentar la leche con la canela a fuego medio',
      'Agregar la avena en hojuelas removiendo para que no se apelmace',
      'Cocinar 6 minutos removiendo hasta que espese',
      'Rallar las manzanas con cáscara e incorporarlas a la olla',
      'Cocinar 3 minutos más para que la manzana se integre',
      'Agregar las pasas y endulzar con miel',
      'Servir caliente en bowl con un poco de canela espolvoreada',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/avena_con_manzana.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con salchicha y palta',
    descripcion: 'Pan con salchicha dorada, palta aplastada y salsa criolla.',
    ingredientes: [
      '4 panes franceses',
      '4 salchichas',
      '2 paltas maduras',
      '1 cebolla roja en pluma',
      '2 limones',
      'Sal al gusto',
    ],
    preparacion: [
      'Hacer cortes diagonales a las salchichas y dorarlas en sartén',
      'Aplastar la palta con sal, pimienta y unas gotas de limón',
      'Preparar salsa criolla con cebolla en pluma, limón y sal',
      'Abrir el pan francés y tostarlo ligeramente',
      'Untar la palta en la base del pan',
      'Colocar la salchicha dorada encima',
      'Terminar con la salsa criolla y cerrar el pan',
    ],
    tiempo_minutos: 18,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_salchicha_y_palta.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tostada con palta y tomate',
    descripcion: 'Pan integral tostado con palta, tomate cherry y aceite de oliva.',
    ingredientes: [
      '4 rebanadas de pan integral',
      '2 paltas maduras',
      '1 taza de tomates cherry',
      '2 cucharadas de aceite de oliva',
      '1 limón',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Tostar las rebanadas de pan integral hasta que queden firmes',
      'Aplastar la palta con sal, pimienta y jugo de limón',
      'Cortar los tomates cherry por la mitad',
      'Untar la palta generosamente sobre el pan tostado',
      'Acomodar los tomates cherry encima',
      'Rociar con aceite de oliva y pimienta recién molida',
      'Servir de inmediato para que la tostada no se ablande',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tostada_con_palta_y_tomate.jpg',
    bebida: 'Jugo verde',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con frejol',
    descripcion: 'Pan francés untado con frejol refrito y queso fresco.',
    ingredientes: [
      '4 panes franceses',
      '2 tazas de frejol cocido',
      '200 g de queso fresco',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      '3 cucharadas de aceite',
    ],
    preparacion: [
      'Preparar un aderezo con cebolla, ajo y ají panca hasta que suelte su aceite',
      'Agregar los frejoles cocidos y escurridos',
      'Aplastarlos con una cuchara mientras se fríen para formar una pasta',
      'Cocinar removiendo hasta que espese y se despegue de la sartén',
      'Abrir el pan francés y tostarlo ligeramente',
      'Untar el frejol refrito generosamente',
      'Colocar láminas de queso fresco encima y cerrar el pan',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_frejol.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sánguche de chicharrón',
    descripcion: 'El clásico sánguche limeño de chicharrón con camote y salsa criolla.',
    ingredientes: [
      '4 panes franceses',
      '500 g de panceta de cerdo',
      '2 camotes en rodajas',
      '1 cebolla roja en pluma',
      '2 limones',
      '1 ají limo picado',
    ],
    preparacion: [
      'Cortar la panceta en trozos y sazonarla con ajo, comino, sal y pimienta',
      'Cocinarla en olla con poca agua hasta que el agua se evapore',
      'Dejar que se fría en su propia grasa hasta quedar dorada y crocante',
      'Freír las rodajas de camote en esa misma grasa hasta caramelizar',
      'Preparar salsa criolla con cebolla en pluma, limón, ají limo y culantro',
      'Abrir el pan y colocar las rodajas de camote en la base',
      'Poner el chicharrón encima, coronar con salsa criolla y cerrar',
    ],
    tiempo_minutos: 75,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/sanguche_de_chicharron.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
];
