// Desayunos — parte 5. Sánguches de puesto, omelettes y panadería dulce.

export const parte = [
  {
    categoria_slug: 'desayunos',
    nombre: 'Sánguche de pollo a la brasa',
    descripcion: 'Pan con pollo a la brasa deshilachado, lechuga y crema de ají.',
    ingredientes: [
      '4 panes francés',
      '400 g de pollo a la brasa',
      '4 hojas de lechuga',
      '1/2 taza de crema de ají amarillo',
      '1 tomate en rodajas',
      '1/4 taza de mayonesa',
    ],
    preparacion: [
      'Deshuesar el pollo a la brasa y deshilacharlo aprovechando la piel dorada',
      'Calentarlo brevemente en sartén para que recupere su textura',
      'Licuar ají amarillo con mayonesa, un poco de leche y sal para la crema',
      'Abrir el pan francés y untar la crema de ají en la base',
      'Colocar una hoja de lechuga bien seca',
      'Acomodar el pollo deshilachado y las rodajas de tomate',
      'Cerrar el pan y servir de inmediato',
    ],
    tiempo_minutos: 18,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sanguche_de_pollo_a_la_brasa.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sánguche de lomo saltado',
    descripcion: 'Pan francés relleno de lomo saltado con papas al hilo.',
    ingredientes: [
      '4 panes franceses',
      '400 g de lomo de res en tiras',
      '1 cebolla roja en pluma',
      '2 tomates en gajos',
      '3 cucharadas de sillao',
      '1 taza de papas al hilo',
    ],
    preparacion: [
      'Cortar el lomo en tiras y sazonarlo con sal, pimienta y comino',
      'Calentar el wok a fuego muy alto hasta que humee',
      'Sellar la carne por tandas para que dore en lugar de hervir',
      'Agregar la cebolla y el tomate, y saltear a fuego vivo',
      'Verter el sillao y el vinagre, y mezclar rápido',
      'Abrir el pan francés y rellenarlo con el saltado caliente',
      'Coronar con papas al hilo y cerrar el pan',
    ],
    tiempo_minutos: 30,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/sanguche_de_lomo_saltado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sánguche de pescado frito',
    descripcion: 'Pan con filete de pescado frito, lechuga y salsa tártara.',
    ingredientes: [
      '4 panes franceses',
      '4 filetes pequeños de pescado',
      '1 taza de pan molido',
      '1 huevo batido',
      '1/2 taza de salsa tártara',
      '4 hojas de lechuga',
    ],
    preparacion: [
      'Sazonar los filetes con sal, pimienta, ajo y limón',
      'Pasarlos por harina, luego por huevo batido y finalmente por pan molido',
      'Freírlos en aceite caliente 3 minutos por lado hasta dorar',
      'Escurrirlos sobre papel absorbente',
      'Abrir el pan y untar salsa tártara en la base',
      'Colocar la lechuga y encima el filete de pescado',
      'Agregar unas gotas de limón y cerrar el pan',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sanguche_de_pescado_frito.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sánguche de chicharrón de pollo',
    descripcion: 'Pan con trozos de pollo apanado crocante y salsa criolla.',
    ingredientes: [
      '4 panes franceses',
      '400 g de pollo en trozos',
      '1 taza de chuño',
      '2 cucharadas de sillao',
      '1 cebolla roja en pluma',
      '2 limones',
    ],
    preparacion: [
      'Cortar el pollo en trozos del tamaño del pan',
      'Marinarlos con sillao, kion rallado, ajo, sal y pimienta',
      'Pasarlos por chuño presionando para que la costra se adhiera',
      'Freírlos en abundante aceite caliente hasta que queden dorados',
      'Escurrirlos sobre rejilla para mantener la crocancia',
      'Preparar salsa criolla con cebolla en pluma, limón y ají limo',
      'Rellenar el pan con el chicharrón y coronar con salsa criolla',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sanguche_de_chicharron_de_pollo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sánguche vegetariano',
    descripcion: 'Pan integral con palta, queso, tomate, lechuga y pepino.',
    ingredientes: [
      '8 rebanadas de pan integral',
      '2 paltas maduras',
      '200 g de queso fresco',
      '1 tomate en rodajas',
      '1 pepino en rodajas',
      '4 hojas de lechuga',
    ],
    preparacion: [
      'Tostar ligeramente las rebanadas de pan integral',
      'Aplastar la palta con sal, pimienta y limón',
      'Cortar el tomate y el pepino en rodajas delgadas',
      'Escurrir las rodajas sobre papel para que no humedezcan el pan',
      'Untar la palta en una rebanada y colocar el queso en láminas',
      'Acomodar la lechuga, el tomate y el pepino en capas',
      'Cerrar el sándwich, presionar suavemente y cortar en diagonal',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sanguche_vegetariano.jpg',
    bebida: 'Jugo verde',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Omelette de queso',
    descripcion: 'Tortilla francesa doblada rellena de queso derretido.',
    ingredientes: [
      '6 huevos',
      '200 g de queso edam',
      '2 cucharadas de mantequilla',
      '2 cucharadas de leche',
      'Sal al gusto',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Batir los huevos con la leche, sal y pimienta hasta que queden uniformes',
      'Calentar la mantequilla en una sartén antiadherente a fuego medio bajo',
      'Verter los huevos y mover la sartén para repartirlos de manera pareja',
      'Levantar los bordes con una espátula dejando que el huevo crudo corra debajo',
      'Cuando la superficie esté casi cuajada, colocar el queso en una mitad',
      'Doblar la tortilla sobre sí misma cubriendo el relleno',
      'Cocinar un minuto más y servir de inmediato',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/omelette_de_queso.jpg',
    bebida: 'Café con leche',
    acompanamiento: 'Pan tostado',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Omelette de jamón y queso',
    descripcion: 'Tortilla de huevo rellena de jamón picado y queso.',
    ingredientes: [
      '6 huevos',
      '150 g de jamón picado',
      '150 g de queso',
      '2 cucharadas de mantequilla',
      'Perejil picado',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Picar el jamón en cubos pequeños y saltearlo brevemente',
      'Batir los huevos con sal, pimienta y perejil picado',
      'Calentar mantequilla en una sartén antiadherente',
      'Verter los huevos y cocinar a fuego bajo sin remover',
      'Repartir el jamón y el queso sobre una mitad de la tortilla',
      'Doblar la tortilla cubriendo el relleno con ayuda de una espátula',
      'Dejar un minuto más para que el queso se derrita y servir',
    ],
    tiempo_minutos: 18,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/omelette_de_jamon_y_queso.jpg',
    bebida: 'Café con leche',
    acompanamiento: 'Pan tostado',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Huevos a la rabona',
    descripcion: 'Huevos fritos servidos sobre arroz con salsa de ají panca.',
    ingredientes: [
      '4 huevos',
      '3 tazas de arroz cocido',
      '2 cucharadas de ají panca molido',
      '1 cebolla picada',
      '2 tomates picados',
      'Culantro picado',
    ],
    preparacion: [
      'Preparar un aderezo con cebolla, ajo y ají panca hasta que suelte su aceite',
      'Agregar el tomate picado y cocinar hasta que se deshaga',
      'Sazonar la salsa con sal, pimienta y comino',
      'Freír los huevos aparte dejando la yema líquida',
      'Servir el arroz caliente en el plato',
      'Colocar los huevos fritos encima del arroz',
      'Bañar con la salsa caliente y terminar con culantro picado',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/huevos_a_la_rabona.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Waffles caseros',
    descripcion: 'Waffles crocantes por fuera y suaves por dentro con miel.',
    ingredientes: [
      '2 tazas de harina',
      '2 huevos',
      '1 1/2 tazas de leche',
      '100 g de mantequilla derretida',
      '2 cucharadas de azúcar',
      '1 cucharada de polvo de hornear',
    ],
    preparacion: [
      'Separar las claras de las yemas y batir las claras a punto de nieve',
      'Mezclar la harina, el azúcar, el polvo de hornear y una pizca de sal',
      'Batir las yemas con la leche y la mantequilla derretida',
      'Unir los líquidos con los secos sin batir en exceso',
      'Incorporar las claras batidas con movimientos envolventes para dar aire',
      'Precalentar la wafflera y engrasarla ligeramente',
      'Cocinar cada waffle 4 minutos y servir con miel o manjar',
    ],
    tiempo_minutos: 35,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/waffles_caseros.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Crepes dulces',
    descripcion: 'Crepes delgadas rellenas de manjar blanco y fruta.',
    ingredientes: [
      '1 taza de harina',
      '2 huevos',
      '1 1/2 tazas de leche',
      '2 cucharadas de mantequilla derretida',
      '1 taza de manjar blanco',
      '2 plátanos en rodajas',
    ],
    preparacion: [
      'Licuar la harina con los huevos, la leche, la mantequilla y una pizca de sal',
      'Dejar reposar la mezcla 30 minutos en frío para que la harina se hidrate',
      'Calentar una sartén antiadherente a fuego medio',
      'Verter un cucharón pequeño y girar la sartén para cubrir el fondo',
      'Cocinar un minuto hasta que los bordes se despeguen, luego voltear',
      'Rellenar cada crepe con manjar blanco y rodajas de plátano',
      'Doblar en triángulo o enrollar y servir espolvoreada con azúcar impalpable',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/crepes_dulces.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Picarones',
    descripcion: 'Aros fritos de masa de zapallo y camote bañados en miel de chancaca.',
    ingredientes: [
      '500 g de zapallo',
      '300 g de camote',
      '500 g de harina',
      '20 g de levadura',
      '300 g de chancaca',
      '1 cucharadita de anís',
    ],
    preparacion: [
      'Cocinar el zapallo y el camote con anís hasta que estén muy blandos',
      'Hacerlos puré y dejarlos entibiar antes de seguir',
      'Activar la levadura en un poco del agua de cocción tibia',
      'Mezclar el puré con la harina y la levadura hasta formar una masa pegajosa',
      'Dejar leudar tapada durante dos horas hasta que burbujee',
      'Con las manos mojadas tomar porciones y formar aros al echarlos al aceite',
      'Freír hasta dorar y servir bañados con miel de chancaca caliente',
    ],
    tiempo_minutos: 180,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/picarones.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Miel de chancaca',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Buñuelos',
    descripcion: 'Masa frita esponjosa espolvoreada con azúcar y canela.',
    ingredientes: [
      '2 tazas de harina',
      '3 huevos',
      '1 taza de leche',
      '2 cucharadas de azúcar',
      '1 cucharada de polvo de hornear',
      'Aceite para freír',
    ],
    preparacion: [
      'Mezclar la harina con el azúcar, el polvo de hornear y una pizca de sal',
      'Batir los huevos con la leche',
      'Unir los líquidos con los secos hasta obtener una masa espesa y pegajosa',
      'Dejar reposar 20 minutos para que la masa gane cuerpo',
      'Calentar abundante aceite a fuego medio, sin que humee',
      'Echar cucharadas de masa al aceite y freír hasta que doren e inflen',
      'Escurrir sobre papel y espolvorear con azúcar y canela',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/bunuelos.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Churros con chocolate',
    descripcion: 'Churros crocantes rellenos de manjar con chocolate caliente.',
    ingredientes: [
      '1 taza de harina',
      '1 taza de agua',
      '50 g de mantequilla',
      '1 taza de manjar blanco',
      '200 g de chocolate',
      'Azúcar y canela para espolvorear',
    ],
    preparacion: [
      'Hervir el agua con la mantequilla y una pizca de sal',
      'Retirar del fuego y agregar la harina de golpe, removiendo con energía',
      'Volver al fuego y cocinar hasta que la masa se despegue de la olla',
      'Dejar entibiar y colocar la masa en una manga con boquilla rizada',
      'Formar churros directamente sobre el aceite caliente y freír hasta dorar',
      'Escurrir, espolvorear con azúcar y canela, y rellenar con manjar',
      'Servir con chocolate caliente espeso para mojar',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/churros_con_chocolate.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Rosquitas de manteca',
    descripcion: 'Rosquitas horneadas de manteca con anís, crocantes y aromáticas.',
    ingredientes: [
      '500 g de harina',
      '200 g de manteca',
      '150 g de azúcar',
      '2 huevos',
      '1 cucharada de anís',
      '1 cucharadita de polvo de hornear',
    ],
    preparacion: [
      'Hervir el anís en un poco de agua y colar la infusión',
      'Batir la manteca con el azúcar hasta que quede cremosa',
      'Agregar los huevos uno a uno sin dejar de batir',
      'Incorporar la harina cernida con el polvo de hornear y la infusión de anís',
      'Amasar hasta obtener una masa suave que no se pegue a las manos',
      'Formar rollitos y unir los extremos para armar las rosquitas',
      'Hornear a 180 grados por 18 minutos hasta que doren ligeramente',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/rosquitas_de_manteca.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Keke de zanahoria',
    descripcion: 'Bizcocho húmedo de zanahoria rallada con nueces y canela.',
    ingredientes: [
      '3 zanahorias ralladas',
      '2 tazas de harina',
      '1 taza de azúcar rubia',
      '3 huevos',
      '1 taza de aceite',
      '1 cucharadita de canela',
    ],
    preparacion: [
      'Rallar finamente las zanahorias para que se integren bien en la masa',
      'Batir los huevos con el azúcar hasta que la mezcla blanquee',
      'Agregar el aceite en hilo sin dejar de batir',
      'Incorporar la zanahoria rallada y mezclar',
      'Añadir la harina cernida con polvo de hornear, canela y una pizca de sal',
      'Mezclar con movimientos envolventes y agregar las nueces picadas',
      'Hornear a 180 grados por 45 minutos hasta que el palillo salga limpio',
    ],
    tiempo_minutos: 65,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/keke_de_zanahoria.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Galletas de avena',
    descripcion: 'Galletas caseras de avena con pasas, ideales para la lonchera.',
    ingredientes: [
      '2 tazas de avena en hojuelas',
      '1 taza de harina',
      '150 g de mantequilla',
      '1 taza de azúcar rubia',
      '1 huevo',
      '1/2 taza de pasas',
    ],
    preparacion: [
      'Batir la mantequilla blanda con el azúcar rubia hasta que quede cremosa',
      'Agregar el huevo y batir hasta integrar por completo',
      'Incorporar la harina cernida con polvo de hornear, canela y sal',
      'Agregar la avena en hojuelas y las pasas, mezclando con espátula',
      'Formar bolitas y aplastarlas ligeramente sobre la bandeja',
      'Dejar espacio entre cada una porque se expanden al hornear',
      'Hornear a 180 grados por 12 minutos y dejar enfriar sobre rejilla',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/galletas_de_avena.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan de camote',
    descripcion: 'Pan suave y ligeramente dulce elaborado con puré de camote.',
    ingredientes: [
      '500 g de camote cocido',
      '1 kg de harina',
      '150 g de azúcar',
      '25 g de levadura',
      '100 g de manteca',
      '1 cucharadita de anís',
    ],
    preparacion: [
      'Cocinar el camote y hacerlo puré mientras esté caliente',
      'Dejarlo entibiar para que no mate la levadura',
      'Activar la levadura en agua tibia con una cucharada de azúcar',
      'Mezclar la harina con el puré de camote, el azúcar, la manteca y el anís',
      'Agregar la levadura activada y amasar hasta obtener una masa suave',
      'Dejar leudar tapada hasta que doble su volumen',
      'Formar los panes, dejar leudar de nuevo y hornear a 190 grados 20 minutos',
    ],
    tiempo_minutos: 160,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pan_de_camote.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan de papa',
    descripcion: 'Pan serrano elaborado con papa sancochada, húmedo y duradero.',
    ingredientes: [
      '500 g de papa cocida',
      '1 kg de harina',
      '25 g de levadura',
      '2 cucharaditas de sal',
      '100 g de manteca',
      '2 tazas de agua tibia',
    ],
    preparacion: [
      'Sancochar las papas, pelarlas y prensarlas hasta obtener un puré fino',
      'Dejar entibiar el puré antes de mezclarlo con la levadura',
      'Activar la levadura en agua tibia con una pizca de azúcar',
      'Mezclar la harina con el puré de papa, la sal y la manteca',
      'Agregar la levadura y amasar largo rato hasta que la masa quede elástica',
      'Dejar leudar hasta que doble su volumen, formar los panes y leudar otra vez',
      'Hornear a 200 grados por 22 minutos hasta que la corteza suene hueca',
    ],
    tiempo_minutos: 170,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pan_de_papa.jpg',
    bebida: 'Mate de coca',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pesque de quinua',
    descripcion: 'Plato puneño de quinua cocida con leche y queso, cremoso y contundente.',
    ingredientes: [
      '2 tazas de quinua',
      '1 litro de leche',
      '250 g de queso fresco',
      '60 g de mantequilla',
      'Sal al gusto',
      'Agua para cocinar',
    ],
    preparacion: [
      'Lavar la quinua frotándola varias veces hasta quitar toda la saponina',
      'Cocinarla en agua con sal hasta que el grano reviente y suelte su almidón',
      'Escurrir el exceso de agua dejando la quinua húmeda',
      'Agregar la leche poco a poco removiendo a fuego bajo',
      'Incorporar la mantequilla y seguir removiendo hasta que quede cremoso',
      'Añadir el queso fresco desmenuzado al final',
      'Servir caliente, tradicionalmente acompañado de queso frito o huevo',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pesque_de_quinua.jpg',
    bebida: 'Mate de muña',
    acompanamiento: 'Queso frito',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Kispiño',
    descripcion: 'Panecillo puneño de quinua amasada con grasa, seco y duradero.',
    ingredientes: [
      '3 tazas de harina de quinua',
      '1/2 taza de manteca',
      '1 cucharadita de sal',
      '1 taza de agua tibia',
      '1 cucharadita de anís',
      'Ceniza de leña opcional',
    ],
    preparacion: [
      'Mezclar la harina de quinua con la sal y el anís',
      'Incorporar la manteca frotando con las manos hasta formar un arenado',
      'Agregar el agua tibia poco a poco hasta formar una masa firme',
      'Amasar hasta que la masa quede compacta y no se resquebraje',
      'Formar bolitas y aplastarlas dándoles forma ovalada',
      'Cocinarlas al vapor durante 30 minutos',
      'Dejarlas secar al aire para que se conserven varios días',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/kispino.jpg',
    bebida: 'Mate de coca',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sopa de pan cusqueña',
    descripcion: 'Sopa serrana de pan remojado con queso, huevo y hierbas.',
    ingredientes: [
      '6 panes duros en rodajas',
      '4 huevos',
      '200 g de queso fresco',
      '1 taza de leche evaporada',
      '1 cebolla picada',
      'Hierbabuena al gusto',
    ],
    preparacion: [
      'Tostar las rodajas de pan duro en el horno hasta que queden crocantes',
      'Preparar un aderezo con cebolla, ajo y un poco de ají panca',
      'Agregar caldo de carne o verduras y llevar a hervor',
      'Incorporar las rodajas de pan tostado y dejar que se ablanden',
      'Escalfar los huevos dentro de la sopa',
      'Verter la leche evaporada y agregar el queso fresco en cubos',
      'Terminar con hierbabuena picada y servir bien caliente',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sopa_de_pan_cusquena.jpg',
    bebida: 'Mate de coca',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Lawa de maíz',
    descripcion: 'Crema andina espesa de maíz molido con queso y hierbas.',
    ingredientes: [
      '2 tazas de harina de maíz',
      '1 litro de leche',
      '200 g de queso fresco',
      '1 cebolla picada',
      '2 cucharadas de ají amarillo molido',
      'Huacatay al gusto',
    ],
    preparacion: [
      'Preparar un aderezo con cebolla, ajo y ají amarillo',
      'Agregar agua o caldo y llevar a hervor',
      'Disolver la harina de maíz en agua fría para evitar grumos',
      'Verterla en hilo sobre el caldo hirviendo removiendo sin parar',
      'Cocinar a fuego bajo 20 minutos removiendo con frecuencia',
      'Agregar la leche y el queso fresco desmenuzado',
      'Terminar con huacatay picado y servir bien caliente',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/lawa_de_maiz.jpg',
    bebida: 'Mate de muña',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tarwi con cancha',
    descripcion: 'Tarwi desamargado con cebolla y limón, servido con cancha tostada.',
    ingredientes: [
      '2 tazas de tarwi desamargado',
      '1 taza de cancha tostada',
      '1 cebolla roja picada',
      '2 tomates picados',
      '3 limones',
      'Culantro picado',
    ],
    preparacion: [
      'Verificar que el tarwi esté bien desamargado probando un grano',
      'Escurrirlo muy bien y secarlo ligeramente',
      'Picar la cebolla y enjuagarla en agua fría para quitarle el picor',
      'Cortar el tomate en cubos pequeños',
      'Mezclar el tarwi con la cebolla, el tomate y el culantro',
      'Aliñar con jugo de limón, sal, pimienta y un chorrito de aceite',
      'Servir con abundante cancha tostada al costado',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tarwi_con_cancha.jpg',
    bebida: 'Mate de coca',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Api con buñuelo',
    descripcion: 'Bebida-desayuno espesa de maíz morado acompañada de buñuelo frito.',
    ingredientes: [
      '2 tazas de harina de maíz morado',
      '1 litro de agua',
      '1 taza de azúcar',
      '1 palito de canela',
      '2 tazas de harina para el buñuelo',
      '1 cucharadita de anís',
    ],
    preparacion: [
      'Disolver la harina de maíz morado en agua fría removiendo bien',
      'Llevar a fuego medio con la canela y el clavo, removiendo sin parar',
      'Cocinar 20 minutos hasta que espese y pierda el sabor a crudo',
      'Endulzar con azúcar y agregar cáscara de naranja para aromatizar',
      'Preparar la masa del buñuelo con harina, levadura, anís y agua tibia',
      'Dejarla leudar y freír porciones estiradas en aceite caliente',
      'Servir el api bien caliente en taza con el buñuelo al costado',
    ],
    tiempo_minutos: 90,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/api_con_bunuelo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con pate',
    descripcion: 'Pan francés untado con paté de hígado y cebolla encurtida.',
    ingredientes: [
      '4 panes franceses',
      '200 g de paté de hígado',
      '1 cebolla roja en pluma',
      '2 limones',
      '4 hojas de lechuga',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Sacar el paté del frío unos minutos antes para que se unte con facilidad',
      'Cortar la cebolla en pluma muy fina',
      'Encurtirla con limón, sal y un poco de pimienta',
      'Abrir el pan francés y tostarlo ligeramente',
      'Untar el paté generosamente sobre la miga tibia',
      'Colocar una hoja de lechuga encima',
      'Terminar con la cebolla encurtida escurrida y cerrar el pan',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_pate.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con pollo deshilachado y palta',
    descripcion: 'Pan con pollo deshilachado, palta y crema de ají amarillo.',
    ingredientes: [
      '4 panes franceses',
      '400 g de pollo cocido',
      '2 paltas maduras',
      '3 cucharadas de ají amarillo molido',
      '1/3 taza de mayonesa',
      '1 limón',
    ],
    preparacion: [
      'Cocinar la pechuga en agua con sal, ajo y laurel, y dejarla enfriar en su caldo',
      'Deshilacharla siguiendo la fibra de la carne',
      'Mezclar la mayonesa con el ají amarillo para hacer una crema',
      'Unir el pollo con parte de esa crema y sazonar',
      'Aplastar la palta con sal, pimienta y limón',
      'Abrir el pan, untar la palta en la base',
      'Colocar el pollo encima, agregar más crema de ají y cerrar',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_pollo_deshilachado_y_palta.jpg',
    bebida: 'Jugo de maracuyá',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tostada con manjar blanco',
    descripcion: 'Pan de molde tostado con manjar blanco y plátano en rodajas.',
    ingredientes: [
      '8 rebanadas de pan de molde',
      '1 taza de manjar blanco',
      '2 plátanos en rodajas',
      '20 g de mantequilla',
      '1 cucharadita de canela',
      '2 cucharadas de nueces picadas',
    ],
    preparacion: [
      'Tostar las rebanadas de pan de molde hasta que queden crocantes',
      'Untar una capa fina de mantequilla mientras siguen calientes',
      'Dejar que la mantequilla se derrita sobre la tostada',
      'Untar el manjar blanco generosamente encima',
      'Cortar los plátanos en rodajas delgadas',
      'Acomodarlas sobre el manjar cubriendo toda la superficie',
      'Espolvorear canela y nueces picadas, y servir de inmediato',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tostada_con_manjar_blanco.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con tortilla de raya',
    descripcion: 'Pan norteño relleno de tortilla de raya con zarza criolla.',
    ingredientes: [
      '4 panes franceses',
      '300 g de raya seca desalada',
      '5 huevos',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      '1 cebolla roja en pluma',
    ],
    preparacion: [
      'Remojar la raya seca varias horas cambiando el agua para desalarla',
      'Sancocharla brevemente y desmenuzarla retirando los cartílagos',
      'Preparar un aderezo con cebolla, ajo y ají panca',
      'Agregar la raya desmenuzada y saltear para que tome sabor',
      'Batir los huevos, mezclarlos con la preparación fría y cuajar la tortilla en sartén',
      'Cortar porciones del tamaño del pan',
      'Rellenar el pan y coronar con zarza criolla de cebolla y limón',
    ],
    tiempo_minutos: 55,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pan_con_tortilla_de_raya.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: null,
    video_url: null,
  },
];
