// Desayunos — parte 6. Huevos al plato, tortillas, panes de grano andino y dulces.

export const parte = [
  {
    categoria_slug: 'desayunos',
    nombre: 'Huevos al plato',
    descripcion: 'Huevos horneados en fuente individual con tomate, queso y orégano.',
    ingredientes: [
      '4 huevos',
      '3 tomates picados',
      '150 g de queso fresco',
      '1 cebolla picada',
      '2 cucharadas de aceite de oliva',
      'Orégano al gusto',
    ],
    preparacion: [
      'Saltear la cebolla y el ajo en aceite de oliva hasta que transparenten',
      'Agregar el tomate picado y cocinar hasta que se deshaga en salsa',
      'Sazonar con sal, pimienta y orégano',
      'Repartir la salsa en fuentes individuales aptas para horno',
      'Hacer un hueco al centro y romper un huevo dentro de cada fuente',
      'Espolvorear queso fresco desmenuzado alrededor de la yema',
      'Hornear a 190 grados por 10 minutos hasta que la clara cuaje y la yema siga líquida',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/huevos_al_plato.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Pan tostado',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Huevo escalfado con pan',
    descripcion: 'Huevo pochado en agua con vinagre servido sobre pan tostado.',
    ingredientes: [
      '4 huevos muy frescos',
      '4 rebanadas de pan',
      '2 cucharadas de vinagre blanco',
      '20 g de mantequilla',
      'Sal al gusto',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Calentar agua en una olla honda sin dejar que llegue a hervir fuerte',
      'Agregar el vinagre, que ayuda a que la clara cuaje alrededor de la yema',
      'Romper cada huevo en una taza pequeña antes de echarlo al agua',
      'Crear un remolino con una cuchara y deslizar el huevo al centro',
      'Cocinar 3 minutos y retirar con espumadera, escurriendo bien',
      'Tostar el pan y untarlo con mantequilla',
      'Colocar el huevo encima, salpimentar y servir de inmediato',
    ],
    tiempo_minutos: 15,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/huevo_escalfado_con_pan.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tortilla de atún',
    descripcion: 'Tortilla de huevo con atún, cebolla y perejil.',
    ingredientes: [
      '6 huevos',
      '2 latas de atún',
      '1 cebolla picada',
      'Perejil picado',
      '2 cucharadas de aceite',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Escurrir muy bien el atún para que la tortilla no quede húmeda',
      'Saltear la cebolla picada hasta que transparente',
      'Agregar el atún desmenuzado y saltear un par de minutos',
      'Batir los huevos con sal, pimienta y perejil picado',
      'Mezclar el atún con el huevo batido',
      'Verter en sartén caliente y cocinar a fuego bajo hasta cuajar la base',
      'Voltear con ayuda de un plato y dorar del otro lado',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tortilla_de_atun.jpg',
    bebida: 'Jugo de naranja',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tortilla de fideos',
    descripcion: 'Tortilla hecha con fideos sobrantes, huevo y queso.',
    ingredientes: [
      '3 tazas de fideos cocidos',
      '5 huevos',
      '150 g de queso',
      '1/2 cebolla picada',
      'Perejil picado',
      '2 cucharadas de aceite',
    ],
    preparacion: [
      'Usar fideos cocidos del día anterior, que se mantienen más firmes',
      'Saltear la cebolla picada hasta que transparente',
      'Batir los huevos con sal, pimienta y perejil',
      'Mezclar los fideos con el huevo batido y el queso rallado',
      'Calentar aceite en una sartén y verter la mezcla',
      'Cocinar a fuego bajo hasta que la base esté firme y dorada',
      'Voltear con ayuda de un plato y dorar del otro lado',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tortilla_de_fideos.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tortitas de quinua',
    descripcion: 'Tortitas fritas de quinua cocida con queso y verduras.',
    ingredientes: [
      '2 tazas de quinua cocida',
      '2 huevos',
      '150 g de queso fresco',
      '1 zanahoria rallada',
      '1/2 taza de harina',
      'Aceite para freír',
    ],
    preparacion: [
      'Cocinar la quinua bien lavada y dejarla enfriar para que no quede aguada',
      'Rallar la zanahoria y exprimirla para quitar el exceso de agua',
      'Mezclar la quinua con los huevos batidos y la harina',
      'Agregar el queso desmenuzado y la zanahoria rallada',
      'Sazonar con sal, pimienta y perejil picado',
      'Formar tortitas con las manos y freírlas en aceite caliente',
      'Dorar 3 minutos por lado y escurrir sobre papel absorbente',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tortitas_de_quinua.jpg',
    bebida: 'Jugo verde',
    acompanamiento: 'Salsa de huacatay',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Panqueques de quinua',
    descripcion: 'Panqueques nutritivos hechos con harina de quinua y plátano.',
    ingredientes: [
      '1 taza de harina de quinua',
      '1 taza de harina',
      '2 huevos',
      '2 tazas de leche',
      '2 plátanos maduros',
      '1 cucharada de polvo de hornear',
    ],
    preparacion: [
      'Aplastar los plátanos maduros hasta hacerlos puré',
      'Mezclar las dos harinas con el polvo de hornear y una pizca de sal',
      'Batir los huevos con la leche y el puré de plátano',
      'Unir los líquidos con los secos sin batir en exceso',
      'Dejar reposar la mezcla 10 minutos',
      'Cocinar cada panqueque en sartén antiadherente a fuego medio',
      'Voltear cuando aparezcan burbujas y servir con miel',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/panqueques_de_quinua.jpg',
    bebida: 'Jugo de papaya',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan de kiwicha',
    descripcion: 'Pan integral enriquecido con harina de kiwicha, nutritivo y aromático.',
    ingredientes: [
      '700 g de harina integral',
      '300 g de harina de kiwicha',
      '25 g de levadura',
      '2 cucharadas de miel',
      '3 cucharadas de aceite',
      '2 tazas de agua tibia',
    ],
    preparacion: [
      'Activar la levadura en agua tibia con la miel hasta que espume',
      'Mezclar la harina integral con la harina de kiwicha y la sal',
      'Agregar la levadura activada y el aceite',
      'Amasar durante 12 minutos hasta obtener una masa elástica',
      'Dejar leudar tapada hasta que doble su volumen',
      'Formar los panes y dejarlos leudar otra media hora en la bandeja',
      'Hornear a 200 grados por 25 minutos hasta que suenen huecos al golpearlos',
    ],
    tiempo_minutos: 160,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pan_de_kiwicha.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Barritas de kiwicha',
    descripcion: 'Barras energéticas de kiwicha tostada con miel y frutos secos.',
    ingredientes: [
      '3 tazas de kiwicha pop',
      '1 taza de miel',
      '1/2 taza de pasas',
      '1/2 taza de nueces picadas',
      '2 cucharadas de mantequilla',
      '1/4 taza de ajonjolí',
    ],
    preparacion: [
      'Tostar la kiwicha en sartén caliente hasta que reviente como palomitas',
      'Tostar ligeramente el ajonjolí y las nueces picadas',
      'Calentar la miel con la mantequilla hasta que burbujee',
      'Cocinar la miel dos minutos para que alcance punto de caramelo suave',
      'Verter la miel caliente sobre la kiwicha y los frutos secos, mezclando rápido',
      'Volcar la mezcla en un molde forrado y presionar con fuerza para compactarla',
      'Dejar enfriar por completo y cortar en barras',
    ],
    tiempo_minutos: 40,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/barritas_de_kiwicha.jpg',
    bebida: 'Jugo de naranja',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con mortadela',
    descripcion: 'Pan francés con mortadela, mayonesa y lechuga.',
    ingredientes: [
      '4 panes franceses',
      '300 g de mortadela en lonjas',
      '1/3 taza de mayonesa',
      '4 hojas de lechuga',
      '1 tomate en rodajas',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Cortar la mortadela en lonjas delgadas',
      'Dorarlas brevemente en sartén si se prefiere caliente',
      'Abrir el pan francés por la mitad',
      'Untar mayonesa en la miga del pan',
      'Colocar una hoja de lechuga bien seca',
      'Acomodar las lonjas de mortadela dobladas para dar volumen',
      'Agregar tomate, salpimentar y cerrar el pan',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_mortadela.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con queso crema y mermelada',
    descripcion: 'Pan tostado con queso crema y mermelada de fresa.',
    ingredientes: [
      '4 panes franceses',
      '200 g de queso crema',
      '1/2 taza de mermelada de fresa',
      '20 g de mantequilla',
      '1 cucharadita de ralladura de limón',
      'Sal al gusto',
    ],
    preparacion: [
      'Sacar el queso crema del frío 10 minutos antes para que se unte fácil',
      'Mezclarlo con una pizca de sal y ralladura de limón',
      'Abrir el pan francés y tostarlo hasta que la corteza quede crocante',
      'Untar una capa fina de mantequilla sobre la miga caliente',
      'Extender el queso crema en una capa gruesa',
      'Agregar la mermelada de fresa encima sin mezclarla',
      'Servir de inmediato mientras el pan sigue tibio',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_queso_crema_y_mermelada.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con miel y mantequilla',
    descripcion: 'Pan tostado con mantequilla derretida y miel de abeja.',
    ingredientes: [
      '4 panes franceses',
      '60 g de mantequilla',
      '1/2 taza de miel de abeja',
      '1 cucharadita de canela',
      '2 cucharadas de nueces picadas',
      'Sal al gusto',
    ],
    preparacion: [
      'Calentar el pan francés en horno o tostadora hasta que quede crocante',
      'Abrirlo por la mitad mientras aún está caliente',
      'Untar la mantequilla de inmediato para que se derrita sobre la miga',
      'Rociar la miel generosamente sobre la mantequilla derretida',
      'Espolvorear una pizca de canela',
      'Agregar las nueces picadas para dar textura',
      'Servir de inmediato acompañado de leche o café',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_miel_y_mantequilla.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con huancaína',
    descripcion: 'Pan francés untado con salsa huancaína y huevo duro.',
    ingredientes: [
      '4 panes franceses',
      '4 ajíes amarillos',
      '200 g de queso fresco',
      '1 taza de leche evaporada',
      '6 galletas de soda',
      '2 huevos duros',
    ],
    preparacion: [
      'Despepitar los ajíes amarillos y freírlos con cebolla y ajo hasta ablandar',
      'Licuar ese sofrito con el queso fresco, la leche y las galletas',
      'Ajustar la textura con más leche si la crema queda muy espesa',
      'Rectificar la sal y dejar enfriar un poco',
      'Abrir el pan francés y tostarlo ligeramente',
      'Untar la salsa huancaína generosamente',
      'Colocar rodajas de huevo duro y aceituna encima',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_huancaina.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Papas doradas con huevo',
    descripcion: 'Papas en cubos doradas en sartén con huevo revuelto y cebolla china.',
    ingredientes: [
      '5 papas en cubos',
      '4 huevos',
      '1 cebolla picada',
      '3 tallos de cebolla china',
      '3 cucharadas de aceite',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Sancochar las papas en cubos hasta que estén tiernas sin deshacerse',
      'Escurrirlas y dejarlas secar unos minutos',
      'Calentar aceite en una sartén amplia y dorar las papas sin moverlas mucho',
      'Agregar la cebolla picada y cocinar hasta que transparente',
      'Batir los huevos con sal y pimienta',
      'Verterlos sobre las papas y revolver suavemente hasta que cuajen',
      'Terminar con cebolla china picada y servir caliente',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/papas_doradas_con_huevo.jpg',
    bebida: 'Café con leche',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Yuca con huevo',
    descripcion: 'Yuca sancochada salteada con huevo revuelto y cebolla china.',
    ingredientes: [
      '800 g de yuca',
      '4 huevos',
      '1 cebolla picada',
      '3 tallos de cebolla china',
      '3 cucharadas de aceite',
      'Sal al gusto',
    ],
    preparacion: [
      'Pelar la yuca y sancocharla en agua con sal hasta que esté tierna',
      'Retirar la fibra central y cortarla en cubos',
      'Calentar aceite en una sartén y dorar la yuca por todos lados',
      'Agregar la cebolla picada y cocinar hasta que transparente',
      'Batir los huevos con sal y pimienta',
      'Verterlos sobre la yuca y revolver hasta que cuajen',
      'Terminar con cebolla china picada y servir con salsa de ají',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/yuca_con_huevo.jpg',
    bebida: 'Café pasado',
    acompanamiento: 'Salsa de ají',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Plátano frito con huevo',
    descripcion: 'Plátano maduro frito servido con huevo frito y arroz.',
    ingredientes: [
      '3 plátanos maduros',
      '4 huevos',
      '2 tazas de arroz cocido',
      '4 cucharadas de aceite',
      'Sal al gusto',
      'Ají al gusto',
    ],
    preparacion: [
      'Elegir plátanos bien maduros, con la cáscara manchada',
      'Pelarlos y cortarlos en tiras diagonales de un centímetro',
      'Freírlos en aceite caliente hasta que caramelicen por fuera',
      'Escurrirlos sobre papel absorbente',
      'Freír los huevos en la misma sartén dejando la yema líquida',
      'Calentar el arroz cocido',
      'Servir el arroz con el plátano y los huevos encima',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/platano_frito_con_huevo.jpg',
    bebida: 'Chapo',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Chifles con queso',
    descripcion: 'Hojuelas fritas de plátano verde servidas con queso fresco.',
    ingredientes: [
      '4 plátanos verdes',
      '250 g de queso fresco',
      'Aceite para freír',
      'Sal al gusto',
      '1 limón',
      'Ají charapita al gusto',
    ],
    preparacion: [
      'Pelar los plátanos verdes haciendo un corte a lo largo de la cáscara',
      'Cortarlos en láminas muy delgadas con mandolina o cuchillo afilado',
      'Remojar las láminas unos minutos en agua con sal',
      'Secarlas muy bien con papel para que no salte el aceite',
      'Freírlas en abundante aceite caliente por tandas hasta que doren',
      'Escurrir sobre papel absorbente y salar de inmediato',
      'Servir con queso fresco en cubos y ají charapita al costado',
    ],
    tiempo_minutos: 35,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chifles_con_queso.jpg',
    bebida: 'Refresco de cocona',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Camote sancochado con queso',
    descripcion: 'Camote cocido servido tibio con queso fresco y miel.',
    ingredientes: [
      '4 camotes medianos',
      '250 g de queso fresco',
      '3 cucharadas de miel',
      '1 palito de canela',
      'Sal al gusto',
      'Agua para cocinar',
    ],
    preparacion: [
      'Lavar bien los camotes sin pelarlos para que no absorban agua',
      'Colocarlos en una olla con agua, sal y un palito de canela',
      'Hervir entre 25 y 30 minutos hasta que se pinchen con facilidad',
      'Escurrirlos y dejarlos entibiar un momento',
      'Pelarlos y cortarlos en rodajas gruesas',
      'Acomodarlos en el plato con el queso fresco al costado',
      'Rociar con un poco de miel y servir tibio',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/camote_sancochado_con_queso.jpg',
    bebida: 'Mate de muña',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Sopa de fideos con huevo',
    descripcion: 'Caldo ligero de fideos con huevo batido en hebras y cebolla china.',
    ingredientes: [
      '150 g de fideos cabello de ángel',
      '1.5 litros de caldo de pollo',
      '3 huevos',
      '3 tallos de cebolla china',
      '1 trozo de kion',
      'Sal al gusto',
    ],
    preparacion: [
      'Calentar el caldo de pollo con el kion y sal hasta que hierva',
      'Retirar el kion una vez que haya perfumado el caldo',
      'Agregar los fideos y cocinarlos apenas 3 minutos',
      'Batir los huevos en un bowl aparte',
      'Verterlos en hilo fino sobre el caldo hirviendo sin remover al inicio',
      'Esperar unos segundos y remover suavemente para formar hebras',
      'Servir con cebolla china picada y unas gotas de sillao',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sopa_de_fideos_con_huevo.jpg',
    bebida: 'Té verde',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con salpicón de pollo',
    descripcion: 'Pan relleno de pollo deshilachado con verduras picadas y mayonesa.',
    ingredientes: [
      '4 panes franceses',
      '400 g de pollo cocido',
      '1 zanahoria cocida en cubos',
      '1 taza de arvejas cocidas',
      '1/2 taza de mayonesa',
      '1 limón',
    ],
    preparacion: [
      'Cocinar la pechuga de pollo y dejarla enfriar en su caldo',
      'Deshilacharla siguiendo la fibra de la carne',
      'Cocinar la zanahoria en cubos y las arvejas, y enfriarlas',
      'Mezclar el pollo con las verduras y la mayonesa',
      'Sazonar con sal, pimienta y unas gotas de limón',
      'Abrir el pan francés por la mitad',
      'Rellenar con el salpicón y servir de inmediato',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_salpicon_de_pollo.jpg',
    bebida: 'Jugo surtido',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Tequeños de queso',
    descripcion: 'Bastones de queso envueltos en masa de wantán y fritos.',
    ingredientes: [
      '20 masas de wantán',
      '400 g de queso edam en bastones',
      '1 huevo batido',
      'Aceite para freír',
      '1/2 taza de guacamole',
      'Sal al gusto',
    ],
    preparacion: [
      'Cortar el queso en bastones del largo de la masa de wantán',
      'Colocar un bastón en una esquina de la masa',
      'Enrollar en diagonal cubriendo bien el queso por todos lados',
      'Sellar el borde final con huevo batido presionando con el dedo',
      'Verificar que no queden aberturas para que el queso no se escape al freír',
      'Freír en abundante aceite caliente hasta que doren de manera pareja',
      'Escurrir sobre papel y servir con guacamole',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tequenos_de_queso.jpg',
    bebida: 'Jugo de maracuyá',
    acompanamiento: 'Guacamole',
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pionono de manjar',
    descripcion: 'Bizcocho enrollado relleno de manjar blanco y espolvoreado con azúcar.',
    ingredientes: [
      '5 huevos',
      '1 taza de azúcar',
      '1 taza de harina',
      '1 taza de manjar blanco',
      '1 cucharadita de vainilla',
      'Azúcar impalpable para espolvorear',
    ],
    preparacion: [
      'Batir los huevos con el azúcar hasta que tripliquen su volumen y blanqueen',
      'Incorporar la harina cernida con movimientos envolventes para no perder aire',
      'Verter en una bandeja forrada con papel, extendiendo en capa delgada',
      'Hornear a 200 grados solo 10 minutos para que quede flexible',
      'Volcar el bizcocho caliente sobre un paño espolvoreado con azúcar',
      'Enrollarlo con el paño mientras está caliente y dejar enfriar enrollado',
      'Desenrollar, untar el manjar blanco, volver a enrollar y espolvorear azúcar',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pionono_de_manjar.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Alfajores de maicena',
    descripcion: 'Galletas suaves de maicena unidas con manjar blanco y coco.',
    ingredientes: [
      '2 tazas de maicena',
      '1 taza de harina',
      '200 g de mantequilla',
      '3 yemas',
      '1 taza de manjar blanco',
      '1 taza de coco rallado',
    ],
    preparacion: [
      'Batir la mantequilla con el azúcar hasta obtener una crema pálida',
      'Agregar las yemas una a una batiendo entre cada adición',
      'Incorporar la maicena y la harina cernidas con polvo de hornear',
      'Formar una masa suave sin amasar en exceso y dejarla reposar en frío',
      'Estirar la masa y cortar discos pequeños',
      'Hornear a 170 grados por 12 minutos sin dejar que doren',
      'Unir los discos con manjar blanco y pasar los bordes por coco rallado',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/alfajores_de_maicena.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Queque de vainilla',
    descripcion: 'Bizcocho clásico de vainilla, esponjoso y sencillo.',
    ingredientes: [
      '2 tazas de harina',
      '1 taza de azúcar',
      '4 huevos',
      '200 g de mantequilla',
      '1 cucharada de esencia de vainilla',
      '1 cucharada de polvo de hornear',
    ],
    preparacion: [
      'Sacar todos los ingredientes del frío 30 minutos antes para que estén a temperatura ambiente',
      'Batir la mantequilla con el azúcar hasta que quede muy cremosa y pálida',
      'Agregar los huevos uno a uno batiendo bien entre cada adición',
      'Incorporar la esencia de vainilla',
      'Añadir la harina cernida con el polvo de hornear en tres tandas',
      'Mezclar con movimientos envolventes sin batir de más',
      'Hornear a 180 grados por 40 minutos hasta que el palillo salga limpio',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/queque_de_vainilla.jpg',
    bebida: 'Leche con café',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Muffins de arándanos',
    descripcion: 'Panecillos individuales esponjosos con arándanos frescos.',
    ingredientes: [
      '2 tazas de harina',
      '3/4 taza de azúcar',
      '2 huevos',
      '1 taza de leche',
      '100 g de mantequilla derretida',
      '1 taza de arándanos',
    ],
    preparacion: [
      'Mezclar la harina con el azúcar, el polvo de hornear y una pizca de sal',
      'Batir los huevos con la leche y la mantequilla derretida',
      'Verter los líquidos sobre los secos y mezclar apenas, dejando grumos',
      'No batir de más, porque eso hace que los muffins queden duros',
      'Pasar los arándanos por un poco de harina para que no se vayan al fondo',
      'Incorporarlos con espátula y repartir la mezcla en moldes de papel',
      'Hornear a 190 grados por 22 minutos hasta que doren y suban',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/muffins_de_arandanos.jpg',
    bebida: 'Café con leche',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan integral casero',
    descripcion: 'Pan de harina integral con semillas, hecho en casa.',
    ingredientes: [
      '1 kg de harina integral',
      '25 g de levadura',
      '2 cucharadas de miel',
      '3 cucharadas de aceite de oliva',
      '1/2 taza de semillas mixtas',
      '2 tazas de agua tibia',
    ],
    preparacion: [
      'Activar la levadura en agua tibia con la miel hasta que forme espuma',
      'Mezclar la harina integral con la sal y las semillas',
      'Agregar la levadura activada y el aceite de oliva',
      'Amasar durante 15 minutos: la masa integral necesita más trabajo que la blanca',
      'Dejar leudar en un bowl aceitado hasta que doble su volumen',
      'Desgasificar, formar el pan y colocarlo en molde para el segundo leudado',
      'Hornear a 210 grados por 35 minutos hasta que suene hueco al golpear la base',
    ],
    tiempo_minutos: 180,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pan_integral_casero.jpg',
    bebida: 'Café pasado',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Pan con ocopa',
    descripcion: 'Pan francés untado con crema de ocopa y papa en rodajas.',
    ingredientes: [
      '4 panes franceses',
      '1 atado de huacatay',
      '1/2 taza de maní tostado',
      '150 g de queso fresco',
      '2 papas sancochadas',
      '1 taza de leche evaporada',
    ],
    preparacion: [
      'Freír cebolla, ajo y ají mirasol hasta que estén blandos',
      'Licuar ese sofrito con el huacatay, el maní tostado y el queso fresco',
      'Agregar la leche evaporada poco a poco hasta lograr una crema espesa',
      'Rectificar la sal, que debe quedar bien marcada',
      'Sancochar las papas y cortarlas en rodajas',
      'Abrir el pan, untar la ocopa y colocar las rodajas de papa',
      'Agregar más ocopa encima y cerrar el pan',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pan_con_ocopa.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'desayunos',
    nombre: 'Wawa de pan',
    descripcion: 'Pan dulce en forma de muñeca, tradicional de Todos los Santos.',
    ingredientes: [
      '1 kg de harina',
      '200 g de azúcar',
      '150 g de manteca',
      '4 huevos',
      '25 g de levadura',
      '1 cucharada de anís',
    ],
    preparacion: [
      'Activar la levadura en agua tibia con una cucharada de azúcar',
      'Hervir el anís en agua y colar la infusión para aromatizar la masa',
      'Mezclar la harina con el azúcar, los huevos, la manteca y la infusión',
      'Agregar la levadura y amasar hasta obtener una masa lisa y elástica',
      'Dejar leudar tapada hasta que doble su volumen',
      'Formar las figuras de wawa estirando y modelando la masa a mano',
      'Dejar leudar una vez más, pincelar con huevo y hornear a 180 grados 25 minutos',
    ],
    tiempo_minutos: 180,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/wawa_de_pan.jpg',
    bebida: 'Chocolate caliente',
    acompanamiento: null,
    video_url: null,
  },
];
