// Almuerzos — parte 5. Aves, cerdo, res y platos de horno.

export const parte = [
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pollo al Horno con Papas',
    descripcion: 'Presas de pollo horneadas con papas doradas, ajo y romero.',
    ingredientes: [
      '1 pollo en presas',
      '6 papas en cuartos',
      '6 dientes de ajo molidos',
      '2 cucharadas de sillao',
      '1 cucharadita de romero',
      '2 limones',
    ],
    preparacion: [
      'Sazonar las presas con ajo molido, sillao, romero, sal, pimienta y limón',
      'Dejar macerar al menos una hora en refrigeración para que tome sabor',
      'Precalentar el horno a 200 grados',
      'Acomodar las papas en cuartos en la base de la fuente con aceite y sal',
      'Colocar las presas encima con la piel hacia arriba',
      'Hornear 50 minutos rociando con el jugo de la fuente cada 15 minutos',
      'Subir la temperatura los últimos 10 minutos para que la piel quede crocante',
    ],
    tiempo_minutos: 80,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pollo_al_horno_con_papas.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Ensalada fresca',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Milanesa de Pollo',
    descripcion: 'Filete de pollo empanizado y frito, crocante por fuera y jugoso por dentro.',
    ingredientes: [
      '4 filetes de pechuga de pollo',
      '2 tazas de pan molido',
      '2 huevos batidos',
      '1 taza de harina',
      '4 dientes de ajo molidos',
      'Aceite para freír',
    ],
    preparacion: [
      'Abrir las pechugas en mariposa y golpearlas hasta dejarlas delgadas',
      'Sazonarlas con ajo molido, sal, pimienta y un poco de orégano',
      'Pasar cada filete por harina, luego por huevo batido y finalmente por pan molido',
      'Repetir el paso por huevo y pan si se quiere una costra más gruesa',
      'Freír en aceite a fuego medio 3 minutos por lado hasta dorar parejo',
      'Escurrir sobre papel absorbente',
      'Servir con arroz, papas fritas, ensalada y limón',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/milanesa_de_pollo.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Papas fritas y ensalada',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pollo Broaster',
    descripcion: 'Pollo marinado y frito con costra crocante, servido con papas y cremas.',
    ingredientes: [
      '1 pollo en presas',
      '2 tazas de harina',
      '1 taza de leche',
      '1 cucharadita de páprika',
      '1 cucharadita de ajo en polvo',
      'Aceite para freír',
    ],
    preparacion: [
      'Marinar las presas en leche con ajo, sal y pimienta durante al menos dos horas',
      'Mezclar la harina con páprika, ajo en polvo, orégano, sal y pimienta',
      'Escurrir ligeramente las presas y pasarlas por la mezcla de harina presionando bien',
      'Dejarlas reposar 10 minutos para que la costra se adhiera',
      'Calentar abundante aceite a fuego medio, sin que humee',
      'Freír las presas entre 12 y 15 minutos hasta que estén doradas y cocidas por dentro',
      'Escurrir sobre rejilla y servir con papas fritas y cremas',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pollo_broaster.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Papas fritas y cremas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pepián de Pava',
    descripcion: 'Guiso norteño de pava con arroz molido y ají, espeso y aromático.',
    ingredientes: [
      '1 kg de presas de pava',
      '1 taza de arroz molido',
      '3 cucharadas de ají amarillo molido',
      '1 atado de culantro licuado',
      '1 cebolla picada',
      '1 cucharadita de palillo',
    ],
    preparacion: [
      'Sazonar y dorar las presas de pava en una olla con aceite caliente',
      'Retirar la carne y preparar un aderezo con cebolla, ajo, ají amarillo y palillo',
      'Agregar el culantro licuado y cocinar unos minutos',
      'Incorporar el arroz molido removiendo constantemente para que no se apelmace',
      'Verter caldo caliente poco a poco hasta lograr una crema espesa',
      'Regresar las presas y cocinar tapado hasta que la pava esté suave',
      'Servir con arroz blanco y yuca sancochada',
    ],
    tiempo_minutos: 95,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pepian_de_pava.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Arroz y yuca',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pato en Ají',
    descripcion: 'Presas de pato guisadas en salsa espesa de ají amarillo y panca.',
    ingredientes: [
      '1 pato en presas',
      '4 cucharadas de ají amarillo molido',
      '2 cucharadas de ají panca molido',
      '1 cebolla picada',
      '1 taza de chicha de jora',
      '3 papas en cubos',
    ],
    preparacion: [
      'Sazonar las presas de pato y dorarlas en su propia grasa hasta que la piel quede crocante',
      'Retirar el pato y desechar parte del exceso de grasa',
      'Preparar un aderezo con cebolla, ajo, ají amarillo y ají panca',
      'Regresar el pato, verter la chicha de jora y tapar',
      'Cocinar a fuego bajo 50 minutos hasta que la carne esté suave',
      'Agregar las papas en cubos y cocinar hasta que ablanden',
      'Rectificar la sal y servir con arroz blanco',
    ],
    tiempo_minutos: 100,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pato_en_aji.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Lechón al Horno',
    descripcion: 'Pierna de cerdo marinada en ají panca y chicha, horneada hasta dorar.',
    ingredientes: [
      '2 kg de pierna de cerdo',
      '4 cucharadas de ají panca molido',
      '1 taza de chicha de jora',
      '6 dientes de ajo molidos',
      '1 cucharadita de comino',
      '2 cucharaditas de orégano',
    ],
    preparacion: [
      'Hacer cortes profundos en la pierna para que la marinada penetre',
      'Mezclar ají panca, ajo, comino, orégano, sal, pimienta y chicha de jora',
      'Embadurnar la carne con esa pasta y dejarla macerar toda la noche en frío',
      'Precalentar el horno a 180 grados y colocar la pierna en una fuente con su jugo',
      'Hornear tapada con papel aluminio durante dos horas',
      'Destapar y hornear 40 minutos más rociando con el jugo para que dore',
      'Dejar reposar 15 minutos antes de cortar y servir con camote y tamal',
    ],
    tiempo_minutos: 180,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/lechon_al_horno.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Camote y salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chicharrón de Cerdo',
    descripcion: 'Cerdo cocido en su propia grasa hasta quedar crocante, con camote y salsa criolla.',
    ingredientes: [
      '1 kg de panceta de cerdo en trozos',
      '4 dientes de ajo molidos',
      '1 cucharadita de comino',
      '2 camotes en rodajas',
      '1 cebolla roja en pluma',
      '2 limones',
    ],
    preparacion: [
      'Cortar la panceta en trozos medianos y sazonarlos con ajo, comino, sal y pimienta',
      'Colocarlos en una olla con un poco de agua y cocinar tapado hasta que el agua se evapore',
      'Destapar y dejar que la carne se fría en su propia grasa, sin moverla mucho',
      'Voltear los trozos para que doren de manera pareja y queden crocantes',
      'Freír las rodajas de camote en esa misma grasa hasta caramelizar',
      'Preparar una salsa criolla con cebolla en pluma, limón, sal y culantro',
      'Servir el chicharrón con camote, salsa criolla y pan francés',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chicharron_de_cerdo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Camote y salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chicharrón de Pollo',
    descripcion: 'Trozos de pollo marinados y fritos con costra crocante de chuño.',
    ingredientes: [
      '800 g de pollo en trozos',
      '1 taza de chuño',
      '3 cucharadas de sillao',
      '1 trozo de kion rallado',
      '2 limones',
      'Aceite para freír',
    ],
    preparacion: [
      'Cortar el pollo en trozos con hueso o sin hueso, según preferencia',
      'Marinar con sillao, kion rallado, ajo, limón, sal y pimienta por 30 minutos',
      'Escurrir el exceso de marinada y pasar los trozos por chuño',
      'Dejar reposar 5 minutos para que la costra se fije',
      'Freír en abundante aceite caliente por tandas hasta que queden dorados',
      'Escurrir sobre rejilla para que no pierdan la crocancia',
      'Servir con salsa criolla, yuca frita y limón',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chicharron_de_pollo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Yuca frita y salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Estofado de Pollo',
    descripcion: 'Pollo guisado en salsa de tomate con zanahoria, arvejas y pasas.',
    ingredientes: [
      '1 kg de presas de pollo',
      '4 tomates licuados',
      '2 zanahorias en rodajas',
      '1 taza de arvejas',
      '1/4 taza de pasas',
      '1/2 taza de vino tinto',
    ],
    preparacion: [
      'Sazonar y dorar las presas de pollo en una olla con aceite caliente',
      'Retirar el pollo y preparar un aderezo con cebolla, ajo y ají panca',
      'Agregar el tomate licuado y cocinar 15 minutos para quitarle la acidez',
      'Verter el vino tinto y dejar evaporar el alcohol',
      'Regresar el pollo con la zanahoria y cocinar tapado 25 minutos',
      'Incorporar las arvejas, las pasas y las papas si se desea',
      'Cocinar hasta que todo esté tierno y servir con arroz blanco',
    ],
    tiempo_minutos: 65,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/estofado_de_pollo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Ají de Langostinos',
    descripcion: 'Langostinos en crema de ají amarillo con pan, leche y queso.',
    ingredientes: [
      '700 g de langostinos pelados',
      '5 cucharadas de ají amarillo molido',
      '6 rodajas de pan remojado en leche',
      '1 taza de leche evaporada',
      '100 g de queso fresco',
      '1/2 taza de vino blanco',
    ],
    preparacion: [
      'Limpiar los langostinos retirando la vena y reservar las cáscaras para un caldo rápido',
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Verter el vino blanco y dejar evaporar el alcohol',
      'Licuar el pan remojado con la leche y agregarlo al aderezo removiendo',
      'Cocinar hasta que la crema espese y agregar el queso fresco',
      'Incorporar los langostinos y cocinarlos solo 3 minutos para que queden tiernos',
      'Servir sobre arroz blanco con papa sancochada y huevo duro',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/aji_de_langostinos.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Saltado de Langostinos',
    descripcion: 'Langostinos salteados al wok con cebolla, tomate y sillao.',
    ingredientes: [
      '600 g de langostinos pelados',
      '1 cebolla roja en pluma',
      '2 tomates en gajos',
      '3 cucharadas de sillao',
      '1 copa de pisco',
      '3 papas fritas en bastones',
    ],
    preparacion: [
      'Limpiar los langostinos y secarlos bien para que sellen en lugar de hervir',
      'Freír las papas en bastones hasta que estén doradas y reservarlas',
      'Calentar el wok a fuego máximo con un poco de aceite',
      'Saltear los langostinos apenas 2 minutos y retirarlos para que no se endurezcan',
      'Saltear la cebolla y el ají amarillo a fuego vivo, luego agregar el tomate',
      'Flamear con pisco, agregar el sillao y regresar los langostinos',
      'Incorporar las papas fritas, mezclar y servir de inmediato con arroz',
    ],
    tiempo_minutos: 35,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/saltado_de_langostinos.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Sudado de Pescado a la Norteña',
    descripcion: 'Pescado cocido al vapor en salsa de tomate, chicha y ají con cebolla.',
    ingredientes: [
      '4 filetes gruesos de pescado',
      '3 tomates en gajos',
      '2 cebollas en pluma',
      '1 taza de chicha de jora',
      '2 ajíes amarillos en tiras',
      'Culantro al gusto',
    ],
    preparacion: [
      'Sazonar los filetes con sal, pimienta, ajo y limón',
      'Preparar un aderezo ligero con cebolla, ajo y ají panca en una olla amplia',
      'Colocar una capa de cebolla en pluma y tomate en gajos sobre el aderezo',
      'Acomodar los filetes encima sin superponerlos',
      'Verter la chicha de jora y cubrir con el resto de cebolla y tomate',
      'Tapar y cocinar a fuego medio 12 minutos sin remover, solo moviendo la olla',
      'Terminar con culantro picado y servir con yuca y arroz',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sudado_de_pescado_a_la_nortena.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Yuca y arroz',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Corvina a la Plancha',
    descripcion: 'Filete de corvina a la plancha con mantequilla, ajo y limón.',
    ingredientes: [
      '4 filetes de corvina',
      '60 g de mantequilla',
      '4 dientes de ajo picados',
      '2 limones',
      'Perejil fresco',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Secar bien los filetes con papel para que sellen correctamente en la plancha',
      'Sazonarlos con sal y pimienta justo antes de cocinarlos',
      'Calentar la plancha o sartén hasta que esté muy caliente',
      'Cocinar el pescado 3 minutos por el lado de la piel sin moverlo',
      'Voltearlo y cocinar 2 minutos más, agregando la mantequilla y el ajo picado',
      'Bañar el filete con la mantequilla derretida usando una cuchara',
      'Terminar con jugo de limón y perejil, y servir con ensalada y papas',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/corvina_a_la_plancha.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Ensalada y papas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Trucha a la Parrilla',
    descripcion: 'Trucha andina abierta y asada a la parrilla con hierbas y limón.',
    ingredientes: [
      '4 truchas abiertas',
      '4 dientes de ajo molidos',
      '2 limones',
      '2 cucharadas de aceite de oliva',
      'Romero y tomillo',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Abrir las truchas por el lomo dejándolas planas y retirar las espinas visibles',
      'Sazonarlas con ajo molido, sal, pimienta, hierbas y aceite de oliva',
      'Dejar reposar 20 minutos para que tomen sabor',
      'Calentar la parrilla y engrasar la rejilla para que la piel no se pegue',
      'Asar primero del lado de la piel durante 5 minutos',
      'Voltear con cuidado y asar 3 minutos más hasta que la carne se vea opaca',
      'Rociar con limón y servir con papas andinas y ensalada',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/trucha_a_la_parrilla.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Papas andinas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Ceviche de Conchas Negras',
    descripcion: 'Ceviche tumbesino de conchas negras con su jugo, limón y ají limo.',
    ingredientes: [
      '24 conchas negras con su jugo',
      '10 limones',
      '2 cebollas rojas en pluma',
      '1 ají limo picado',
      'Culantro fresco',
      '1 camote sancochado',
    ],
    preparacion: [
      'Abrir las conchas negras reservando todo su jugo oscuro, que es parte del sabor',
      'Enjuagar ligeramente las conchas sin quitarles el jugo por completo',
      'Cortar la cebolla en pluma fina y enjuagarla en agua fría',
      'Mezclar las conchas con su jugo, el jugo de limón y sal',
      'Agregar el ají limo picado y el culantro',
      'Incorporar la cebolla justo antes de servir para que quede crocante',
      'Servir bien frío con camote, yuca y cancha',
    ],
    tiempo_minutos: 25,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/ceviche_de_conchas_negras.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Camote y cancha',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Ceviche de Pulpo',
    descripcion: 'Pulpo cocido en cubos con limón, cebolla, ají y culantro.',
    ingredientes: [
      '800 g de pulpo cocido',
      '10 limones',
      '2 cebollas rojas en pluma',
      '1 ají limo picado',
      'Culantro fresco',
      '1 choclo sancochado',
    ],
    preparacion: [
      'Cocinar el pulpo en agua sin sal con una cebolla hasta que esté tierno',
      'Enfriarlo en su propia agua de cocción para que no se endurezca',
      'Cortarlo en rodajas o cubos medianos',
      'Sazonar con sal, ajo molido y ají limo picado',
      'Agregar el jugo de limón recién exprimido y mezclar',
      'Incorporar la cebolla en pluma y el culantro picado',
      'Servir bien frío con choclo, camote y cancha serrana',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/ceviche_de_pulpo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Choclo y camote',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chicharrón de Calamar',
    descripcion: 'Anillos de calamar apanados en chuño y fritos hasta quedar crocantes.',
    ingredientes: [
      '800 g de calamar en anillos',
      '1 taza de chuño',
      '4 limones',
      '4 dientes de ajo molidos',
      'Aceite para freír',
      '1 cebolla roja en pluma',
    ],
    preparacion: [
      'Limpiar el calamar y cortarlo en anillos parejos',
      'Sazonarlos con ajo molido, sal, pimienta y unas gotas de limón',
      'Escurrirlos muy bien para que la costra se adhiera y no salte el aceite',
      'Pasarlos por chuño sacudiendo el exceso',
      'Freír en aceite bien caliente solo 2 minutos, porque el calamar se endurece rápido',
      'Escurrir sobre papel absorbente',
      'Servir con salsa criolla, yuca frita y salsa tártara',
    ],
    tiempo_minutos: 30,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chicharron_de_calamar.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Yuca frita y salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Aguadito de Mariscos',
    descripcion: 'Sopa de arroz verde con mariscos surtidos y culantro.',
    ingredientes: [
      '500 g de mariscos surtidos',
      '1 taza de arroz',
      '1 atado de culantro licuado',
      '1 taza de arvejas',
      '1 choclo desgranado',
      '1/2 taza de vino blanco',
    ],
    preparacion: [
      'Preparar un fondo de pescado con cabezas y espinas hervidas 20 minutos, luego colar',
      'Hacer un aderezo con cebolla, ajo y ají amarillo',
      'Agregar el culantro licuado y cocinar 3 minutos',
      'Verter el vino blanco y dejar evaporar el alcohol',
      'Añadir el fondo colado, el arroz, las arvejas y el choclo',
      'Cuando el arroz esté casi cocido, incorporar los mariscos',
      'Cocinar 4 minutos más y servir con limón y ají al gusto',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/aguadito_de_mariscos.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Sopa de Choros',
    descripcion: 'Caldo marino de choros con papa, arroz y culantro.',
    ingredientes: [
      '1 kg de choros frescos',
      '1/2 taza de arroz',
      '2 papas en cubos',
      '1 cebolla picada',
      '2 tomates picados',
      'Culantro al gusto',
    ],
    preparacion: [
      'Limpiar los choros raspando las conchas y retirando las barbas',
      'Cocinarlos en una olla tapada con un poco de agua hasta que se abran',
      'Retirar la carne de los choros y colar el líquido de cocción, que es el caldo base',
      'Preparar un aderezo con cebolla, ajo y ají panca, y agregar el tomate',
      'Verter el caldo colado y dejar hervir',
      'Agregar el arroz y las papas, cocinando hasta que estén tiernos',
      'Regresar la carne de los choros, añadir culantro y servir con limón',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sopa_de_choros.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Tortilla de Raya',
    descripcion: 'Tortilla norteña de raya seca desmenuzada con huevo y cebolla.',
    ingredientes: [
      '400 g de raya seca',
      '6 huevos',
      '1 cebolla picada fina',
      '2 cucharadas de ají panca molido',
      '4 dientes de ajo molidos',
      'Culantro picado',
    ],
    preparacion: [
      'Remojar la raya seca en agua durante varias horas cambiando el agua para desalarla',
      'Sancocharla brevemente y desmenuzarla retirando los cartílagos',
      'Preparar un aderezo con cebolla, ajo y ají panca',
      'Agregar la raya desmenuzada y saltearla para que tome sabor',
      'Batir los huevos y mezclarlos con la preparación ya fría',
      'Verter en una sartén con aceite caliente y cocinar a fuego medio',
      'Voltear con ayuda de un plato y dorar del otro lado, servir con arroz y zarza',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tortilla_de_raya.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Arroz y zarza criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Frito Trujillano',
    descripcion: 'Cerdo frito norteño servido con mote, camote y salsa criolla.',
    ingredientes: [
      '1 kg de carne de cerdo en trozos',
      '2 tazas de mote cocido',
      '2 camotes en rodajas',
      '4 dientes de ajo molidos',
      '1 cucharadita de comino',
      '1 cebolla roja en pluma',
    ],
    preparacion: [
      'Sazonar el cerdo con ajo molido, comino, sal, pimienta y un poco de vinagre',
      'Colocarlo en una olla con poca agua y cocinar tapado hasta que ablande',
      'Destapar y dejar que la carne se fría en su propia grasa hasta dorar',
      'Sancochar el mote hasta que reviente y esté tierno',
      'Freír las rodajas de camote en la grasa del cerdo',
      'Preparar una salsa criolla con cebolla en pluma, limón, sal y culantro',
      'Servir el frito con mote, camote y la salsa criolla encima',
    ],
    tiempo_minutos: 85,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/frito_trujillano.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Mote y camote',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Arroz Árabe',
    descripcion: 'Arroz con fideos dorados, pasas y almendras, guarnición muy usada en Perú.',
    ingredientes: [
      '3 tazas de arroz',
      '1 taza de fideos cabello de ángel',
      '1/2 taza de pasas',
      '1/2 taza de almendras fileteadas',
      '4 dientes de ajo molidos',
      '4 cucharadas de mantequilla',
    ],
    preparacion: [
      'Dorar los fideos partidos en mantequilla hasta que tomen color tostado',
      'Retirar los fideos y en la misma olla freír el ajo molido',
      'Agregar el arroz y saltearlo unos segundos para sellar el grano',
      'Verter el caldo caliente y sal, y llevar a hervor',
      'Incorporar los fideos dorados y las pasas',
      'Tapar y cocinar a fuego muy bajo durante 18 minutos sin destapar',
      'Soltar el arroz con tenedor y terminar con almendras fileteadas tostadas',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/arroz_arabe.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Pollo o carne guisada',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Tallarín a la Huancaína con Lomo',
    descripcion: 'Pasta bañada en salsa huancaína cremosa con lomo saltado encima.',
    ingredientes: [
      '500 g de tallarín',
      '400 g de lomo de res en tiras',
      '4 ajíes amarillos',
      '200 g de queso fresco',
      '1 taza de leche evaporada',
      '6 galletas de soda',
    ],
    preparacion: [
      'Freír los ajíes amarillos despepitados con cebolla y ajo hasta que estén blandos',
      'Licuar ese sofrito con el queso fresco, la leche y las galletas hasta obtener una crema',
      'Cocinar el tallarín en agua con sal hasta que esté al dente',
      'Calentar el wok a fuego alto y saltear el lomo en tiras con cebolla y tomate',
      'Agregar sillao y vinagre al saltado y mezclar rápido',
      'Mezclar la pasta con la salsa huancaína tibia hasta cubrirla por completo',
      'Servir la pasta con el lomo saltado encima y papas fritas al costado',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tallarin_a_la_huancaina_con_lomo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Papas fritas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Causa de Atún',
    descripcion: 'Masa de papa amarilla con ají y limón rellena de atún con mayonesa.',
    ingredientes: [
      '1 kg de papa amarilla',
      '3 cucharadas de ají amarillo molido',
      '4 limones',
      '2 latas de atún',
      '1 taza de mayonesa',
      '1 palta',
    ],
    preparacion: [
      'Sancochar las papas amarillas, pelarlas y prensarlas en caliente',
      'Amasar la papa con ají amarillo, jugo de limón, aceite y sal hasta que quede suave',
      'Mezclar el atún escurrido con mayonesa, cebolla picada y sal',
      'Colocar una capa de masa de papa en un molde presionando ligeramente',
      'Poner una capa del relleno de atún y otra de palta en láminas',
      'Cubrir con otra capa de masa y alisar la superficie',
      'Refrigerar una hora, desmoldar y decorar con mayonesa, huevo y aceituna',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/causa_de_atun.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Hojas de lechuga',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Arroz Chaufa de Pollo',
    descripcion: 'Arroz salteado al wok con pollo, tortilla de huevo, sillao y cebolla china.',
    ingredientes: [
      '4 tazas de arroz cocido frío',
      '500 g de pollo en cubos',
      '4 huevos',
      '5 cucharadas de sillao',
      '5 tallos de cebolla china',
      '1 cucharada de aceite de ajonjolí',
    ],
    preparacion: [
      'Usar arroz cocido del día anterior y bien frío para que quede suelto',
      'Batir los huevos y hacer una tortilla delgada, luego cortarla en tiras',
      'Sazonar el pollo en cubos con sillao, kion y pimienta',
      'Calentar el wok a fuego máximo y saltear el pollo hasta que dore',
      'Agregar el arroz frío y saltearlo despegándolo con la espátula',
      'Verter el sillao por el borde del wok para que se caramelice',
      'Incorporar la tortilla en tiras, la cebolla china y el aceite de ajonjolí, y servir',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/arroz_chaufa_de_pollo.jpg',
    bebida: 'Té de jazmín',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Tacu Tacu con Lomo',
    descripcion: 'Tortilla de arroz y frejol dorada, coronada con lomo saltado.',
    ingredientes: [
      '3 tazas de frejol canario cocido',
      '3 tazas de arroz cocido',
      '400 g de lomo de res en tiras',
      '1 cebolla roja en pluma',
      '2 tomates en gajos',
      '3 cucharadas de ají amarillo molido',
    ],
    preparacion: [
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Aplastar los frejoles cocidos e incorporarlos al aderezo',
      'Agregar el arroz cocido y mezclar hasta formar una masa homogénea',
      'Calentar una sartén con aceite y verter una porción de la masa',
      'Darle forma alargada y dorarla por ambos lados hasta que forme costra',
      'Aparte, saltear el lomo en tiras al wok con cebolla, tomate y sillao',
      'Servir el tacu tacu con el lomo saltado encima y huevo frito si se desea',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tacu_tacu_con_lomo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Ají de Fideos',
    descripcion: 'Fideos bañados en crema de ají amarillo con queso, versión económica y sabrosa.',
    ingredientes: [
      '500 g de fideos',
      '5 cucharadas de ají amarillo molido',
      '6 rodajas de pan remojado en leche',
      '200 g de queso fresco',
      '1 taza de leche evaporada',
      '1/2 taza de maní tostado molido',
    ],
    preparacion: [
      'Cocinar los fideos en agua con sal hasta que estén al dente y escurrirlos',
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Licuar el pan remojado con la leche y el maní tostado',
      'Agregar esa mezcla al aderezo removiendo hasta que espese',
      'Incorporar el queso fresco desmenuzado y dejar que se integre',
      'Mezclar los fideos con la crema hasta cubrirlos por completo',
      'Servir con papa sancochada, huevo duro y aceituna',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/aji_de_fideos.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Papa y huevo duro',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chupe Verde',
    descripcion: 'Sopa andina de papa con crema de huacatay, queso y huevo escalfado.',
    ingredientes: [
      '6 papas en cubos',
      '1 atado de huacatay',
      '1 atado de paico',
      '200 g de queso fresco',
      '1 taza de leche evaporada',
      '4 huevos',
    ],
    preparacion: [
      'Cocinar las papas en cubos en agua con sal hasta que estén tiernas',
      'Licuar el huacatay y el paico con un poco de agua y colar la mezcla',
      'Preparar un aderezo suave con cebolla y ajo',
      'Verter el caldo de papas y la mezcla verde licuada',
      'Cocinar unos minutos sin dejar que hierva fuerte para no perder el color',
      'Escalfar los huevos dentro de la sopa',
      'Agregar la leche y el queso fresco en cubos, y servir de inmediato',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chupe_verde.jpg',
    bebida: 'Mate de muña',
    acompanamiento: null,
    video_url: null,
  },
];
