// Almuerzos — parte 3. Chifa peruano, saltados y frituras.

export const parte = [
  {
    categoria_slug: 'almuerzos',
    nombre: 'Tallarín Saltado Criollo',
    descripcion: 'Fideos salteados al wok con carne, cebolla, tomate y sillao.',
    ingredientes: [
      '400 g de tallarín cocido al dente',
      '500 g de lomo de res en tiras',
      '1 cebolla roja en pluma',
      '2 tomates en gajos',
      '4 cucharadas de sillao',
      '1 ají amarillo en tiras',
    ],
    preparacion: [
      'Cocinar el tallarín en abundante agua con sal hasta que esté al dente y escurrirlo con un chorrito de aceite',
      'Calentar el wok a fuego muy alto hasta que humee ligeramente',
      'Sellar la carne en tiras por tandas durante un minuto y reservarla',
      'Saltear la cebolla y el ají amarillo a fuego alto para que queden crocantes',
      'Agregar el tomate en gajos y saltear brevemente sin que se deshaga',
      'Regresar la carne, añadir el sillao y el vinagre, y mezclar rápido',
      'Incorporar el tallarín y saltear todo junto un minuto para que se impregne del jugo',
    ],
    tiempo_minutos: 35,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tallarin_saltado_criollo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Tallarines Rojos',
    descripcion: 'Pasta en salsa roja de tomate con carne guisada, al estilo peruano.',
    ingredientes: [
      '500 g de tallarín',
      '600 g de carne de res en trozos',
      '6 tomates maduros licuados',
      '1 cebolla picada fina',
      '1 cucharadita de orégano',
      '100 g de queso parmesano rallado',
    ],
    preparacion: [
      'Sellar la carne en una olla con aceite caliente hasta dorarla por todos lados',
      'Retirar la carne y en esa misma grasa freír cebolla y ajo hasta dorar',
      'Agregar el tomate licuado y cocinar a fuego bajo al menos 30 minutos para que pierda la acidez',
      'Regresar la carne a la salsa, sazonar con orégano, sal y pimienta, y cocinar tapado hasta que esté suave',
      'Cocinar el tallarín en agua con sal hasta que esté al dente y escurrirlo',
      'Mezclar la pasta con parte de la salsa para que no quede seca',
      'Servir con un trozo de carne encima y queso parmesano rallado',
    ],
    tiempo_minutos: 90,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/tallarines_rojos.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Sopa Seca Chinchana',
    descripcion: 'Fideos teñidos de achiote y albahaca con presas de gallina, típicos de Chincha.',
    ingredientes: [
      '500 g de fideos tallarín',
      '1 kg de presas de gallina',
      '1 atado de albahaca licuada',
      '2 cucharadas de achiote',
      '3 tomates picados',
      '1 cebolla picada',
    ],
    preparacion: [
      'Sancochar las presas de gallina en agua con sal hasta que estén suaves y reservar el caldo',
      'Preparar un aderezo con cebolla, ajo, ají panca y achiote hasta que tome color rojizo intenso',
      'Agregar el tomate picado y la albahaca licuada, cocinando 5 minutos',
      'Verter el caldo de gallina y dejar que hierva',
      'Añadir los fideos crudos directamente al caldo hirviendo',
      'Cocinar a fuego medio removiendo hasta que el fideo absorba casi todo el líquido y quede seco',
      'Servir con la presa de gallina encima, tradicionalmente junto a carapulcra',
    ],
    tiempo_minutos: 75,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/sopa_seca_chinchana.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Carapulcra',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Bistec a lo Pobre',
    descripcion: 'Bistec de res con papas fritas, plátano frito y huevo frito encima.',
    ingredientes: [
      '4 bistecs de res',
      '4 papas grandes en bastones',
      '2 plátanos maduros',
      '4 huevos',
      '4 dientes de ajo molidos',
      '1 taza de arroz cocido',
    ],
    preparacion: [
      'Sazonar los bistecs con ajo molido, sal, pimienta y comino, y dejar reposar 15 minutos',
      'Freír las papas en bastones en abundante aceite hasta que estén doradas y crocantes',
      'Cortar los plátanos maduros en tiras y freírlos hasta que caramelicen por fuera',
      'Calentar bien una sartén o plancha y sellar los bistecs 2 minutos por lado',
      'Freír los huevos dejando la yema líquida',
      'Montar el plato con arroz, el bistec, las papas y el plátano frito',
      'Coronar con el huevo frito y servir de inmediato',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/bistec_a_lo_pobre.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Apanado de Carne',
    descripcion: 'Filete de res empanizado y frito, servido con arroz, papas y ensalada.',
    ingredientes: [
      '4 filetes delgados de res',
      '2 tazas de pan molido',
      '2 huevos batidos',
      '1 taza de harina',
      '4 dientes de ajo molidos',
      'Aceite para freír',
    ],
    preparacion: [
      'Golpear los filetes con un mazo hasta dejarlos delgados y parejos',
      'Sazonarlos con ajo molido, sal, pimienta y comino',
      'Pasar cada filete primero por harina, luego por huevo batido y finalmente por pan molido',
      'Presionar bien el pan molido para que la capa quede compacta y no se despegue al freír',
      'Calentar aceite a fuego medio y freír cada filete 3 minutos por lado hasta dorar',
      'Escurrir sobre papel absorbente para quitar el exceso de aceite',
      'Servir con arroz blanco, papas fritas, ensalada fresca y limón',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/apanado_de_carne.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Arroz y papas fritas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chi Jau Kay',
    descripcion: 'Pollo apanado bañado en salsa chi jau kay agridulce de chifa.',
    ingredientes: [
      '800 g de pechuga de pollo en trozos',
      '1 taza de chuño',
      '4 cucharadas de salsa chi jau kay',
      '2 cucharadas de sillao',
      '1 cucharada de azúcar',
      '1 trozo de kion rallado',
    ],
    preparacion: [
      'Cortar la pechuga en trozos medianos y sazonarlos con sillao, kion y pimienta',
      'Pasar el pollo por chuño hasta cubrirlo de manera pareja',
      'Freír en abundante aceite caliente hasta que quede dorado y crocante, luego escurrir',
      'En un wok calentar un poco de aceite y sofreír ajo y kion rallado',
      'Agregar la salsa chi jau kay, el sillao, el azúcar y un poco de agua',
      'Dejar hervir y espesar con chuño disuelto en agua fría hasta que brille',
      'Bañar el pollo crocante con la salsa justo antes de servir con arroz blanco',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chi_jau_kay.jpg',
    bebida: 'Té de jazmín',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Kam Lu Wantán',
    descripcion: 'Wantanes fritos con cerdo, langostinos y verduras en salsa agridulce.',
    ingredientes: [
      '20 masas de wantán',
      '300 g de carne de cerdo en trozos',
      '200 g de langostinos',
      '1 pimiento en cubos',
      '1 taza de piña en cubos',
      '4 cucharadas de salsa agridulce',
    ],
    preparacion: [
      'Freír las masas de wantán vacías en aceite caliente hasta que inflen y queden crocantes',
      'Saltear el cerdo en cubos a fuego alto hasta que dore por fuera',
      'Agregar los langostinos y cocinarlos apenas dos minutos para que no se endurezcan',
      'Incorporar el pimiento, la cebolla y la piña en cubos, salteando a fuego vivo',
      'Verter la salsa agridulce con un poco de caldo y dejar hervir',
      'Espesar con chuño disuelto en agua fría hasta que la salsa nape los ingredientes',
      'Servir sobre los wantanes fritos justo antes de comer para que no se ablanden',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/kam_lu_wantan.jpg',
    bebida: 'Té de jazmín',
    acompanamiento: 'Arroz chaufa',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Sopa Wantán',
    descripcion: 'Caldo claro de chifa con wantanes rellenos, char siu y verduras.',
    ingredientes: [
      '20 wantanes rellenos de cerdo',
      '2 litros de caldo de pollo',
      '200 g de char siu en láminas',
      '1 taza de col china picada',
      '2 cucharadas de sillao',
      '1 trozo de kion',
    ],
    preparacion: [
      'Preparar un caldo claro hirviendo huesos de pollo con kion y cebolla china, luego colarlo',
      'Rellenar los wantanes con carne de cerdo sazonada y sellarlos bien con agua en los bordes',
      'Llevar el caldo a hervor suave y sazonarlo con sillao, sal y pimienta',
      'Cocinar los wantanes en el caldo hasta que suban a la superficie, unos 4 minutos',
      'Agregar la col china y las verduras, cocinando apenas un minuto para que queden crocantes',
      'Servir en plato hondo con láminas de char siu encima',
      'Terminar con cebolla china picada y unas gotas de aceite de ajonjolí',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/sopa_wantan.jpg',
    bebida: 'Té de jazmín',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Aeropuerto',
    descripcion: 'Combinación de arroz chaufa y tallarín saltado en un solo plato de chifa.',
    ingredientes: [
      '2 tazas de arroz cocido frío',
      '250 g de tallarín cocido',
      '200 g de pollo en tiras',
      '200 g de cerdo char siu',
      '3 huevos',
      '4 cucharadas de sillao',
    ],
    preparacion: [
      'Usar arroz cocido del día anterior, bien frío y suelto, para que no se apelmace',
      'Hacer una tortilla delgada con los huevos y cortarla en tiras finas',
      'Calentar el wok a fuego máximo y saltear el pollo y el char siu',
      'Agregar el arroz y saltearlo con sillao hasta que tome color parejo',
      'En otra sartén saltear el tallarín con verduras y sillao',
      'Juntar el chaufa y el tallarín en el wok y mezclar rápidamente',
      'Terminar con cebolla china, la tortilla en tiras y unas gotas de aceite de ajonjolí',
    ],
    tiempo_minutos: 40,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/aeropuerto.jpg',
    bebida: 'Té de jazmín',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chaufa de Mariscos',
    descripcion: 'Arroz chaufa salteado con mariscos frescos, kion y sillao.',
    ingredientes: [
      '3 tazas de arroz cocido frío',
      '400 g de mariscos surtidos',
      '3 huevos',
      '4 cucharadas de sillao',
      '1 trozo de kion rallado',
      '4 tallos de cebolla china',
    ],
    preparacion: [
      'Limpiar bien los mariscos y escurrirlos para que no suelten agua en el wok',
      'Hacer una tortilla fina con los huevos y cortarla en tiras',
      'Calentar el wok a fuego muy alto con un poco de aceite',
      'Saltear el kion y el ajo unos segundos, luego agregar los mariscos por 2 minutos',
      'Incorporar el arroz frío y saltear despegándolo con la espátula',
      'Verter el sillao por el borde del wok para que se caramelice al tocar el metal',
      'Agregar la tortilla y la cebolla china, mezclar y servir de inmediato',
    ],
    tiempo_minutos: 35,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chaufa_de_mariscos.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pollo Saltado',
    descripcion: 'Versión con pollo del saltado criollo, con papas fritas y arroz.',
    ingredientes: [
      '600 g de pechuga de pollo en tiras',
      '1 cebolla roja en pluma',
      '2 tomates en gajos',
      '3 papas grandes fritas',
      '4 cucharadas de sillao',
      '2 cucharadas de vinagre tinto',
    ],
    preparacion: [
      'Cortar el pollo en tiras gruesas y sazonarlo con sal, pimienta y comino',
      'Freír las papas en bastones hasta que queden doradas y crocantes, luego reservar',
      'Calentar el wok a fuego muy alto hasta que humee',
      'Saltear el pollo por tandas para que se selle en lugar de hervir en su jugo',
      'Agregar la cebolla y el ají amarillo, salteando un minuto a fuego vivo',
      'Incorporar el tomate, el sillao y el vinagre, mezclando rápido',
      'Añadir las papas fritas al final, mezclar y servir de inmediato con arroz',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pollo_saltado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Saltado de Coliflor',
    descripcion: 'Saltado vegetariano de coliflor rebozada con cebolla, tomate y sillao.',
    ingredientes: [
      '1 coliflor grande en floretes',
      '1 taza de harina',
      '2 huevos',
      '1 cebolla roja en pluma',
      '2 tomates en gajos',
      '3 cucharadas de sillao',
    ],
    preparacion: [
      'Blanquear los floretes de coliflor en agua hirviendo con sal por 3 minutos y escurrirlos bien',
      'Preparar un rebozado con harina, huevo, sal y un poco de agua hasta lograr una mezcla espesa',
      'Pasar la coliflor por el rebozado y freírla en aceite caliente hasta dorar',
      'Calentar el wok a fuego alto y saltear la cebolla y el ají amarillo',
      'Agregar el tomate en gajos y saltear brevemente',
      'Incorporar la coliflor frita, el sillao y el vinagre, mezclando con cuidado',
      'Servir de inmediato con arroz blanco y papas fritas',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/saltado_de_coliflor.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Hígado Encebollado',
    descripcion: 'Hígado de res salteado con abundante cebolla, tomate y vinagre.',
    ingredientes: [
      '700 g de hígado de res en tiras',
      '3 cebollas rojas en pluma',
      '2 tomates en gajos',
      '3 cucharadas de vinagre tinto',
      '2 cucharadas de sillao',
      '4 dientes de ajo molidos',
    ],
    preparacion: [
      'Cortar el hígado en tiras delgadas retirando las membranas',
      'Remojarlo unos minutos en leche o agua con vinagre para suavizar su sabor',
      'Escurrirlo bien y sazonarlo con ajo, sal, pimienta y comino',
      'Calentar el wok a fuego muy alto y saltear el hígado apenas 2 minutos para que no se endurezca',
      'Retirar el hígado y saltear la cebolla en pluma hasta que quede crocante',
      'Agregar el tomate, el vinagre y el sillao, y regresar el hígado',
      'Mezclar rápido y servir con arroz blanco y papas fritas',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/higado_encebollado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz y papas fritas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Malaya Frita',
    descripcion: 'Malaya de res sancochada y luego frita hasta quedar crocante por fuera.',
    ingredientes: [
      '1 kg de malaya de res',
      '4 dientes de ajo molidos',
      '1 cucharadita de comino',
      '2 hojas de laurel',
      'Aceite para freír',
      '1 cebolla roja en pluma',
    ],
    preparacion: [
      'Cocinar la malaya en agua con sal, laurel, ajo y cebolla hasta que esté muy suave',
      'Retirarla del caldo y dejarla enfriar para poder cortarla sin deshacerla',
      'Cortarla en porciones y sazonarlas con ajo molido, comino, sal y pimienta',
      'Calentar aceite en una sartén amplia a fuego medio alto',
      'Freír las porciones hasta que estén bien doradas y crocantes por fuera',
      'Escurrir sobre papel absorbente',
      'Servir con salsa criolla, yuca o papa dorada y arroz blanco',
    ],
    tiempo_minutos: 110,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/malaya_frita.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Salsa criolla y yuca',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Papa Rellena',
    descripcion: 'Masa de papa amarilla rellena de carne guisada, frita hasta dorar.',
    ingredientes: [
      '1 kg de papa amarilla sancochada',
      '400 g de carne molida',
      '1 cebolla picada fina',
      '2 huevos duros picados',
      '50 g de aceitunas picadas',
      '1 taza de harina',
    ],
    preparacion: [
      'Sancochar las papas amarillas, pelarlas y prensarlas en caliente hasta formar una masa fina',
      'Dejar enfriar la masa y sazonarla con sal para que se pueda manipular',
      'Preparar el relleno con aderezo de cebolla, ajo y ají panca, y dorar la carne molida',
      'Agregar al relleno huevo duro, aceitunas y pasas, y dejar enfriar',
      'Tomar una porción de masa en la mano, aplanarla y colocar el relleno al centro',
      'Cerrar formando un óvalo compacto sin que queden aberturas, y pasarlo por harina',
      'Freír en abundante aceite caliente hasta dorar y servir con salsa criolla',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/papa_rellena.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pescado a lo Macho',
    descripcion: 'Filete de pescado frito bañado en salsa picante de mariscos y ají panca.',
    ingredientes: [
      '4 filetes de pescado',
      '400 g de mariscos surtidos',
      '3 cucharadas de ají panca molido',
      '2 cucharadas de ají amarillo molido',
      '1/2 taza de vino blanco',
      '1 taza de caldo de pescado',
    ],
    preparacion: [
      'Sazonar los filetes con sal, pimienta y limón, pasarlos por harina y freírlos hasta dorar',
      'En otra sartén preparar un aderezo con cebolla, ajo, ají panca y ají amarillo',
      'Agregar el tomate rallado y cocinar hasta que se deshaga',
      'Incorporar los mariscos y saltearlos brevemente para que no se endurezcan',
      'Verter el vino blanco y dejar evaporar el alcohol',
      'Añadir el caldo de pescado y dejar que la salsa espese y brille',
      'Bañar el pescado frito con la salsa de mariscos y servir con arroz y yuca',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pescado_a_lo_macho.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco y yuca',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pescado a la Chorrillana',
    descripcion: 'Pescado frito cubierto con salsa de cebolla, tomate y ají amarillo.',
    ingredientes: [
      '4 filetes de pescado',
      '2 cebollas en pluma',
      '3 tomates en gajos',
      '2 ajíes amarillos en tiras',
      '1/2 taza de vino blanco',
      '2 cucharadas de sillao',
    ],
    preparacion: [
      'Sazonar los filetes con sal, pimienta, ajo y limón',
      'Pasarlos ligeramente por harina y freírlos en aceite caliente hasta dorar por ambos lados',
      'Reservar el pescado en un plato tibio',
      'En la misma sartén saltear la cebolla en pluma y el ají amarillo a fuego alto',
      'Agregar el tomate en gajos y saltear sin deshacerlo',
      'Verter el vino blanco y el sillao, y dejar reducir un par de minutos',
      'Cubrir el pescado con esta salsa y servir con arroz blanco y papas doradas',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pescado_a_la_chorrillana.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Conchitas a la Parmesana',
    descripcion: 'Conchas de abanico gratinadas con mantequilla, vino blanco y parmesano.',
    ingredientes: [
      '24 conchas de abanico en su concha',
      '150 g de queso parmesano rallado',
      '80 g de mantequilla',
      '1/4 taza de vino blanco',
      '2 limones',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Limpiar las conchas de abanico dejándolas sobre su valva',
      'Sazonarlas con unas gotas de limón, sal y pimienta',
      'Colocar sobre cada una un trocito de mantequilla y unas gotas de vino blanco',
      'Cubrir generosamente con queso parmesano rallado',
      'Acomodarlas en una fuente para horno sobre una cama de sal gruesa para que no se volteen',
      'Gratinar a 220 grados por 6 a 8 minutos hasta que el queso burbujee y dore',
      'Servir de inmediato con rodajas de limón',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/conchitas_a_la_parmesana.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Pan tostado',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pulpo al Olivo',
    descripcion: 'Láminas de pulpo cocido bañadas en mayonesa de aceituna botija.',
    ingredientes: [
      '1 kg de pulpo cocido',
      '150 g de aceitunas botija',
      '1 taza de mayonesa',
      '1 limón',
      '2 cucharadas de aceite de oliva',
      'Pimienta al gusto',
    ],
    preparacion: [
      'Cocinar el pulpo en agua sin sal con una cebolla y un corcho hasta que esté tierno',
      'Dejarlo enfriar dentro de su propia agua de cocción para que no se endurezca',
      'Cortarlo en láminas delgadas y acomodarlas en el plato',
      'Deshuesar las aceitunas botija y licuarlas con la mayonesa hasta lograr una crema morada',
      'Ajustar con unas gotas de limón y pimienta, sin agregar sal porque la aceituna ya es salada',
      'Bañar las láminas de pulpo con la salsa de aceituna',
      'Terminar con un hilo de aceite de oliva y servir bien frío',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pulpo_al_olivo.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Pan tostado',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Leche de Tigre',
    descripcion: 'El jugo concentrado del cebiche servido como entrada en vaso, con pescado y mariscos.',
    ingredientes: [
      '300 g de filete de pescado',
      '200 g de mariscos cocidos',
      '10 limones',
      '1 ají limo',
      '1 trozo de kion',
      'Culantro fresco',
    ],
    preparacion: [
      'Reservar los recortes de pescado y licuarlos con un poco de jugo de limón, kion, ajo y hielo',
      'Colar la mezcla para obtener un líquido cremoso y sin fibras',
      'Sazonar con sal, ají limo picado y culantro',
      'Cortar el resto del pescado en cubos pequeños y mezclarlo con la leche de tigre',
      'Agregar los mariscos cocidos y la cebolla en pluma',
      'Servir en vaso bien frío con choclo desgranado y cancha encima',
      'Acompañar con una rodaja de camote y consumir de inmediato',
    ],
    tiempo_minutos: 25,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/leche_de_tigre.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Cancha y choclo',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Ceviche Mixto',
    descripcion: 'Ceviche de pescado con mariscos surtidos, limón, cebolla y ají limo.',
    ingredientes: [
      '500 g de filete de pescado en cubos',
      '300 g de mariscos surtidos',
      '12 limones',
      '2 cebollas rojas en pluma',
      '1 ají limo picado',
      '1 camote sancochado',
      '1 choclo sancochado',
    ],
    preparacion: [
      'Cortar el pescado en cubos parejos de unos 2 cm y mantenerlo bien frío',
      'Blanquear los mariscos en agua hirviendo por un minuto y enfriarlos de inmediato',
      'Cortar la cebolla en pluma fina y enjuagarla en agua con hielo para quitarle el picor',
      'Sazonar el pescado con sal, ajo molido y ají limo picado',
      'Exprimir los limones sin apretar la cáscara y verterlos sobre el pescado',
      'Mezclar apenas unos segundos, agregar los mariscos y la cebolla',
      'Servir de inmediato con camote, choclo, cancha y hojas de lechuga',
    ],
    tiempo_minutos: 30,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/ceviche_mixto.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Camote y choclo',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Arroz con Conchas',
    descripcion: 'Arroz cremoso teñido con el coral de las conchas de abanico.',
    ingredientes: [
      '3 tazas de arroz',
      '600 g de conchas de abanico con coral',
      '1/2 taza de vino blanco',
      '2 cucharadas de ají amarillo molido',
      '1 taza de arvejas',
      '100 g de queso parmesano',
    ],
    preparacion: [
      'Separar el coral de las conchas y licuarlo con un poco de caldo para dar color al arroz',
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Agregar el coral licuado y cocinar dos minutos',
      'Verter el vino blanco y dejar evaporar el alcohol',
      'Añadir el arroz y el caldo de pescado caliente, y cocinar tapado a fuego bajo',
      'Cuando el arroz esté casi listo, incorporar las conchas y las arvejas',
      'Apagar el fuego, agregar queso parmesano y culantro picado, y dejar reposar 5 minutos',
    ],
    tiempo_minutos: 55,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/arroz_con_conchas.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Picante de Mariscos',
    descripcion: 'Guiso cremoso de mariscos en salsa de ají panca y leche, servido con arroz.',
    ingredientes: [
      '700 g de mariscos surtidos',
      '3 cucharadas de ají panca molido',
      '2 cucharadas de ají amarillo molido',
      '1 taza de leche evaporada',
      '1/2 taza de vino blanco',
      '4 rodajas de pan remojado',
    ],
    preparacion: [
      'Limpiar y escurrir bien los mariscos para que no suelten demasiada agua',
      'Preparar un aderezo con cebolla, ajo, ají panca y ají amarillo hasta que suelte aceite',
      'Verter el vino blanco y dejar que evapore el alcohol',
      'Licuar el pan remojado con leche y agregarlo al aderezo para espesar la salsa',
      'Incorporar los mariscos y cocinarlos solo 4 minutos para que queden tiernos',
      'Rectificar la sal y agregar culantro picado',
      'Servir caliente sobre arroz blanco con papa sancochada al lado',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/picante_de_mariscos.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Trucha Frita',
    descripcion: 'Trucha andina entera sazonada y frita, servida con papas y ensalada.',
    ingredientes: [
      '4 truchas limpias',
      '1 taza de harina',
      '4 dientes de ajo molidos',
      '2 limones',
      'Aceite para freír',
      '4 papas sancochadas',
    ],
    preparacion: [
      'Limpiar las truchas retirando vísceras y escamas, y hacerles dos cortes diagonales en cada lado',
      'Sazonarlas por dentro y por fuera con ajo molido, sal, pimienta y limón',
      'Dejar reposar 15 minutos para que tomen sabor',
      'Pasarlas por harina sacudiendo el exceso',
      'Freír en aceite caliente unos 5 minutos por lado hasta que la piel quede dorada y crocante',
      'Escurrir sobre papel absorbente',
      'Servir con papas sancochadas, arroz y ensalada fresca con limón',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/trucha_frita.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Papas y ensalada',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chupe de Pescado',
    descripcion: 'Sopa espesa de pescado con leche, papa, arroz y huevo escalfado.',
    ingredientes: [
      '600 g de filete de pescado en trozos',
      '1/2 taza de arroz',
      '3 papas en rodajas',
      '1 taza de leche evaporada',
      '4 huevos',
      '100 g de queso fresco',
      '2 cucharadas de ají panca molido',
    ],
    preparacion: [
      'Preparar un fondo con las espinas y cabezas del pescado hervidas 20 minutos, luego colar',
      'Hacer un aderezo con cebolla, ajo y ají panca hasta que suelte su aceite',
      'Verter el fondo colado y dejar hervir',
      'Agregar el arroz y cocinar 10 minutos',
      'Incorporar las papas en rodajas y el choclo, cocinando hasta que ablanden',
      'Añadir el pescado y cocinarlo apenas 4 minutos para que no se deshaga',
      'Escalfar los huevos en la sopa, verter la leche y el queso, y servir de inmediato',
    ],
    tiempo_minutos: 55,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chupe_de_pescado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
];
