// Almuerzos — parte 2. Criollos, sopas y guisos regionales.

export const parte = [
  {
    categoria_slug: 'almuerzos',
    nombre: 'Cau Cau',
    descripcion: 'Guiso limeño de mondongo y papa en dorado de ají amarillo con palillo y hierbabuena.',
    ingredientes: [
      '700 g de mondongo precocido, en cubos',
      '4 papas blancas, en cubos',
      '3 cucharadas de ají amarillo molido',
      '1 cucharadita de palillo',
      '1 cebolla mediana, picada fina',
      '1 ramita de hierbabuena',
    ],
    preparacion: [
      'Hervir el mondongo en agua con sal y una ramita de hierbabuena hasta que esté suave, luego cortarlo en cubos parejos',
      'Preparar un aderezo friendo la cebolla picada con ajo hasta que transparente',
      'Agregar el ají amarillo molido y el palillo, cocinando a fuego bajo hasta que el aderezo suelte su aceite',
      'Incorporar el mondongo y saltearlo unos minutos para que tome color del aderezo',
      'Añadir las papas en cubos y un poco de caldo, cocinando tapado hasta que la papa esté cocida pero firme',
      'Agregar la hierbabuena picada al final y rectificar la sal',
      'Servir caliente acompañado de arroz blanco graneado',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/cau_cau.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Anticuchos de corazón',
    descripcion: 'Brochetas de corazón de res marinadas en ají panca y vinagre, asadas a la parrilla.',
    ingredientes: [
      '1 kg de corazón de res limpio, en cubos',
      '4 cucharadas de ají panca molido',
      '1/2 taza de vinagre tinto',
      '4 dientes de ajo molidos',
      '1 cucharadita de comino',
      '4 papas sancochadas',
      '2 choclos sancochados',
    ],
    preparacion: [
      'Limpiar el corazón retirando nervios y grasa, y cortarlo en cubos de unos 3 cm',
      'Mezclar el ají panca, el vinagre, el ajo, el comino, sal y pimienta para formar la marinada',
      'Marinar la carne en esa mezcla por lo menos 4 horas, idealmente toda la noche en refrigeración',
      'Ensartar tres o cuatro cubos por palito de caña, sin apretarlos demasiado',
      'Asar sobre parrilla muy caliente 2 a 3 minutos por lado, pincelando con la marinada restante',
      'Retirar apenas estén dorados por fuera y aún jugosos por dentro',
      'Servir con papa sancochada, choclo y salsa de ají',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/anticuchos_de_corazon.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Papa sancochada y choclo',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Rocoto Relleno',
    descripcion: 'Clásico arequipeño de rocoto desvenado relleno de carne, queso y huevo, horneado.',
    ingredientes: [
      '6 rocotos grandes',
      '500 g de carne de res molida',
      '1 cebolla grande, picada',
      '100 g de queso fresco en tajadas',
      '3 huevos duros, picados',
      '1/2 taza de leche evaporada',
      'Azúcar y vinagre para desflemar',
    ],
    preparacion: [
      'Cortar la tapa de los rocotos y retirar venas y pepas con cuidado, usando guantes',
      'Desflemar los rocotos hirviéndolos en agua con azúcar y vinagre, cambiando el agua tres veces para bajar el picante',
      'Preparar un aderezo con cebolla, ajo y ají panca, luego dorar la carne molida hasta que esté cocida',
      'Agregar al relleno el huevo duro picado, maní tostado y sal, y dejar enfriar un poco',
      'Rellenar cada rocoto, colocar una tajada de queso encima y taparlo con su propia tapa',
      'Acomodar en una fuente con papas en rodajas, bañar con leche y queso, y hornear a 180 grados por 25 minutos',
      'Servir caliente con el pastel de papa que se formó al fondo',
    ],
    tiempo_minutos: 90,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/rocoto_relleno.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Pastel de papa',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Adobo Arequipeño',
    descripcion: 'Cerdo macerado en chicha de guiñapo y ají panca, cocido lento hasta quedar muy suave.',
    ingredientes: [
      '1 kg de carne de cerdo en trozos',
      '2 tazas de chicha de guiñapo',
      '4 cucharadas de ají panca molido',
      '2 cebollas en gajos gruesos',
      '1 cucharadita de orégano seco',
      '4 dientes de ajo molidos',
    ],
    preparacion: [
      'Macerar el cerdo desde la noche anterior en chicha de guiñapo con ajo, ají panca, orégano, sal y pimienta',
      'Al día siguiente, colocar la carne con toda su maceración en una olla de barro o de fondo grueso',
      'Agregar la cebolla en gajos gruesos y llevar a hervor suave',
      'Bajar el fuego y cocinar tapado entre una hora y media y dos horas, sin revolver demasiado',
      'Controlar el líquido: debe quedar un caldo concentrado y algo espeso, no seco',
      'Rectificar la sal y dejar reposar unos minutos antes de servir',
      'Servir en plato hondo con pan de tres puntas para mojar',
    ],
    tiempo_minutos: 120,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/adobo_arequipeno.jpg',
    bebida: 'Chicha de guiñapo',
    acompanamiento: 'Pan de tres puntas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chupe de Camarones',
    descripcion: 'Sopa arequipeña espesa con camarones de río, leche, huevo escalfado y queso.',
    ingredientes: [
      '1 kg de camarones de río frescos',
      '1 taza de arroz',
      '2 papas en rodajas gruesas',
      '1 choclo en rodajas',
      '1 taza de leche evaporada',
      '4 huevos',
      '100 g de queso fresco',
    ],
    preparacion: [
      'Limpiar los camarones reservando el coral de las cabezas, que da el color y el sabor característicos',
      'Hacer un caldo hirviendo las cabezas y cáscaras por 20 minutos, luego colar',
      'Preparar un aderezo con cebolla, ajo y ají panca, y agregar el coral reservado',
      'Verter el caldo colado, añadir el arroz, el choclo y las habas, y cocinar 10 minutos',
      'Incorporar las papas en rodajas y cocinar hasta que estén tiernas',
      'Agregar los camarones y cocinarlos solo 3 minutos para que no se endurezcan',
      'Escalfar los huevos dentro de la sopa, verter la leche y el queso en cubos, y apagar el fuego',
      'Servir de inmediato con orégano espolvoreado encima',
    ],
    tiempo_minutos: 75,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/chupe_de_camarones.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Parihuela',
    descripcion: 'Sopa marina potente con pescado, mariscos, ají panca y un toque de pisco.',
    ingredientes: [
      '500 g de pescado en trozos',
      '300 g de mariscos surtidos',
      '2 cangrejos partidos',
      '3 cucharadas de ají panca molido',
      '1 copa de pisco',
      '2 tomates picados',
      '1 cebolla picada',
    ],
    preparacion: [
      'Preparar un fondo con las cabezas y espinas del pescado hervidas 20 minutos, luego colar',
      'Hacer un aderezo con cebolla, ajo, ají panca y ají amarillo hasta que suelte su aceite',
      'Agregar el tomate picado y cocinar hasta deshacerlo por completo',
      'Incorporar los cangrejos y las conchas, y saltear un par de minutos',
      'Verter el pisco y dejar evaporar el alcohol antes de añadir el fondo de pescado',
      'Dejar hervir 10 minutos, luego agregar el pescado y los mariscos más delicados',
      'Cocinar 4 minutos más, rectificar la sal y añadir culantro picado',
      'Servir bien caliente en plato hondo con limón aparte',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/parihuela.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Canchita serrana',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Aguadito de Pollo',
    descripcion: 'Sopa espesa de arroz y pollo teñida de verde por el culantro licuado.',
    ingredientes: [
      '1 kg de presas de pollo',
      '1 taza de arroz',
      '1 atado de culantro licuado',
      '1 taza de arvejas',
      '2 papas en cubos',
      '1 choclo desgranado',
      '1 cebolla picada',
    ],
    preparacion: [
      'Dorar las presas de pollo en una olla con aceite caliente hasta sellarlas por ambos lados y reservar',
      'En la misma olla preparar un aderezo con cebolla, ajo y ají amarillo',
      'Licuar el culantro con un poco de agua e incorporarlo al aderezo, cocinando 3 minutos',
      'Regresar el pollo, cubrir con caldo caliente y dejar hervir 15 minutos',
      'Agregar el arroz, las arvejas y el choclo desgranado',
      'Cuando el arroz esté casi listo, añadir la papa en cubos y cocinar hasta que ablande',
      'Rectificar la sal y servir con limón y ají al gusto',
    ],
    tiempo_minutos: 55,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/aguadito_de_pollo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Caldo de Gallina',
    descripcion: 'Caldo reconfortante de gallina con fideos, papa y huevo duro.',
    ingredientes: [
      '1 gallina en presas',
      '250 g de fideos cabello de ángel',
      '4 papas amarillas',
      '4 huevos duros',
      '1 cebolla china picada',
      '1 trozo de kion',
    ],
    preparacion: [
      'Colocar las presas de gallina en una olla grande con agua fría, kion y sal',
      'Hervir a fuego bajo por al menos dos horas, retirando la espuma que sube a la superficie',
      'Sacar las presas cuando estén suaves y reservarlas tapadas para que no se sequen',
      'Colar el caldo y volver a ponerlo al fuego',
      'Cocinar las papas enteras dentro del caldo hasta que estén tiernas',
      'Agregar los fideos y cocinarlos apenas 3 minutos para que no se pasen',
      'Servir en plato hondo con una presa, papa, medio huevo duro y cebolla china encima',
    ],
    tiempo_minutos: 150,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/caldo_de_gallina.jpg',
    bebida: 'Infusión de hierbas',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Sopa Criolla',
    descripcion: 'Sopa rápida de carne picada, fideos, leche y huevo, con pan frito encima.',
    ingredientes: [
      '300 g de carne de res picada fina',
      '150 g de fideos cabello de ángel',
      '1 taza de leche evaporada',
      '2 tomates picados',
      '4 huevos',
      '2 cucharadas de ají panca molido',
      '4 rodajas de pan frito',
    ],
    preparacion: [
      'Saltear la carne picada a fuego alto hasta que dore y suelte su jugo',
      'Agregar cebolla, ajo y ají panca, y cocinar hasta formar un aderezo brillante',
      'Incorporar el tomate picado y dejar que se deshaga por completo',
      'Verter caldo de res caliente y dejar hervir 10 minutos',
      'Añadir los fideos y cocinarlos 3 minutos',
      'Escalfar los huevos en la sopa y verter la leche evaporada sin dejar que hierva',
      'Servir con una rodaja de pan frito y orégano encima',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sopa_criolla.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Pan frito',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Menestrón',
    descripcion: 'Sopa espesa de verduras, fideos y frejoles con pesto de albahaca peruano.',
    ingredientes: [
      '300 g de carne de res en trozos',
      '1 taza de frejoles cocidos',
      '2 zanahorias en cubos',
      '1 zapallo pequeño en cubos',
      '1 atado de albahaca',
      '150 g de fideos codito',
      '100 g de queso fresco rallado',
    ],
    preparacion: [
      'Cocinar la carne en agua con sal hasta que esté suave, formando un caldo sabroso',
      'Agregar la zanahoria, el zapallo, la vainita y el apio picados, y cocinar 15 minutos',
      'Incorporar los frejoles ya cocidos y la papa en cubos',
      'Licuar la albahaca con un poco de aceite, ajo y queso para formar el pesto',
      'Añadir los fideos al caldo y cocinarlos hasta que estén al dente',
      'Apagar el fuego e incorporar el pesto de albahaca, sin dejar que vuelva a hervir',
      'Servir espolvoreado con queso fresco rallado',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/menestron.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Olluquito con Charqui',
    descripcion: 'Guiso andino de olluco en tiras salteado con charqui deshilachado y ají amarillo.',
    ingredientes: [
      '1 kg de ollucos en tiras finas',
      '300 g de charqui remojado y deshilachado',
      '3 cucharadas de ají amarillo molido',
      '1 cebolla picada fina',
      '4 dientes de ajo molidos',
      'Culantro picado al gusto',
    ],
    preparacion: [
      'Remojar el charqui en agua tibia por 30 minutos, luego escurrirlo y deshilacharlo con las manos',
      'Cortar los ollucos en tiras delgadas y parejas',
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Agregar el charqui deshilachado y saltearlo 5 minutos para que tome sabor',
      'Incorporar los ollucos y mezclar bien, cocinando tapado a fuego medio',
      'No agregar agua: el olluco suelta su propio jugo y debe quedar firme, nunca aguado',
      'Añadir culantro picado al final y servir con arroz blanco',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/olluquito_con_charqui.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Seco de Cabrito',
    descripcion: 'Cabrito norteño macerado en chicha de jora y culantro, servido con frejoles y arroz.',
    ingredientes: [
      '1.5 kg de cabrito tierno en presas',
      '2 tazas de chicha de jora',
      '1 atado grande de culantro licuado',
      '3 cucharadas de ají amarillo molido',
      '2 tazas de frejol canario cocido',
      '1 cebolla picada',
    ],
    preparacion: [
      'Macerar las presas de cabrito en chicha de jora con ajo, sal y pimienta durante al menos 3 horas',
      'Escurrir la carne reservando la maceración y dorarla en una olla con aceite bien caliente',
      'Retirar la carne y en la misma olla hacer un aderezo con cebolla, ajo y ají amarillo',
      'Licuar el culantro con un poco de agua e incorporarlo al aderezo, cocinando 5 minutos',
      'Regresar la carne, verter la chicha de la maceración y tapar',
      'Cocinar a fuego bajo entre una hora y hora y media hasta que el cabrito esté muy suave',
      'Servir con frejoles, arroz blanco y salsa criolla',
    ],
    tiempo_minutos: 120,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/seco_de_cabrito.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Frejoles y arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Arroz con Pato',
    descripcion: 'Arroz norteño cocido en culantro y cerveza negra con presas de pato doradas.',
    ingredientes: [
      '1 pato en presas',
      '3 tazas de arroz',
      '1 atado grande de culantro licuado',
      '1 botella de cerveza negra',
      '1 taza de arvejas',
      '1 loche rallado o zapallo',
      '3 cucharadas de ají amarillo molido',
    ],
    preparacion: [
      'Sazonar las presas de pato con sal, pimienta y comino, y dorarlas en su propia grasa hasta que la piel quede crocante',
      'Retirar el pato y en esa grasa preparar un aderezo con cebolla, ajo y ají amarillo',
      'Agregar el loche rallado y el culantro licuado, cocinando hasta que el aderezo tome color verde intenso',
      'Regresar las presas, verter la cerveza negra y dejar cocinar tapado 40 minutos',
      'Retirar el pato ya cocido y medir el líquido para el arroz',
      'Agregar el arroz y las arvejas al líquido hirviendo, tapar y cocinar a fuego bajo 18 minutos',
      'Servir el arroz graneado con la presa de pato encima y salsa criolla al lado',
    ],
    tiempo_minutos: 100,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/arroz_con_pato.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Juane',
    descripcion: 'Bollo amazónico de arroz con gallina y huevo envuelto en hoja de bijao.',
    ingredientes: [
      '1 kg de presas de gallina',
      '4 tazas de arroz',
      '8 huevos',
      'Hojas de bijao',
      '2 cucharaditas de palillo',
      'Aceitunas negras',
      'Hojas de sachaculantro',
    ],
    preparacion: [
      'Cocinar las presas de gallina en agua con sal, ajo y palillo hasta que estén suaves',
      'Cocinar el arroz en ese mismo caldo para que tome color y sabor',
      'Batir los huevos y mezclarlos con el arroz aún caliente hasta integrar bien',
      'Pasar las hojas de bijao por agua caliente para que se ablanden y no se quiebren',
      'Colocar una porción de arroz sobre la hoja, poner encima una presa, medio huevo duro y una aceituna',
      'Cerrar la hoja formando un bollo redondo y amarrarlo firmemente con pabilo',
      'Hervir los juanes en agua por 45 minutos y servirlos calientes dentro de su hoja',
    ],
    tiempo_minutos: 120,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/juane.jpg',
    bebida: 'Chapo',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Tacacho con Cecina',
    descripcion: 'Bolas de plátano verde asado y machacado con manteca, servidas con cecina frita.',
    ingredientes: [
      '6 plátanos verdes',
      '400 g de cecina ahumada',
      '100 g de chicharrón de cerdo',
      '3 cucharadas de manteca de cerdo',
      '1 cebolla en pluma',
      'Sal al gusto',
    ],
    preparacion: [
      'Asar los plátanos verdes con cáscara sobre la brasa o parrilla hasta que estén tiernos por dentro',
      'Pelarlos y machacarlos en un batán o mortero mientras siguen calientes',
      'Agregar la manteca de cerdo y el chicharrón picado, mezclando hasta formar una masa homogénea',
      'Formar bolas compactas del tamaño de un puño y reservarlas tapadas',
      'Freír la cecina en una sartén caliente hasta que dore por ambos lados',
      'Preparar una ensalada de cebolla en pluma con limón y ají charapita',
      'Servir el tacacho con la cecina encima y la ensalada al costado',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tacacho_con_cecina.jpg',
    bebida: 'Refresco de cocona',
    acompanamiento: 'Ensalada de cebolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Picante de Carne',
    descripcion: 'Guiso andino de carne en salsa espesa de ají panca con papa y maní.',
    ingredientes: [
      '700 g de carne de res en cubos',
      '4 cucharadas de ají panca molido',
      '4 papas en cubos',
      '1 cebolla picada fina',
      '1/2 taza de maní tostado molido',
      '4 dientes de ajo molidos',
    ],
    preparacion: [
      'Sellar la carne en cubos a fuego alto hasta que dore por todos lados y reservar',
      'Preparar un aderezo con cebolla, ajo y ají panca hasta que suelte su aceite',
      'Regresar la carne al aderezo y cubrirla con caldo caliente',
      'Cocinar tapado a fuego bajo hasta que la carne esté suave, aproximadamente una hora',
      'Agregar el maní tostado molido para espesar la salsa',
      'Incorporar las papas en cubos y cocinar hasta que estén tiernas',
      'Rectificar la sal y servir con arroz blanco y perejil picado',
    ],
    tiempo_minutos: 90,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/picante_de_carne.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Cuy Chactado',
    descripcion: 'Cuy aplastado con piedra y frito hasta quedar dorado y crocante.',
    ingredientes: [
      '2 cuyes limpios y abiertos',
      '1 taza de harina de maíz',
      '4 dientes de ajo molidos',
      '1 cucharadita de comino',
      'Aceite para freír',
      '4 papas sancochadas',
    ],
    preparacion: [
      'Limpiar bien los cuyes y abrirlos por la mitad dejándolos planos',
      'Sazonarlos con ajo molido, comino, sal y pimienta, y dejar reposar 30 minutos',
      'Pasarlos por harina de maíz presionando para que se adhiera bien',
      'Calentar abundante aceite en una sartén amplia de fondo grueso',
      'Colocar el cuy y encima una piedra plana limpia y caliente para mantenerlo aplastado',
      'Freír unos 10 minutos por lado hasta que la piel quede muy dorada y crocante',
      'Escurrir sobre papel y servir con papa sancochada, mote y salsa de ají',
    ],
    tiempo_minutos: 60,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/cuy_chactado.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Papa sancochada y mote',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chicharrón de Pescado',
    descripcion: 'Trozos de pescado apanados en chuño y fritos, servidos con salsa criolla.',
    ingredientes: [
      '800 g de filete de pescado en trozos',
      '1 taza de chuño o harina de maíz',
      '4 limones',
      '1 cebolla roja en pluma',
      '1 ají limo picado',
      'Aceite para freír',
      '2 camotes fritos',
    ],
    preparacion: [
      'Cortar el pescado en trozos regulares y sazonarlos con sal, pimienta, ajo y limón',
      'Dejar reposar 10 minutos para que tomen sabor sin que el limón los cocine',
      'Pasar cada trozo por chuño presionando ligeramente y sacudir el exceso',
      'Calentar abundante aceite hasta que un trocito de pan dore en segundos',
      'Freír el pescado por tandas pequeñas durante 3 minutos hasta que quede dorado y crocante',
      'Escurrir sobre papel absorbente para que no quede aceitoso',
      'Servir con salsa criolla fresca, camote frito y rodajas de limón',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chicharron_de_pescado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Salsa criolla y camote frito',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Jalea Mixta',
    descripcion: 'Fritura crocante de pescado y mariscos con yuca, salsa criolla y zarza.',
    ingredientes: [
      '500 g de filete de pescado en trozos',
      '300 g de mariscos surtidos',
      '1 taza de chuño',
      '2 yucas sancochadas',
      '1 cebolla roja en pluma',
      '1 ají limo',
      '4 limones',
    ],
    preparacion: [
      'Sazonar el pescado y los mariscos con sal, pimienta, ajo y unas gotas de limón',
      'Sancochar la yuca en agua con sal hasta que esté tierna, luego cortarla en bastones',
      'Pasar pescado y mariscos por chuño, cubriéndolos de manera pareja',
      'Freír en abundante aceite caliente por tandas para que no baje la temperatura',
      'Freír también la yuca hasta que quede dorada por fuera',
      'Preparar la zarza criolla con cebolla en pluma, ají limo, limón, sal y culantro',
      'Servir la fritura sobre la yuca con la zarza encima y limones al lado',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/jalea_mixta.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Yuca frita y zarza criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Tiradito de Pescado',
    descripcion: 'Láminas finas de pescado crudo bañadas en crema de ají amarillo y limón.',
    ingredientes: [
      '600 g de filete de pescado muy fresco',
      '8 limones',
      '3 cucharadas de ají amarillo molido',
      '1 trozo pequeño de kion',
      'Culantro fresco',
      'Sal al gusto',
    ],
    preparacion: [
      'Cortar el pescado en láminas muy delgadas, como si fuera sashimi, y acomodarlas en el plato',
      'Exprimir los limones sin apretar la cáscara para que el jugo no amargue',
      'Licuar el jugo de limón con el ají amarillo, un trocito de kion, sal y hielo',
      'Colar la mezcla para obtener una crema fina y homogénea',
      'Bañar las láminas de pescado con la crema justo antes de servir',
      'Decorar con culantro picado y rodajas de ají limo',
      'Servir de inmediato bien frío, acompañado de choclo y camote',
    ],
    tiempo_minutos: 25,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/tiradito_de_pescado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Choclo y camote',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Ocopa Arequipeña',
    descripcion: 'Papas sancochadas bañadas en crema de huacatay, maní y queso.',
    ingredientes: [
      '6 papas amarillas sancochadas',
      '1 atado de huacatay',
      '1/2 taza de maní tostado',
      '150 g de queso fresco',
      '4 galletas de vainilla',
      '3 ajíes mirasol',
      '1 taza de leche evaporada',
    ],
    preparacion: [
      'Sancochar las papas con cáscara hasta que estén tiernas, luego pelarlas y cortarlas en rodajas gruesas',
      'Freír la cebolla, el ajo y los ajíes mirasol despepitados hasta que estén blandos',
      'Licuar ese sofrito con el huacatay, el maní tostado, el queso fresco y las galletas',
      'Agregar la leche evaporada poco a poco hasta lograr una crema espesa pero fluida',
      'Rectificar la sal: la crema debe quedar bien sazonada porque la papa es neutra',
      'Acomodar las rodajas de papa sobre hojas de lechuga y bañarlas con la ocopa',
      'Decorar con huevo duro y aceituna negra, y servir frío o a temperatura ambiente',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/ocopa_arequipena.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Huevo duro y aceituna',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Solterito Arequipeño',
    descripcion: 'Ensalada fría de habas, choclo, queso, tomate y aceituna con vinagreta.',
    ingredientes: [
      '2 tazas de habas cocidas',
      '2 choclos desgranados y cocidos',
      '200 g de queso fresco en cubos',
      '2 tomates en cubos',
      '1 cebolla roja picada',
      '100 g de aceitunas botija',
      'Vinagre y aceite de oliva',
    ],
    preparacion: [
      'Cocinar las habas peladas y el choclo desgranado en agua con sal, luego enfriarlos',
      'Cortar el tomate y el queso fresco en cubos del mismo tamaño',
      'Picar la cebolla roja y enjuagarla con agua fría para quitarle el picor fuerte',
      'Deshuesar las aceitunas botija y cortarlas en mitades',
      'Mezclar todos los ingredientes en un bowl amplio con movimientos suaves',
      'Aliñar con aceite de oliva, vinagre, sal, pimienta y perejil picado',
      'Dejar reposar 15 minutos en frío antes de servir para que se integren los sabores',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/solterito_arequipeno.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chanfainita',
    descripcion: 'Guiso popular de bofe de res picado con papa en salsa de ají panca y hierbabuena.',
    ingredientes: [
      '700 g de bofe de res',
      '4 papas en cubos',
      '3 cucharadas de ají panca molido',
      '1 cebolla picada fina',
      '1 ramita de hierbabuena',
      '4 dientes de ajo molidos',
    ],
    preparacion: [
      'Hervir el bofe en agua con sal y hierbabuena hasta que esté suave, luego cortarlo en cubos pequeños',
      'Preparar un aderezo friendo cebolla y ajo hasta dorar',
      'Agregar el ají panca molido y cocinar a fuego bajo hasta que suelte su aceite',
      'Incorporar el bofe picado y saltearlo para que absorba el aderezo',
      'Verter un poco del caldo de cocción y dejar hervir 10 minutos',
      'Añadir las papas en cubos y cocinar hasta que estén tiernas y la salsa espese',
      'Terminar con hierbabuena picada y servir con arroz blanco y mote',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chanfainita.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco y mote',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Mondonguito a la Italiana',
    descripcion: 'Mondongo en tiras salteado con tomate, vino y hierbas, al estilo italo-peruano.',
    ingredientes: [
      '700 g de mondongo precocido en tiras',
      '3 tomates pelados y picados',
      '1/2 taza de vino tinto',
      '1 cebolla picada',
      '1 cucharadita de orégano seco',
      '100 g de queso parmesano rallado',
    ],
    preparacion: [
      'Cocinar el mondongo en agua con sal y hierbas hasta que esté suave, luego cortarlo en tiras finas',
      'Saltear cebolla y ajo en aceite hasta que estén transparentes',
      'Agregar el tomate pelado y picado, cocinando hasta que se deshaga en una salsa',
      'Verter el vino tinto y dejar reducir a fuego medio',
      'Incorporar el mondongo en tiras y cocinar 15 minutos para que tome sabor',
      'Sazonar con orégano, sal y pimienta, y espesar la salsa si hace falta',
      'Servir con puré de papas o arroz y espolvorear parmesano rallado',
    ],
    tiempo_minutos: 80,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/mondonguito_a_la_italiana.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Puré de papas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Arroz Tapado',
    descripcion: 'Molde de arroz relleno de carne molida guisada con pasas, huevo y aceituna.',
    ingredientes: [
      '4 tazas de arroz cocido',
      '500 g de carne molida',
      '1 cebolla picada fina',
      '1/4 taza de pasas',
      '2 huevos duros picados',
      '50 g de aceitunas picadas',
      '2 cucharadas de ají panca molido',
    ],
    preparacion: [
      'Preparar un aderezo con cebolla, ajo y ají panca hasta que esté bien cocido',
      'Agregar la carne molida y saltearla a fuego alto hasta que dore y pierda el agua',
      'Incorporar las pasas, las aceitunas picadas y el huevo duro, y sazonar con comino y sal',
      'Dejar que el relleno quede jugoso pero no aguado, y retirar del fuego',
      'Engrasar un molde individual y colocar una capa de arroz presionando ligeramente',
      'Poner una capa generosa del relleno y cubrir con más arroz, presionando de nuevo',
      'Desmoldar sobre el plato con cuidado y servir con plátano frito o huevo frito encima',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/arroz_tapado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Plátano frito',
    video_url: null,
  },
];
