// Almuerzos — parte 6. Guarniciones sustanciosas, entradas criollas y platos de olla.

export const parte = [
  {
    categoria_slug: 'almuerzos',
    nombre: 'Escabeche de Pescado',
    descripcion: 'Pescado frito marinado en vinagre con cebolla, ají amarillo y especias.',
    ingredientes: [
      '4 filetes de pescado',
      '3 cebollas en pluma gruesa',
      '3 ajíes amarillos en tiras',
      '1/2 taza de vinagre tinto',
      '1 cucharadita de orégano',
      '2 huevos duros',
    ],
    preparacion: [
      'Sazonar los filetes con sal, pimienta y ajo, pasarlos por harina y freírlos hasta dorar',
      'Reservar el pescado frito en una fuente honda',
      'En una sartén saltear la cebolla en pluma gruesa con ají amarillo a fuego alto',
      'Agregar ají panca molido, orégano, comino, sal y pimienta',
      'Verter el vinagre y dejar hervir un minuto para que pierda el filo',
      'Cubrir el pescado con esta cebolla encurtida caliente',
      'Dejar reposar al menos una hora y servir con camote, huevo duro y aceituna',
    ],
    tiempo_minutos: 50,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/escabeche_de_pescado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Camote y aceituna',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Ceviche de Champiñones',
    descripcion: 'Versión vegetariana del cebiche con champiñones, limón y ají limo.',
    ingredientes: [
      '600 g de champiñones frescos',
      '10 limones',
      '2 cebollas rojas en pluma',
      '1 ají limo picado',
      'Culantro fresco',
      '1 camote sancochado',
    ],
    preparacion: [
      'Limpiar los champiñones con un paño húmedo y cortarlos en láminas gruesas',
      'Blanquearlos en agua hirviendo por un minuto y enfriarlos de inmediato en agua con hielo',
      'Escurrirlos muy bien para que no suelten agua en el cebiche',
      'Sazonarlos con sal, ajo molido, kion rallado y ají limo picado',
      'Agregar el jugo de limón recién exprimido y mezclar',
      'Incorporar la cebolla en pluma y el culantro picado',
      'Servir bien frío con camote, choclo y cancha',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/ceviche_de_champinones.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Camote y choclo',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Ají de Gallina Vegetariano',
    descripcion: 'Versión sin carne del ají de gallina, con champiñones deshilachados.',
    ingredientes: [
      '600 g de champiñones en láminas',
      '5 cucharadas de ají amarillo molido',
      '6 rodajas de pan remojado en leche',
      '1 taza de leche evaporada',
      '1/2 taza de nueces',
      '100 g de queso parmesano',
    ],
    preparacion: [
      'Saltear los champiñones en láminas a fuego alto hasta que pierdan el agua y doren',
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Licuar el pan remojado con la leche y las nueces hasta obtener una crema',
      'Agregar esa crema al aderezo removiendo constantemente para que no se pegue',
      'Incorporar los champiñones salteados y cocinar 10 minutos',
      'Agregar el queso parmesano y rectificar la sal',
      'Servir sobre arroz blanco con papa sancochada, huevo duro y aceituna',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/aji_de_gallina_vegetariano.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Seco de Res con Frejoles',
    descripcion: 'Carne de res guisada en culantro y chicha, acompañada de frejoles cremosos.',
    ingredientes: [
      '1 kg de carne de res en trozos',
      '1 atado de culantro licuado',
      '2 tazas de chicha de jora',
      '3 cucharadas de ají amarillo molido',
      '2 tazas de frejol canario cocido',
      '1 taza de arvejas',
    ],
    preparacion: [
      'Sazonar la carne con ajo, comino, sal y pimienta',
      'Sellarla en una olla con aceite muy caliente hasta dorarla por todos lados',
      'Retirar la carne y preparar un aderezo con cebolla, ajo y ají amarillo',
      'Agregar el culantro licuado y cocinar hasta que tome color verde oscuro',
      'Regresar la carne, verter la chicha de jora y cocinar tapado a fuego bajo',
      'Dejar cocinar una hora y media hasta que la carne esté muy suave',
      'Servir con frejoles guisados, arroz blanco y salsa criolla',
    ],
    tiempo_minutos: 120,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/seco_de_res_con_frejoles.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Frejoles y arroz',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Carne Guisada con Papas',
    descripcion: 'Guiso casero de res con papas en salsa de tomate y ají panca.',
    ingredientes: [
      '800 g de carne de res en cubos',
      '4 papas en cubos grandes',
      '3 tomates licuados',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      '2 hojas de laurel',
    ],
    preparacion: [
      'Sellar la carne en cubos a fuego alto hasta dorarla por todos lados',
      'Retirarla y preparar un aderezo con cebolla, ajo y ají panca',
      'Agregar el tomate licuado y cocinar 15 minutos para quitar la acidez',
      'Regresar la carne, añadir laurel y cubrir con caldo caliente',
      'Cocinar tapado a fuego bajo hasta que la carne esté suave',
      'Incorporar las papas en cubos grandes y cocinar hasta que ablanden',
      'Dejar que la salsa espese y servir con arroz blanco',
    ],
    tiempo_minutos: 95,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/carne_guisada_con_papas.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Asado de Res a la Olla',
    descripcion: 'Trozo de res cocido lentamente en salsa espesa de cebolla y vino.',
    ingredientes: [
      '1.5 kg de asado de res',
      '3 cebollas licuadas',
      '1 taza de vino tinto',
      '3 cucharadas de ají panca molido',
      '2 zanahorias',
      '2 hojas de laurel',
    ],
    preparacion: [
      'Sazonar el trozo de carne con ajo, sal, pimienta y comino por todos lados',
      'Sellarlo en una olla pesada con aceite muy caliente',
      'Retirar la carne y freír la cebolla licuada hasta que reduzca y tome color',
      'Agregar el ají panca y cocinar hasta que suelte su aceite',
      'Regresar la carne, verter el vino tinto y el caldo, y añadir el laurel',
      'Cocinar tapado a fuego muy bajo dos horas, volteando la carne a la mitad',
      'Cortar en tajadas y servir bañado con la salsa espesa y puré de papas',
    ],
    tiempo_minutos: 150,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/asado_de_res_a_la_olla.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Puré de papas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pollo a la Olla',
    descripcion: 'Pollo entero cocido lento con verduras y hierbas en su propio jugo.',
    ingredientes: [
      '1 pollo entero',
      '3 zanahorias en trozos',
      '2 cebollas en cuartos',
      '4 papas enteras',
      '1 taza de vino blanco',
      '2 ramitas de romero',
    ],
    preparacion: [
      'Sazonar el pollo por dentro y por fuera con ajo molido, sal, pimienta y romero',
      'Dorarlo en una olla pesada con aceite caliente por todos sus lados',
      'Agregar la cebolla en cuartos y la zanahoria alrededor',
      'Verter el vino blanco y dejar evaporar el alcohol',
      'Tapar y cocinar a fuego muy bajo durante una hora',
      'Agregar las papas enteras y cocinar 30 minutos más',
      'Trinchar el pollo y servirlo con las verduras y su jugo de cocción',
    ],
    tiempo_minutos: 110,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pollo_a_la_olla.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Papas y verduras',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Costillas de Cerdo al Horno',
    descripcion: 'Costillar marinado en ají panca y miel, horneado hasta caramelizar.',
    ingredientes: [
      '1.5 kg de costillas de cerdo',
      '3 cucharadas de ají panca molido',
      '3 cucharadas de miel',
      '3 cucharadas de sillao',
      '6 dientes de ajo molidos',
      '1 cucharadita de comino',
    ],
    preparacion: [
      'Retirar la membrana del costillar por la parte posterior para que quede más tierno',
      'Mezclar ají panca, miel, sillao, ajo, comino, sal y pimienta',
      'Embadurnar las costillas y dejarlas marinar al menos cuatro horas',
      'Hornear a 160 grados cubiertas con papel aluminio durante hora y media',
      'Destapar y pincelar con la marinada restante',
      'Subir a 210 grados y hornear 20 minutos más hasta que caramelicen',
      'Dejar reposar 10 minutos antes de cortar entre los huesos y servir',
    ],
    tiempo_minutos: 140,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/costillas_de_cerdo_al_horno.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Papas al horno',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pastel de Papa',
    descripcion: 'Capas de papa en rodajas horneadas con leche, queso y anís.',
    ingredientes: [
      '1.5 kg de papa blanca en rodajas',
      '2 tazas de leche evaporada',
      '250 g de queso fresco',
      '3 huevos',
      '1 cucharadita de anís',
      '60 g de mantequilla',
    ],
    preparacion: [
      'Pelar las papas y cortarlas en rodajas delgadas y parejas',
      'Sancocharlas apenas 5 minutos para que empiecen a ablandar sin deshacerse',
      'Batir la leche con los huevos, sal, pimienta y anís',
      'Engrasar una fuente y colocar una capa de papas superpuestas',
      'Cubrir con queso fresco y un poco de la mezcla de leche, y repetir las capas',
      'Terminar con queso encima y trocitos de mantequilla',
      'Hornear a 180 grados durante 45 minutos hasta que la superficie quede dorada',
    ],
    tiempo_minutos: 75,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pastel_de_papa.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Rocoto relleno',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Budín de Verduras',
    descripcion: 'Molde horneado de verduras con huevo y queso, ligero y casero.',
    ingredientes: [
      '2 zapallitos italianos rallados',
      '2 zanahorias ralladas',
      '1 taza de espinaca cocida',
      '5 huevos',
      '200 g de queso fresco',
      '1 taza de leche evaporada',
    ],
    preparacion: [
      'Rallar los zapallitos y la zanahoria, y exprimirlos para quitar el exceso de agua',
      'Saltear las verduras con cebolla y ajo hasta que pierdan humedad',
      'Picar la espinaca cocida y bien escurrida, e incorporarla',
      'Batir los huevos con la leche, sal, pimienta y nuez moscada',
      'Mezclar las verduras con el batido y el queso fresco en cubos',
      'Verter en un molde engrasado y enharinado',
      'Hornear a 180 grados por 40 minutos hasta que cuaje y dore la superficie',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/budin_de_verduras.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Ensalada fresca',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Locro de Pecho',
    descripcion: 'Guiso espeso de zapallo con pecho de res, choclo y queso.',
    ingredientes: [
      '700 g de pecho de res',
      '1 kg de zapallo macre en cubos',
      '2 choclos desgranados',
      '3 papas en cubos',
      '150 g de queso fresco',
      '3 cucharadas de ají amarillo molido',
    ],
    preparacion: [
      'Cocinar el pecho de res en agua con sal hasta que esté suave, reservando el caldo',
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Agregar el zapallo en cubos y tapar para que se cocine en su propio jugo',
      'Cuando el zapallo se deshaga, aplastarlo parcialmente con una cuchara',
      'Incorporar el caldo de carne, el choclo desgranado y las papas',
      'Cocinar hasta que la papa esté tierna y el guiso espese',
      'Agregar el queso fresco en cubos y la carne desmenuzada antes de servir',
    ],
    tiempo_minutos: 95,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/locro_de_pecho.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Sopa de Quinua',
    descripcion: 'Sopa andina de quinua con verduras, papa y queso fresco.',
    ingredientes: [
      '1 taza de quinua lavada',
      '2 papas en cubos',
      '1 zanahoria en cubos',
      '1 taza de habas frescas',
      '150 g de queso fresco',
      '1 cebolla picada',
    ],
    preparacion: [
      'Lavar la quinua frotándola varias veces hasta que el agua salga clara',
      'Preparar un aderezo suave con cebolla, ajo y un poco de ají panca',
      'Agregar agua o caldo de verduras y llevar a hervor',
      'Incorporar la quinua y cocinar 15 minutos',
      'Añadir la zanahoria, las habas y las papas en cubos',
      'Cocinar hasta que las verduras estén tiernas y la sopa haya espesado',
      'Agregar el queso fresco en cubos y hierbabuena picada antes de servir',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sopa_de_quinua.jpg',
    bebida: 'Mate de muña',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Sopa de Habas',
    descripcion: 'Caldo andino espeso de habas secas con papa y hierbabuena.',
    ingredientes: [
      '2 tazas de habas secas peladas',
      '3 papas en cubos',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      'Hierbabuena al gusto',
      '150 g de queso fresco',
    ],
    preparacion: [
      'Remojar las habas secas desde la noche anterior y escurrirlas',
      'Cocinarlas en abundante agua con sal hasta que estén muy tiernas',
      'Aplastar parte de las habas para que la sopa espese naturalmente',
      'Preparar un aderezo con cebolla, ajo y ají panca',
      'Incorporar el aderezo a la olla y mezclar bien',
      'Agregar las papas en cubos y cocinar hasta que ablanden',
      'Terminar con hierbabuena picada y queso fresco desmenuzado',
    ],
    tiempo_minutos: 85,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sopa_de_habas.jpg',
    bebida: 'Mate de muña',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Caldo de Mote',
    descripcion: 'Caldo serrano de mote con carne de res y verduras.',
    ingredientes: [
      '2 tazas de mote pelado',
      '600 g de carne de res con hueso',
      '2 papas en trozos',
      '1 zanahoria en rodajas',
      '1 cebolla picada',
      'Hierbabuena al gusto',
    ],
    preparacion: [
      'Remojar el mote desde la noche anterior para acortar la cocción',
      'Cocinar la carne con hueso en abundante agua para formar el caldo base',
      'Retirar la espuma que sube a la superficie para que el caldo quede limpio',
      'Agregar el mote y cocinar a fuego bajo hasta que reviente',
      'Incorporar la zanahoria y luego las papas en trozos',
      'Rectificar la sal y cocinar hasta que todo esté tierno',
      'Servir con hierbabuena picada y ají al gusto',
    ],
    tiempo_minutos: 120,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/caldo_de_mote.jpg',
    bebida: 'Mate de coca',
    acompanamiento: 'Cancha tostada',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chupe de Quinua',
    descripcion: 'Sopa cremosa de quinua con leche, queso y huevo escalfado.',
    ingredientes: [
      '1 taza de quinua lavada',
      '3 papas en cubos',
      '1 taza de leche evaporada',
      '4 huevos',
      '150 g de queso fresco',
      '2 cucharadas de ají amarillo molido',
    ],
    preparacion: [
      'Lavar bien la quinua hasta quitar toda la saponina',
      'Preparar un aderezo con cebolla, ajo y ají amarillo',
      'Agregar caldo o agua y llevar a hervor',
      'Incorporar la quinua y cocinar 15 minutos removiendo de vez en cuando',
      'Añadir las papas en cubos y cocinar hasta que estén tiernas',
      'Escalfar los huevos dentro de la sopa con cuidado',
      'Verter la leche y el queso en cubos, apagar el fuego y servir de inmediato',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chupe_de_quinua.jpg',
    bebida: 'Mate de muña',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Arroz con Mariscos al Ají',
    descripcion: 'Arroz amarillo con mariscos, vino blanco y parmesano.',
    ingredientes: [
      '3 tazas de arroz',
      '600 g de mariscos surtidos',
      '4 cucharadas de ají amarillo molido',
      '1/2 taza de vino blanco',
      '1 taza de arvejas',
      '100 g de queso parmesano',
    ],
    preparacion: [
      'Preparar un fondo de pescado con cabezas y espinas, y colarlo',
      'Hacer un aderezo con cebolla, ajo, ají amarillo y ají panca hasta que suelte aceite',
      'Verter el vino blanco y dejar evaporar el alcohol',
      'Agregar el arroz y saltearlo unos segundos para sellar el grano',
      'Verter el fondo caliente, tapar y cocinar a fuego bajo 15 minutos',
      'Incorporar los mariscos y las arvejas, y cocinar 5 minutos más',
      'Apagar el fuego, agregar parmesano y culantro, y dejar reposar antes de servir',
    ],
    tiempo_minutos: 55,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/arroz_con_mariscos_al_aji.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pescado Sudado a la Chiclayana',
    descripcion: 'Pescado entero sudado con chicha, ají y abundante cebolla.',
    ingredientes: [
      '2 pescados enteros limpios',
      '3 cebollas en pluma',
      '3 tomates en gajos',
      '1 taza de chicha de jora',
      '3 ajíes amarillos en tiras',
      'Culantro al gusto',
    ],
    preparacion: [
      'Limpiar los pescados y hacerles cortes diagonales para que la cocción sea pareja',
      'Sazonarlos con sal, pimienta, ajo y limón',
      'Cubrir el fondo de una olla amplia con cebolla en pluma y tomate',
      'Acomodar el pescado entero encima de esa cama de verduras',
      'Agregar el ají amarillo en tiras y verter la chicha de jora',
      'Tapar y cocinar a fuego medio 15 minutos sin destapar, moviendo solo la olla',
      'Servir con abundante culantro picado, yuca sancochada y arroz',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pescado_sudado_a_la_chiclayana.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Yuca y arroz',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Saltado de Vainitas',
    descripcion: 'Vainitas salteadas al wok con carne, cebolla y sillao.',
    ingredientes: [
      '500 g de vainitas en trozos',
      '400 g de carne de res en tiras',
      '1 cebolla roja en pluma',
      '2 tomates en gajos',
      '3 cucharadas de sillao',
      '2 cucharadas de vinagre tinto',
    ],
    preparacion: [
      'Cortar las vainitas en trozos diagonales y blanquearlas 3 minutos en agua hirviendo',
      'Enfriarlas en agua con hielo para que mantengan el color verde intenso',
      'Calentar el wok a fuego máximo y sellar la carne en tiras por tandas',
      'Retirar la carne y saltear la cebolla y el ají amarillo',
      'Agregar las vainitas escurridas y saltear a fuego vivo',
      'Regresar la carne, añadir el tomate, el sillao y el vinagre',
      'Mezclar rápido y servir de inmediato con arroz blanco',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/saltado_de_vainitas.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pollo Enrollado',
    descripcion: 'Pechuga de pollo rellena de jamón y queso, horneada en salsa.',
    ingredientes: [
      '4 pechugas de pollo abiertas',
      '8 lonjas de jamón',
      '200 g de queso edam',
      '1 taza de crema de leche',
      '1/2 taza de vino blanco',
      '200 g de champiñones',
    ],
    preparacion: [
      'Abrir las pechugas en mariposa y golpearlas hasta dejarlas delgadas y parejas',
      'Sazonarlas con sal, pimienta y un poco de mostaza',
      'Colocar el jamón y el queso encima, y enrollar apretando bien',
      'Asegurar cada rollo con palillos o hilo de cocina',
      'Sellarlos en una sartén caliente hasta dorar por todos lados',
      'Agregar los champiñones, el vino blanco y la crema, y llevar al horno 25 minutos',
      'Cortar en rodajas y servir bañado con la salsa y puré de papas',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pollo_enrollado.jpg',
    bebida: 'Limonada',
    acompanamiento: 'Puré de papas',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pastel de Choclo Salado',
    descripcion: 'Molde horneado de choclo molido con relleno de carne y aceitunas.',
    ingredientes: [
      '8 choclos molidos',
      '500 g de carne molida',
      '1 cebolla picada fina',
      '2 huevos duros picados',
      '50 g de aceitunas picadas',
      '1/2 taza de leche evaporada',
    ],
    preparacion: [
      'Moler los choclos tiernos hasta obtener una pasta y cocinarla con leche y mantequilla',
      'Remover constantemente a fuego bajo hasta que espese y se despegue de la olla',
      'Preparar un aderezo con cebolla, ajo y ají panca, y dorar la carne molida',
      'Agregar al relleno las aceitunas, el huevo duro y las pasas',
      'Colocar la mitad de la masa de choclo en un molde engrasado',
      'Poner el relleno y cubrir con el resto de la masa, alisando la superficie',
      'Espolvorear azúcar encima y hornear a 180 grados por 35 minutos hasta dorar',
    ],
    tiempo_minutos: 80,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pastel_de_choclo_salado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Ensalada fresca',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Lomo a lo Pobre',
    descripcion: 'Lomo fino sellado con plátano frito, papas fritas y huevo.',
    ingredientes: [
      '4 medallones de lomo fino',
      '2 plátanos maduros',
      '4 papas en bastones',
      '4 huevos',
      '4 dientes de ajo molidos',
      '40 g de mantequilla',
    ],
    preparacion: [
      'Sacar el lomo del frío 20 minutos antes y sazonarlo con sal, pimienta y ajo',
      'Freír las papas en bastones hasta que estén doradas y crocantes',
      'Cortar los plátanos maduros en tiras y freírlos hasta caramelizar',
      'Calentar una sartén hasta que esté muy caliente y sellar los medallones 3 minutos por lado',
      'Agregar mantequilla al final y bañar la carne con ella',
      'Freír los huevos dejando la yema líquida',
      'Montar el plato con arroz, la carne, las papas, el plátano y el huevo encima',
    ],
    tiempo_minutos: 40,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/lomo_a_lo_pobre.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Arroz Chaufa Amazónico',
    descripcion: 'Chaufa selvático con cecina, chorizo regional y plátano frito.',
    ingredientes: [
      '4 tazas de arroz cocido frío',
      '300 g de cecina en tiras',
      '200 g de chorizo regional',
      '3 huevos',
      '2 plátanos maduros fritos',
      '4 cucharadas de sillao',
    ],
    preparacion: [
      'Freír la cecina en tiras hasta que quede dorada y reservarla',
      'Dorar el chorizo regional en la misma sartén para que suelte su grasa',
      'Hacer una tortilla delgada con los huevos y cortarla en tiras',
      'Calentar el wok a fuego máximo y saltear el arroz frío con la grasa del chorizo',
      'Agregar la cecina, el chorizo y el sillao vertido por el borde del wok',
      'Incorporar la tortilla en tiras y la cebolla china picada',
      'Servir con plátano maduro frito al costado y ají charapita',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/arroz_chaufa_amazonico.jpg',
    bebida: 'Refresco de cocona',
    acompanamiento: 'Plátano frito',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Timbuche',
    descripcion: 'Caldo amazónico ligero de pescado fresco con huevo y sachaculantro.',
    ingredientes: [
      '600 g de pescado de río en trozos',
      '2 huevos',
      '1 plátano verde rallado',
      'Sachaculantro al gusto',
      '4 dientes de ajo molidos',
      '1 cucharadita de palillo',
    ],
    preparacion: [
      'Llevar a hervor agua con ajo, sal y palillo en una olla amplia',
      'Agregar el plátano verde rallado para dar cuerpo al caldo',
      'Incorporar los trozos de pescado y cocinar apenas 8 minutos',
      'Batir los huevos y verterlos en hilo sobre el caldo hirviendo',
      'Remover suavemente para que se formen hebras de huevo',
      'Rectificar la sal y agregar abundante sachaculantro picado',
      'Servir bien caliente con ají charapita y limón al gusto',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/timbuche.jpg',
    bebida: 'Refresco de cocona',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Picante de Cuy',
    descripcion: 'Cuy frito bañado en salsa espesa de ají panca y maní.',
    ingredientes: [
      '2 cuyes en presas',
      '4 cucharadas de ají panca molido',
      '1/2 taza de maní tostado molido',
      '4 papas sancochadas',
      '1 cebolla picada',
      '4 dientes de ajo molidos',
    ],
    preparacion: [
      'Sazonar las presas de cuy con ajo, comino, sal y pimienta',
      'Freírlas en abundante aceite caliente hasta que estén doradas y crocantes',
      'Retirar el cuy y en esa grasa preparar un aderezo con cebolla, ajo y ají panca',
      'Agregar el maní tostado molido y un poco de caldo, removiendo hasta espesar',
      'Cocinar la salsa a fuego bajo 15 minutos para que los sabores se integren',
      'Incorporar las papas sancochadas en trozos a la salsa',
      'Servir las presas de cuy bañadas con la salsa y acompañadas de arroz y mote',
    ],
    tiempo_minutos: 80,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/picante_de_cuy.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Papa y mote',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chicharrón de Trucha',
    descripcion: 'Trozos de trucha apanados en chuño y fritos, típicos de la sierra.',
    ingredientes: [
      '800 g de filete de trucha en trozos',
      '1 taza de chuño',
      '4 limones',
      '4 dientes de ajo molidos',
      'Aceite para freír',
      '2 tazas de mote cocido',
    ],
    preparacion: [
      'Cortar la trucha en trozos regulares retirando las espinas',
      'Sazonarlos con ajo molido, sal, pimienta y unas gotas de limón',
      'Dejar reposar 10 minutos sin que el limón alcance a cocinar el pescado',
      'Pasar los trozos por chuño cubriéndolos de manera pareja',
      'Freír en abundante aceite caliente 3 minutos hasta que queden dorados',
      'Escurrir sobre papel absorbente',
      'Servir con mote, papa sancochada, salsa criolla y limón',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chicharron_de_trucha.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Mote y salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Puré de Pallares con Pescado',
    descripcion: 'Crema suave de pallares servida con filete de pescado frito.',
    ingredientes: [
      '2 tazas de pallares cocidos',
      '4 filetes de pescado',
      '1 taza de leche evaporada',
      '3 cucharadas de ají amarillo molido',
      '60 g de mantequilla',
      '1 cebolla picada',
    ],
    preparacion: [
      'Cocinar los pallares remojados hasta que estén muy tiernos',
      'Licuarlos o prensarlos con parte de su agua de cocción hasta obtener una crema',
      'Preparar un aderezo con cebolla, ajo y ají amarillo',
      'Incorporar el puré de pallares al aderezo removiendo constantemente',
      'Agregar la leche y la mantequilla hasta lograr una textura suave',
      'Freír los filetes de pescado sazonados y pasados por harina hasta dorar',
      'Servir el puré como base con el pescado encima y salsa criolla',
    ],
    tiempo_minutos: 90,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pure_de_pallares_con_pescado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Estofado de Res',
    descripcion: 'Res guisada en salsa de tomate y vino con papas y zanahoria.',
    ingredientes: [
      '900 g de carne de res en cubos',
      '4 tomates licuados',
      '1 taza de vino tinto',
      '3 zanahorias en rodajas',
      '4 papas en cubos',
      '2 hojas de laurel',
    ],
    preparacion: [
      'Sellar la carne en cubos a fuego alto hasta dorarla por todos lados',
      'Retirarla y preparar un aderezo con cebolla, ajo y ají panca',
      'Agregar el tomate licuado y cocinar hasta que pierda la acidez',
      'Verter el vino tinto y dejar evaporar el alcohol',
      'Regresar la carne con el laurel y cocinar tapado a fuego bajo una hora',
      'Incorporar la zanahoria y luego las papas en cubos',
      'Cocinar hasta que todo esté tierno y la salsa espese, y servir con arroz',
    ],
    tiempo_minutos: 100,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/estofado_de_res.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Carapulcra con Sopa Seca',
    descripcion: 'El clásico dúo chinchano de papa seca guisada junto a fideos rojos.',
    ingredientes: [
      '500 g de papa seca',
      '600 g de carne de cerdo en cubos',
      '1/2 taza de maní tostado molido',
      '400 g de fideos tallarín',
      '1 atado de albahaca',
      '3 cucharadas de ají panca molido',
    ],
    preparacion: [
      'Tostar la papa seca en una olla sin aceite hasta que aromatice, luego remojarla una hora',
      'Dorar el cerdo en cubos y reservarlo',
      'Preparar un aderezo con cebolla, ajo y ají panca hasta que suelte su aceite',
      'Agregar la papa seca escurrida y caldo caliente, cocinando a fuego bajo',
      'Incorporar el maní molido y el cerdo, y cocinar hasta que la papa esté suave',
      'Para la sopa seca, hacer un aderezo con achiote, tomate y albahaca licuada',
      'Cocinar los fideos en ese aderezo hasta que absorban el líquido y servir ambos juntos',
    ],
    tiempo_minutos: 110,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/carapulcra_con_sopa_seca.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Yuca sancochada',
    video_url: null,
  },
];
