// Recetas de la categoría "almuerzos". Fuente canónica del seed.
// Los generadores de database/*.mjs leen de aquí vía recetasSeedData.js.

export const parte = [
  {
    categoria_slug: 'almuerzos',
    nombre: "Lomo Saltado",
    descripcion: "Salteado criollo-chino de carne de res, cebolla, tomate y papas fritas.",
    ingredientes: [
      "600 g de lomo de res, en tiras",
      "1 cebolla roja grande, en pluma",
      "2 tomates, en gajos",
      "3 papas grandes, fritas",
      "4 cucharadas de sillao (salsa de soya)",
      "1 ají amarillo, en tiras",
    ],
    preparacion: [
      "Cortar el lomo de res en tiras gruesas, la cebolla en pluma y el tomate en gajos",
      "Freír las papas en abundante aceite caliente hasta que doren y queden crocantes por fuera, luego reservar sobre papel absorbente",
      "Calentar un wok o sartén amplia a fuego muy alto hasta que humee ligeramente",
      "Saltear la carne por tandas pequeñas durante 1 a 2 minutos para sellarla sin que suelte demasiado jugo, y reservar",
      "En el mismo wok, saltear la cebolla y el ají amarillo en tiras a fuego alto durante 1 minuto",
      "Incorporar el tomate y saltear brevemente para que mantenga su textura firme",
      "Regresar la carne al wok, añadir el sillao, sal y pimienta, y saltear todo junto 1 minuto más",
      "Agregar las papas fritas al final, mezclando con movimientos rápidos para que se impregnen del jugo sin perder su crocancia",
      "Servir de inmediato acompañado de arroz blanco",
    ],
    tiempo_minutos: 30,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/lomo_saltado.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Arroz blanco",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Ají de Gallina",
    descripcion: "Crema espesa de ají amarillo con gallina deshilachada sobre arroz.",
    ingredientes: [
      "600 g de pechuga de gallina",
      "4 ajíes amarillos, licuados",
      "2 rebanadas de pan de molde, remojadas en leche",
      "1/2 taza de nueces, picadas",
      "1/2 taza de queso parmesano, rallado",
    ],
    preparacion: [
      "Cocer la pechuga de gallina en agua con sal, cebolla y apio durante 30 minutos, reservando el caldo",
      "Deshilachar la gallina cocida en tiras finas con las manos",
      "Remojar el pan de molde en leche tibia hasta que se ablande por completo",
      "Licuar el ají amarillo sin pepas junto con el pan remojado, las nueces y un poco del caldo de gallina hasta obtener una crema lisa",
      "Sofreír cebolla picada y ajo molido en aceite hasta que estén transparentes",
      "Verter la crema licuada sobre el sofrito y cocinar a fuego medio, revolviendo constantemente para que no se pegue",
      "Incorporar la gallina deshilachada y el queso parmesano rallado, y cocinar 10 minutos más hasta que espese",
      "Ajustar la sal y añadir más caldo si queda demasiado espesa",
      "Servir sobre arroz blanco, decorado con una rodaja de huevo duro y una aceituna",
    ],
    tiempo_minutos: 50,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/aji_de_gallina.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Arroz blanco",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Arroz con Pollo",
    descripcion: "Arroz verde aromático cocido con presas de pollo y verduras.",
    ingredientes: [
      "8 presas de pollo",
      "3 tazas de arroz",
      "2 atados de culantro, licuados",
      "1 taza de arvejas",
      "1 zanahoria, en cubos",
    ],
    preparacion: [
      "Sazonar las presas de pollo con sal, comino y pimienta",
      "Dorar el pollo en una olla grande con aceite caliente por todos sus lados y reservar",
      "Licuar el culantro con un poco de agua o caldo hasta obtener un puré verde intenso",
      "En la misma olla, sofreír cebolla, ajo y ají amarillo picados hasta que estén transparentes",
      "Añadir el culantro licuado y cocinar a fuego medio durante 5 minutos para que pierda el sabor crudo",
      "Incorporar el pollo dorado junto con la zanahoria en cubos y cubrir con caldo de pollo",
      "Añadir el arroz lavado y cocinar tapado a fuego bajo, sin destapar, hasta que el arroz absorba todo el líquido",
      "Cinco minutos antes de terminar la cocción, incorporar las arvejas",
      "Dejar reposar tapado 5 minutos más antes de servir, esponjando el arroz con un tenedor",
    ],
    tiempo_minutos: 45,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/arroz_con_pollo.jpg",
    bebida: "Chicha de jora",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Seco de Res",
    descripcion: "Guiso de carne de res en salsa de culantro, típico de la costa norte.",
    ingredientes: [
      "800 g de carne de res, en trozos",
      "2 atados de culantro, licuados",
      "1 taza de chicha de jora",
      "1 taza de arvejas",
      "300 g de zapallo loche, en cubos",
    ],
    preparacion: [
      "Cortar la carne de res en trozos grandes y sazonar con sal, comino y pimienta",
      "Sellar la carne en una olla con aceite bien caliente hasta dorar todos los lados, y reservar",
      "Licuar el culantro con un poco de agua hasta obtener un puré bien verde",
      "En la misma olla, sofreír cebolla, ajo y ají amarillo picados finamente",
      "Incorporar el culantro licuado y cocinar 5 minutos a fuego medio removiendo constantemente",
      "Regresar la carne a la olla, añadir la chicha de jora y suficiente caldo o agua hasta cubrir",
      "Cocinar tapado a fuego lento durante 50 minutos, revisando de vez en cuando y añadiendo líquido si se reduce demasiado",
      "Agregar el zapallo loche en cubos y las arvejas cuando la carne esté casi suave, cocinando 15 minutos más",
      "Verificar que la carne se deshaga fácilmente con el tenedor antes de retirar del fuego",
      "Servir caliente acompañado de frejoles y arroz blanco",
    ],
    tiempo_minutos: 70,
    dificultad: "dificil",
    imagen_asset: "/assets/images/recetas/seco_de_res.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Frejoles y arroz",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Carapulcra",
    descripcion: "Guiso afroperuano de papa seca con cerdo y maní tostado.",
    ingredientes: [
      "500 g de papa seca",
      "500 g de carne de cerdo, en trozos",
      "1 taza de maní tostado, molido",
      "4 cucharadas de ají panca, licuado",
      "30 g de chocolate (una onza)",
    ],
    preparacion: [
      "Remojar la papa seca en agua tibia durante al menos 1 hora hasta que se hidrate y ablande",
      "Sazonar el cerdo en trozos con sal, comino y pimienta",
      "Dorar el cerdo en una olla con aceite caliente hasta sellar bien todos los lados, y reservar",
      "Sofreír cebolla y ajo picados en la misma grasa hasta que estén transparentes",
      "Añadir el ají panca licuado y cocinar 5 minutos removiendo para que no se pegue",
      "Incorporar la papa seca escurrida y tostar ligeramente junto al aderezo por un par de minutos",
      "Regresar el cerdo a la olla, cubrir con caldo caliente y cocinar tapado a fuego lento durante 40 minutos",
      "Moler el maní tostado hasta obtener un polvo grueso e incorporarlo a la olla junto con una onza de chocolate rallado",
      "Cocinar 20 minutos más a fuego muy bajo, revolviendo con frecuencia para que espese sin pegarse",
      "Rectificar la sazón y servir caliente acompañado de arroz blanco",
    ],
    tiempo_minutos: 90,
    dificultad: "dificil",
    imagen_asset: "/assets/images/recetas/carapulcra.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Arroz blanco",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Tallarines Verdes",
    descripcion: "Pasta bañada en salsa de albahaca cremosa, acompañada de bistec.",
    ingredientes: [
      "500 g de tallarines",
      "2 atados de albahaca",
      "1 atado de espinaca",
      "200 g de queso fresco",
      "1/2 taza de nueces",
    ],
    preparacion: [
      "Deshojar la albahaca y la espinaca, y blanquearlas en agua hirviendo por 30 segundos, luego pasarlas a agua con hielo para fijar el color",
      "Licuar la albahaca y espinaca blanqueadas junto con el queso fresco, las nueces, un diente de ajo y un chorro de leche o caldo hasta obtener una salsa cremosa",
      "Sofreír cebolla picada en un poco de aceite hasta que esté transparente",
      "Verter la salsa licuada sobre el sofrito y cocinar a fuego bajo por 5 minutos, sin dejar que hierva fuerte para que no pierda el color",
      "Cocer los tallarines en abundante agua con sal hasta que estén al dente, siguiendo el tiempo indicado en el paquete",
      "Escurrir la pasta reservando un poco del agua de cocción",
      "Mezclar los tallarines con la salsa verde caliente, añadiendo un poco del agua reservada si queda muy espesa",
      "Freír o dorar el bistec aparte con sal y pimienta hasta el punto deseado",
      "Servir los tallarines verdes coronados con el bistec en tiras",
    ],
    tiempo_minutos: 30,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/tallarines_verdes.jpg",
    bebida: "Limonada",
    acompanamiento: "Bistec apanado",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Causa Limeña",
    descripcion: "Puré de papa amarilla sazonado con ají y limón, relleno de pollo o atún.",
    ingredientes: [
      "1 kg de papa amarilla",
      "3 ajíes amarillos, licuados",
      "4 limones",
      "2 paltas",
      "300 g de pollo deshilachado o atún",
    ],
    preparacion: [
      "Cocer la papa amarilla con cáscara en agua con sal hasta que esté bien suave, luego pelar y prensar en caliente",
      "Sazonar el puré de papa con ají amarillo licuado, jugo de limón, sal y un chorrito de aceite, amasando hasta lograr una masa lisa sin grumos",
      "Dejar enfriar la masa de papa a temperatura ambiente",
      "Preparar el relleno mezclando pollo deshilachado o atún con mayonesa, cebolla picada y un toque de limón",
      "Cortar la palta en láminas delgadas",
      "Forrar un molde con film y colocar una capa de masa de papa presionando bien",
      "Añadir una capa del relleno de pollo o atún y cubrir con láminas de palta",
      "Terminar con otra capa de masa de papa, presionando para compactar",
      "Desmoldar con cuidado, decorar la superficie y refrigerar al menos 30 minutos antes de servir",
    ],
    tiempo_minutos: 40,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/causa_limena.jpg",
    bebida: "Chicha morada",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Papa a la Huancaína",
    descripcion: "Papas cocidas bañadas en salsa cremosa de ají amarillo y queso.",
    ingredientes: [
      "1 kg de papa blanca",
      "4 ajíes amarillos",
      "300 g de queso fresco",
      "1 taza de leche",
      "6 galletas de soda",
    ],
    preparacion: [
      "Cocer las papas blancas con cáscara en agua con sal hasta que estén suaves al pincharlas con un tenedor",
      "Dejar enfriar las papas, pelarlas y cortarlas en rodajas gruesas",
      "Sofreír el ají amarillo sin pepas ni venas en un poco de aceite hasta que pierda el sabor picante fuerte",
      "Licuar el ají sofrito junto con el queso fresco, la leche y las galletas de soda hasta obtener una crema espesa y homogénea",
      "Probar y ajustar la sal, añadiendo más leche si la salsa queda demasiado espesa",
      "Acomodar las rodajas de papa sobre un plato con hojas de lechuga",
      "Bañar generosamente las papas con la salsa huancaína",
      "Decorar con huevo duro en rodajas y una aceituna de botija antes de servir",
    ],
    tiempo_minutos: 25,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/papa_a_la_huancaina.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Huevo duro y aceituna",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Escabeche",
    descripcion: "Pescado frito bañado en un guiso agridulce de cebolla y ají panca.",
    ingredientes: [
      "4 filetes de pescado (800 g)",
      "2 cebollas grandes, en pluma",
      "3 cucharadas de ají panca, licuado",
      "1/2 taza de vinagre",
      "2 camotes",
    ],
    preparacion: [
      "Sazonar los filetes de pescado con sal y pimienta, y pasarlos ligeramente por harina",
      "Freír el pescado en aceite caliente hasta dorar por ambos lados, y reservar sobre papel absorbente",
      "Cortar la cebolla en pluma gruesa y sofreírla en un poco de aceite hasta que empiece a transparentar sin perder su textura crocante",
      "Añadir el ají panca licuado y cocinar 3 minutos a fuego medio",
      "Incorporar el vinagre, un poco de agua o caldo, sal, pimienta y una pizca de azúcar, y hervir 5 minutos para que la cebolla se cocine a medias",
      "Cocer el camote en agua con sal hasta que esté suave y cortarlo en rodajas",
      "Colocar el pescado frito en una fuente y bañarlo con el escabeche caliente",
      "Servir acompañado del camote y yuca sancochada, y decorar con huevo duro y aceitunas",
    ],
    tiempo_minutos: 40,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/escabeche.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Camote y yuca",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Pollo a la Brasa",
    descripcion: "Pollo marinado y asado a fuego lento hasta quedar dorado y jugoso.",
    ingredientes: [
      "1 pollo entero (2 kg aprox.)",
      "4 cucharadas de ají panca",
      "1 taza de cerveza negra",
      "1 cucharadita de comino, orégano y pimienta",
      "4 papas grandes, fritas",
    ],
    preparacion: [
      "Limpiar bien el pollo entero, retirando exceso de grasa y secándolo con papel toalla",
      "Licuar el ají panca junto con ajo, sal, comino, pimienta, orégano y un poco de cerveza negra hasta obtener una marinada espesa",
      "Frotar el pollo con la marinada por dentro y por fuera, asegurándose de cubrir bien toda la superficie",
      "Dejar reposar en refrigeración cubierto durante al menos 4 horas, idealmente toda la noche",
      "Precalentar el horno o la parrilla a fuego medio-alto preparando una cocción indirecta",
      "Colocar el pollo en una rejilla con una bandeja debajo para recoger los jugos, y asar volteando cada 20 minutos",
      "Pincelar con más marinada o con los propios jugos durante la cocción para mantenerlo húmedo",
      "Verificar el punto de cocción pinchando el muslo, hasta que los jugos salgan claros, aproximadamente 70 a 80 minutos en total",
      "Dejar reposar 10 minutos antes de trozar y servir con papas fritas y ensalada",
    ],
    tiempo_minutos: 100,
    dificultad: "dificil",
    imagen_asset: "/assets/images/recetas/pollo_a_la_brasa.jpg",
    bebida: "Gaseosa",
    acompanamiento: "Papas fritas y ensalada",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Arroz Chaufa",
    descripcion: "Arroz salteado al estilo chifa con huevo, cebolla china y sillao.",
    ingredientes: [
      "4 tazas de arroz cocido y frío",
      "3 huevos",
      "1 atado de cebolla china",
      "4 cucharadas de sillao",
      "300 g de pollo o carne, en cubos",
    ],
    preparacion: [
      "Utilizar arroz cocido y frío, preferiblemente del día anterior, para que los granos queden sueltos",
      "Batir los huevos con una pizca de sal, verterlos en un wok bien caliente con aceite y revolver rápido hasta cocinar en trozos pequeños; reservar",
      "Cortar el pollo o la carne en cubos pequeños y saltearlos en el wok a fuego alto hasta dorar; reservar",
      "Picar la cebolla china separando la parte blanca de la verde",
      "En el mismo wok bien caliente, saltear la parte blanca de la cebolla china con un poco de aceite",
      "Añadir el arroz frío y saltear a fuego alto, desmenuzando los grumos con la espátula para que se suelte",
      "Incorporar el sillao poco a poco por los bordes del wok, mezclando rápido para que se distribuya de manera uniforme sin quedar aguado",
      "Regresar el huevo y la carne al wok, añadir la parte verde de la cebolla china y saltear todo junto 2 minutos más",
      "Servir bien caliente de inmediato",
    ],
    tiempo_minutos: 20,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/arroz_chaufa.jpg",
    bebida: "Chicha morada",
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Tacu Tacu",
    descripcion: "Frejoles y arroz del día anterior dorados en sartén, servidos con bistec o mariscos.",
    ingredientes: [
      "2 tazas de frejoles cocidos",
      "2 tazas de arroz cocido",
      "1 ají amarillo, picado",
      "1/2 cebolla, picada",
      "4 bistecs",
    ],
    preparacion: [
      "Sofreír cebolla picada y ají amarillo en un poco de aceite hasta que estén bien dorados",
      "Aplastar los frejoles cocidos con un tenedor dejando algunos enteros para dar textura",
      "Mezclar en un bowl los frejoles aplastados con el arroz cocido y el sofrito, sazonando con sal y comino",
      "Calentar una sartén con aceite y verter la mezcla, extendiéndola y presionándola para formar una capa uniforme",
      "Dorar a fuego medio sin mover durante unos 5 minutos hasta que se forme una costra dorada en la base",
      "Doblar el tacu tacu sobre sí mismo como una tortilla y dorar el otro lado 3 minutos más",
      "Sazonar y freír el bistec aparte con sal y pimienta hasta el punto deseado, o freír un huevo",
      "Servir el tacu tacu caliente coronado con el bistec o el huevo frito",
    ],
    tiempo_minutos: 30,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/tacu_tacu.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Bistec o huevo frito",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Frejoles con seco",
    descripcion: "Frejoles canarios guisados servidos junto a un seco de carne.",
    ingredientes: [
      "2 tazas de frejoles canarios",
      "600 g de carne de res, en trozos",
      "1 atado de culantro, licuado",
      "1 cebolla, picada",
      "3 dientes de ajo",
    ],
    preparacion: [
      "Remojar los frejoles canarios desde la noche anterior para acortar el tiempo de cocción",
      "Cocer los frejoles en agua con un trozo de cebolla y ajo hasta que estén suaves, reservando el caldo de cocción",
      "Sofreír cebolla y ajo picados en una olla aparte hasta que estén dorados",
      "Incorporar los frejoles cocidos con un poco de su caldo y cocinar a fuego medio 15 minutos, sazonando con sal y comino",
      "Sellar la carne de res en trozos en otra olla hasta dorar por todos lados",
      "Licuar culantro con un poco de agua y añadirlo a la carne junto con cebolla y ajo sofritos",
      "Cocinar la carne tapada a fuego lento durante 40 minutos, añadiendo caldo si se reduce demasiado, hasta que esté suave",
      "Servir los frejoles guisados junto al seco de carne y una porción de arroz blanco",
    ],
    tiempo_minutos: 60,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/frejoles_con_seco.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Arroz blanco",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Estofado",
    descripcion: "Guiso de carne o pollo cocido lentamente en salsa de tomate.",
    ingredientes: [
      "800 g de carne o pollo, en trozos",
      "3 tomates, picados",
      "2 zanahorias, en trozos",
      "3 papas, en trozos",
      "1 taza de arvejas",
    ],
    preparacion: [
      "Cortar la carne o el pollo en trozos medianos y sazonar con sal y pimienta",
      "Sellar la carne en una olla con aceite caliente hasta dorar todos los lados, y reservar",
      "Sofreír cebolla y ajo picados en la misma olla hasta que estén transparentes",
      "Añadir el tomate picado o triturado y cocinar a fuego medio hasta que se deshaga formando una salsa",
      "Regresar la carne a la olla, añadir un chorrito de vino o vinagre si se desea, y cubrir con caldo o agua",
      "Cocinar tapado a fuego lento hasta que la carne esté tierna, entre 30 y 40 minutos según el corte",
      "Incorporar la papa y la zanahoria en trozos, y cocinar 15 minutos más",
      "Añadir las arvejas en los últimos 5 minutos de cocción",
      "Rectificar la sazón y dejar que la salsa espese ligeramente antes de servir con arroz blanco",
    ],
    tiempo_minutos: 60,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/estofado.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Arroz blanco",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Pescado Frito",
    descripcion: "Filete de pescado frito y crocante, clásico de los almuerzos costeños.",
    ingredientes: [
      "4 filetes de pescado (800 g)",
      "1 taza de harina",
      "2 limones",
      "Sal al gusto",
      "2 tazas de aceite para freír",
    ],
    preparacion: [
      "Secar bien los filetes de pescado con papel toalla para que la harina se adhiera mejor",
      "Sazonar el pescado con sal, pimienta y jugo de limón, dejando reposar unos minutos",
      "Pasar cada filete por harina, sacudiendo el exceso para lograr una capa fina y uniforme",
      "Calentar abundante aceite en una sartén a fuego medio-alto hasta que esté bien caliente",
      "Freír el pescado por tandas, sin sobrecargar la sartén, entre 3 y 4 minutos por lado hasta dorar",
      "Retirar y colocar sobre papel absorbente para eliminar el exceso de aceite",
      "Servir de inmediato con un toque extra de limón, arroz y ensalada fresca",
    ],
    tiempo_minutos: 25,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/pescado_frito.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Arroz y ensalada",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Sudado",
    descripcion: "Pescado cocido a fuego lento en un guiso ligero de tomate y cebolla.",
    ingredientes: [
      "4 filetes o trozos de pescado (800 g)",
      "2 tomates, en rodajas",
      "1 cebolla grande, en pluma",
      "1 ají amarillo, en tiras",
      "1/2 atado de culantro, picado",
    ],
    preparacion: [
      "Sazonar los trozos o filetes de pescado con sal, pimienta y un poco de limón",
      "Cortar la cebolla en pluma gruesa y el tomate en rodajas",
      "Sofreír la cebolla y el ají amarillo en tiras con un poco de aceite hasta que empiecen a ablandar",
      "Añadir el tomate y cocinar 3 minutos, agregando un chorrito de agua o caldo de pescado",
      "Colocar el pescado sazonado sobre el sofrito, cubriéndolo parcialmente con la cebolla y el tomate",
      "Añadir culantro picado y tapar la olla, cocinando a fuego lento entre 12 y 15 minutos sin remover bruscamente para que el pescado no se rompa",
      "Verificar que el pescado esté cocido y opaco por dentro antes de retirar",
      "Servir caliente con el jugo del guiso, acompañado de arroz blanco",
    ],
    tiempo_minutos: 35,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/sudado.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Arroz blanco",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Ceviche",
    descripcion: "Pescado fresco marinado en limón con cebolla, ají y culantro.",
    ingredientes: [
      "600 g de pescado fresco, en cubos",
      "10 limones (jugo)",
      "1 cebolla roja grande, en pluma",
      "2 ajíes limo, picados",
      "1/2 atado de culantro, picado",
    ],
    preparacion: [
      "Elegir pescado muy fresco y cortarlo en cubos parejos de aproximadamente 2 centímetros",
      "Colocar el pescado en un bowl frío y sazonar con sal y un poco de ajo molido",
      "Exprimir limones frescos hasta obtener suficiente jugo para cubrir el pescado por completo",
      "Verter el jugo de limón sobre el pescado y mezclar suavemente, dejando marinar entre 5 y 10 minutos hasta que la carne cambie a un tono opaco",
      "Cortar la cebolla roja en pluma fina y lavarla brevemente en agua fría para suavizar su sabor",
      "Picar finamente el ají limo y el culantro",
      "Incorporar la cebolla, el ají limo y el culantro al pescado marinado, mezclando con cuidado para no romper los trozos",
      "Probar y ajustar la sal y el picante al gusto",
      "Servir de inmediato bien frío, acompañado de camote sancochado y choclo",
    ],
    tiempo_minutos: 20,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/ceviche.jpg",
    bebida: "Chicha morada",
    acompanamiento: "Camote y choclo",
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: "Arroz con Mariscos",
    descripcion: "Arroz meloso cocido con una mezcla generosa de mariscos.",
    ingredientes: [
      "3 tazas de arroz",
      "800 g de mariscos mixtos",
      "2 ajíes amarillos, licuados",
      "1 pimiento, picado",
      "1 atado de culantro, picado",
    ],
    preparacion: [
      "Limpiar bien los mariscos mixtos, retirando conchas o impurezas según corresponda",
      "Preparar un caldo rápido hirviendo las cáscaras o cabezas de los mariscos con un trozo de cebolla y apio, y colar",
      "Sofreír cebolla, ajo, ají amarillo licuado y pimiento picado en una olla amplia con aceite hasta que estén bien cocidos",
      "Añadir los mariscos más firmes primero (como calamar o pulpo) y saltear 2 minutos",
      "Incorporar el resto de los mariscos y saltear brevemente hasta que tomen color, luego retirar la mitad para añadir al final y evitar que se pasen de cocción",
      "Agregar el arroz lavado al sofrito y tostarlo un par de minutos para que absorba los sabores",
      "Cubrir con el caldo caliente de mariscos y cocinar a fuego medio-bajo sin tapar del todo, removiendo ocasionalmente para lograr una textura melosa",
      "Cuando el arroz esté casi en su punto, incorporar los mariscos reservados y el culantro picado",
      "Cocinar unos minutos más hasta que el arroz esté cocido pero jugoso, y servir de inmediato",
    ],
    tiempo_minutos: 45,
    dificultad: "dificil",
    imagen_asset: "/assets/images/recetas/arroz_con_mariscos.jpg",
    bebida: "Chicha morada",
    acompanamiento: null,
    video_url: null,
  },
];
