// Almuerzos — parte 4. Menestras, guisos de olla y platos del norte.

export const parte = [
  {
    categoria_slug: 'almuerzos',
    nombre: 'Lentejas Guisadas',
    descripcion: 'Menestra de lentejas cocidas con aderezo criollo, servida con arroz y bistec.',
    ingredientes: [
      '2 tazas de lentejas',
      '1 cebolla picada fina',
      '4 dientes de ajo molidos',
      '2 cucharadas de ají panca molido',
      '1 zanahoria en cubos',
      '2 hojas de laurel',
    ],
    preparacion: [
      'Remojar las lentejas por una hora para acortar la cocción',
      'Cocinarlas en agua con laurel y sal hasta que estén tiernas pero enteras',
      'Preparar aparte un aderezo con cebolla, ajo y ají panca hasta que suelte su aceite',
      'Agregar la zanahoria en cubos pequeños y cocinar unos minutos',
      'Incorporar el aderezo a las lentejas y mezclar bien',
      'Cocinar 15 minutos más a fuego bajo para que espese sin secarse',
      'Servir con arroz blanco, bistec apanado y salsa criolla',
    ],
    tiempo_minutos: 70,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/lentejas_guisadas.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco y bistec',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Frejol Panamito Guisado',
    descripcion: 'Frejoles blancos cocidos en aderezo criollo hasta quedar cremosos.',
    ingredientes: [
      '2 tazas de frejol panamito',
      '1 cebolla picada fina',
      '4 dientes de ajo molidos',
      '2 cucharadas de ají panca molido',
      '100 g de tocino picado',
      '2 hojas de laurel',
    ],
    preparacion: [
      'Remojar los frejoles desde la noche anterior y descartar esa agua',
      'Cocinarlos en agua nueva con laurel hasta que estén muy suaves',
      'Freír el tocino picado hasta que suelte su grasa y quede dorado',
      'En esa grasa preparar un aderezo con cebolla, ajo y ají panca',
      'Agregar el aderezo a los frejoles y mezclar',
      'Aplastar una parte de los frejoles con cuchara para que el guiso quede cremoso',
      'Cocinar 20 minutos más a fuego bajo y servir con arroz y seco de res',
    ],
    tiempo_minutos: 100,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/frejol_panamito_guisado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pallares Guisados',
    descripcion: 'Pallares cremosos guisados con aderezo de ají panca y culantro.',
    ingredientes: [
      '2 tazas de pallares',
      '1 cebolla picada fina',
      '3 cucharadas de ají panca molido',
      '4 dientes de ajo molidos',
      'Culantro picado al gusto',
      '2 hojas de laurel',
    ],
    preparacion: [
      'Remojar los pallares toda la noche y cambiar el agua antes de cocinarlos',
      'Hervirlos con laurel hasta que estén muy tiernos, sin dejar que se deshagan del todo',
      'Preparar un aderezo con cebolla, ajo y ají panca hasta que esté bien cocido',
      'Incorporar el aderezo a los pallares con parte de su agua de cocción',
      'Aplastar una porción de pallares para espesar naturalmente el guiso',
      'Sazonar con sal, pimienta y culantro picado',
      'Servir con arroz blanco y carne guisada o pescado frito',
    ],
    tiempo_minutos: 95,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/pallares_guisados.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Garbanzos Guisados',
    descripcion: 'Garbanzos cocidos en aderezo criollo con tomate y trozos de cerdo.',
    ingredientes: [
      '2 tazas de garbanzos',
      '300 g de carne de cerdo en cubos',
      '2 tomates picados',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      '1 zanahoria en cubos',
    ],
    preparacion: [
      'Remojar los garbanzos desde la noche anterior para que ablanden bien',
      'Cocinarlos en agua con sal hasta que estén tiernos y reservar su caldo',
      'Dorar los cubos de cerdo en una olla hasta sellarlos por fuera',
      'Agregar cebolla, ajo y ají panca, formando un aderezo brillante',
      'Incorporar el tomate picado y cocinar hasta deshacerlo',
      'Añadir los garbanzos con parte de su caldo y la zanahoria',
      'Cocinar 25 minutos a fuego bajo hasta que espese y servir con arroz',
    ],
    tiempo_minutos: 100,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/garbanzos_guisados.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Seco de Pollo',
    descripcion: 'Presas de pollo guisadas en culantro licuado con arvejas y papa.',
    ingredientes: [
      '1 kg de presas de pollo',
      '1 atado de culantro licuado',
      '3 cucharadas de ají amarillo molido',
      '1 taza de arvejas',
      '3 papas en cubos',
      '1 taza de chicha de jora',
    ],
    preparacion: [
      'Sazonar las presas con sal, pimienta y comino, y dorarlas en aceite caliente',
      'Retirar el pollo y en la misma olla hacer un aderezo con cebolla, ajo y ají amarillo',
      'Agregar el culantro licuado y cocinar 5 minutos para que pierda el sabor crudo',
      'Regresar las presas, verter la chicha de jora y tapar la olla',
      'Cocinar a fuego bajo 30 minutos hasta que el pollo esté suave',
      'Incorporar las arvejas y las papas en cubos, cocinando hasta que ablanden',
      'Servir con arroz blanco, frejoles y salsa criolla',
    ],
    tiempo_minutos: 65,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/seco_de_pollo.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Arroz y frejoles',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Seco de Cordero',
    descripcion: 'Cordero tierno guisado lentamente en culantro y chicha hasta deshacerse.',
    ingredientes: [
      '1.2 kg de cordero en presas',
      '1 atado grande de culantro licuado',
      '2 tazas de chicha de jora',
      '3 cucharadas de ají amarillo molido',
      '1 taza de arvejas',
      '1 cebolla picada',
    ],
    preparacion: [
      'Sazonar el cordero con ajo, sal, pimienta y comino, y dejarlo reposar 30 minutos',
      'Sellarlo en una olla con aceite muy caliente hasta que dore por todos lados',
      'Retirar la carne y preparar un aderezo con cebolla, ajo y ají amarillo',
      'Agregar el culantro licuado y cocinar hasta que el aderezo tome color verde oscuro',
      'Regresar el cordero, verter la chicha de jora y tapar',
      'Cocinar a fuego muy bajo entre hora y media y dos horas hasta que la carne se desprenda del hueso',
      'Agregar las arvejas al final y servir con yuca, arroz y frejoles',
    ],
    tiempo_minutos: 130,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/seco_de_cordero.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Yuca y frejoles',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Cabrito a la Norteña',
    descripcion: 'Cabrito norteño en salsa espesa de loche, culantro y chicha de jora.',
    ingredientes: [
      '1.5 kg de cabrito en presas',
      '1 loche rallado',
      '1 atado de culantro licuado',
      '2 tazas de chicha de jora',
      '3 cucharadas de ají amarillo molido',
      '2 tazas de frejol cocido',
    ],
    preparacion: [
      'Macerar el cabrito en chicha de jora con ajo y sal por al menos dos horas',
      'Dorar las presas escurridas en aceite bien caliente y reservarlas',
      'Preparar un aderezo con cebolla, ajo, ají amarillo y loche rallado',
      'Agregar el culantro licuado y cocinar hasta integrar',
      'Regresar la carne con la chicha de la maceración y cocinar tapado a fuego bajo',
      'Dejar que se cocine una hora y media hasta que el cabrito esté muy suave',
      'Servir con frejoles, arroz y yuca sancochada',
    ],
    tiempo_minutos: 135,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/cabrito_a_la_nortena.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Frejoles y yuca',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Espesado Chiclayano',
    descripcion: 'Guiso norteño espeso de choclo rallado con carne de res y loche.',
    ingredientes: [
      '600 g de carne de res en trozos',
      '6 choclos rallados',
      '1 loche rallado',
      '1 atado de culantro licuado',
      '1 taza de yuca en trozos',
      '3 cucharadas de ají amarillo molido',
    ],
    preparacion: [
      'Cocinar la carne en agua con sal hasta que esté suave, reservando el caldo',
      'Rallar los choclos tiernos hasta obtener una pasta espesa',
      'Preparar un aderezo con cebolla, ajo, ají amarillo y loche rallado',
      'Agregar el culantro licuado y luego el choclo rallado, removiendo constantemente',
      'Verter el caldo de carne poco a poco para que no se formen grumos',
      'Cocinar a fuego bajo removiendo hasta que espese como una crema',
      'Agregar la yuca y la carne, y servir bien caliente con arroz',
    ],
    tiempo_minutos: 90,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/espesado_chiclayano.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Arroz con Chancho',
    descripcion: 'Arroz cocido con trozos de cerdo dorados, culantro y arvejas.',
    ingredientes: [
      '800 g de carne de cerdo en cubos',
      '3 tazas de arroz',
      '1 atado de culantro licuado',
      '1 taza de arvejas',
      '1 pimiento en cubos',
      '3 cucharadas de ají amarillo molido',
    ],
    preparacion: [
      'Sazonar el cerdo con ajo, comino, sal y pimienta',
      'Dorarlo en una olla con su propia grasa hasta que quede crocante por fuera',
      'Retirar la carne y en esa grasa preparar un aderezo con cebolla, ajo y ají amarillo',
      'Agregar el culantro licuado y cocinar unos minutos',
      'Regresar la carne, verter el caldo caliente y dejar hervir',
      'Añadir el arroz, las arvejas y el pimiento, tapar y cocinar a fuego bajo 18 minutos',
      'Dejar reposar 5 minutos y servir con salsa criolla',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/arroz_con_chancho.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Seco de Chavelo',
    descripcion: 'Plato piurano de plátano verde majado con cecina y aderezo criollo.',
    ingredientes: [
      '6 plátanos verdes',
      '400 g de cecina de res',
      '2 tomates picados',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      '2 cucharadas de vinagre',
    ],
    preparacion: [
      'Asar o sancochar los plátanos verdes hasta que estén tiernos',
      'Majarlos en un batán o mortero hasta formar trozos gruesos, sin hacerlos puré',
      'Freír la cecina cortada en tiras hasta que dore y reservarla',
      'En esa misma grasa preparar un aderezo con cebolla, ajo y ají panca',
      'Agregar el tomate picado y el vinagre, cocinando hasta formar una salsa',
      'Incorporar el plátano majado y la cecina, mezclando bien',
      'Servir caliente con una ensalada de cebolla y limón encima',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/seco_de_chavelo.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Ensalada de cebolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Majado de Yuca',
    descripcion: 'Yuca sancochada y majada con aderezo, servida con chicharrón de cerdo.',
    ingredientes: [
      '1.5 kg de yuca',
      '500 g de chicharrón de cerdo',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      '4 dientes de ajo molidos',
      '1 cebolla roja en pluma',
    ],
    preparacion: [
      'Sancochar la yuca en agua con sal hasta que esté muy tierna y retirar la fibra central',
      'Majarla con un mazo o tenedor mientras aún está caliente',
      'Freír el cerdo en su propia grasa hasta obtener chicharrón dorado y crocante',
      'En esa grasa hacer un aderezo con cebolla, ajo y ají panca',
      'Mezclar el aderezo con la yuca majada hasta que tome color parejo',
      'Preparar una ensalada de cebolla en pluma con limón, sal y culantro',
      'Servir el majado con el chicharrón encima y la ensalada al costado',
    ],
    tiempo_minutos: 65,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/majado_de_yuca.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Chicharrón y salsa criolla',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Shámbar',
    descripcion: 'Sopa trujillana espesa de trigo con menestras variadas y carne de cerdo.',
    ingredientes: [
      '1 taza de trigo pelado',
      '1 taza de menestras surtidas',
      '400 g de carne de cerdo',
      '200 g de jamón del país',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      'Hierbabuena al gusto',
    ],
    preparacion: [
      'Remojar el trigo y las menestras desde la noche anterior',
      'Cocinar la carne de cerdo y el jamón en abundante agua hasta que estén suaves',
      'Agregar el trigo remojado y cocinar una hora a fuego medio',
      'Incorporar las menestras y seguir cocinando hasta que todo esté tierno',
      'Preparar aparte un aderezo con cebolla, ajo y ají panca, y añadirlo a la olla',
      'Dejar que la sopa espese removiendo de vez en cuando para que no se pegue',
      'Servir con hierbabuena picada y cancha tostada encima',
    ],
    tiempo_minutos: 150,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/shambar.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Cancha tostada',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Patasca',
    descripcion: 'Sopa andina de mote con carne y menudencias, cocida por horas.',
    ingredientes: [
      '2 tazas de mote pelado',
      '700 g de carne de res con hueso',
      '300 g de mondongo',
      '1 cebolla picada',
      '2 cucharadas de ají panca molido',
      'Hierbabuena al gusto',
    ],
    preparacion: [
      'Remojar el mote desde la noche anterior para acortar la cocción',
      'Cocinar la carne con hueso y el mondongo en abundante agua por una hora',
      'Agregar el mote remojado y seguir cocinando a fuego bajo',
      'Preparar un aderezo con cebolla, ajo y ají panca y añadirlo a la olla',
      'Continuar la cocción hasta que el mote reviente y la sopa espese, unas dos horas',
      'Rectificar la sal y agregar hierbabuena picada',
      'Servir bien caliente con ají y limón al gusto',
    ],
    tiempo_minutos: 180,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/patasca.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chairo',
    descripcion: 'Sopa altiplánica de chuño, carne y verduras, espesa y reconfortante.',
    ingredientes: [
      '1 taza de chuño negro remojado',
      '600 g de carne de res con hueso',
      '1 taza de habas frescas',
      '2 papas en cubos',
      '1 zanahoria en cubos',
      'Hierbabuena al gusto',
    ],
    preparacion: [
      'Remojar el chuño en agua toda la noche, luego pelarlo y machacarlo en trozos',
      'Cocinar la carne con hueso en agua con sal hasta formar un caldo sustancioso',
      'Agregar el chuño machacado y cocinar 30 minutos a fuego medio',
      'Incorporar las habas, la zanahoria y el trigo si se usa',
      'Preparar un aderezo con cebolla, ajo y ají panca, y verterlo a la sopa',
      'Añadir las papas en cubos y cocinar hasta que estén tiernas',
      'Terminar con hierbabuena picada y servir bien caliente',
    ],
    tiempo_minutos: 120,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chairo.jpg',
    bebida: 'Mate de coca',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Guiso de Quinua',
    descripcion: 'Quinua guisada con verduras y queso fresco, cremosa y nutritiva.',
    ingredientes: [
      '2 tazas de quinua lavada',
      '1 cebolla picada fina',
      '2 cucharadas de ají amarillo molido',
      '1 zanahoria en cubos',
      '150 g de queso fresco',
      '1/2 taza de leche evaporada',
    ],
    preparacion: [
      'Lavar la quinua frotándola varias veces para quitarle la saponina amarga',
      'Cocinarla en agua con sal hasta que el germen se separe, unos 15 minutos',
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Agregar la zanahoria y las arvejas en cubos pequeños',
      'Incorporar la quinua cocida y mezclar bien',
      'Verter la leche evaporada y el queso fresco desmenuzado, sin dejar que hierva',
      'Servir cremoso con huevo frito encima o carne guisada al costado',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/guiso_de_quinua.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Huevo frito',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Quinua Atamalada',
    descripcion: 'Quinua cocida al estilo tamal con aderezo amarillo y queso.',
    ingredientes: [
      '2 tazas de quinua',
      '3 cucharadas de ají amarillo molido',
      '1 cebolla picada fina',
      '200 g de queso fresco',
      '1 taza de leche evaporada',
      'Huacatay al gusto',
    ],
    preparacion: [
      'Lavar bien la quinua hasta que el agua salga clara',
      'Cocinarla en agua con sal hasta que esté tierna y suelte su almidón',
      'Preparar un aderezo abundante con cebolla, ajo y ají amarillo',
      'Incorporar la quinua cocida al aderezo removiendo constantemente',
      'Agregar leche evaporada y un poco de huacatay picado',
      'Añadir el queso fresco en cubos y remover hasta que se derrita parcialmente',
      'Servir en plato hondo, cremoso, con huevo duro o carne al costado',
    ],
    tiempo_minutos: 50,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/quinua_atamalada.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Huevo duro',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Trigo Atamalado',
    descripcion: 'Trigo cocido cremoso con aderezo de ají y trozos de cerdo.',
    ingredientes: [
      '2 tazas de trigo pelado',
      '400 g de carne de cerdo en cubos',
      '3 cucharadas de ají amarillo molido',
      '1 cebolla picada',
      '150 g de queso fresco',
      '1 taza de leche evaporada',
    ],
    preparacion: [
      'Remojar el trigo desde la noche anterior y cocinarlo en agua con sal hasta que reviente',
      'Dorar los cubos de cerdo en una olla hasta sellarlos',
      'Preparar un aderezo con cebolla, ajo y ají amarillo en esa misma grasa',
      'Incorporar el trigo cocido con parte de su agua de cocción',
      'Cocinar removiendo hasta que la mezcla espese y quede cremosa',
      'Agregar la leche evaporada y el queso fresco desmenuzado',
      'Rectificar la sal y servir bien caliente',
    ],
    tiempo_minutos: 110,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/trigo_atamalado.jpg',
    bebida: 'Chicha morada',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Locro de Zapallo',
    descripcion: 'Guiso cremoso de zapallo macre con choclo, papa y queso fresco.',
    ingredientes: [
      '1 kg de zapallo macre en cubos',
      '2 papas en cubos',
      '1 choclo desgranado',
      '3 cucharadas de ají amarillo molido',
      '150 g de queso fresco',
      '1 taza de leche evaporada',
      'Huacatay al gusto',
    ],
    preparacion: [
      'Preparar un aderezo con cebolla, ajo y ají amarillo hasta que suelte su aceite',
      'Agregar el zapallo en cubos y tapar la olla para que se cocine en su propio jugo',
      'Cuando el zapallo empiece a deshacerse, aplastarlo parcialmente con cuchara',
      'Incorporar la papa en cubos y el choclo desgranado',
      'Agregar un poco de caldo si hace falta y cocinar hasta que la papa esté tierna',
      'Verter la leche evaporada y el queso fresco en cubos, y apagar el fuego',
      'Terminar con huacatay picado y servir con arroz blanco',
    ],
    tiempo_minutos: 50,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/locro_de_zapallo.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Arroz blanco',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pepián de Choclo',
    descripcion: 'Guiso espeso de choclo rallado con presas de pollo y ají panca.',
    ingredientes: [
      '6 choclos rallados',
      '1 kg de presas de pollo',
      '3 cucharadas de ají panca molido',
      '1 cebolla picada',
      '4 dientes de ajo molidos',
      '1 cucharadita de palillo',
    ],
    preparacion: [
      'Sazonar y dorar las presas de pollo en una olla con aceite caliente',
      'Retirar el pollo y preparar un aderezo con cebolla, ajo, ají panca y palillo',
      'Agregar el choclo rallado y remover constantemente para que no se pegue',
      'Verter caldo de pollo poco a poco mientras se sigue removiendo',
      'Regresar las presas de pollo a la olla y tapar',
      'Cocinar a fuego bajo hasta que el choclo espese y el pollo esté tierno',
      'Servir con arroz blanco y yuca sancochada',
    ],
    tiempo_minutos: 75,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pepian_de_choclo.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Arroz y yuca',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Carne a la Olla',
    descripcion: 'Trozo grande de res cocido lentamente con verduras en su propio jugo.',
    ingredientes: [
      '1.5 kg de carne de res en trozo',
      '3 zanahorias en trozos',
      '2 cebollas en cuartos',
      '4 papas enteras',
      '2 hojas de laurel',
      '1 taza de vino tinto',
    ],
    preparacion: [
      'Sazonar el trozo de carne con ajo molido, sal, pimienta y comino por todos lados',
      'Sellarlo en una olla pesada con aceite muy caliente hasta dorarlo uniformemente',
      'Agregar la cebolla en cuartos y la zanahoria alrededor de la carne',
      'Verter el vino tinto y dejar evaporar el alcohol',
      'Añadir laurel y un poco de caldo, tapar y cocinar a fuego muy bajo dos horas',
      'Agregar las papas enteras en la última media hora de cocción',
      'Cortar la carne en tajadas gruesas y servirla bañada con su propio jugo',
    ],
    tiempo_minutos: 150,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/carne_a_la_olla.jpg',
    bebida: 'Chicha morada',
    acompanamiento: 'Papas y arroz',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Pachamanca a la Olla',
    descripcion: 'Versión casera de la pachamanca con carnes marinadas en huacatay y chincho.',
    ingredientes: [
      '500 g de carne de cerdo',
      '500 g de presas de pollo',
      '4 papas enteras',
      '2 camotes',
      '1 atado de huacatay',
      '1 atado de chincho',
      '2 tazas de habas',
    ],
    preparacion: [
      'Licuar el huacatay, el chincho, el ají panca, el ajo y la chicha para formar la marinada',
      'Marinar las carnes en esa mezcla durante al menos cuatro horas',
      'Colocar en el fondo de una olla grande las hojas verdes sobrantes',
      'Acomodar encima las carnes con toda su marinada',
      'Cubrir con las papas, los camotes, las habas y el choclo',
      'Tapar herméticamente y cocinar a fuego bajo una hora y media sin destapar',
      'Servir todo junto en una fuente con salsa de huacatay al costado',
    ],
    tiempo_minutos: 135,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/pachamanca_a_la_olla.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Salsa de huacatay',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Patarashca',
    descripcion: 'Pescado amazónico envuelto en hoja de bijao y asado a la brasa.',
    ingredientes: [
      '4 pescados de río limpios',
      'Hojas de bijao',
      '2 tomates en rodajas',
      '1 cebolla en pluma',
      'Sachaculantro al gusto',
      '2 ajíes dulces',
    ],
    preparacion: [
      'Limpiar el pescado y hacerle cortes diagonales en ambos lados',
      'Sazonarlo con sal, pimienta, ajo y jugo de limón por dentro y por fuera',
      'Rellenarlo con cebolla, tomate, ají dulce y sachaculantro picados',
      'Pasar las hojas de bijao por calor para que se ablanden',
      'Envolver cada pescado con las hojas formando un paquete cerrado y amarrarlo',
      'Asar sobre brasas medianas unos 20 minutos, volteando a la mitad',
      'Abrir el paquete en la mesa y servir con yuca sancochada y plátano asado',
    ],
    tiempo_minutos: 55,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/patarashca.jpg',
    bebida: 'Refresco de cocona',
    acompanamiento: 'Yuca y plátano asado',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Inchicapi',
    descripcion: 'Sopa amazónica espesa de gallina con maní, maíz y sachaculantro.',
    ingredientes: [
      '1 kg de presas de gallina',
      '1 taza de maní tostado molido',
      '1 taza de harina de maíz',
      '2 yucas en trozos',
      'Sachaculantro al gusto',
      '1 cucharadita de palillo',
    ],
    preparacion: [
      'Cocinar las presas de gallina en abundante agua con sal, ajo y palillo',
      'Cuando la gallina esté suave, retirarla y reservar el caldo',
      'Licuar el maní tostado con la harina de maíz y un poco de caldo',
      'Verter esa mezcla al caldo hirviendo removiendo constantemente para evitar grumos',
      'Cocinar a fuego bajo hasta que la sopa espese como una crema',
      'Agregar la yuca en trozos y cocinar hasta que esté tierna',
      'Regresar las presas, añadir sachaculantro picado y servir bien caliente',
    ],
    tiempo_minutos: 90,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/inchicapi.jpg',
    bebida: 'Chapo',
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Chicharrón Colorado',
    descripcion: 'Cerdo cusqueño frito en su grasa con ají panca, servido con mote y papa.',
    ingredientes: [
      '1 kg de carne de cerdo en trozos',
      '3 cucharadas de ají panca molido',
      '2 tazas de mote cocido',
      '4 papas sancochadas',
      '4 dientes de ajo molidos',
      '1 cucharadita de comino',
    ],
    preparacion: [
      'Sazonar el cerdo con ajo molido, comino, sal y pimienta',
      'Colocarlo en una olla con un poco de agua y cocinar tapado hasta que el agua se evapore',
      'Dejar que la carne se fría en su propia grasa hasta dorarse',
      'Agregar el ají panca molido y saltear para que impregne la carne de color rojizo',
      'Cocinar unos minutos más cuidando que no se queme el ají',
      'Sancochar aparte el mote y las papas',
      'Servir el chicharrón con mote, papa y ensalada de cebolla con rocoto',
    ],
    tiempo_minutos: 80,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chicharron_colorado.jpg',
    bebida: 'Chicha de jora',
    acompanamiento: 'Mote y papa',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Sopa de Morón',
    descripcion: 'Sopa espesa de cebada morón con carne, verduras y papa.',
    ingredientes: [
      '1 taza de cebada morón',
      '500 g de carne de res con hueso',
      '2 papas en cubos',
      '1 zanahoria en cubos',
      '1 cebolla picada',
      'Hierbabuena al gusto',
    ],
    preparacion: [
      'Remojar la cebada morón por una hora para acortar la cocción',
      'Cocinar la carne con hueso en abundante agua para formar un buen caldo',
      'Agregar la cebada y cocinar a fuego medio unos 40 minutos',
      'Preparar un aderezo con cebolla, ajo y ají panca, y verterlo en la olla',
      'Incorporar la zanahoria y las papas en cubos',
      'Cocinar hasta que todo esté tierno y la sopa haya espesado',
      'Terminar con hierbabuena picada y servir bien caliente',
    ],
    tiempo_minutos: 90,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sopa_de_moron.jpg',
    bebida: 'Infusión de hierbas',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'almuerzos',
    nombre: 'Dieta de Pollo',
    descripcion: 'Caldo claro y ligero de pollo con fideos, papa y verduras.',
    ingredientes: [
      '600 g de presas de pollo',
      '150 g de fideos cabello de ángel',
      '2 papas en trozos',
      '1 zanahoria en rodajas',
      '1 apio en trozos',
      '1 poro en rodajas',
    ],
    preparacion: [
      'Colocar las presas de pollo en agua fría con apio, poro y zanahoria',
      'Llevar a hervor suave retirando la espuma que sube a la superficie',
      'Cocinar 40 minutos a fuego bajo para obtener un caldo claro y limpio',
      'Colar el caldo si se desea una sopa más transparente',
      'Agregar las papas en trozos y cocinar hasta que estén tiernas',
      'Añadir los fideos y cocinarlos apenas tres minutos',
      'Servir con perejil picado y unas gotas de limón',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/dieta_de_pollo.jpg',
    bebida: 'Infusión de hierbas',
    acompanamiento: 'Pan francés',
    video_url: null,
  },
];
