// Bebidas — parte 4. Extractos, jugos verdes, batidos, cremoladas y limonadas.

export const parte = [
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de zanahoria',
    descripcion: 'Extracto fresco de zanahoria con naranja y un toque de kion.',
    ingredientes: [
      '8 zanahorias',
      '4 naranjas',
      '1 trozo pequeño de kion',
      '1 limón',
      'Hielo al gusto',
      'Miel al gusto',
    ],
    preparacion: [
      'Lavar y pelar las zanahorias retirando los extremos',
      'Cortarlas en trozos que quepan en el extractor',
      'Pasar la zanahoria y el kion por el extractor de jugos',
      'Exprimir las naranjas aparte',
      'Mezclar ambos jugos y remover bien',
      'Agregar unas gotas de limón para conservar el color',
      'Servir de inmediato, porque el extracto se oxida rápido',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_zanahoria.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de betarraga',
    descripcion: 'Extracto de betarraga con naranja y zanahoria, de color intenso.',
    ingredientes: [
      '2 betarragas',
      '4 zanahorias',
      '4 naranjas',
      '1 trozo de kion',
      '1 limón',
      'Hielo al gusto',
    ],
    preparacion: [
      'Pelar las betarragas con cuidado porque tiñen mucho las manos',
      'Cortarlas en trozos junto con las zanahorias',
      'Pasarlas por el extractor alternando ambos vegetales',
      'Agregar el kion al extractor para dar un toque picante',
      'Exprimir las naranjas y mezclar con el extracto',
      'Agregar unas gotas de limón para equilibrar el sabor terroso',
      'Servir de inmediato bien frío',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_betarraga.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Extracto de alfalfa',
    descripcion: 'Jugo verde de alfalfa con piña y manzana, muy tradicional en Perú.',
    ingredientes: [
      '2 atados de alfalfa',
      '1/2 piña',
      '2 manzanas',
      '2 limones',
      'Miel al gusto',
      'Hielo al gusto',
    ],
    preparacion: [
      'Lavar la alfalfa hoja por hoja en agua con unas gotas de vinagre',
      'Enjuagarla varias veces hasta que el agua salga limpia',
      'Pasarla por el extractor junto con la manzana en trozos',
      'Licuar la piña aparte y colarla',
      'Mezclar el extracto verde con el jugo de piña',
      'Endulzar con miel y agregar jugo de limón',
      'Servir de inmediato, porque los jugos verdes se oxidan rápido',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/extracto_de_alfalfa.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo verde',
    descripcion: 'Mezcla de espinaca, apio, pepino, piña y manzana.',
    ingredientes: [
      '2 tazas de espinaca',
      '2 tallos de apio',
      '1 pepino',
      '1/2 piña',
      '1 manzana verde',
      '2 limones',
    ],
    preparacion: [
      'Lavar todas las verduras en agua con vinagre y enjuagarlas bien',
      'Cortar el pepino y el apio en trozos sin pelarlos',
      'Pelar la piña y cortarla en cubos',
      'Licuar la espinaca con la piña primero, porque aporta líquido',
      'Agregar el resto de ingredientes y licuar hasta que quede homogéneo',
      'Colar si se prefiere una textura más ligera',
      'Agregar jugo de limón y servir de inmediato',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_verde.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de apio con piña',
    descripcion: 'Jugo digestivo de apio fresco con piña y limón.',
    ingredientes: [
      '4 tallos de apio',
      '1/2 piña',
      '1 litro de agua',
      '2 limones',
      'Miel al gusto',
      'Hielo al gusto',
    ],
    preparacion: [
      'Lavar bien los tallos de apio incluyendo las hojas tiernas',
      'Cortarlos en trozos pequeños',
      'Pelar la piña y cortarla en cubos, descartando el corazón',
      'Licuar el apio con la piña y el agua',
      'Colar con un colador fino para eliminar la fibra del apio',
      'Endulzar con miel y agregar jugo de limón',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_apio_con_pina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de pepino con limón',
    descripcion: 'Bebida hidratante de pepino, limón y hierbabuena.',
    ingredientes: [
      '2 pepinos',
      '1 litro de agua fría',
      '4 limones',
      'Hojas de hierbabuena',
      'Miel al gusto',
      'Hielo al gusto',
    ],
    preparacion: [
      'Lavar los pepinos y cortarlos en trozos sin pelarlos',
      'La cáscara aporta color verde y nutrientes a la bebida',
      'Licuarlos con el agua fría y las hojas de hierbabuena',
      'Colar con un colador fino para quitar la fibra',
      'Agregar el jugo de limón recién exprimido',
      'Endulzar ligeramente con miel si se desea',
      'Servir muy frío con rodajas de pepino y hielo',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_pepino_con_limon.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de espinaca con manzana',
    descripcion: 'Jugo verde suave de espinaca, manzana y limón.',
    ingredientes: [
      '3 tazas de espinaca',
      '3 manzanas verdes',
      '1 litro de agua',
      '2 limones',
      'Miel al gusto',
      'Hielo al gusto',
    ],
    preparacion: [
      'Lavar la espinaca hoja por hoja y escurrirla bien',
      'Descorazonar las manzanas y cortarlas en trozos con cáscara',
      'Rociar la manzana con limón para que no se oxide',
      'Licuar la espinaca con la manzana y el agua',
      'Colar con un colador fino si se prefiere sin fibra',
      'Endulzar con miel y agregar más limón al gusto',
      'Servir de inmediato bien helado',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_espinaca_con_manzana.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de zanahoria con naranja y kion',
    descripcion: 'Combinación energética de zanahoria, naranja y jengibre fresco.',
    ingredientes: [
      '6 zanahorias',
      '6 naranjas',
      '1 trozo grande de kion',
      '1 cucharadita de cúrcuma',
      'Miel al gusto',
      'Hielo al gusto',
    ],
    preparacion: [
      'Pelar las zanahorias y cortarlas en bastones',
      'Pelar el kion y cortarlo en rodajas delgadas',
      'Pasar la zanahoria y el kion por el extractor',
      'Exprimir las naranjas por separado',
      'Mezclar ambos jugos y agregar la cúrcuma en polvo',
      'Endulzar con miel si se desea',
      'Servir de inmediato en vaso con hielo',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_zanahoria_con_naranja_y_kion.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Batido de lúcuma',
    descripcion: 'Batido espeso de lúcuma con leche, hielo y vainilla.',
    ingredientes: [
      '3 lúcumas maduras',
      '2 tazas de leche',
      '1/3 taza de azúcar',
      '2 tazas de hielo',
      '1 cucharadita de vainilla',
      '1 pizca de canela',
    ],
    preparacion: [
      'Pelar las lúcumas y retirar la pepa central',
      'Cortar la pulpa en trozos pequeños',
      'Colocar la pulpa, la leche y el azúcar en la licuadora',
      'Licuar hasta que la mezcla quede completamente lisa',
      'Agregar el hielo y licuar de nuevo a velocidad alta',
      'Ajustar el dulzor y agregar la vainilla',
      'Servir de inmediato en vaso alto con canela espolvoreada',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/batido_de_lucuma.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Batido de fresa con leche',
    descripcion: 'Milkshake cremoso de fresas frescas con leche y hielo.',
    ingredientes: [
      '500 g de fresas',
      '2 tazas de leche',
      '1/2 taza de azúcar',
      '2 tazas de hielo',
      '1 cucharadita de vainilla',
      '1 limón',
    ],
    preparacion: [
      'Lavar las fresas y retirarles las hojas verdes',
      'Reservar algunas fresas para decorar',
      'Licuar el resto con la leche y el azúcar',
      'Agregar el hielo y licuar a velocidad alta hasta que espese',
      'Probar y ajustar el dulzor',
      'Agregar unas gotas de limón para realzar el sabor de la fruta',
      'Servir en vaso alto decorado con una fresa',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/batido_de_fresa_con_leche.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Batido de plátano con avena',
    descripcion: 'Batido nutritivo de plátano, avena y leche para empezar el día.',
    ingredientes: [
      '3 plátanos maduros',
      '1/2 taza de avena en hojuelas',
      '2 tazas de leche',
      '2 cucharadas de miel',
      '1 cucharadita de canela',
      'Hielo al gusto',
    ],
    preparacion: [
      'Remojar la avena en un poco de leche durante 10 minutos',
      'El remojo ablanda la hojuela y hace el batido más cremoso',
      'Pelar los plátanos maduros y cortarlos en trozos',
      'Licuar el plátano con la avena remojada y el resto de la leche',
      'Agregar la miel y la canela',
      'Licuar con hielo hasta lograr la textura deseada',
      'Servir de inmediato espolvoreado con canela',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/batido_de_platano_con_avena.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Batido de mango con yogurt',
    descripcion: 'Smoothie cremoso de mango, yogurt natural y miel.',
    ingredientes: [
      '3 mangos maduros',
      '2 tazas de yogurt natural',
      '3 cucharadas de miel',
      '2 tazas de hielo',
      '1 limón',
      '1 cucharada de semillas de chía',
    ],
    preparacion: [
      'Pelar los mangos y separar la pulpa del hueso',
      'Cortar la pulpa en cubos y congelarla si se quiere más espeso',
      'Licuar el mango con el yogurt natural',
      'Agregar la miel y licuar hasta integrar',
      'Añadir el hielo y licuar a velocidad alta',
      'Agregar unas gotas de limón para equilibrar el dulzor',
      'Servir en vaso alto con semillas de chía encima',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/batido_de_mango_con_yogurt.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Batido de chirimoya',
    descripcion: 'Batido cremoso de chirimoya con leche y hielo.',
    ingredientes: [
      '2 chirimoyas maduras',
      '2 tazas de leche',
      '1/4 taza de azúcar',
      '2 tazas de hielo',
      '1 cucharadita de vainilla',
      '1 limón',
    ],
    preparacion: [
      'Abrir las chirimoyas y retirar la pulpa con una cuchara',
      'Separar con paciencia todas las semillas negras',
      'Licuar la pulpa con la leche durante poco tiempo',
      'No licuar en exceso para que no se vuelva amarga',
      'Agregar el azúcar y la vainilla',
      'Añadir el hielo y licuar brevemente',
      'Servir de inmediato con unas gotas de limón',
    ],
    tiempo_minutos: 18,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/batido_de_chirimoya.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Cremolada de fresa',
    descripcion: 'Granizado espeso de fresa con hielo, típico de la calle limeña.',
    ingredientes: [
      '600 g de fresas',
      '3 tazas de hielo',
      '1 taza de azúcar',
      '1/2 taza de agua',
      '1 limón',
      '1 pizca de sal',
    ],
    preparacion: [
      'Lavar las fresas y retirarles las hojas',
      'Congelar la mitad de las fresas por al menos cuatro horas',
      'Preparar un jarabe hirviendo el azúcar con el agua y dejarlo enfriar',
      'Licuar las fresas congeladas con las frescas y el jarabe',
      'Agregar el hielo poco a poco mientras se licua',
      'Buscar una textura espesa que se pueda comer con cuchara',
      'Servir de inmediato en vaso con una fresa encima',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cremolada_de_fresa.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Cremolada de maracuyá',
    descripcion: 'Granizado ácido y dulce de maracuyá con hielo molido.',
    ingredientes: [
      '12 maracuyás',
      '3 tazas de hielo',
      '1 taza de azúcar',
      '1/2 taza de agua',
      '1 pizca de sal',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Extraer la pulpa de los maracuyás y licuarla brevemente con agua',
      'Colar para separar las semillas',
      'Preparar un jarabe con el azúcar y el agua, y dejarlo enfriar',
      'Congelar parte del jugo de maracuyá en cubetera',
      'Licuar los cubos de jugo congelado con el jugo fresco y el jarabe',
      'Agregar hielo hasta lograr una textura espesa de granizado',
      'Servir de inmediato con hierbabuena',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cremolada_de_maracuya.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Cremolada de lúcuma',
    descripcion: 'Granizado cremoso de lúcuma con leche condensada.',
    ingredientes: [
      '4 lúcumas maduras',
      '3 tazas de hielo',
      '1 lata de leche condensada',
      '1 taza de leche',
      '1 cucharadita de vainilla',
      '1 pizca de canela',
    ],
    preparacion: [
      'Pelar las lúcumas y retirar las pepas',
      'Cortar la pulpa en trozos y congelarla por cuatro horas',
      'Licuar la pulpa congelada con la leche',
      'Agregar la leche condensada poco a poco mientras se licua',
      'Añadir el hielo hasta lograr una textura espesa',
      'Agregar la vainilla y mezclar',
      'Servir de inmediato espolvoreado con canela',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cremolada_de_lucuma.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Cremolada de guanábana',
    descripcion: 'Granizado perfumado de guanábana con hielo y azúcar.',
    ingredientes: [
      '1 guanábana madura',
      '3 tazas de hielo',
      '1 taza de azúcar',
      '1 taza de agua',
      '1 limón',
      '1 pizca de sal',
    ],
    preparacion: [
      'Abrir la guanábana y retirar la pulpa blanca',
      'Separar con cuidado todas las semillas negras, que no se deben licuar',
      'Preparar un jarabe con el azúcar y el agua, y enfriarlo',
      'Congelar parte de la pulpa por al menos cuatro horas',
      'Licuar la pulpa congelada con la fresca y el jarabe',
      'Agregar hielo hasta lograr la textura de granizado',
      'Servir de inmediato con unas gotas de limón',
    ],
    tiempo_minutos: 25,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/cremolada_de_guanabana.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Maracuyá frozen',
    descripcion: 'Bebida frozen de maracuyá batida con hielo hasta quedar espumosa.',
    ingredientes: [
      '10 maracuyás',
      '4 tazas de hielo',
      '1 taza de azúcar',
      '1 taza de agua',
      '1 clara de huevo',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Extraer la pulpa de los maracuyás y licuarla brevemente con agua',
      'Colar para eliminar las semillas',
      'Preparar un jarabe con el azúcar y el agua, y dejarlo enfriar',
      'Colocar el jugo, el jarabe y el hielo en la licuadora',
      'Licuar a velocidad máxima durante un minuto completo',
      'Agregar la clara de huevo y licuar 20 segundos más para dar espuma',
      'Servir de inmediato en copa con hierbabuena',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/maracuya_frozen.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Limonada frozen',
    descripcion: 'Limonada batida con hielo hasta quedar espumosa y helada.',
    ingredientes: [
      '10 limones',
      '4 tazas de hielo',
      '1 taza de azúcar',
      '2 tazas de agua',
      'Hojas de hierbabuena',
      '1 pizca de sal',
    ],
    preparacion: [
      'Exprimir los limones sin presionar demasiado la cáscara',
      'Preparar un jarabe disolviendo el azúcar en agua caliente y enfriarlo',
      'Colocar el jugo de limón, el jarabe y el agua en la licuadora',
      'Agregar todo el hielo de una vez',
      'Licuar a velocidad máxima durante un minuto hasta que quede espumoso',
      'Probar y ajustar el equilibrio entre ácido y dulce',
      'Servir de inmediato con hierbabuena',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/limonada_frozen.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Limonada clásica',
    descripcion: 'Limonada peruana con jugo de limón, agua, azúcar y hielo.',
    ingredientes: [
      '10 limones',
      '2 litros de agua',
      '1 taza de azúcar',
      'Hielo al gusto',
      'Hojas de hierbabuena',
      '1 pizca de sal',
    ],
    preparacion: [
      'Rodar los limones sobre la mesa presionando para que suelten más jugo',
      'Cortarlos por la mitad y exprimirlos sin apretar la cáscara',
      'Disolver el azúcar en un poco de agua tibia para hacer un jarabe',
      'Mezclar el jarabe con el resto del agua fría',
      'Agregar el jugo de limón y remover bien',
      'Probar y ajustar el dulzor y la acidez',
      'Servir bien helado con hielo y hierbabuena',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/limonada_clasica.jpg',
    bebida: null,
    acompanamiento: 'Almuerzos criollos',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Limonada de hierbabuena',
    descripcion: 'Limonada aromatizada con hojas de hierbabuena machacadas.',
    ingredientes: [
      '10 limones',
      '2 litros de agua',
      '1 atado de hierbabuena',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 pizca de sal',
    ],
    preparacion: [
      'Machacar las hojas de hierbabuena con el azúcar en un mortero',
      'El machacado libera los aceites esenciales de la hoja',
      'Exprimir los limones y reservar el jugo',
      'Mezclar la hierbabuena machacada con el agua fría',
      'Dejar reposar 10 minutos para que infusione',
      'Colar y agregar el jugo de limón',
      'Servir bien helado con hojas frescas de hierbabuena',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/limonada_de_hierbabuena.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Agua de manzana con canela',
    descripcion: 'Bebida aromática de manzana hervida con canela y clavo.',
    ingredientes: [
      '6 manzanas',
      '2 litros de agua',
      '2 palitos de canela',
      '6 clavos de olor',
      'Azúcar al gusto',
      '2 limones',
    ],
    preparacion: [
      'Lavar las manzanas y cortarlas en trozos con cáscara',
      'Colocarlas en una olla con el agua, la canela y el clavo',
      'Hervir 30 minutos a fuego medio',
      'Aplastar las manzanas dentro de la olla para soltar más sabor',
      'Colar el líquido descartando los sólidos',
      'Endulzar al gusto mientras aún está caliente',
      'Servir caliente en invierno o bien helada con limón en verano',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/agua_de_manzana_con_canela.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Agua de jengibre con limón',
    descripcion: 'Infusión digestiva de kion fresco con limón y miel.',
    ingredientes: [
      '1 trozo grande de kion',
      '2 litros de agua',
      '6 limones',
      '3 cucharadas de miel',
      '1 palito de canela',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Pelar el kion y cortarlo en rodajas delgadas',
      'Hervir el agua y agregar el kion con la canela',
      'Cocinar a fuego bajo durante 15 minutos',
      'Apagar el fuego y dejar reposar tapado 10 minutos más',
      'Colar el líquido descartando el kion',
      'Agregar el jugo de limón cuando ya no esté hirviendo',
      'Endulzar con miel y servir caliente o helada',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/agua_de_jengibre_con_limon.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Agua saborizada de cítricos',
    descripcion: 'Agua fría infusionada con rodajas de cítricos y hierbabuena.',
    ingredientes: [
      '2 naranjas',
      '2 limones',
      '1 mandarina',
      '2 litros de agua',
      'Hojas de hierbabuena',
      'Hielo al gusto',
    ],
    preparacion: [
      'Lavar muy bien los cítricos porque se usan con cáscara',
      'Cortarlos en rodajas delgadas',
      'Colocar las rodajas en una jarra grande',
      'Agregar las hojas de hierbabuena ligeramente machacadas',
      'Verter el agua fría y remover suavemente',
      'Refrigerar al menos tres horas para que infusione',
      'Servir con hielo, retirando los cítricos después de un día',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/agua_saborizada_de_citricos.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Yogurt casero de fresa',
    descripcion: 'Yogurt natural hecho en casa con mermelada de fresa.',
    ingredientes: [
      '2 litros de leche fresca',
      '1 taza de yogurt natural',
      '1 taza de mermelada de fresa',
      '1/2 taza de azúcar',
      '1 cucharadita de vainilla',
      '300 g de fresas frescas',
    ],
    preparacion: [
      'Hervir la leche y dejarla entibiar hasta unos 45 grados',
      'Comprobar la temperatura: debe sentirse tibia, no caliente',
      'Disolver el yogurt natural en un poco de esa leche tibia',
      'Mezclarlo con el resto de la leche removiendo suavemente',
      'Tapar y envolver el recipiente con una manta para conservar el calor',
      'Dejar reposar entre 8 y 10 horas sin moverlo',
      'Refrigerar, endulzar y mezclar con la mermelada y las fresas picadas',
    ],
    tiempo_minutos: 600,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/yogurt_casero_de_fresa.jpg',
    bebida: null,
    acompanamiento: 'Granola',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Leche con plátano y algarrobina',
    descripcion: 'Batido energético de leche, plátano y algarrobina.',
    ingredientes: [
      '3 plátanos maduros',
      '2 tazas de leche',
      '3 cucharadas de algarrobina',
      '2 cucharadas de azúcar',
      'Hielo al gusto',
      '1 pizca de canela',
    ],
    preparacion: [
      'Pelar los plátanos maduros y cortarlos en trozos',
      'Colocarlos en la licuadora con la leche fría',
      'Agregar la algarrobina, que aporta color oscuro y sabor tostado',
      'Licuar hasta que la mezcla quede completamente cremosa',
      'Endulzar al gusto recordando que la algarrobina ya es dulce',
      'Agregar hielo y licuar de nuevo',
      'Servir en vaso alto espolvoreado con canela',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/leche_con_platano_y_algarrobina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo surtido especial',
    descripcion: 'Mezcla de papaya, plátano, betarraga, naranja y alfalfa.',
    ingredientes: [
      '1/2 papaya',
      '2 plátanos',
      '1 betarraga cocida',
      '4 naranjas',
      '1 atado de alfalfa',
      '2 cucharadas de miel',
    ],
    preparacion: [
      'Exprimir las naranjas y reservar el jugo',
      'Pasar la alfalfa lavada por el extractor',
      'Cocinar la betarraga y cortarla en trozos',
      'Licuar la papaya, el plátano y la betarraga con el jugo de naranja',
      'Agregar el extracto de alfalfa y licuar de nuevo',
      'Endulzar con miel al gusto',
      'Servir de inmediato en vaso grande',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_surtido_especial.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Batido de papaya con avena',
    descripcion: 'Batido espeso de papaya, avena y leche, muy saciante.',
    ingredientes: [
      '1/2 papaya madura',
      '1/2 taza de avena',
      '2 tazas de leche',
      '2 cucharadas de miel',
      'Hielo al gusto',
      '1 cucharadita de canela',
    ],
    preparacion: [
      'Remojar la avena en leche durante 10 minutos para ablandarla',
      'Pelar la papaya, retirar las semillas y cortarla en cubos',
      'Licuar la papaya con la avena remojada y el resto de la leche',
      'Licuar hasta que la avena quede completamente integrada',
      'Endulzar con miel al gusto',
      'Agregar hielo y licuar brevemente',
      'Servir espolvoreado con canela',
    ],
    tiempo_minutos: 18,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/batido_de_papaya_con_avena.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
];
