// Bebidas — parte 6. Ponches, chocolates calientes y clásicos con pisco.
// Nota: las últimas nueve llevan alcohol. Si la ruleta debe excluirlas,
// filtrar por nombre o agregar una columna "alcoholica" al esquema.

export const parte = [
  {
    categoria_slug: 'bebidas',
    nombre: 'Ponche de habas',
    descripcion: 'Bebida caliente y espesa de habas tostadas con leche y canela.',
    ingredientes: [
      '2 tazas de habas secas',
      '1 litro de leche',
      '1 litro de agua',
      '1 taza de azúcar',
      '2 palitos de canela',
      '6 clavos de olor',
    ],
    preparacion: [
      'Tostar las habas secas en una olla hasta que doren y aromaticen',
      'Molerlas hasta obtener una harina gruesa',
      'Hervirlas en agua con la canela y el clavo durante 40 minutos',
      'Colar el líquido presionando el bagazo para extraer todo el sabor',
      'Regresar al fuego y agregar la leche poco a poco',
      'Cocinar removiendo hasta que espese ligeramente',
      'Endulzar y servir muy caliente en taza',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/ponche_de_habas.jpg',
    bebida: null,
    acompanamiento: 'Pan con queso',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Ponche de maní',
    descripcion: 'Ponche cremoso de maní tostado con leche, canela y clavo.',
    ingredientes: [
      '2 tazas de maní tostado',
      '1.5 litros de leche',
      '1 taza de azúcar',
      '1/2 taza de arroz remojado',
      '2 palitos de canela',
      '6 clavos de olor',
    ],
    preparacion: [
      'Frotar el maní tostado en un paño para retirarle la piel',
      'Remojar el arroz en agua durante una hora',
      'Licuar el maní con el arroz y un poco de agua hasta que quede muy fino',
      'Colar la mezcla con un paño fino exprimiendo con fuerza',
      'Llevar a fuego bajo con la leche, la canela y el clavo',
      'Remover constantemente para que no se pegue ni se corte',
      'Endulzar y servir bien caliente',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/ponche_de_mani.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Ponche navideño',
    descripcion: 'Ponche caliente de frutas secas, canela y clavo para las fiestas.',
    ingredientes: [
      '2 manzanas en cubos',
      '1 taza de pasas',
      '1 taza de orejones de durazno',
      '3 litros de agua',
      '3 palitos de canela',
      '1 taza de chancaca',
      '8 clavos de olor',
    ],
    preparacion: [
      'Colocar el agua en una olla grande con la canela y el clavo',
      'Llevar a hervor y agregar la chancaca en trozos',
      'Remover hasta que la chancaca se disuelva por completo',
      'Agregar los orejones y las pasas, y cocinar 20 minutos',
      'Incorporar la manzana en cubos en los últimos 10 minutos',
      'Probar y ajustar el dulzor',
      'Servir muy caliente en taza con un poco de la fruta',
    ],
    tiempo_minutos: 55,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/ponche_navideno.jpg',
    bebida: null,
    acompanamiento: 'Panetón',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Ponche de leche',
    descripcion: 'Leche caliente batida con huevo, canela y azúcar.',
    ingredientes: [
      '1.5 litros de leche',
      '4 huevos',
      '1 taza de azúcar',
      '2 palitos de canela',
      '1 cucharadita de vainilla',
      '1 pizca de nuez moscada',
    ],
    preparacion: [
      'Calentar la leche con la canela sin dejar que hierva',
      'Batir los huevos con el azúcar hasta que blanqueen y espumen',
      'Verter un poco de leche caliente sobre los huevos batiendo sin parar',
      'Este paso atempera los huevos y evita que se cocinen de golpe',
      'Regresar la mezcla a la olla removiendo constantemente a fuego bajo',
      'Cocinar hasta que espese ligeramente sin llegar a hervir',
      'Agregar la vainilla, espolvorear nuez moscada y servir caliente',
    ],
    tiempo_minutos: 30,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/ponche_de_leche.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Ponche de quinua',
    descripcion: 'Bebida caliente y espesa de quinua con leche, canela y manzana.',
    ingredientes: [
      '1 taza de quinua',
      '1 litro de leche',
      '1 litro de agua',
      '2 manzanas',
      '1 taza de azúcar',
      '2 palitos de canela',
    ],
    preparacion: [
      'Lavar la quinua frotándola varias veces para quitar la saponina',
      'Hervirla en agua con la canela hasta que el grano reviente',
      'Agregar la manzana en cubos y cocinar 10 minutos más',
      'Licuar todo y colar si se prefiere una textura más fina',
      'Regresar al fuego y agregar la leche poco a poco',
      'Cocinar removiendo hasta que espese ligeramente',
      'Endulzar y servir muy caliente en taza',
    ],
    tiempo_minutos: 55,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/ponche_de_quinua.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Calientito',
    descripcion: 'Infusión caliente de té con frutas y especias, típica de las noches frías.',
    ingredientes: [
      '4 bolsitas de té negro',
      '2 litros de agua',
      '2 manzanas en cubos',
      '1 piña en trozos',
      '3 palitos de canela',
      '1 taza de azúcar',
      '8 clavos de olor',
    ],
    preparacion: [
      'Hervir el agua con la canela, el clavo y la cáscara de piña',
      'Cocinar 20 minutos para que las especias suelten su aroma',
      'Agregar la manzana y la piña en cubos',
      'Cocinar 10 minutos más hasta que la fruta esté blanda',
      'Apagar el fuego y agregar las bolsitas de té',
      'Dejar infusionar 4 minutos y retirar las bolsitas',
      'Endulzar y servir muy caliente con un poco de fruta en la taza',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/calientito.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chocolate cusqueño',
    descripcion: 'Chocolate caliente espeso de tableta de cacao con canela y clavo.',
    ingredientes: [
      '300 g de tableta de chocolate de Cusco',
      '1.5 litros de leche',
      '2 palitos de canela',
      '6 clavos de olor',
      '1/2 taza de azúcar',
      '1 pizca de sal',
    ],
    preparacion: [
      'Calentar la leche con la canela y el clavo a fuego bajo',
      'Dejar que infusione 10 minutos sin llegar a hervir',
      'Rallar o picar la tableta de chocolate en trozos pequeños',
      'Agregarlo a la leche caliente removiendo constantemente',
      'Batir con molinillo o batidor para que quede espumoso',
      'Cocinar a fuego bajo hasta que espese, sin dejar de remover',
      'Endulzar al gusto y servir muy caliente con pan',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chocolate_cusqueno.jpg',
    bebida: null,
    acompanamiento: 'Panetón',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Submarino',
    descripcion: 'Leche caliente con una barra de chocolate que se derrite en la taza.',
    ingredientes: [
      '1 litro de leche entera',
      '4 barras de chocolate',
      '2 cucharadas de azúcar',
      '1 palito de canela',
      '1 cucharadita de vainilla',
      '1 pizca de sal',
    ],
    preparacion: [
      'Calentar la leche con la canela a fuego medio',
      'No dejar que hierva para que no se forme nata en la superficie',
      'Agregar el azúcar y la vainilla, y remover',
      'Retirar la canela y servir la leche muy caliente en la taza',
      'Introducir la barra de chocolate entera en la taza',
      'Dejar que se derrita lentamente por acción del calor',
      'Remover con la cuchara antes de tomar',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/submarino.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Leche con canela',
    descripcion: 'Leche caliente infusionada con canela y un toque de vainilla.',
    ingredientes: [
      '1 litro de leche',
      '3 palitos de canela',
      '1/3 taza de azúcar',
      '1 cucharadita de vainilla',
      '4 clavos de olor',
      '1 pizca de nuez moscada',
    ],
    preparacion: [
      'Colocar la leche en una olla con la canela y el clavo',
      'Calentar a fuego bajo sin dejar que llegue a hervir',
      'Dejar que infusione durante 10 minutos removiendo de vez en cuando',
      'Retirar la canela y el clavo',
      'Agregar el azúcar y la vainilla',
      'Remover hasta disolver por completo',
      'Servir muy caliente espolvoreada con canela molida',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/leche_con_canela.jpg',
    bebida: null,
    acompanamiento: 'Pan con mantequilla',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Café bombón',
    descripcion: 'Espresso servido sobre leche condensada en capas.',
    ingredientes: [
      '2 cucharadas de café molido fino',
      '1/2 taza de agua',
      '4 cucharadas de leche condensada',
      '1 pizca de canela',
      '1 pizca de cacao',
      'Hielo opcional',
    ],
    preparacion: [
      'Colocar la leche condensada en el fondo de un vaso pequeño de vidrio',
      'Preparar un espresso bien cargado',
      'Verter el café muy lentamente sobre el dorso de una cuchara',
      'La cuchara evita que el café se mezcle y permite ver las dos capas',
      'Dejar que se formen las capas visibles antes de servir',
      'Espolvorear una pizca de canela o cacao',
      'Servir con cucharita para que cada quien lo mezcle',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cafe_bombon.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Horchata de arroz',
    descripcion: 'Bebida refrescante de arroz molido con canela y leche.',
    ingredientes: [
      '1 taza de arroz',
      '1.5 litros de agua',
      '2 tazas de leche',
      '1 taza de azúcar',
      '2 palitos de canela',
      '1 cucharadita de vainilla',
    ],
    preparacion: [
      'Remojar el arroz con la canela en agua durante toda la noche',
      'El remojo largo es lo que da cuerpo y sabor a la horchata',
      'Licuar el arroz con su agua de remojo hasta que quede muy fino',
      'Colar con un paño fino exprimiendo bien el bagazo',
      'Agregar la leche y el azúcar removiendo hasta disolver',
      'Añadir la vainilla y ajustar el dulzor',
      'Refrigerar y servir muy helada con canela espolvoreada',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/horchata_de_arroz.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Quinua con piña',
    descripcion: 'Refresco de quinua cocida con piña y canela, servido tibio o frío.',
    ingredientes: [
      '1 taza de quinua',
      '1 piña',
      '2.5 litros de agua',
      '1 taza de azúcar',
      '2 palitos de canela',
      '4 clavos de olor',
    ],
    preparacion: [
      'Lavar la quinua frotándola hasta que el agua salga limpia',
      'Hervirla en agua con la canela, el clavo y la cáscara de piña',
      'Cocinar 30 minutos hasta que el grano reviente por completo',
      'Retirar la cáscara de piña y licuar la quinua con su agua',
      'Colar la mezcla con un colador fino',
      'Agregar la pulpa de piña licuada y colada',
      'Endulzar al gusto y servir tibia en la mañana o helada al mediodía',
    ],
    tiempo_minutos: 55,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/quinua_con_pina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Maca con algarrobina',
    descripcion: 'Bebida energética de maca con leche y algarrobina.',
    ingredientes: [
      '3 cucharadas de harina de maca',
      '1 litro de leche',
      '3 cucharadas de algarrobina',
      '1/3 taza de azúcar',
      '1 palito de canela',
      '1 cucharadita de vainilla',
    ],
    preparacion: [
      'Disolver la harina de maca en un poco de leche fría',
      'Remover bien para que no queden grumos',
      'Calentar el resto de la leche con la canela',
      'Verter la maca disuelta removiendo constantemente',
      'Cocinar a fuego bajo 10 minutos para que la maca se cocine bien',
      'Agregar la algarrobina y el azúcar, removiendo hasta integrar',
      'Añadir la vainilla y servir caliente en el desayuno',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/maca_con_algarrobina.jpg',
    bebida: null,
    acompanamiento: 'Pan con queso',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chicha de manzana',
    descripcion: 'Refresco de manzana hervida con canela, clavo y cáscara de piña.',
    ingredientes: [
      '8 manzanas',
      '3 litros de agua',
      '2 palitos de canela',
      '8 clavos de olor',
      '1 taza de azúcar',
      '3 limones',
    ],
    preparacion: [
      'Lavar las manzanas y cortarlas en trozos con cáscara y corazón',
      'La cáscara y las pepas aportan sabor y color a la bebida',
      'Colocarlas en una olla con el agua, la canela y el clavo',
      'Hervir 40 minutos a fuego medio',
      'Aplastar las manzanas dentro de la olla y colar el líquido',
      'Endulzar mientras está caliente y dejar enfriar',
      'Agregar jugo de limón y servir bien helada',
    ],
    tiempo_minutos: 55,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chicha_de_manzana.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de hierbabuena con limón',
    descripcion: 'Bebida fría de hierbabuena infusionada con limón y miel.',
    ingredientes: [
      '2 atados de hierbabuena',
      '2 litros de agua',
      '6 limones',
      'Miel al gusto',
      'Hielo al gusto',
      '1 pepino en rodajas',
    ],
    preparacion: [
      'Lavar bien la hierbabuena y separar las hojas de los tallos',
      'Hervir el agua y retirarla del fuego',
      'Agregar las hojas y dejar infusionar 10 minutos tapado',
      'Colar el líquido y dejarlo enfriar por completo',
      'Agregar el jugo de limón recién exprimido',
      'Endulzar con miel al gusto',
      'Servir muy helada con rodajas de pepino y hojas frescas',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_hierbabuena_con_limon.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Agua de coco natural',
    descripcion: 'Agua de coco fresca servida con hielo y limón.',
    ingredientes: [
      '3 cocos verdes',
      '2 limones',
      'Hielo al gusto',
      'Miel al gusto',
      'Hojas de hierbabuena',
      '1 pizca de sal',
    ],
    preparacion: [
      'Elegir cocos verdes, que son los que tienen más agua',
      'Abrir la parte superior con un cuchillo pesado y con cuidado',
      'Verter el agua a través de un colador para retirar fibras',
      'Raspar la pulpa tierna del interior con una cuchara',
      'Mezclar el agua con la pulpa raspada',
      'Agregar unas gotas de limón y una pizca de sal para realzar el sabor',
      'Servir muy helada con hielo y hierbabuena',
    ],
    tiempo_minutos: 20,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/agua_de_coco_natural.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Bebida de aloe vera con miel',
    descripcion: 'Bebida de cristal de sábila con limón y miel.',
    ingredientes: [
      '2 pencas de aloe vera',
      '1.5 litros de agua',
      '4 limones',
      '4 cucharadas de miel',
      'Hielo al gusto',
      '1 ramita de hierbabuena',
    ],
    preparacion: [
      'Cortar las pencas y dejarlas paradas 20 minutos para que escurra el acíbar',
      'El acíbar es el líquido amarillo amargo que debe eliminarse',
      'Pelar la penca y extraer el cristal transparente del interior',
      'Enjuagar el cristal varias veces bajo el chorro de agua',
      'Licuarlo con el agua durante pocos segundos',
      'Agregar el jugo de limón y la miel',
      'Servir muy helada, consumiendo con moderación',
    ],
    tiempo_minutos: 35,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/bebida_de_aloe_vera_con_miel.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Té de frutas',
    descripcion: 'Infusión fría de té con trozos de fruta fresca y hierbabuena.',
    ingredientes: [
      '4 bolsitas de té negro',
      '2 litros de agua',
      '1 taza de fresas',
      '1 naranja en rodajas',
      '1 durazno en cubos',
      'Miel al gusto',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Hervir el agua y retirarla del fuego',
      'Colocar las bolsitas de té y dejar infusionar 4 minutos',
      'Retirar las bolsitas sin exprimirlas para que no amargue',
      'Dejar enfriar el té por completo',
      'Agregar la fruta cortada en trozos y las hojas de hierbabuena',
      'Refrigerar al menos tres horas para que la fruta infusione',
      'Servir con hielo y un poco de la fruta en cada vaso',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/te_de_frutas.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Crema de café casera',
    descripcion: 'Bebida fría y cremosa de café con leche condensada y hielo.',
    ingredientes: [
      '1 taza de café cargado frío',
      '1 lata de leche condensada',
      '1 taza de leche evaporada',
      '3 tazas de hielo',
      '1 cucharadita de vainilla',
      '1 pizca de canela',
    ],
    preparacion: [
      'Preparar un café bien cargado y dejarlo enfriar por completo',
      'Refrigerarlo al menos una hora',
      'Colocar el café frío en la licuadora con la leche condensada',
      'Agregar la leche evaporada y la vainilla',
      'Licuar hasta integrar todo',
      'Añadir el hielo y licuar a velocidad alta hasta que quede cremoso',
      'Servir de inmediato en vaso alto con canela espolvoreada',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/crema_de_cafe_casera.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Pisco Sour',
    descripcion: 'Cóctel bandera del Perú: pisco, limón, jarabe, clara y amargo.',
    ingredientes: [
      '3 onzas de pisco quebranta',
      '1 onza de jugo de limón',
      '1 onza de jarabe de goma',
      '1 clara de huevo',
      '1 taza de hielo',
      'Amargo de angostura',
    ],
    preparacion: [
      'Preparar el jarabe de goma hirviendo partes iguales de azúcar y agua, y enfriarlo',
      'Exprimir los limones al momento, sin apretar la cáscara',
      'Colocar el pisco, el limón, el jarabe y la clara en la licuadora',
      'Licuar unos segundos sin hielo para que la clara espume bien',
      'Agregar el hielo y licuar 10 segundos más, sin triturarlo del todo',
      'Servir en copa dejando que se forme la capa de espuma',
      'Terminar con tres gotas de amargo de angostura sobre la espuma',
    ],
    tiempo_minutos: 15,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pisco_sour.jpg',
    bebida: null,
    acompanamiento: 'Piqueos criollos',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chilcano de Pisco',
    descripcion: 'Trago largo y refrescante de pisco con ginger ale y limón.',
    ingredientes: [
      '2 onzas de pisco quebranta',
      '1/2 onza de jugo de limón',
      'Ginger ale al gusto',
      'Hielo en cubos',
      '2 gotas de amargo de angostura',
      '1 rodaja de limón',
    ],
    preparacion: [
      'Llenar un vaso alto con abundante hielo en cubos',
      'Usar hielo en cubos grandes, que se derriten más lento',
      'Verter el pisco sobre el hielo',
      'Agregar el jugo de limón recién exprimido',
      'Completar con ginger ale bien frío vertido lentamente',
      'Agregar dos gotas de amargo de angostura',
      'Remover suavemente y decorar con una rodaja de limón',
    ],
    tiempo_minutos: 5,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chilcano_de_pisco.jpg',
    bebida: null,
    acompanamiento: 'Piqueos criollos',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Algarrobina',
    descripcion: 'Cóctel dulce y cremoso de pisco con leche condensada y algarrobina.',
    ingredientes: [
      '2 onzas de pisco',
      '3 cucharadas de algarrobina',
      '1/2 taza de leche evaporada',
      '3 cucharadas de leche condensada',
      '1 yema de huevo',
      '1 taza de hielo',
      'Canela en polvo',
    ],
    preparacion: [
      'Colocar el pisco, la algarrobina y las leches en la licuadora',
      'Agregar la yema de huevo, que aporta cremosidad y color',
      'Licuar durante 30 segundos hasta que quede homogéneo',
      'Agregar el hielo y licuar de nuevo hasta que espese',
      'Probar y ajustar el dulzor con más leche condensada si hace falta',
      'Servir en copa ancha',
      'Espolvorear canela en polvo sobre la superficie',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/algarrobina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Machu Picchu',
    descripcion: 'Cóctel peruano de tres capas de colores con pisco y granadina.',
    ingredientes: [
      '2 onzas de pisco',
      '2 onzas de jugo de naranja',
      '1 onza de granadina',
      '1 onza de crema de menta',
      '1 taza de hielo',
      '1 cucharada de azúcar',
    ],
    preparacion: [
      'Colocar la granadina en el fondo de una copa alta',
      'Licuar el pisco con el jugo de naranja, azúcar y hielo',
      'Verter esa mezcla lentamente sobre el dorso de una cuchara',
      'La cuchara evita que se mezcle con la granadina del fondo',
      'Dejar que se asiente formando la segunda capa anaranjada',
      'Agregar la crema de menta por encima con la misma técnica',
      'Servir de inmediato sin remover, para que se vean las tres capas',
    ],
    tiempo_minutos: 15,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/machu_picchu.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Capitán',
    descripcion: 'Cóctel clásico peruano de pisco con vermut rojo.',
    ingredientes: [
      '2 onzas de pisco quebranta',
      '1 onza de vermut rojo',
      'Hielo en cubos',
      '1 cereza al marrasquino',
      '1 cáscara de limón',
      '2 gotas de amargo de angostura',
    ],
    preparacion: [
      'Enfriar previamente la copa coctelera en el congelador',
      'Llenar un vaso mezclador con hielo en cubos',
      'Verter el pisco y el vermut rojo sobre el hielo',
      'Remover con cuchara larga durante 20 segundos',
      'Este cóctel se remueve, nunca se agita, para mantenerlo cristalino',
      'Colar en la copa fría usando un colador de gusanillo',
      'Decorar con una cereza y la cáscara de limón',
    ],
    tiempo_minutos: 8,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/capitan.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Perú Libre',
    descripcion: 'Trago largo de pisco con cola y limón, versión peruana del cuba libre.',
    ingredientes: [
      '2 onzas de pisco',
      'Gaseosa de cola al gusto',
      '1/2 onza de jugo de limón',
      'Hielo en cubos',
      '1 rodaja de limón',
      '1 pizca de azúcar',
    ],
    preparacion: [
      'Llenar un vaso alto con abundante hielo en cubos',
      'Verter el pisco sobre el hielo',
      'Agregar el jugo de limón recién exprimido',
      'Completar con gaseosa de cola bien fría vertida lentamente',
      'Verter despacio para conservar el gas de la bebida',
      'Remover una sola vez con cuchara larga',
      'Decorar con una rodaja de limón y servir de inmediato',
    ],
    tiempo_minutos: 5,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/peru_libre.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Sangría peruana',
    descripcion: 'Vino tinto macerado con frutas, pisco y gaseosa.',
    ingredientes: [
      '1 botella de vino tinto',
      '1/2 taza de pisco',
      '2 manzanas en cubos',
      '2 naranjas en rodajas',
      '1 taza de gaseosa de limón',
      '1/2 taza de azúcar',
      '1 palito de canela',
    ],
    preparacion: [
      'Cortar las frutas en cubos y rodajas',
      'Colocarlas en una jarra grande con el azúcar y la canela',
      'Verter el vino tinto y el pisco sobre la fruta',
      'Remover y refrigerar al menos cuatro horas',
      'La maceración larga es lo que da sabor a la sangría',
      'Agregar la gaseosa de limón justo antes de servir',
      'Servir muy fría con hielo y un poco de fruta en cada vaso',
    ],
    tiempo_minutos: 270,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/sangria_peruana.jpg',
    bebida: null,
    acompanamiento: 'Piqueos',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Pisco Punch',
    descripcion: 'Cóctel histórico de pisco con piña macerada y limón.',
    ingredientes: [
      '2 onzas de pisco',
      '1 taza de piña en cubos',
      '1 onza de jugo de limón',
      '1 onza de jarabe de goma',
      'Hielo en cubos',
      '1 rodaja de piña',
    ],
    preparacion: [
      'Cortar la piña en cubos y macerarla en jarabe de goma por dos horas',
      'Reservar el jarabe que la piña ha perfumado',
      'Colocar el pisco, el jugo de limón y el jarabe de piña en la coctelera',
      'Agregar unos cubos de piña macerada',
      'Llenar con hielo y agitar con fuerza durante 15 segundos',
      'Colar en un vaso con hielo fresco',
      'Decorar con una rodaja de piña',
    ],
    tiempo_minutos: 140,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/pisco_punch.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Licor de guinda',
    descripcion: 'Macerado casero de guindas en pisco con azúcar y canela.',
    ingredientes: [
      '1 kg de guindas',
      '1 litro de pisco',
      '500 g de azúcar',
      '2 palitos de canela',
      '6 clavos de olor',
      '1 cáscara de naranja',
    ],
    preparacion: [
      'Lavar las guindas y retirarles los tallos sin quitarles la pepa',
      'Pincharlas una por una con un tenedor para que suelten su jugo',
      'Colocarlas en un frasco de vidrio con el azúcar y las especias',
      'Verter el pisco hasta cubrir por completo la fruta',
      'Tapar herméticamente y guardar en lugar oscuro y fresco',
      'Agitar el frasco una vez por semana durante dos meses',
      'Colar y embotellar, sirviendo en copa pequeña',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/licor_de_guinda.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
];
