// Bebidas — parte 5. Mates, infusiones medicinales, tés y cafés.

export const parte = [
  {
    categoria_slug: 'bebidas',
    nombre: 'Mate de coca',
    descripcion: 'Infusión andina de hojas de coca, tradicional contra el soroche.',
    ingredientes: [
      '1 puñado de hojas de coca',
      '1 litro de agua',
      'Azúcar o miel al gusto',
      '1 rodaja de limón',
      '1 palito de canela',
      'Hojas de muña opcional',
    ],
    preparacion: [
      'Hervir el agua y retirarla del fuego',
      'Esperar un momento para que baje de los 100 grados',
      'Colocar las hojas de coca en una tetera o taza',
      'Verter el agua caliente sobre las hojas',
      'Tapar y dejar infusionar entre 5 y 8 minutos',
      'No hervir las hojas directamente, porque el sabor se vuelve amargo',
      'Colar, endulzar al gusto y servir caliente',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/mate_de_coca.jpg',
    bebida: null,
    acompanamiento: 'Pan chuta',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Mate de muña',
    descripcion: 'Infusión de muña, la menta andina, digestiva y aromática.',
    ingredientes: [
      '1 puñado de muña fresca',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 palito de canela',
      'Hojas de hierbabuena opcional',
    ],
    preparacion: [
      'Lavar las ramitas de muña con agua fría',
      'Hervir el agua y retirarla del fuego',
      'Colocar la muña en una tetera',
      'Verter el agua caliente sobre las hojas',
      'Tapar y dejar infusionar 6 minutos para que suelte su aroma',
      'Colar y endulzar con miel',
      'Servir caliente, especialmente después de comidas pesadas',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/mate_de_muna.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Mate de anís',
    descripcion: 'Infusión dulce y aromática de anís en grano.',
    ingredientes: [
      '2 cucharadas de anís en grano',
      '1 litro de agua',
      'Azúcar al gusto',
      '1 palito de canela',
      '1 rodaja de limón',
      'Miel opcional',
    ],
    preparacion: [
      'Colocar el anís en grano en una olla con el agua',
      'Llevar a hervor suave durante 5 minutos',
      'Apagar el fuego y dejar reposar tapado 10 minutos',
      'El reposo tapado concentra el aroma del anís',
      'Colar el líquido con un colador fino',
      'Endulzar al gusto con azúcar o miel',
      'Servir caliente en taza',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/mate_de_anis.jpg',
    bebida: null,
    acompanamiento: 'Pan con mantequilla',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Manzanilla',
    descripcion: 'Infusión de flores de manzanilla, calmante y digestiva.',
    ingredientes: [
      '2 cucharadas de flores de manzanilla',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 ramita de hierbabuena',
      '1 palito de canela',
    ],
    preparacion: [
      'Hervir el agua y retirarla del fuego',
      'Colocar las flores de manzanilla en una tetera',
      'Verter el agua caliente sobre las flores',
      'Tapar de inmediato para que no se escapen los aceites esenciales',
      'Dejar infusionar 5 minutos, ni más ni menos',
      'Una infusión demasiado larga vuelve amarga la manzanilla',
      'Colar, endulzar con miel y servir caliente',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/manzanilla.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Hierba luisa',
    descripcion: 'Infusión cítrica y relajante de hojas de hierba luisa.',
    ingredientes: [
      '1 puñado de hojas de hierba luisa',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 ramita de cedrón',
      'Azúcar opcional',
    ],
    preparacion: [
      'Lavar las hojas de hierba luisa y cortarlas en trozos',
      'El corte libera más aroma que la hoja entera',
      'Hervir el agua y retirarla del fuego',
      'Colocar las hojas en una tetera y verter el agua caliente',
      'Tapar y dejar infusionar 7 minutos',
      'Colar el líquido',
      'Endulzar con miel y servir caliente',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/hierba_luisa.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de cedrón',
    descripcion: 'Mate suave de cedrón, tradicional para la digestión.',
    ingredientes: [
      '1 puñado de hojas de cedrón',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 palito de canela',
      'Hojas de hierbabuena opcional',
    ],
    preparacion: [
      'Lavar las hojas de cedrón con agua fría',
      'Hervir el agua y retirarla del fuego',
      'Colocar las hojas en una tetera',
      'Verter el agua caliente y tapar de inmediato',
      'Dejar infusionar 6 minutos',
      'Colar el líquido descartando las hojas',
      'Endulzar con miel y servir caliente después de las comidas',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_cedron.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de toronjil',
    descripcion: 'Mate de toronjil, usado tradicionalmente para calmar los nervios.',
    ingredientes: [
      '1 puñado de hojas de toronjil',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 ramita de manzanilla',
      'Azúcar opcional',
    ],
    preparacion: [
      'Lavar las hojas de toronjil con cuidado',
      'Hervir el agua y retirarla del fuego',
      'Colocar las hojas en la tetera',
      'Verter el agua caliente sobre las hojas',
      'Tapar y dejar infusionar 6 minutos',
      'Colar el líquido',
      'Endulzar con miel y servir caliente, preferentemente en la noche',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_toronjil.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de menta',
    descripcion: 'Mate fresco de hojas de menta, digestivo y aromático.',
    ingredientes: [
      '1 puñado de hojas de menta',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 trozo pequeño de kion',
      'Azúcar opcional',
    ],
    preparacion: [
      'Lavar las hojas de menta y machacarlas ligeramente con la mano',
      'El machacado suave libera los aceites esenciales',
      'Hervir el agua y retirarla del fuego',
      'Colocar las hojas en la tetera y verter el agua caliente',
      'Tapar y dejar infusionar 5 minutos',
      'Colar el líquido',
      'Endulzar con miel y servir caliente o fría con hielo',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_menta.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de boldo',
    descripcion: 'Mate amargo de boldo, tradicional para el hígado.',
    ingredientes: [
      '1 cucharada de hojas de boldo',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 ramita de hierbabuena',
      '1 palito de canela',
    ],
    preparacion: [
      'Hervir el agua y retirarla del fuego',
      'Colocar las hojas de boldo en la tetera',
      'Usar poca cantidad, porque el boldo es muy concentrado',
      'Verter el agua caliente y tapar',
      'Dejar infusionar solo 4 minutos para que no amargue en exceso',
      'Colar de inmediato',
      'Endulzar con miel y servir caliente',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_boldo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de eucalipto',
    descripcion: 'Mate de hojas de eucalipto, usado para las vías respiratorias.',
    ingredientes: [
      '6 hojas de eucalipto',
      '1 litro de agua',
      'Miel al gusto',
      '2 limones',
      '1 trozo de kion',
      '1 palito de canela',
    ],
    preparacion: [
      'Lavar las hojas de eucalipto y romperlas con las manos',
      'Colocarlas en una olla con el agua',
      'Llevar a hervor y cocinar 8 minutos a fuego bajo',
      'Agregar el kion en rodajas y la canela',
      'Apagar el fuego y dejar reposar tapado 10 minutos',
      'Colar el líquido descartando las hojas',
      'Endulzar con miel, agregar limón y servir muy caliente',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_eucalipto.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Té de canela y clavo',
    descripcion: 'Infusión caliente y especiada de canela con clavo de olor.',
    ingredientes: [
      '3 palitos de canela',
      '8 clavos de olor',
      '1 litro de agua',
      'Azúcar al gusto',
      '1 rodaja de naranja',
      '1 estrella de anís',
    ],
    preparacion: [
      'Colocar la canela y el clavo en una olla con el agua fría',
      'Llevar a hervor lentamente para que las especias suelten su aroma',
      'Cocinar a fuego bajo durante 10 minutos',
      'Agregar la cáscara de naranja y el anís estrella',
      'Apagar el fuego y dejar reposar tapado 10 minutos más',
      'Colar el líquido',
      'Endulzar al gusto y servir bien caliente',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/te_de_canela_y_clavo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de tilo',
    descripcion: 'Mate de flores de tilo, relajante y suave.',
    ingredientes: [
      '2 cucharadas de flores de tilo',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 ramita de manzanilla',
      'Azúcar opcional',
    ],
    preparacion: [
      'Hervir el agua y retirarla del fuego',
      'Colocar las flores de tilo en la tetera',
      'Verter el agua caliente sobre las flores',
      'Tapar de inmediato para retener los aromas',
      'Dejar infusionar 6 minutos',
      'Colar el líquido descartando las flores',
      'Endulzar con miel y servir caliente antes de dormir',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_tilo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de valeriana',
    descripcion: 'Mate de raíz de valeriana, tradicionalmente usado para el descanso.',
    ingredientes: [
      '1 cucharadita de raíz de valeriana',
      '1 litro de agua',
      'Miel al gusto',
      '1 ramita de toronjil',
      '1 rodaja de limón',
      '1 palito de canela',
    ],
    preparacion: [
      'Colocar la raíz de valeriana en una olla con el agua',
      'Llevar a hervor suave durante 5 minutos',
      'Agregar el toronjil y apagar el fuego',
      'Dejar reposar tapado 10 minutos',
      'Colar el líquido con un colador fino',
      'Endulzar con miel, que suaviza su sabor terroso',
      'Servir caliente en la noche, una taza a la vez',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_valeriana.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de paico',
    descripcion: 'Mate andino de paico, usado tradicionalmente para el estómago.',
    ingredientes: [
      '1 puñado de hojas de paico',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 ramita de hierbabuena',
      'Azúcar opcional',
    ],
    preparacion: [
      'Lavar bien las hojas de paico con agua fría',
      'Hervir el agua y retirarla del fuego',
      'Colocar las hojas en la tetera',
      'Verter el agua caliente sobre el paico',
      'Tapar y dejar infusionar 5 minutos',
      'Usar poca cantidad porque el paico tiene sabor muy fuerte',
      'Colar, endulzar y servir caliente',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_paico.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de llantén',
    descripcion: 'Mate de hojas de llantén, usado para la garganta.',
    ingredientes: [
      '1 puñado de hojas de llantén',
      '1 litro de agua',
      'Miel al gusto',
      '2 limones',
      '1 trozo de kion',
      '1 palito de canela',
    ],
    preparacion: [
      'Lavar bien las hojas de llantén, que suelen crecer a ras del suelo',
      'Hervir el agua con el kion en rodajas',
      'Retirar del fuego y agregar las hojas de llantén',
      'Tapar y dejar infusionar 8 minutos',
      'Colar el líquido descartando las hojas',
      'Agregar el jugo de limón cuando ya no esté hirviendo',
      'Endulzar con miel y servir caliente',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_llanten.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de hercampuri',
    descripcion: 'Mate amargo andino de hercampuri.',
    ingredientes: [
      '1 cucharadita de hercampuri',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 ramita de hierbabuena',
      '1 palito de canela',
    ],
    preparacion: [
      'Colocar el hercampuri en una olla con el agua',
      'Llevar a hervor suave durante 5 minutos',
      'Usar poca cantidad porque es una planta muy amarga',
      'Apagar el fuego y dejar reposar tapado 5 minutos',
      'Colar el líquido con un colador fino',
      'Endulzar con miel para suavizar el amargor',
      'Servir caliente, tradicionalmente en ayunas',
    ],
    tiempo_minutos: 18,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_hercampuri.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de chanca piedra',
    descripcion: 'Mate de chanca piedra, planta amazónica muy usada en Perú.',
    ingredientes: [
      '1 puñado de chanca piedra',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 trozo de kion',
      '1 palito de canela',
    ],
    preparacion: [
      'Lavar bien la planta de chanca piedra',
      'Colocarla en una olla con el agua fría',
      'Llevar a hervor y cocinar 10 minutos a fuego bajo',
      'Apagar el fuego y dejar reposar tapado 10 minutos',
      'Colar el líquido descartando los tallos',
      'Endulzar con miel al gusto',
      'Servir caliente o a temperatura ambiente a lo largo del día',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_chanca_piedra.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de uña de gato',
    descripcion: 'Mate amazónico de corteza de uña de gato.',
    ingredientes: [
      '2 cucharadas de corteza de uña de gato',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 palito de canela',
      '1 trozo de kion',
    ],
    preparacion: [
      'Colocar la corteza de uña de gato en una olla con el agua fría',
      'Llevar a hervor lentamente',
      'Cocinar a fuego bajo durante 15 minutos, porque la corteza es dura',
      'Agregar la canela y el kion en los últimos minutos',
      'Apagar el fuego y dejar reposar tapado',
      'Colar el líquido con un colador fino',
      'Endulzar con miel y servir caliente',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_una_de_gato.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Té negro con leche',
    descripcion: 'Té negro cargado servido con leche caliente y azúcar.',
    ingredientes: [
      '4 bolsitas de té negro',
      '1/2 litro de agua',
      '1/2 litro de leche',
      'Azúcar al gusto',
      '1 palito de canela',
      '4 clavos de olor',
    ],
    preparacion: [
      'Hervir el agua y retirarla del fuego',
      'Colocar las bolsitas de té y dejar infusionar 4 minutos',
      'No dejar el té más tiempo, porque libera taninos amargos',
      'Retirar las bolsitas sin exprimirlas',
      'Calentar la leche aparte con la canela y el clavo sin dejar que hierva',
      'Mezclar el té con la leche caliente',
      'Endulzar al gusto y servir bien caliente',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/te_negro_con_leche.jpg',
    bebida: null,
    acompanamiento: 'Pan con mantequilla',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Té verde con limón',
    descripcion: 'Infusión de té verde con limón y miel, ligera y antioxidante.',
    ingredientes: [
      '4 bolsitas de té verde',
      '1 litro de agua',
      '2 limones',
      'Miel al gusto',
      '1 ramita de hierbabuena',
      '1 trozo pequeño de kion',
    ],
    preparacion: [
      'Hervir el agua y dejarla reposar dos minutos fuera del fuego',
      'El té verde se amarga si se prepara con agua hirviendo',
      'Colocar las bolsitas en la tetera y verter el agua a unos 80 grados',
      'Dejar infusionar solo 3 minutos',
      'Retirar las bolsitas de inmediato',
      'Agregar el jugo de limón y la miel cuando esté tibio',
      'Servir caliente o con hielo y hierbabuena',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/te_verde_con_limon.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Té piteado',
    descripcion: 'Té negro caliente con un chorro de pisco, típico de noches frías.',
    ingredientes: [
      '4 bolsitas de té negro',
      '1 litro de agua',
      '1/2 taza de pisco',
      'Azúcar al gusto',
      '2 limones',
      '1 palito de canela',
    ],
    preparacion: [
      'Hervir el agua con la canela',
      'Retirar del fuego y colocar las bolsitas de té',
      'Dejar infusionar 4 minutos y retirar las bolsitas',
      'Endulzar el té caliente al gusto',
      'Servir en taza y agregar el pisco al final',
      'Agregar el alcohol fuera del fuego para que no se evapore',
      'Terminar con unas gotas de limón y servir de inmediato',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/te_piteado.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Café americano',
    descripcion: 'Café filtrado suave, servido negro y caliente.',
    ingredientes: [
      '60 g de café molido',
      '1 litro de agua',
      'Azúcar al gusto',
      'Leche opcional',
      '1 pizca de canela',
      '1 pizca de sal',
    ],
    preparacion: [
      'Moler el café en grano justo antes de preparar, si es posible',
      'Calentar el agua hasta unos 92 grados, sin dejar que hierva',
      'El agua hirviendo quema el café y lo vuelve amargo',
      'Colocar el café molido en el filtro',
      'Verter el agua en círculos, lentamente, en dos o tres tandas',
      'Dejar que filtre por completo sin presionar',
      'Servir caliente, con azúcar o leche si se desea',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cafe_americano.jpg',
    bebida: null,
    acompanamiento: 'Pan con mantequilla',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Café cortado',
    descripcion: 'Café espresso cortado con un poco de leche caliente.',
    ingredientes: [
      '2 cucharadas de café molido fino',
      '1/2 taza de agua',
      '1/2 taza de leche',
      'Azúcar al gusto',
      '1 pizca de canela',
      '1 pizca de cacao',
    ],
    preparacion: [
      'Preparar un espresso cargado con el café molido fino',
      'Calentar la leche sin dejar que hierva',
      'La leche hervida pierde dulzor natural y toma sabor a cocido',
      'Verter el espresso en una taza pequeña',
      'Agregar solo un chorro de leche caliente, sin llenar la taza',
      'Endulzar al gusto',
      'Espolvorear una pizca de canela o cacao y servir',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cafe_cortado.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Capuchino casero',
    descripcion: 'Café con leche espumada y cacao espolvoreado encima.',
    ingredientes: [
      '2 cucharadas de café molido',
      '1/2 taza de agua',
      '1 taza de leche entera',
      'Azúcar al gusto',
      '1 cucharadita de cacao en polvo',
      '1 pizca de canela',
    ],
    preparacion: [
      'Preparar un café cargado y reservarlo caliente',
      'Calentar la leche entera hasta unos 65 grados',
      'Batir la leche con un batidor manual o espumador hasta que doble su volumen',
      'La leche entera espuma mejor que la descremada',
      'Verter el café en la taza',
      'Agregar la leche espumada por encima sosteniendo la espuma con una cuchara',
      'Espolvorear cacao y canela, y servir de inmediato',
    ],
    tiempo_minutos: 15,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/capuchino_casero.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Café con algarrobina',
    descripcion: 'Café con leche endulzado con algarrobina en lugar de azúcar.',
    ingredientes: [
      '3 cucharadas de café molido',
      '1/2 taza de agua',
      '2 tazas de leche',
      '3 cucharadas de algarrobina',
      '1 pizca de canela',
      '1 cucharadita de vainilla',
    ],
    preparacion: [
      'Preparar un café cargado con el café molido',
      'Calentar la leche con la canela sin dejar que hierva',
      'Disolver la algarrobina en un poco de leche caliente',
      'Remover bien hasta que no queden grumos oscuros',
      'Mezclar la leche con algarrobina y el café',
      'Agregar la vainilla y probar el dulzor',
      'Servir caliente espolvoreado con canela',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cafe_con_algarrobina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Café helado',
    descripcion: 'Café frío batido con hielo, leche y un toque de vainilla.',
    ingredientes: [
      '1 taza de café cargado frío',
      '1 taza de leche',
      '3 tazas de hielo',
      '3 cucharadas de azúcar',
      '1 cucharadita de vainilla',
      '1 pizca de canela',
    ],
    preparacion: [
      'Preparar el café cargado y dejarlo enfriar por completo',
      'Refrigerarlo al menos una hora antes de usarlo',
      'Usar café ya frío evita que el hielo se derrita y aguade la bebida',
      'Colocar el café, la leche, el azúcar y la vainilla en la licuadora',
      'Agregar el hielo y licuar a velocidad alta',
      'Buscar una textura espumosa y bien fría',
      'Servir de inmediato en vaso alto con canela espolvoreada',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/cafe_helado.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Infusión de manayupa',
    descripcion: 'Mate andino de manayupa, planta depurativa tradicional.',
    ingredientes: [
      '1 puñado de manayupa',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 ramita de hierbabuena',
      '1 palito de canela',
    ],
    preparacion: [
      'Lavar bien la planta de manayupa con agua fría',
      'Colocarla en una olla con el agua',
      'Llevar a hervor y cocinar 8 minutos a fuego bajo',
      'Apagar el fuego y dejar reposar tapado 10 minutos',
      'Colar el líquido descartando los tallos y hojas',
      'Endulzar con miel al gusto',
      'Servir caliente o a temperatura ambiente durante el día',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/infusion_de_manayupa.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Agua de romero',
    descripcion: 'Infusión aromática de romero fresco con limón y miel.',
    ingredientes: [
      '4 ramitas de romero fresco',
      '1 litro de agua',
      '2 limones',
      'Miel al gusto',
      '1 trozo de kion',
      '1 palito de canela',
    ],
    preparacion: [
      'Lavar las ramitas de romero con agua fría',
      'Hervir el agua con el kion en rodajas',
      'Retirar del fuego y agregar el romero',
      'Tapar y dejar infusionar 8 minutos',
      'El romero suelta mucho aroma, no conviene pasarse del tiempo',
      'Colar el líquido y agregar el jugo de limón ya tibio',
      'Endulzar con miel y servir caliente o helada',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/agua_de_romero.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Mate de coca con muña',
    descripcion: 'Combinación andina de hoja de coca y muña, muy digestiva.',
    ingredientes: [
      '1 puñado de hojas de coca',
      '1 puñado de muña',
      '1 litro de agua',
      'Miel al gusto',
      '1 rodaja de limón',
      '1 palito de canela',
    ],
    preparacion: [
      'Hervir el agua con la canela y retirarla del fuego',
      'Esperar un minuto para que baje la temperatura',
      'Colocar las hojas de coca y la muña en la tetera',
      'Verter el agua caliente sobre las hierbas',
      'Tapar y dejar infusionar 7 minutos',
      'Colar el líquido descartando las hojas',
      'Endulzar con miel y servir muy caliente en la altura',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/mate_de_coca_con_muna.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
];
