// Bebidas — parte 2. Chichas, refrescos de grano y bebidas amazónicas.

export const parte = [
  {
    categoria_slug: 'bebidas',
    nombre: 'Chicha morada',
    descripcion: 'Refresco de maíz morado hervido con piña, membrillo y especias.',
    ingredientes: [
      '500 g de maíz morado',
      '1 piña con cáscara',
      '2 membrillos',
      '1 palito de canela',
      '6 clavos de olor',
      '6 limones',
      'Azúcar al gusto',
    ],
    preparacion: [
      'Lavar el maíz morado y colocarlo en una olla grande con 3 litros de agua',
      'Agregar la cáscara de piña, el membrillo en trozos, la canela y el clavo',
      'Hervir a fuego medio durante 45 minutos hasta que el agua tome color morado intenso',
      'Colar el líquido y desechar el maíz y las cáscaras',
      'Dejar enfriar por completo antes de endulzar',
      'Agregar el azúcar y el jugo de limón al final, cuando ya está frío',
      'Servir bien helado con cubos de piña y manzana picada',
    ],
    tiempo_minutos: 70,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chicha_morada.jpg',
    bebida: null,
    acompanamiento: 'Almuerzos criollos',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chicha de jora',
    descripcion: 'Bebida ancestral de maíz germinado fermentado, base de muchos guisos.',
    ingredientes: [
      '1 kg de jora (maíz germinado y seco)',
      '200 g de cebada',
      '5 litros de agua',
      '1 taza de chancaca',
      '1 palito de canela',
      '4 clavos de olor',
    ],
    preparacion: [
      'Tostar ligeramente la jora y la cebada en una olla seca hasta que aromaticen',
      'Hervirlas en abundante agua durante dos horas a fuego bajo',
      'Colar el líquido con un paño limpio y desechar el bagazo',
      'Agregar la chancaca derretida, la canela y el clavo',
      'Dejar enfriar por completo en un recipiente de barro o vidrio',
      'Tapar con un paño y dejar fermentar de dos a cinco días según el clima',
      'Probar a diario hasta alcanzar el punto deseado y servir en vaso o poto',
    ],
    tiempo_minutos: 180,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/chicha_de_jora.jpg',
    bebida: null,
    acompanamiento: 'Seco de cabrito',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chicha de maní',
    descripcion: 'Bebida cremosa de maní tostado con canela y leche.',
    ingredientes: [
      '2 tazas de maní tostado',
      '2 litros de leche',
      '1 taza de arroz remojado',
      '1 palito de canela',
      '1 taza de azúcar',
      '4 clavos de olor',
    ],
    preparacion: [
      'Tostar el maní en sartén y frotarlo en un paño para quitarle la piel',
      'Remojar el arroz en agua durante una hora',
      'Licuar el maní con el arroz remojado y un poco de agua hasta que quede fino',
      'Colar la mezcla con un paño fino presionando para extraer todo el líquido',
      'Llevar a fuego bajo con la leche, la canela y el clavo',
      'Cocinar removiendo constantemente para que no se corte ni se pegue',
      'Endulzar al gusto y servir caliente o bien frío',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chicha_de_mani.jpg',
    bebida: null,
    acompanamiento: 'Pan con mantequilla',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chicha blanca de trigo',
    descripcion: 'Refresco refrescante de trigo hervido con piña y canela.',
    ingredientes: [
      '2 tazas de trigo',
      '1 piña con cáscara',
      '1 palito de canela',
      '4 clavos de olor',
      '1 taza de azúcar',
      '4 limones',
    ],
    preparacion: [
      'Lavar el trigo varias veces hasta que el agua salga limpia',
      'Hervirlo en 3 litros de agua con la cáscara de piña, canela y clavo',
      'Cocinar a fuego bajo durante una hora hasta que el trigo reviente',
      'Colar el líquido con un colador fino',
      'Dejar enfriar por completo antes de endulzar',
      'Agregar azúcar y jugo de limón al gusto',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 80,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chicha_blanca_de_trigo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chicha de guiñapo',
    descripcion: 'Chicha arequipeña de maíz negro germinado, base del adobo.',
    ingredientes: [
      '1 kg de guiñapo (maíz negro germinado)',
      '5 litros de agua',
      '1 taza de chancaca',
      '1 palito de canela',
      'Clavos de olor al gusto',
      'Cáscara de piña',
    ],
    preparacion: [
      'Moler ligeramente el guiñapo para liberar sus almidones',
      'Hervirlo en abundante agua durante dos horas removiendo de vez en cuando',
      'Colar el líquido con un paño limpio, presionando el bagazo',
      'Agregar la chancaca derretida y las especias',
      'Enfriar por completo en un recipiente de barro',
      'Tapar con un paño y dejar fermentar dos o tres días en lugar fresco',
      'Colar de nuevo antes de servir en vaso alto',
    ],
    tiempo_minutos: 180,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/chicha_de_guinapo.jpg',
    bebida: null,
    acompanamiento: 'Adobo arequipeño',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chicha de siete semillas',
    descripcion: 'Bebida nutritiva hecha con siete granos tostados y molidos.',
    ingredientes: [
      '1/2 taza de cebada',
      '1/2 taza de trigo',
      '1/2 taza de quinua',
      '1/2 taza de kiwicha',
      '1/2 taza de linaza',
      '1/2 taza de maní',
      '1/2 taza de habas',
    ],
    preparacion: [
      'Tostar cada grano por separado, porque cada uno tiene un punto distinto',
      'Dejar enfriar y molerlos juntos hasta obtener una harina fina',
      'Disolver la harina en agua fría removiendo bien para evitar grumos',
      'Llevar a fuego medio removiendo constantemente hasta que hierva',
      'Cocinar 20 minutos a fuego bajo para que pierda el sabor a crudo',
      'Agregar canela, clavo y azúcar al gusto',
      'Servir caliente en taza, tradicionalmente en el desayuno',
    ],
    tiempo_minutos: 70,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/chicha_de_siete_semillas.jpg',
    bebida: null,
    acompanamiento: 'Pan francés',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de cebada',
    descripcion: 'Bebida de cebada tostada hervida con piña y limón, servida helada.',
    ingredientes: [
      '2 tazas de cebada tostada',
      '3 litros de agua',
      'Cáscara de 1 piña',
      '1 palito de canela',
      '1 taza de azúcar',
      '4 limones',
    ],
    preparacion: [
      'Tostar la cebada en una olla seca hasta que tome color dorado oscuro',
      'Cuidar que no se queme, porque amarga toda la bebida',
      'Agregar el agua, la cáscara de piña y la canela',
      'Hervir 40 minutos a fuego medio',
      'Colar el líquido y dejarlo enfriar',
      'Endulzar con azúcar y agregar jugo de limón',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 55,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_cebada.jpg',
    bebida: null,
    acompanamiento: 'Menú del día',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de linaza',
    descripcion: 'Bebida gelatinosa de linaza con limón y piña, refrescante y digestiva.',
    ingredientes: [
      '1 taza de linaza',
      '3 litros de agua',
      '1 piña',
      '6 limones',
      '1 taza de azúcar',
      '1 palito de canela',
    ],
    preparacion: [
      'Enjuagar la linaza rápidamente bajo el chorro de agua',
      'Hervirla en agua con la cáscara de piña y la canela durante 30 minutos',
      'El agua tomará una textura ligeramente gelatinosa, que es lo característico',
      'Colar el líquido presionando suavemente las semillas',
      'Dejar enfriar por completo',
      'Agregar el jugo de limón, la piña licuada y el azúcar',
      'Servir bien helado',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_linaza.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de maíz morado con piña',
    descripcion: 'Versión ligera de la chicha morada con más piña y menos azúcar.',
    ingredientes: [
      '300 g de maíz morado',
      '1 piña entera',
      '1 manzana',
      '1 palito de canela',
      '4 limones',
      'Azúcar al gusto',
    ],
    preparacion: [
      'Hervir el maíz morado con la cáscara de piña y la canela por 40 minutos',
      'Colar el líquido y reservarlo',
      'Licuar la pulpa de piña con un poco del líquido morado',
      'Colar el licuado para quitar la fibra',
      'Mezclar ambos líquidos y dejar enfriar',
      'Endulzar ligeramente y agregar jugo de limón',
      'Servir con cubos de manzana picada y hielo',
    ],
    tiempo_minutos: 55,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_maiz_morado_con_pina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Frutillada',
    descripcion: 'Bebida cusqueña de chicha de jora fermentada con fresas molidas.',
    ingredientes: [
      '2 litros de chicha de jora',
      '1 kg de fresas',
      '1 taza de azúcar',
      '1 palito de canela',
      '4 clavos de olor',
      'Hielo al gusto',
    ],
    preparacion: [
      'Lavar las fresas y molerlas en batán o licuarlas brevemente',
      'Hervir las fresas molidas con azúcar, canela y clavo por 15 minutos',
      'Dejar enfriar por completo la preparación de fresa',
      'Mezclarla con la chicha de jora ya fermentada',
      'Dejar reposar la mezcla un día para que los sabores se integren',
      'Colar antes de servir si se prefiere sin pulpa',
      'Servir en vaso grande, tradicionalmente en chicherías cusqueñas',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/frutillada.jpg',
    bebida: null,
    acompanamiento: 'Chicharrón colorado',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Api morado',
    descripcion: 'Bebida andina caliente y espesa de maíz morado con canela y clavo.',
    ingredientes: [
      '2 tazas de harina de maíz morado',
      '2 litros de agua',
      '1 taza de azúcar',
      '1 palito de canela',
      '4 clavos de olor',
      'Cáscara de naranja',
    ],
    preparacion: [
      'Disolver la harina de maíz morado en agua fría removiendo muy bien',
      'Colar la mezcla para asegurarse de que no queden grumos',
      'Llevar a fuego medio con la canela, el clavo y la cáscara de naranja',
      'Remover constantemente con cuchara de madera mientras espesa',
      'Cocinar 20 minutos para que pierda el sabor a harina cruda',
      'Endulzar con azúcar al gusto',
      'Servir bien caliente en taza, tradicionalmente con buñuelo',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/api_morado.jpg',
    bebida: null,
    acompanamiento: 'Buñuelo',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Api blanco',
    descripcion: 'Versión clara del api, hecha con maíz blanco y leche.',
    ingredientes: [
      '2 tazas de harina de maíz blanco',
      '1 litro de leche',
      '1 litro de agua',
      '1 taza de azúcar',
      '1 palito de canela',
      '1 cucharadita de vainilla',
    ],
    preparacion: [
      'Disolver la harina de maíz blanco en agua fría hasta que no queden grumos',
      'Colar la mezcla por precaución',
      'Llevar a fuego medio con la canela removiendo sin parar',
      'Cuando empiece a espesar, agregar la leche poco a poco',
      'Seguir removiendo para que la leche no se corte',
      'Cocinar 15 minutos más y endulzar al gusto',
      'Agregar la vainilla al final y servir caliente',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/api_blanco.jpg',
    bebida: null,
    acompanamiento: 'Buñuelo',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chicha de quinua',
    descripcion: 'Refresco de quinua cocida con manzana, piña y canela.',
    ingredientes: [
      '1 taza de quinua',
      '3 litros de agua',
      '2 manzanas',
      'Cáscara de 1 piña',
      '1 palito de canela',
      '1 taza de azúcar',
    ],
    preparacion: [
      'Lavar la quinua frotándola varias veces para quitar la saponina amarga',
      'Hervirla en abundante agua con la canela y la cáscara de piña',
      'Cocinar 30 minutos hasta que el grano reviente por completo',
      'Agregar la manzana en trozos y cocinar 10 minutos más',
      'Licuar todo y colar con un colador fino',
      'Endulzar al gusto y dejar enfriar',
      'Servir bien helado o tibio según la preferencia',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chicha_de_quinua.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de kiwicha',
    descripcion: 'Bebida nutritiva de kiwicha cocida con manzana y canela.',
    ingredientes: [
      '1 taza de kiwicha',
      '2.5 litros de agua',
      '2 manzanas',
      '1 palito de canela',
      '4 clavos de olor',
      '1 taza de azúcar',
    ],
    preparacion: [
      'Lavar la kiwicha con un colador muy fino porque el grano es diminuto',
      'Hervirla en agua con la canela y el clavo durante 25 minutos',
      'Agregar la manzana cortada en trozos con cáscara',
      'Cocinar 10 minutos más hasta que la manzana esté blanda',
      'Licuar todo y colar con un colador fino',
      'Endulzar al gusto mientras aún está tibia',
      'Servir caliente en la mañana o bien helada en días de calor',
    ],
    tiempo_minutos: 50,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_kiwicha.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de habas tostadas',
    descripcion: 'Bebida andina de habas tostadas molidas con canela.',
    ingredientes: [
      '2 tazas de habas secas',
      '2.5 litros de agua',
      '1 palito de canela',
      '4 clavos de olor',
      '1 taza de azúcar',
      'Cáscara de naranja',
    ],
    preparacion: [
      'Tostar las habas secas en una olla hasta que tomen color dorado',
      'Molerlas gruesamente en molino o licuadora',
      'Hervirlas en agua con la canela, el clavo y la cáscara de naranja',
      'Cocinar 40 minutos a fuego bajo removiendo de vez en cuando',
      'Colar el líquido presionando el bagazo para extraer todo el sabor',
      'Endulzar al gusto',
      'Servir caliente en taza como desayuno andino',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_habas_tostadas.jpg',
    bebida: null,
    acompanamiento: 'Pan chuta',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Emoliente con uña de gato',
    descripcion: 'Emoliente reforzado con uña de gato, cola de caballo y llantén.',
    ingredientes: [
      '1/2 taza de cebada tostada',
      '1/4 taza de linaza',
      '1 puñado de uña de gato',
      '1 puñado de cola de caballo',
      '1 puñado de llantén',
      '6 limones',
      'Azúcar rubia al gusto',
    ],
    preparacion: [
      'Tostar la cebada en olla seca hasta que dore sin quemarse',
      'Hervirla en 3 litros de agua durante 20 minutos',
      'Agregar la linaza y cocinar 15 minutos más para que suelte su mucílago',
      'Añadir la uña de gato, la cola de caballo y el llantén',
      'Apagar el fuego y dejar reposar tapado 10 minutos para que infusione',
      'Colar el líquido y endulzar con azúcar rubia',
      'Servir caliente con abundante jugo de limón exprimido al momento',
    ],
    tiempo_minutos: 50,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/emoliente_con_una_de_gato.jpg',
    bebida: null,
    acompanamiento: 'Pan con queso',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Leche de soya',
    descripcion: 'Bebida vegetal casera de soya remojada, molida y colada.',
    ingredientes: [
      '2 tazas de soya en grano',
      '2 litros de agua',
      '1 palito de canela',
      '1 taza de azúcar',
      '1 cucharadita de vainilla',
      'Sal al gusto',
    ],
    preparacion: [
      'Remojar la soya en abundante agua durante 12 horas',
      'Escurrirla y frotarla entre las manos para retirar las cáscaras',
      'Licuarla con agua limpia hasta obtener una mezcla blanca y espesa',
      'Colar con un paño fino exprimiendo bien para extraer toda la leche',
      'Hervir el líquido con la canela durante 20 minutos removiendo',
      'Es importante hervirla bien para eliminar el sabor crudo de la soya',
      'Endulzar, agregar vainilla y servir caliente o fría',
    ],
    tiempo_minutos: 60,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/leche_de_soya.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Leche de almendras',
    descripcion: 'Bebida vegetal suave de almendras remojadas y licuadas.',
    ingredientes: [
      '1 taza de almendras',
      '1 litro de agua',
      '3 dátiles o 2 cucharadas de miel',
      '1 cucharadita de vainilla',
      '1 pizca de canela',
      '1 pizca de sal',
    ],
    preparacion: [
      'Remojar las almendras en agua durante 8 horas o toda la noche',
      'Escurrirlas y enjuagarlas con agua limpia',
      'Licuarlas con el litro de agua a velocidad alta por dos minutos',
      'Colar con una bolsa de tela o paño fino exprimiendo bien',
      'Regresar la leche a la licuadora con los dátiles y la vainilla',
      'Licuar de nuevo hasta integrar y agregar una pizca de sal y canela',
      'Guardar refrigerada y consumir en tres días como máximo',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/leche_de_almendras.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Leche de ajonjolí',
    descripcion: 'Bebida cremosa de ajonjolí tostado con canela y miel.',
    ingredientes: [
      '1 taza de ajonjolí',
      '1 litro de agua',
      '3 cucharadas de miel',
      '1 palito de canela',
      '1 cucharadita de vainilla',
      '1 pizca de sal',
    ],
    preparacion: [
      'Tostar ligeramente el ajonjolí en sartén removiendo constantemente',
      'Retirarlo apenas empiece a dorar, porque se quema muy rápido',
      'Remojarlo en agua tibia durante dos horas',
      'Licuarlo con el agua a velocidad alta hasta que quede muy fino',
      'Colar con un paño exprimiendo con fuerza',
      'Calentar la leche con la canela sin dejar que hierva',
      'Endulzar con miel, agregar vainilla y servir',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/leche_de_ajonjoli.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Masato de yuca',
    descripcion: 'Bebida amazónica tradicional de yuca cocida y fermentada.',
    ingredientes: [
      '2 kg de yuca',
      '2 litros de agua',
      '1 taza de azúcar',
      '1 camote morado rallado',
      'Hojas de plátano',
      'Sal al gusto',
    ],
    preparacion: [
      'Pelar la yuca y sancocharla en agua con sal hasta que esté muy tierna',
      'Retirar la fibra central de cada trozo',
      'Machacar la yuca caliente en un batán hasta formar una masa fina',
      'Agregar el camote morado rallado, que aporta los azúcares para la fermentación',
      'Colocar la masa en un recipiente de barro cubierto con hojas de plátano',
      'Dejar fermentar de dos a tres días en lugar fresco y oscuro',
      'Diluir con agua, colar, endulzar al gusto y servir',
    ],
    tiempo_minutos: 120,
    dificultad: 'dificil',
    imagen_asset: '/assets/images/recetas/masato_de_yuca.jpg',
    bebida: null,
    acompanamiento: 'Juane',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Chapo',
    descripcion: 'Bebida amazónica dulce de plátano maduro cocido con leche.',
    ingredientes: [
      '6 plátanos maduros',
      '2 litros de agua',
      '1 taza de leche evaporada',
      '1 palito de canela',
      '1/2 taza de azúcar',
      '4 clavos de olor',
    ],
    preparacion: [
      'Pelar los plátanos maduros y cortarlos en trozos grandes',
      'Hervirlos en agua con la canela y el clavo por 20 minutos',
      'Aplastarlos dentro de la misma olla con un machacador',
      'Licuar la mezcla con parte del agua de cocción',
      'Colar para obtener una bebida suave sin fibras',
      'Regresar al fuego, agregar la leche y el azúcar',
      'Calentar sin dejar hervir y servir caliente en taza',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/chapo.jpg',
    bebida: null,
    acompanamiento: 'Tacacho',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Aguajina',
    descripcion: 'Refresco amazónico del fruto del aguaje, cremoso y anaranjado.',
    ingredientes: [
      '1 kg de aguaje maduro',
      '2 litros de agua tibia',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 limón',
      '1 pizca de sal',
    ],
    preparacion: [
      'Remojar los aguajes en agua tibia durante una hora para ablandar la cáscara',
      'Retirar las escamas frotando cada fruto con las manos',
      'Raspar la pulpa anaranjada que rodea la pepa',
      'Licuar la pulpa con agua tibia sin romper las semillas',
      'Colar con un colador fino para eliminar las fibras',
      'Endulzar con azúcar y agregar unas gotas de limón',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 45,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/aguajina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de cocona',
    descripcion: 'Bebida amazónica ácida y refrescante del fruto de cocona.',
    ingredientes: [
      '6 coconas maduras',
      '2 litros de agua',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 limón',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Lavar las coconas y sumergirlas brevemente en agua hirviendo',
      'Pelarlas con facilidad después de ese escaldado',
      'Cortarlas en trozos retirando parte de las semillas',
      'Licuarlas con agua fría por poco tiempo para no amargar',
      'Colar con un colador fino',
      'Endulzar al gusto y agregar unas gotas de limón',
      'Servir bien helado con hojas de hierbabuena',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_cocona.jpg',
    bebida: null,
    acompanamiento: 'Tacacho con cecina',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de camu camu',
    descripcion: 'Bebida amazónica del fruto más rico en vitamina C del mundo.',
    ingredientes: [
      '500 g de camu camu',
      '2 litros de agua',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 cucharadita de ralladura de limón',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Lavar los frutos de camu camu y retirarles las semillas',
      'Licuar la pulpa con agua fría durante poco tiempo',
      'No licuar en exceso para no romper las semillas restantes',
      'Colar con un colador fino',
      'Endulzar generosamente, porque el camu camu es muy ácido',
      'Refrigerar al menos una hora antes de servir',
      'Servir bien helado con hierbabuena y hielo',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_camu_camu.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de carambola',
    descripcion: 'Bebida cítrica y ligera del fruto estrella, muy refrescante.',
    ingredientes: [
      '8 carambolas maduras',
      '2 litros de agua',
      '1 taza de azúcar',
      '1 palito de canela',
      'Hielo al gusto',
      '2 limones',
    ],
    preparacion: [
      'Lavar las carambolas y retirar los bordes oscuros de las aristas',
      'Cortarlas en trozos reservando algunas rodajas para decorar',
      'Licuarlas con agua fría brevemente',
      'Colar con un colador fino para eliminar la fibra',
      'Endulzar al gusto y agregar unas gotas de limón',
      'Refrigerar al menos una hora',
      'Servir helada con una rodaja de carambola en forma de estrella',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_carambola.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de tumbo',
    descripcion: 'Bebida andina ácida del tumbo serrano, pariente del maracuyá.',
    ingredientes: [
      '8 tumbos maduros',
      '2 litros de agua',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 pizca de canela',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Cortar los tumbos por la mitad y extraer la pulpa con las semillas',
      'Licuar la pulpa con agua fría durante pocos segundos',
      'Licuar poco para no triturar las semillas, que amargan la bebida',
      'Colar con un colador fino presionando suavemente',
      'Endulzar generosamente porque el tumbo es muy ácido',
      'Refrigerar al menos una hora antes de servir',
      'Servir bien helado con hierbabuena',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_tumbo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Agua de cebada tostada',
    descripcion: 'Infusión simple de cebada tostada, sin azúcar, digestiva.',
    ingredientes: [
      '1 taza de cebada',
      '2 litros de agua',
      '1 palito de canela',
      'Cáscara de naranja',
      'Miel al gusto',
      '2 limones',
    ],
    preparacion: [
      'Tostar la cebada en una olla seca a fuego medio removiendo constantemente',
      'Retirarla cuando tome color café oscuro pero antes de que humee',
      'Agregar el agua caliente con cuidado porque salpica',
      'Hervir 25 minutos con la canela y la cáscara de naranja',
      'Colar el líquido y probar el sabor',
      'Endulzar con miel solo si se desea, o dejarla natural',
      'Servir caliente en taza o fría con hielo y limón',
    ],
    tiempo_minutos: 40,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/agua_de_cebada_tostada.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Refresco de piña con cáscara',
    descripcion: 'Bebida económica hecha hirviendo la cáscara de la piña con canela.',
    ingredientes: [
      'Cáscara de 2 piñas',
      '3 litros de agua',
      '1 palito de canela',
      '6 clavos de olor',
      '1 taza de azúcar',
      '3 limones',
    ],
    preparacion: [
      'Lavar muy bien las piñas antes de pelarlas, porque se usa la cáscara',
      'Colocar las cáscaras en una olla con el agua, la canela y el clavo',
      'Hervir 30 minutos hasta que el agua tome color y aroma',
      'Colar el líquido y desechar las cáscaras',
      'Dejar enfriar por completo antes de endulzar',
      'Agregar azúcar y jugo de limón al gusto',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 45,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/refresco_de_pina_con_cascara.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
];
