// Bebidas — parte 3. Jugos de fruta.

export const parte = [
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de naranja',
    descripcion: 'Jugo natural de naranja recién exprimido, sin colar.',
    ingredientes: [
      '10 naranjas de jugo',
      'Azúcar al gusto',
      'Hielo al gusto',
      '1 pizca de sal',
      '1 cucharadita de ralladura',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Elegir naranjas pesadas para su tamaño, que son las más jugosas',
      'Rodarlas sobre la mesa presionando con la palma para soltar el jugo',
      'Cortarlas por la mitad y exprimirlas con exprimidor manual',
      'No presionar demasiado la cáscara para que el jugo no amargue',
      'Colar solo si se prefiere sin pulpa, aunque la pulpa aporta fibra',
      'Endulzar apenas o dejarlo natural según lo dulce de la fruta',
      'Servir de inmediato con hielo, porque pierde vitaminas al reposar',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_naranja.jpg',
    bebida: null,
    acompanamiento: 'Pan con palta',
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de piña',
    descripcion: 'Jugo fresco de piña madura con un toque de hierbabuena.',
    ingredientes: [
      '1 piña madura',
      '1 litro de agua fría',
      'Azúcar al gusto',
      'Hielo al gusto',
      'Hojas de hierbabuena',
      '1 limón',
    ],
    preparacion: [
      'Elegir una piña que desprenda aroma dulce en la base',
      'Pelarla retirando bien los ojos oscuros de la cáscara',
      'Cortarla en cubos descartando el corazón fibroso del centro',
      'Licuar los cubos con agua fría hasta que quede homogéneo',
      'Colar si se prefiere una textura más ligera',
      'Endulzar solo si hace falta y agregar unas gotas de limón',
      'Servir bien helado con hojas de hierbabuena',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_pina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de fresa',
    descripcion: 'Jugo cremoso de fresas frescas con leche y azúcar.',
    ingredientes: [
      '500 g de fresas',
      '1 litro de leche',
      '1/2 taza de azúcar',
      'Hielo al gusto',
      '1 cucharadita de vainilla',
      '1 limón',
    ],
    preparacion: [
      'Lavar las fresas en agua con un chorrito de vinagre y enjuagarlas bien',
      'Retirar las hojas verdes y cortar las más grandes por la mitad',
      'Licuar las fresas con la leche fría',
      'Agregar el azúcar poco a poco probando el dulzor',
      'Añadir unas gotas de limón para realzar el sabor de la fruta',
      'Licuar con hielo si se quiere más espeso y frío',
      'Servir de inmediato antes de que se separe',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_fresa.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de plátano con leche',
    descripcion: 'Batido espeso de plátano maduro con leche y canela.',
    ingredientes: [
      '4 plátanos maduros',
      '1 litro de leche',
      '1/3 taza de azúcar',
      '1 cucharadita de canela',
      'Hielo al gusto',
      '1 cucharadita de vainilla',
    ],
    preparacion: [
      'Elegir plátanos bien maduros, con manchas oscuras en la cáscara',
      'Pelarlos y cortarlos en trozos',
      'Licuarlos con la leche fría hasta que quede completamente cremoso',
      'Agregar el azúcar, la vainilla y una pizca de canela',
      'Licuar con hielo si se prefiere más frío y espeso',
      'Probar y ajustar el dulzor según lo maduro del plátano',
      'Servir de inmediato espolvoreado con canela',
    ],
    tiempo_minutos: 10,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_platano_con_leche.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de mango',
    descripcion: 'Jugo espeso y dulce de mango maduro con agua y limón.',
    ingredientes: [
      '4 mangos maduros',
      '1 litro de agua fría',
      'Azúcar al gusto',
      'Hielo al gusto',
      '1 limón',
      '1 pizca de sal',
    ],
    preparacion: [
      'Elegir mangos que cedan ligeramente al presionarlos con el dedo',
      'Pelarlos y separar la pulpa del hueso central',
      'Cortar la pulpa en cubos',
      'Licuarla con agua fría hasta obtener una mezcla homogénea',
      'Colar si el mango tiene mucha fibra',
      'Agregar unas gotas de limón y una pizca de sal para realzar el sabor',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_mango.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de maracuyá',
    descripcion: 'Jugo ácido y aromático de maracuyá con agua y azúcar.',
    ingredientes: [
      '10 maracuyás',
      '1.5 litros de agua',
      '1 taza de azúcar',
      'Hielo al gusto',
      'Hojas de hierbabuena',
      '1 pizca de sal',
    ],
    preparacion: [
      'Cortar los maracuyás por la mitad y extraer la pulpa con una cuchara',
      'Licuar la pulpa con agua fría solo unos segundos',
      'Licuar poco tiempo para no triturar las semillas, que amargan',
      'Colar con un colador fino presionando suavemente',
      'Endulzar generosamente porque el maracuyá es muy ácido',
      'Refrigerar al menos media hora',
      'Servir bien helado con hierbabuena',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_maracuya.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de granadilla',
    descripcion: 'Jugo suave de granadilla con agua fría, dulce y aromático.',
    ingredientes: [
      '8 granadillas',
      '1 litro de agua fría',
      'Azúcar al gusto',
      'Hielo al gusto',
      '1 limón',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Romper la cáscara de las granadillas presionando con los dedos',
      'Extraer la pulpa gelatinosa con las semillas',
      'Licuar muy brevemente con agua fría, apenas unos segundos',
      'Colar con un colador fino para separar las semillas',
      'Endulzar ligeramente, porque la granadilla ya es dulce',
      'Agregar unas gotas de limón para balancear',
      'Servir bien helado',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_granadilla.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de tuna',
    descripcion: 'Jugo refrescante del fruto del nopal, dulce y ligero.',
    ingredientes: [
      '10 tunas maduras',
      '1 litro de agua',
      'Azúcar al gusto',
      '2 limones',
      'Hielo al gusto',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Manipular las tunas con guantes o papel para evitar las espinas finas',
      'Pelarlas cortando los extremos y abriendo la cáscara a lo largo',
      'Retirar la pulpa entera con una cuchara',
      'Licuarla brevemente con agua fría sin triturar las semillas',
      'Colar con un colador fino',
      'Endulzar al gusto y agregar jugo de limón',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_tuna.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de sauco',
    descripcion: 'Jugo andino de sauco, de color morado intenso y sabor ácido.',
    ingredientes: [
      '500 g de sauco',
      '1.5 litros de agua',
      '1 taza de azúcar',
      '1 palito de canela',
      'Hielo al gusto',
      '1 limón',
    ],
    preparacion: [
      'Lavar los racimos de sauco y separar las bayas de los tallos',
      'Hervir las bayas en agua con la canela durante 15 minutos',
      'Aplastarlas dentro de la olla para que suelten todo su color',
      'Colar el líquido con un colador fino',
      'Endulzar generosamente mientras está caliente',
      'Dejar enfriar por completo y agregar jugo de limón',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 35,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_sauco.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de aguaymanto',
    descripcion: 'Jugo andino del aguaymanto, agridulce y rico en vitamina C.',
    ingredientes: [
      '500 g de aguaymanto',
      '1.5 litros de agua',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 limón',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Retirar las hojas secas que envuelven cada aguaymanto',
      'Lavar bien los frutos, porque suelen quedar pegajosos',
      'Licuarlos con agua fría hasta que queden completamente deshechos',
      'Colar con un colador fino para eliminar las semillas pequeñas',
      'Endulzar al gusto, recordando que el aguaymanto es bastante ácido',
      'Agregar unas gotas de limón',
      'Servir bien helado con hierbabuena',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_aguaymanto.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de guanábana',
    descripcion: 'Jugo cremoso y perfumado de guanábana con leche.',
    ingredientes: [
      '1 guanábana madura',
      '1 litro de leche',
      '1/2 taza de azúcar',
      'Hielo al gusto',
      '1 cucharadita de vainilla',
      '1 limón',
    ],
    preparacion: [
      'Elegir una guanábana que ceda al tacto pero no esté pasada',
      'Abrirla por la mitad y retirar la pulpa blanca con las manos',
      'Separar pacientemente todas las semillas negras, que son tóxicas',
      'Licuar la pulpa con la leche fría',
      'Endulzar al gusto y agregar la vainilla',
      'Agregar unas gotas de limón para evitar que se oxide',
      'Servir de inmediato bien helado',
    ],
    tiempo_minutos: 25,
    dificultad: 'media',
    imagen_asset: '/assets/images/recetas/jugo_de_guanabana.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de lúcuma',
    descripcion: 'Batido espeso de lúcuma con leche, dulce y muy peruano.',
    ingredientes: [
      '3 lúcumas maduras',
      '1 litro de leche',
      '1/2 taza de azúcar',
      'Hielo al gusto',
      '1 cucharadita de vainilla',
      '1 pizca de canela',
    ],
    preparacion: [
      'Elegir lúcumas de pulpa anaranjada intensa y textura harinosa',
      'Pelarlas y retirar la pepa grande del centro',
      'Cortar la pulpa en trozos',
      'Licuarla con la leche fría hasta que quede completamente lisa',
      'Agregar azúcar al gusto, aunque la lúcuma ya es dulce',
      'Licuar con hielo para lograr una textura de milkshake',
      'Servir de inmediato espolvoreado con canela',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_lucuma.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de chirimoya',
    descripcion: 'Jugo cremoso de chirimoya con leche, suave y perfumado.',
    ingredientes: [
      '2 chirimoyas maduras',
      '1 litro de leche',
      '1/3 taza de azúcar',
      'Hielo al gusto',
      '1 cucharadita de vainilla',
      '1 limón',
    ],
    preparacion: [
      'Elegir chirimoyas que cedan suavemente al presionarlas',
      'Abrirlas y retirar la pulpa blanca con una cuchara',
      'Separar todas las semillas negras con paciencia',
      'Licuar la pulpa con la leche fría por poco tiempo',
      'Endulzar ligeramente porque la chirimoya ya es muy dulce',
      'Agregar unas gotas de limón para que no se oxide',
      'Servir de inmediato bien helado',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_chirimoya.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de melón',
    descripcion: 'Jugo ligero y dulce de melón con agua y limón.',
    ingredientes: [
      '1 melón maduro',
      '1 litro de agua fría',
      'Azúcar al gusto',
      '2 limones',
      'Hielo al gusto',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Elegir un melón que desprenda aroma dulce en el extremo del tallo',
      'Partirlo por la mitad y retirar las semillas con una cuchara',
      'Separar la pulpa de la cáscara y cortarla en cubos',
      'Licuar la pulpa con agua fría',
      'Endulzar solo si hace falta, porque el melón maduro es dulce',
      'Agregar jugo de limón para dar frescura',
      'Servir bien helado con hierbabuena',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_melon.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de sandía',
    descripcion: 'Jugo muy refrescante de sandía con limón y hierbabuena.',
    ingredientes: [
      '1/2 sandía',
      '2 limones',
      'Azúcar al gusto',
      'Hielo al gusto',
      'Hojas de hierbabuena',
      '1 pizca de sal',
    ],
    preparacion: [
      'Cortar la sandía y separar la pulpa roja de la cáscara',
      'Retirar la mayor cantidad posible de pepas',
      'Cortar la pulpa en cubos',
      'Licuarla sin agregar agua, porque la sandía ya tiene mucha',
      'Colar si quedaron restos de pepas',
      'Agregar jugo de limón y una pizca de sal para realzar el sabor',
      'Servir bien helado con hierbabuena',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_sandia.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de papaya con leche',
    descripcion: 'Batido cremoso de papaya con leche y un toque de vainilla.',
    ingredientes: [
      '1/2 papaya madura',
      '1 litro de leche',
      '1/3 taza de azúcar',
      'Hielo al gusto',
      '1 cucharadita de vainilla',
      '1 limón',
    ],
    preparacion: [
      'Elegir una papaya de cáscara amarilla y pulpa anaranjada',
      'Partirla, retirar las semillas negras y separar la pulpa de la cáscara',
      'Cortar la pulpa en cubos',
      'Licuarla con la leche fría hasta que quede cremosa',
      'Endulzar al gusto y agregar la vainilla',
      'Agregar unas gotas de limón para equilibrar el dulzor',
      'Servir de inmediato bien helado',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_papaya_con_leche.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de manzana',
    descripcion: 'Jugo fresco de manzana con canela, servido bien frío.',
    ingredientes: [
      '6 manzanas',
      '1 litro de agua fría',
      '1 palito de canela',
      '2 limones',
      'Azúcar al gusto',
      'Hielo al gusto',
    ],
    preparacion: [
      'Lavar bien las manzanas y descorazonarlas sin pelarlas',
      'Cortarlas en trozos y rociarlas de inmediato con limón',
      'El limón evita que la pulpa se oxide y se ponga oscura',
      'Licuar los trozos con agua fría',
      'Colar con un colador fino para quitar la fibra',
      'Endulzar solo si hace falta y agregar canela molida',
      'Servir de inmediato bien helado',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_manzana.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de pera',
    descripcion: 'Jugo suave de pera madura con limón y hielo.',
    ingredientes: [
      '6 peras maduras',
      '1 litro de agua fría',
      '2 limones',
      'Azúcar al gusto',
      'Hielo al gusto',
      '1 pizca de canela',
    ],
    preparacion: [
      'Elegir peras maduras que cedan al presionar cerca del tallo',
      'Lavarlas, descorazonarlas y cortarlas en trozos con cáscara',
      'Rociarlas con limón para evitar que se oxiden',
      'Licuarlas con agua fría hasta que queden homogéneas',
      'Colar para obtener una bebida más ligera',
      'Endulzar apenas, porque la pera madura ya es dulce',
      'Servir bien helado con una pizca de canela',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_pera.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de durazno',
    descripcion: 'Jugo espeso de durazno con agua, canela y azúcar.',
    ingredientes: [
      '8 duraznos maduros',
      '1.5 litros de agua',
      '1 palito de canela',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 limón',
    ],
    preparacion: [
      'Escaldar los duraznos 30 segundos en agua hirviendo para pelarlos fácil',
      'Pasarlos a agua fría y retirar la piel con los dedos',
      'Deshuesarlos y cortar la pulpa en trozos',
      'Cocinar los trozos brevemente con agua, canela y azúcar',
      'Dejar enfriar y licuar todo junto',
      'Colar si se prefiere una textura más fina',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 30,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_durazno.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de uva',
    descripcion: 'Jugo natural de uva borgoña, intenso y dulce.',
    ingredientes: [
      '1 kg de uva borgoña',
      '1 litro de agua',
      'Azúcar al gusto',
      '2 limones',
      'Hielo al gusto',
      '1 pizca de sal',
    ],
    preparacion: [
      'Lavar bien los racimos y desgranar las uvas',
      'Licuarlas con un poco de agua durante poco tiempo',
      'Licuar brevemente para no romper las pepas, que amargan',
      'Colar con un colador fino presionando suavemente',
      'Agregar el resto del agua y ajustar la concentración',
      'Endulzar solo si hace falta y agregar jugo de limón',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 20,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_uva.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de tamarindo',
    descripcion: 'Refresco agridulce de pulpa de tamarindo con azúcar.',
    ingredientes: [
      '300 g de tamarindo',
      '2 litros de agua',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 pizca de sal',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Pelar las vainas de tamarindo retirando la cáscara quebradiza',
      'Remojar la pulpa en agua tibia durante una hora',
      'Frotar la pulpa con las manos dentro del agua para desprenderla de las semillas',
      'Colar el líquido con un colador fino presionando el bagazo',
      'Agregar el resto del agua y endulzar generosamente',
      'Probar y ajustar el equilibrio entre ácido y dulce',
      'Servir bien helado con hielo',
    ],
    tiempo_minutos: 80,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_tamarindo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de níspero',
    descripcion: 'Jugo dulce y aromático de níspero con agua fría.',
    ingredientes: [
      '1 kg de nísperos maduros',
      '1.5 litros de agua',
      'Azúcar al gusto',
      '2 limones',
      'Hielo al gusto',
      '1 pizca de canela',
    ],
    preparacion: [
      'Lavar los nísperos y cortarlos por la mitad',
      'Retirar las semillas grandes y brillantes del interior',
      'Quitar la piel fina si se desea una textura más suave',
      'Licuar la pulpa con agua fría',
      'Colar con un colador fino para quitar la fibra',
      'Endulzar al gusto y agregar jugo de limón',
      'Servir bien helado con una pizca de canela',
    ],
    tiempo_minutos: 25,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_nispero.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de mora',
    descripcion: 'Jugo andino de mora, de color intenso y sabor ácido.',
    ingredientes: [
      '600 g de moras',
      '1.5 litros de agua',
      '1 taza de azúcar',
      'Hielo al gusto',
      '1 limón',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Lavar las moras con cuidado porque se deshacen con facilidad',
      'Licuarlas con la mitad del agua durante poco tiempo',
      'Colar con un colador fino para separar las semillas pequeñas',
      'Agregar el resto del agua y mezclar',
      'Endulzar generosamente porque la mora es bastante ácida',
      'Agregar unas gotas de limón',
      'Servir bien helado con hierbabuena',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_mora.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de mandarina',
    descripcion: 'Jugo dulce de mandarina recién exprimida.',
    ingredientes: [
      '15 mandarinas',
      'Azúcar al gusto',
      'Hielo al gusto',
      '1 pizca de sal',
      '1 cucharadita de ralladura',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Elegir mandarinas pesadas y de cáscara firme',
      'Rodarlas sobre la mesa presionando para soltar el jugo',
      'Cortarlas por la mitad y exprimirlas con exprimidor manual',
      'No presionar la cáscara en exceso para que no amargue',
      'Colar si se prefiere sin pulpa',
      'Endulzar solo si las mandarinas están ácidas',
      'Servir de inmediato con hielo',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_mandarina.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de toronja',
    descripcion: 'Jugo cítrico y ligeramente amargo de toronja rosada.',
    ingredientes: [
      '6 toronjas',
      'Azúcar o miel al gusto',
      'Hielo al gusto',
      '1 pizca de sal',
      'Hojas de hierbabuena',
      '1 limón',
    ],
    preparacion: [
      'Elegir toronjas pesadas de cáscara lisa',
      'Cortarlas por la mitad transversalmente',
      'Exprimirlas con exprimidor sin presionar la parte blanca',
      'La parte blanca de la cáscara es la que aporta el amargor',
      'Colar el jugo para quitar los restos de pulpa gruesa',
      'Endulzar con miel para suavizar el amargor natural',
      'Servir bien helado con hierbabuena',
    ],
    tiempo_minutos: 12,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_toronja.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de membrillo',
    descripcion: 'Refresco aromático de membrillo cocido con canela.',
    ingredientes: [
      '4 membrillos',
      '2 litros de agua',
      '1 taza de azúcar',
      '1 palito de canela',
      '4 clavos de olor',
      '2 limones',
    ],
    preparacion: [
      'Lavar los membrillos frotando la pelusa de la cáscara',
      'Cortarlos en trozos sin pelarlos y retirar el corazón',
      'Hervirlos en agua con la canela y el clavo durante 40 minutos',
      'El membrillo crudo es muy áspero, por eso siempre se cocina',
      'Licuar todo junto una vez cocido y tibio',
      'Colar con un colador fino y endulzar al gusto',
      'Servir frío con hielo y unas gotas de limón',
    ],
    tiempo_minutos: 60,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_membrillo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de higo',
    descripcion: 'Jugo dulce de higos maduros con leche y canela.',
    ingredientes: [
      '10 higos maduros',
      '1 litro de leche',
      '1/3 taza de azúcar',
      '1 palito de canela',
      'Hielo al gusto',
      '1 cucharadita de vainilla',
    ],
    preparacion: [
      'Lavar los higos y retirarles el tallo',
      'Cortarlos en cuartos sin pelarlos, porque la piel aporta color',
      'Licuarlos con la leche fría',
      'Colar si se prefiere sin las semillas pequeñas',
      'Endulzar apenas, porque el higo maduro es muy dulce',
      'Agregar la vainilla y una pizca de canela',
      'Servir bien helado',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_higo.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: 'Jugo de pitahaya',
    descripcion: 'Jugo suave de pitahaya con limón, de color llamativo.',
    ingredientes: [
      '3 pitahayas',
      '1 litro de agua fría',
      'Azúcar al gusto',
      '2 limones',
      'Hielo al gusto',
      'Hojas de hierbabuena',
    ],
    preparacion: [
      'Cortar las pitahayas por la mitad a lo largo',
      'Extraer la pulpa con una cuchara separándola de la cáscara',
      'Licuarla con agua fría durante poco tiempo',
      'Licuar brevemente para no triturar las semillas negras',
      'Colar solo si se prefiere sin semillas',
      'Endulzar al gusto y agregar jugo de limón para dar acidez',
      'Servir bien helado con hierbabuena',
    ],
    tiempo_minutos: 15,
    dificultad: 'facil',
    imagen_asset: '/assets/images/recetas/jugo_de_pitahaya.jpg',
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
];
