// Recetas de la categoría "bebidas". Fuente canónica del seed.
// Los generadores de database/*.mjs leen de aquí vía recetasSeedData.js.

export const parte = [
  {
    categoria_slug: 'bebidas',
    nombre: "Quinua",
    descripcion: "Bebida caliente y nutritiva a base de quinua, canela y manzana.",
    ingredientes: [
      "1 taza de quinua (200 g)",
      "2 litros de agua",
      "1 rama de canela",
      "2 clavos de olor",
      "1 manzana, picada",
      "1/2 taza de azúcar",
    ],
    preparacion: [
      "Lavar bien la quinua en agua fría, frotándola con las manos hasta que el agua salga clara, para retirar la saponina",
      "Colocar la quinua en una olla con abundante agua junto con la canela en rama y el clavo de olor",
      "Cocer a fuego medio durante 20 minutos, revolviendo de vez en cuando, hasta que el grano reviente",
      "Pelar y picar la manzana en cubos pequeños e incorporarla a la olla",
      "Añadir azúcar al gusto y dejar hervir 5 minutos más para que se integren los sabores",
      "Retirar la canela y el clavo, y licuar ligeramente si se prefiere una textura más suave",
      "Servir bien caliente",
    ],
    tiempo_minutos: 25,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/quinua.jpg",
    bebida: null,
    acompanamiento: "Pan con queso fresco",
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: "Avena",
    descripcion: "Refresco espeso y dulce de avena con canela, típico del desayuno peruano.",
    ingredientes: [
      "1 taza de avena",
      "1 litro de agua",
      "1 rama de canela",
      "1 litro de leche",
      "1/2 taza de azúcar",
    ],
    preparacion: [
      "Colocar la avena en una olla con agua y la canela en rama",
      "Cocer a fuego medio durante 15 minutos, revolviendo con frecuencia para que no se pegue en el fondo",
      "Retirar la canela una vez que la avena esté suave y el líquido haya espesado ligeramente",
      "Licuar la avena cocida junto con la leche hasta obtener una mezcla homogénea",
      "Colar si se desea una textura más fina, o dejar tal cual para mayor cuerpo",
      "Endulzar con azúcar al gusto y servir bien frío o caliente según preferencia",
    ],
    tiempo_minutos: 20,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/avena.jpg",
    bebida: null,
    acompanamiento: "Pan con palta",
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: "Maca",
    descripcion: "Bebida energizante a base de maca en polvo, típica de la sierra peruana.",
    ingredientes: [
      "2 cucharadas de maca en polvo",
      "1 litro de leche o agua",
      "1 pizca de canela molida",
      "Azúcar al gusto",
    ],
    preparacion: [
      "Entibiar la leche o el agua en una olla pequeña sin dejar que hierva",
      "Disolver la maca en polvo poco a poco en el líquido tibio, batiendo para evitar grumos",
      "Añadir una pizca de canela molida para realzar el sabor",
      "Endulzar con azúcar al gusto",
      "Batir enérgicamente con una cuchara o con un molinillo hasta que quede espumosa",
      "Servir caliente de inmediato",
    ],
    tiempo_minutos: 10,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/maca.jpg",
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: "Emoliente",
    descripcion: "Infusión caliente de hierbas y cebada, bebida callejera tradicional.",
    ingredientes: [
      "1/2 taza de cebada",
      "2 cucharadas de linaza",
      "1 puñado de cola de caballo",
      "2 litros de agua",
      "2 limones",
      "Miel al gusto",
    ],
    preparacion: [
      "Lavar la cebada, la linaza y la cola de caballo en agua fría",
      "Colocar todos los ingredientes en una olla grande con abundante agua",
      "Hervir a fuego medio durante 25 minutos hasta que el agua tome un color amarillento y las semillas de linaza suelten su mucílago",
      "Colar el líquido presionando bien las hierbas para extraer todo su sabor",
      "Servir en un vaso o taza y añadir el jugo de limón y miel al gusto justo antes de tomar",
      "Disfrutar caliente, revolviendo bien para integrar la miel",
    ],
    tiempo_minutos: 30,
    dificultad: "media",
    imagen_asset: "/assets/images/recetas/emoliente.jpg",
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: "Jugo de papaya",
    descripcion: "Jugo espeso y dulce de papaya fresca con leche.",
    ingredientes: [
      "300 g de papaya (1/2 papaya mediana)",
      "2 tazas de leche",
      "3 cucharadas de azúcar",
      "1 taza de hielo",
    ],
    preparacion: [
      "Pelar la papaya, retirar las pepas y cortar la pulpa en trozos medianos",
      "Colocar los trozos de papaya en la licuadora junto con la leche",
      "Añadir azúcar al gusto y unos cubos de hielo",
      "Licuar hasta obtener una mezcla suave y homogénea, sin grumos",
      "Probar y ajustar el dulzor si es necesario",
      "Servir bien frío de inmediato",
    ],
    tiempo_minutos: 10,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/jugo_de_papaya.jpg",
    bebida: null,
    acompanamiento: "Pan con palta",
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: "Jugo surtido",
    descripcion: "Combinado de frutas de estación licuadas, refrescante y nutritivo.",
    ingredientes: [
      "150 g de papaya",
      "1 plátano",
      "2 naranjas (jugo)",
      "1 taza de leche",
    ],
    preparacion: [
      "Pelar y trocear la papaya y el plátano",
      "Exprimir la naranja para obtener su jugo, colando las semillas",
      "Colocar las frutas troceadas en la licuadora junto con el jugo de naranja y la leche",
      "Licuar a velocidad alta hasta integrar completamente todos los ingredientes",
      "Colar si se desea una textura más ligera, o dejar espeso",
      "Endulzar al gusto y servir frío de inmediato",
    ],
    tiempo_minutos: 10,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/jugo_surtido.jpg",
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: "Leche con café",
    descripcion: "Café pasado con leche caliente, el desayuno más clásico del Perú.",
    ingredientes: [
      "4 cucharadas de café molido",
      "2 tazas de agua caliente",
      "1 litro de leche",
      "Azúcar al gusto",
    ],
    preparacion: [
      "Colocar el café molido en un filtro de tela o de papel",
      "Verter agua caliente lentamente sobre el filtro, dejando que el café pasado gotee en una jarra hasta obtener un concentrado oscuro",
      "Calentar la leche en una olla aparte, cuidando que no llegue a hervir",
      "Verter una porción del concentrado de café en cada taza",
      "Completar con la leche caliente en la proporción deseada",
      "Endulzar con azúcar al gusto y remover antes de servir",
    ],
    tiempo_minutos: 10,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/leche_con_cafe.jpg",
    bebida: null,
    acompanamiento: "Pan con mantequilla",
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: "Chocolate caliente",
    descripcion: "Chocolate de taza espeso y aromático con canela.",
    ingredientes: [
      "200 g de chocolate de taza",
      "1 litro de leche",
      "1 rama de canela",
      "2 clavos de olor",
    ],
    preparacion: [
      "Calentar la leche en una olla junto con la canela en rama y el clavo de olor",
      "Cuando la leche esté caliente pero sin hervir, incorporar el chocolate de taza troceado",
      "Revolver constantemente con una cuchara de madera hasta que el chocolate se disuelva por completo",
      "Batir enérgicamente con un molinillo durante un par de minutos para generar espuma y homogeneizar",
      "Retirar la canela y el clavo de olor",
      "Servir bien caliente en tazas",
    ],
    tiempo_minutos: 15,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/chocolate_caliente.jpg",
    bebida: null,
    acompanamiento: "Pan",
    video_url: null,
  },
  {
    categoria_slug: 'bebidas',
    nombre: "Infusión de hierbas",
    descripcion: "Infusión suave de hierbas aromáticas como manzanilla, anís y hierbaluisa.",
    ingredientes: [
      "1 cucharadita de manzanilla",
      "1 cucharadita de anís",
      "1 cucharadita de hierbaluisa",
      "1 litro de agua",
      "Miel al gusto",
    ],
    preparacion: [
      "Poner a hervir agua en una olla pequeña",
      "Retirar del fuego apenas rompa el hervor y añadir la manzanilla, el anís y la hierbaluisa",
      "Tapar la olla y dejar reposar entre 5 y 8 minutos para que las hierbas suelten su aroma",
      "Colar la infusión y servir en una taza",
      "Endulzar con miel al gusto y remover antes de beber",
    ],
    tiempo_minutos: 10,
    dificultad: "facil",
    imagen_asset: "/assets/images/recetas/infusion_de_hierbas.jpg",
    bebida: null,
    acompanamiento: null,
    video_url: null,
  },
];
